Repository ManageIQ/manageiq, pull requests merged in 2018-03, with the labels that each got.

#17070 Core changes for azure targeted refresh
  app/models/load_balancer_pool.rb
  app/models/manager_refresh/inventory_collection_default/network_manager.rb
Labels: bug, enhancement, providers/inventory

#17021 Remove custom have_attributes matcher
  spec/support/custom_matchers/have_attributes.rb
Labels: technical debt, test

#17074 Adding missing Product Feature for viewing a single container
  db/fixtures/miq_product_features.yml
Labels: bug, gaprindashvili/yes

#17076 Consolidate Azure refresh workers
  lib/workers/miq_worker_types.rb
Labels: bug, gaprindashvili/yes, providers/microsoft/cloud

#17026 ConfigurationScriptSource to have last_updated_on column
  app/models/manager_refresh/inventory/core.rb
Labels: enhancement, providers/ansible_tower

#16931 Miq expression column parsing
  lib/extensions/ar_virtual.rb
  lib/miq_expression.rb
  lib/miq_expression/target.rb
  spec/lib/extensions/ar_virtual_spec.rb
Labels: core, refactoring

#17072 Move SchemaMigration from ManageIQ to ManageIQ::Schema plugin
  app/models/schema_migration.rb
Labels: bug, gaprindashvili/yes

#17038 Removal of nil's before relationship remove_children
  app/models/mixins/relationship_mixin.rb
  spec/models/mixins/relationship_mixin_spec.rb
Labels: bug, providers

#17071 Backend enhancements for transformation plan request to better support UI
  app/models/miq_request.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, transformation

#17080 Remove new fields from export if empty
  app/models/miq_ae_method.rb
  spec/models/miq_ae_method_spec.rb
Labels: automate, gaprindashvili/yes

#17075 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#17082 Add uniqueness of service for generation chargeback report for SSUI
  app/models/service.rb
  spec/models/service_spec.rb
Labels: bug, chargeback, gaprindashvili/yes

#17017 truncate realtime metrics instead of purging
  app/models/metric/purging.rb
  spec/models/metric/purging_spec.rb
Labels: bug, performance, providers/metrics

#17079 Add tagging feature for Ansible Credentials
  db/fixtures/miq_product_features.yml
Labels: blocker, enhancement, gaprindashvili/yes

#17090 Add more container columns to evm:inventory
  app/models/ext_management_system.rb
Labels: tools

#17077 Calculate totals for hours of exitstence in metering reports
  app/models/metering_container_image.rb
  app/models/metering_container_project.rb
  app/models/metering_vm.rb
  spec/models/metering_container_image_spec.rb
  spec/models/metering_container_project_spec.rb
  spec/models/metering_vm_spec.rb
Labels: bug, chargeback, gaprindashvili/yes

#15854 Don't use EVM / CFME in control event definitions
  db/fixtures/miq_event_definition_sets.csv
  db/fixtures/miq_event_definitions.csv
Labels: refactoring, ui

#17091 Add ConfigurationScriptSource to RBAC
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: blocker, bug, enhancement, gaprindashvili/yes, rbac

#17084 Remove options[:user_message] during miq_request_task creation.
  app/models/miq_request.rb
  spec/models/miq_request_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes

#17093 Moved creating task instances message.
  app/models/miq_request.rb
Labels: enhancement

#17095 Delete #retire_now since it has been moved to shared code
  app/models/manageiq/providers/embedded_ansible/automation_manager/job.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
Labels: bug

#17061 Fix RBAC for User and enable tagging for Tenants
  app/models/miq_group.rb
  app/models/user.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
  spec/lib/services/resource_sharer_spec.rb
Labels: bug, gaprindashvili/yes, rbac

#17094 Fix single security group in provisioning
  product/dialogs/miq_dialogs/miq_provision_openstack_dialogs_template.yaml
Labels: bug, providers/openstack/cloud

#17088 Remove GCE regions from factories
  spec/factories/ext_management_system.rb
Labels: cleanup, providers/cloud, test

#17096 Added Embedded Ansible Content plugin
  lib/vmdb/plugins.rb
  lib/vmdb/plugins/ansible_content.rb
Labels: enhancement

#17102 Fix ambiguous created_recently scope
  app/models/miq_request.rb
  spec/models/miq_request_spec.rb
Labels: bug, gaprindashvili/no

#17117 Removed useless variables, moved before each to appropriate context
  spec/models/custom_button_spec.rb
Labels: technical debt, test

#17116 change in dialog_field_text_box_spec.rb, change variables to let
  spec/models/dialog_field_text_box_spec.rb
Labels: test

#17121 Bump manageiq-smartstate to 0.2.10 version
  Gemfile
Labels: bug, dependencies, fine/yes, smart state

#17103 Scope the default zone to the current region
  app/models/zone.rb
  spec/models/zone_spec.rb
Labels: bug

#17123 Removed not used initialization when testing custom actions for Generic Object
  spec/models/generic_object_spec.rb
Labels: gaprindashvili/no, technical debt, test

#17097 Remove graphiql-rails gem
  Gemfile
  config/routes.rb
Labels: dependencies, technical debt

#17046 Adds purging for notifications
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/notification.rb
  app/models/notification/purging.rb
  config/settings.yml
  spec/models/notification/purging_spec.rb
Labels: core, performance

#17104 Prefer let before instance variable
  spec/models/database_backup_spec.rb
Labels: technical debt, test

#17081 [FINE] Add service model for MiqTask which is needed by event state machine.
  lib/miq_automation_engine/service_models/miq_ae_service_miq_task.rb
Labels: bug

#17111 Testing
  spec/models/ems_event_spec.rb
Labels: technical debt, test

#17127 Create an empty CSS file that is outside the asset pipeline
  public/custom.css
Labels: enhancement, gaprindashvili/yes, ui

#17130 Fix Default log level for automation log
  config/settings.yml
  lib/vmdb/loggers.rb
Labels: automate, bug, control

#17136 Alphabets are hard...
  lib/vmdb/loggers.rb
Labels: bug, gaprindashvili/yes

#17107 prefering let instead of before
  spec/models/miq_ae_method_spec.rb
Labels: technical debt, test

#17112 repaired at let
  spec/models/dialog_field_spec.rb
Labels: technical debt, test

#17132 Do not divide recipients to subgroup when sending attached report
  app/models/miq_report/notification.rb
  config/settings.yml
Labels: bug, fine/yes, gaprindashvili/yes, reporting

#17135 Return a task when queueing chargeback report generation for services
  app/models/service.rb
  spec/models/service_spec.rb
Labels: enhancement, services

#17099 Add tagging feature for Ansible Playbooks
  db/fixtures/miq_product_features.yml
Labels: blocker, enhancement, gaprindashvili/yes

#17139 Only update zone if found
  app/models/miq_server/configuration_management.rb
  spec/models/miq_server/configuration_management_spec.rb
Labels: bug, core

#17044 Tower Rhv credential type
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/rhv_credential.rb
Labels: enhancement, providers/ansible_tower

#17140 Prefer default_value_for to set zone and name
  app/models/miq_server.rb
  config/settings.yml
Labels: core, gaprindashvili/no, technical debt

#17100 Report datetime columns(begining and end of resource's existence) in metering report of VMs
  app/models/chargeback/consumption.rb
  app/models/metering.rb
  app/models/metering_container_image.rb
  app/models/metering_container_project.rb
  app/models/metering_vm.rb
  lib/miq_expression.rb
  spec/models/metering_container_image_spec.rb
  spec/models/metering_container_project_spec.rb
  spec/models/metering_vm_spec.rb
Labels: enhancement, gaprindashvili/yes

#17125 [WIP] Don't define DISALLOWED_SUFFIXES if already defined
  app/models/metering.rb
Labels: wip

#17144 Stop unbounded growth of targets
  app/models/ems_refresh.rb
  spec/models/ems_refresh_spec.rb
Labels: bug, providers/inventory

#17138 replace before with let in test miq_template_spec
  spec/models/miq_template_spec.rb
Labels: technical debt, test

#16722 Keep container quota history by archiving
  app/models/container_project.rb
  app/models/container_quota.rb
  app/models/container_quota_item.rb
  app/models/ems_refresh/save_inventory_container.rb
  app/models/manageiq/providers/container_manager.rb
Labels: enhancement, gaprindashvili/yes

#17149 Add encryption key validation rake task
  lib/tasks/evm.rake
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: bug, core, gaprindashvili/no

#17150 Bump to Rails 5.0.6
  Gemfile
Labels: core, dependencies, rails5

#16832 Corrected tests evaluating MiqExpression for Custom Button
  spec/models/service_template_spec.rb
Labels: technical debt, test

#17126 Allow OrchestrationTemplate subclass to customize md5 calculation
  app/models/orchestration_template.rb
  spec/models/orchestration_template_spec.rb
Labels: enhancement, gaprindashvili/yes

#17159 Downgrade dalli to 2.7.6 to fix issues with session in the UI
  Gemfile
Labels: dependencies, euwe/yes, fine/yes, gaprindashvili/yes

#17110 change before to let
  spec/models/dialog_field_drop_down_list_spec.rb
Labels: technical debt

#17115 changes in lan_spec.rb, change variables lan, vm and template to let
  spec/models/lan_spec.rb
Labels: technical debt, test

#17109 Using let in tests
  spec/models/miq_group_spec.rb
Labels: technical debt, test

#17160 Add an :update event group to the expected list.
  spec/models/ems_event_spec.rb
Labels: gaprindashvili/yes, providers, test

#17161 Remove :class_name for ems.vms_and_templates
  app/models/ext_management_system.rb
Labels: cleanup

#17124 [FINE] Truncate realtime metrics instead of purging
  app/models/metric.rb
  app/models/metric/purging.rb
  spec/models/metric/purging_spec.rb
  spec/models/metric_spec.rb
Labels: bug

#17036 Fix policy_events relationship on VmOrTemplate
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes

#17164 Add detail and name to the new update event group
  config/settings.yml
Labels: bug

#16728 Make VimPerformanceTagValue no longer backed by a DB table
  app/models/metric/common.rb
  app/models/metric/purging.rb
  app/models/vim_performance_tag.rb
  app/models/vim_performance_tag_value.rb
  lib/active_metrics/connection_adapters/miq_postgres_adapter.rb
  tools/purge_orphaned_tag_values.rb
Labels: gaprindashvili/no, technical debt

#16684 Move VimConnectMixin
  app/models/mixins/vim_connect_mixin.rb
Labels: providers/vmware/infra, refactoring

#17034 Add documentation for db layout of metrics and metric_rollups
  app/models/metric.rb
  app/models/metric_rollup.rb
Labels: documentation, providers/metrics

#17165 Allow usage of string factories
  spec/support/missing_factory_helper.rb
Labels: gaprindashvili/no, test

#15896 Clean-up ScanningOperationsMixin
  app/models/mixins/scanning_operations_mixin.rb
  app/models/scanning_operations.rb
Labels: core, fine/no, technical debt

#17145 Use vm_ems_ref to reconnect events
  app/models/ems_event.rb
  app/models/vm_or_template.rb
Labels: bug, providers/vmware/infra

#17154 [FINE] Fix tool tip while setting the ownership for VMs
  bower.json
Labels: bug

#17173 Bad skipping of assert in production env
  app/models/manager_refresh/inventory_collection/index/proxy.rb
Labels: bug, providers/inventory

#17142 Add rates to chargeback report
  app/models/chargeable_field.rb
  app/models/chargeback.rb
  app/models/chargeback_rate_detail.rb
  app/models/chargeback_vm.rb
  spec/models/chargeback_vm_spec.rb
Labels: chargeback, enhancement

#17133 Support for hidden columns in reports and views
  app/models/miq_report.rb
  app/models/miq_report/generator/html.rb
  lib/vmdb/global_methods.rb
  spec/models/miq_report_spec.rb
Labels: enhancement, gaprindashvili/yes, reporting, transformation

#17158 Fix active_provision quota check for infra VM request with invalid vm_template.
  app/models/mixins/miq_provision_quota_mixin.rb
  spec/models/miq_provision_request_spec.rb
Labels: bug, provisioning

#17179 Update manageiq-api-client to 0.3.0
  Gemfile
Labels: api, bug, dependencies, fine/yes, gaprindashvili/yes

#17182 Expose get_assigned_tos as virtual attribute to allow access via the API
  app/models/miq_alert_set.rb
  spec/models/mixins/assignment_mixin_spec.rb
Labels: enhancement

#17067 Fail Cinder/Swift Ensures if Service not Present
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_parser.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_parser.rb
  spec/models/manageiq/providers/cloud_manager_spec.rb
Labels: bug, gaprindashvili/yes, storage

#17184 Add vault credential support to Ansible playbook service template.
  app/models/service_template_ansible_playbook.rb
  spec/models/service_template_ansible_playbook_spec.rb
Labels: enhancement, services

#17087 Improve rake evm:status_full
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: tools

#17146 Add miq_v2v_ui plugin to Gemfile
  Gemfile
Labels: dependencies, enhancement, gaprindashvili/no, ui

#17167 Purging of ContainerQuota & ContainerQuotaItem
  app/models/container_quota.rb
  app/models/container_quota/purging.rb
  app/models/container_quota_item.rb
  app/models/container_quota_item/purging.rb
  app/models/miq_schedule_worker/jobs.rb
  config/settings.yml
  spec/models/container_quota/purging_spec.rb
  spec/models/container_quota_item/purging_spec.rb
Labels: enhancement, gaprindashvili/yes

#17176 [Gaprindashvili] Fix DB loading strategy
  app/models/manager_refresh/inventory_collection.rb
Labels: bug

#16388 TopologicalSort: use graphviz format in exceptions
  app/models/manager_refresh/graph/topological_sort.rb
Labels: developer, enhancement, gaprindashvili/no, providers/inventory, unmergeable

#17193 Fix grammar in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cleanup

#17192 Add vault credential support to automat playbook method.
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_spec.rb
Labels: automate, enhancement, gaprindashvili/yes

#17187 Fix RefreshWorker dequeue race condition
  config/settings.yml
Labels: bug, core/workers, gaprindashvili/yes

#17152 openscap report filter fixup
  product/reports/170_Configuration Management - Containers/130_Images by Failed OpenSCAP Rule Results.yaml
Labels: performance, reporting

#17196 Move MiqVimBroker and EmsRefreshCore workers
  app/models/miq_ems_refresh_core_worker.rb
  app/models/miq_ems_refresh_core_worker/runner.rb
  app/models/miq_vim_broker_worker.rb
  app/models/miq_vim_broker_worker/runner.rb
  spec/models/miq_ems_refresh_core_worker/runner_spec.rb
  spec/models/miq_ems_refresh_core_worker_spec.rb
  spec/models/miq_vim_broker_worker/runner_spec.rb
  spec/models/miq_vim_broker_worker_spec.rb
Labels: providers/vmware/infra, refactoring

#17205 Fix provider proxy settings fallback
  lib/vmdb/util.rb
  spec/lib/vmdb/util_spec.rb
Labels: bug

#17197 Add case insensitivity when validating uniqueness of name of new group/role
  app/models/miq_group.rb
  app/models/miq_user_role.rb
Labels: bug

#17191 Fixed case of expression in OOTB report.
  product/reports/520_Events - Policy/120_Policy Events2.yaml
Labels: blocker, bug, gaprindashvili/yes

#17186 introduce evm:queue
  lib/tasks/evm.rake
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: enhancement, tools

#17206 Cleanup order of model request types
  app/models/miq_request.rb
Labels: cleanup

#17218 Makes http_proxy_uri class method
  app/models/manageiq/providers/base_manager.rb
Labels: bug

#17190 Fix establishing relations of tenants and cloud tenants between different cloud tenant -> tenant sync
  app/models/manageiq/providers/cloud_manager.rb
  spec/models/manageiq/providers/cloud_manager_spec.rb
Labels: blocker, bug, fine/yes, gaprindashvili/yes

#17208 Add ownership for MiqRequest in RBAC
  app/models/miq_request.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#17170 Check for roles required by the worker when using `run_single_worker`
  lib/workers/bin/run_single_worker.rb
Labels: bug, tools

#17221 Change the method signatures for ServiceTemplateContainerTemplate.
  app/models/service_template_container_template.rb
Labels: bug, gaprindashvili/yes, services

#17013 Adding request id to evm log
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/miq_request_task/post_install_callback.rb
  app/models/miq_request_task/state_machine.rb
  app/models/service_reconfigure_task.rb
  app/models/service_template_provision_task.rb
  spec/models/service_reconfigure_task_spec.rb
  spec/models/service_template_provision_task_spec.rb
Labels: enhancement

#17214 [GAPRINDASHVILI] Compare decimal columns correctly in batch saver
  app/models/manager_refresh/save_collection/saver/base.rb
  app/models/manager_refresh/save_collection/saver/concurrent_safe_batch.rb
  spec/models/manager_refresh/save_inventory/init_data_helper.rb
  spec/models/manager_refresh/save_inventory/saver_strategies_spec.rb
  spec/models/manager_refresh/save_inventory/spec_parsed_data.rb
Labels: enhancement

#17114 Let changes
  spec/models/condition_spec.rb
Labels: technical debt, test

#17220 Don't ignore errors in Vm#running_processes
  app/models/vm.rb
Labels: bug

#17203 [EUWE] Update to 2.3.6
  .travis.yml
  lib/miq_automation_engine/engine/drb_remote_invoker.rb
  lib/miq_automation_engine/engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_service.rb
  spec/lib/miq_automation_engine/engine/drb_remote_invoker_spec.rb
  spec/lib/miq_automation_engine/engine/miq_ae_method_spec.rb
Labels: bug

#17224 use 2.3.6 on travis
  .travis.yml
Labels: test

#17066 [FINE] Use new pg-pglogical version
  Gemfile
Labels: blocker, bug, core, dependencies, replication

#17238 Add specs to show save! supports string keys
  spec/lib/vmdb/settings_spec.rb
Labels: test
