Repository ManageIQ/manageiq, pull requests merged in 2018-02, with the labels that each got.

#16920 Don't return in a rake task
  lib/tasks/locale.rake
Labels: enhancement, gaprindashvili/no, internationalization

#16965 Lookup a category_id if a tag control passes it in
  app/models/dialog_field_importer.rb
  spec/models/dialog_field_importer_spec.rb
Labels: blocker, bug, gaprindashvili/yes, services

#16978 Use correct comparison for multi-value default value inclusion rules
  app/models/dialog_field_drop_down_list.rb
  spec/models/dialog/orchestration_template_service_dialog_spec.rb
  spec/models/dialog_field_drop_down_list_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#16455 Introduce $nuage_log that logs into log/nuage.log
  .rubocop_local.yml
  config/settings.yml
  lib/vmdb/loggers.rb
Labels: enhancement

#16787 Introduce model changes for v2v
  app/models/transformation_mapping.rb
  app/models/transformation_mapping_item.rb
  spec/factories/transformation_mapping.rb
  spec/factories/transformation_mapping_item.rb
  spec/models/transformation_mapping_spec.rb
Labels: transformation

#16985 Bump manageiq-smartstate gem to 0.2.8
  Gemfile
Labels: dependencies, fine/yes, gaprindashvili/yes, smart state

#16988 Fix typo in transformation mapping product features
  db/fixtures/miq_product_features.yml
Labels: bug

#16989 Re-check the provider authentication if the API is responding
  app/models/embedded_ansible_worker/runner.rb
  spec/models/embedded_ansible_worker/runner_spec.rb
Labels: bug, core/workers, gaprindashvili/yes

#16700 Reconfigure VM: Add / Remove Network Adapters
  app/models/mixins/supports_feature_mixin.rb
  app/models/vm_reconfigure_task.rb
Labels: enhancement, providers

#16979 Add support for bind dn and bind pwd on the command line.
  spec/tools/miqldap_to_sssd/cli_spec.rb
  spec/tools/miqldap_to_sssd/miqldap_configuration_spec.rb
  tools/miqldap_to_sssd/cli.rb
  tools/miqldap_to_sssd/miqldap_configuration.rb
Labels: authentication, bug, gaprindashvili/yes

#16950 Fix reason scope for MiqRequest
  app/models/miq_request.rb
Labels: core, enhancement

#16919 Remove empty array associations created via UI from association list
  app/models/dialog_import_validator.rb
Labels: bug, gaprindashvili/yes

#16994 Rename network module to not overrun network class
  lib/manageiq/network_discovery/discovery.rb
  lib/manageiq/network_discovery/ipmi/discovery.rb
  lib/manageiq/network_discovery/port.rb
  spec/lib/network_discovery/discovery_spec.rb
  spec/lib/network_discovery/port_spec.rb
Labels: bug, core

#16997 Fix replication validation for not saved subscriptions
  app/models/pglogical_subscription.rb
  spec/models/pglogical_subscription_spec.rb
Labels: bug, gaprindashvili/yes, replication

#17001 Fix automate specs after MulticastLogger changes
  spec/support/workflow_spec_helper.rb
Labels: blocker, bug/sporadic test failure, gaprindashvili/yes

#17000 Adding classifications for V2V
  db/fixtures/classifications.yml
Labels: enhancement, transformation

#17003 Add miq_product_features to miq_group
  app/models/miq_group.rb
Labels: enhancement

#16902 Fix alerts based on hourly timer for container entities
  app/models/zone.rb
  spec/models/miq_alert_spec.rb
Labels: bug, providers/containers

#17009 Fix errors in help message
  spec/tools/miqldap_to_sssd/cli_spec.rb
  spec/tools/miqldap_to_sssd/configure_apache_spec.rb
  spec/tools/miqldap_to_sssd/miqldap_configuration_spec.rb
  tools/miqldap_to_sssd/cli.rb
  tools/miqldap_to_sssd/configure_apache.rb
  tools/miqldap_to_sssd/converter.rb
  tools/miqldap_to_sssd/miqldap_configuration.rb
  tools/miqldap_to_sssd/sssd_conf.rb
  tools/miqldap_to_sssd/sssd_conf/sssd.rb
Labels: authentication, bug, gaprindashvili/yes

#17007 Add sui_product_features method to miq_group
  app/models/miq_group.rb
  spec/models/miq_group_spec.rb
Labels: enhancement

#17008 Change from collect to pluck for feature_identifiers
  app/models/miq_user_role.rb
Labels: cleanup

#17004 Update gettext_i18n_rails_js to 1.3.0
  Gemfile
Labels: dependencies, gaprindashvili/no, internationalization

#16894 Removed LDAP Models that are no longer used
  app/models/ldap_domain.rb
  app/models/ldap_group.rb
  app/models/ldap_management.rb
  app/models/ldap_region.rb
  app/models/ldap_server.rb
  app/models/ldap_user.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  config/settings.yml
  db/fixtures/miq_product_features.yml
  spec/models/ldap_domain_spec.rb
  spec/models/ldap_server_spec.rb
  spec/models/ldap_user_spec.rb
  spec/models/miq_schedule_worker/runner_spec.rb
Labels: gaprindashvili/no, technical debt

#16998 Handle group names with encoded special characters
  app/models/authenticator/httpd.rb
  spec/models/authenticator/httpd_spec.rb
Labels: authentication, bug, gaprindashvili/yes

#16833 Singularize plural model
  app/models/asset_detail.rb
  app/models/asset_details.rb
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/physical_server.rb
  spec/factories/asset_details.rb
Labels: gaprindashvili/no, providers/physical

#15884 [REARCH] Container workers
  app/models/manageiq/providers/base_manager/metrics_collector_worker.rb
  app/models/miq_ems_metrics_processor_worker.rb
  app/models/miq_event_handler.rb
  app/models/miq_generic_worker.rb
  app/models/miq_priority_worker.rb
  app/models/miq_reporting_worker.rb
  app/models/miq_schedule_worker.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/stop.rb
  app/models/miq_server/worker_management/monitor/system_limits.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  app/models/miq_ui_worker.rb
  app/models/miq_ui_worker/runner.rb
  app/models/miq_vim_broker_worker.rb
  app/models/miq_web_service_worker.rb
  app/models/miq_websocket_worker.rb
  app/models/miq_worker.rb
  app/models/miq_worker/container_common.rb
  app/models/miq_worker/deployment_per_worker.rb
  app/models/miq_worker/replica_per_worker.rb
  app/models/miq_worker/service_worker.rb
  app/models/mixins/per_ems_worker_mixin.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: core/workers, enhancement, gaprindashvili/no

#16939 Add MiqRequest factory with MiqApproval
  spec/factories/miq_request.rb
Labels: test

#16960 Transformation Plan, Request, and Task for V2V
  app/models/miq_request.rb
  app/models/resource_action_workflow.rb
  app/models/service_template.rb
  app/models/service_template_provision_task.rb
  app/models/service_template_transformation_plan.rb
  app/models/service_template_transformation_plan_request.rb
  app/models/service_template_transformation_plan_task.rb
  spec/factories/miq_request.rb
  spec/factories/miq_request_task.rb
  spec/factories/service_template.rb
  spec/models/miq_request_spec.rb
  spec/models/service_template_transformation_plan_request_spec.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: transformation

#17025 Add the artemis auth info as env variables in worker containers
  lib/container_orchestrator/object_definition.rb
Labels: core/queue, enhancement, gaprindashvili/no

#17028 Differentiate being in a container vs running in OpenShift/k8s
  app/models/authenticator/httpd.rb
  app/models/embedded_ansible_worker/runner.rb
  app/models/miq_group.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/system_limits.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  app/models/miq_ui_worker/runner.rb
  app/models/miq_worker.rb
  lib/miq_environment.rb
  spec/models/embedded_ansible_worker/runner_spec.rb
Labels: core, enhancement, gaprindashvili/no

#16878 Update the human description for "cpu_used_delta_summation"
  locale/en.yml
Labels: bug, gaprindashvili/yes, internationalization

#17019 Add lans as a virtual relationship to ems_cluster
  app/models/ems_cluster.rb
  app/models/mixins/aggregation_mixin/methods.rb
Labels: transformation

#16882 Graph refresh skeletal precreate
  app/models/manager_refresh/inventory_collection.rb
  app/models/manager_refresh/inventory_collection/data_storage.rb
  app/models/manager_refresh/inventory_collection/index/proxy.rb
  app/models/manager_refresh/inventory_collection/index/type/skeletal.rb
  app/models/manager_refresh/inventory_collection/reference.rb
  app/models/manager_refresh/inventory_collection/scanner.rb
  app/models/manager_refresh/inventory_object_lazy.rb
  app/models/manager_refresh/save_collection/saver/base.rb
  app/models/manager_refresh/save_collection/saver/concurrent_safe.rb
  app/models/manager_refresh/save_collection/saver/concurrent_safe_batch.rb
  app/models/manager_refresh/save_collection/saver/sql_helper.rb
Labels: enhancement, providers/inventory

#17002 Group chargeback report for VMs by tenant
  app/models/chargeback.rb
  app/models/chargeback/consumption_history.rb
  app/models/chargeback/consumption_with_rollups.rb
  app/models/chargeback/consumption_without_rollups.rb
  app/models/chargeback/report_options.rb
  app/models/chargeback_vm.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/metering_vm_spec.rb
Labels: enhancement, gaprindashvili/yes

#17032 Fix build methods
  app/models/manager_refresh/inventory_collection/data_storage.rb
  spec/models/manager_refresh/persister/finders_spec.rb
Labels: bug, providers/inventory

#16946 Activate network discovery refactor
  Gemfile
  app/models/host.rb
Labels: dependencies, enhancement, gaprindashvili/no

#16980 Inventory task
  app/models/ext_management_system.rb
  app/models/host.rb
  lib/tasks/evm.rake
  spec/lib/extensions/virtual_total_spec.rb
  spec/models/ext_management_system_spec.rb
  spec/models/host_spec.rb
Labels: core, enhancement

#16825 Tower 3.2.2 vault credential types
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/vault_credential.rb
Labels: enhancement, gaprindashvili/yes

#17027 Update vm transformation status in a plan
  app/models/service_template_provision_task.rb
  app/models/service_template_transformation_plan.rb
  app/models/service_template_transformation_plan_request.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, transformation

#16981 Get targeted arel query automatically
  app/models/manager_refresh/application_record_iterator.rb
  app/models/manager_refresh/inventory_collection.rb
  app/models/manager_refresh/inventory_collection/scanner.rb
  app/models/manager_refresh/inventory_collection_default.rb
  app/models/manager_refresh/inventory_collection_default/cloud_manager.rb
  app/models/manager_refresh/inventory_collection_default/network_manager.rb
Labels: enhancement

#16918 Add circular reference association check to import for ui update
  lib/services/dialog_import_service.rb
  spec/lib/services/dialog_import_service_spec.rb
Labels: enhancement, gaprindashvili/yes

#16318 EMS infra: adds Openstack undercloud discovery
  app/models/ext_management_system.rb
  app/models/host.rb
  spec/models/ext_management_system_spec.rb
Labels: enhancement

#17041 Fix failing test now that vCloud supports destroy
  spec/models/vm_or_template_spec.rb
Labels: providers, test

#17012 Use arel to build local_db multiselect condition
  app/models/manager_refresh/inventory_collection/index/type/local_db.rb
Labels: enhancement, providers/inventory

#16886 query also archived objects for a new ems
  app/models/manager_refresh/inventory_collection_default.rb
Labels: bug, providers/inventory

#17045 Add #orderable? as alias method
  app/models/service_template_transformation_plan.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: bug, gaprindashvili/yes, transformation

#17033 Changes to catch the retirement requester in automate.
  app/models/mixins/retirement_mixin.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, gaprindashvili/yes

#16991 remove MiqReport#includes that are unnecessary
  app/models/miq_report/generator.rb
  spec/models/miq_report_spec.rb
Labels: core, enhancement, reporting, ui

#16817 #1518279 For all roles that have sui product features adds sui_notifications
  db/fixtures/miq_user_roles.yml
Labels: bug, gaprindashvili/yes

#17020 Compare decimal columns correctly in batch saver
  app/models/manager_refresh/save_collection/saver/base.rb
  app/models/manager_refresh/save_collection/saver/concurrent_safe_batch.rb
  spec/models/manager_refresh/helpers/spec_parsed_data.rb
  spec/models/manager_refresh/save_inventory/init_data_helper.rb
  spec/models/manager_refresh/save_inventory/saver_strategies_spec.rb
Labels: enhancement, gaprindashvili/yes

#17042 Stop container workers cleanly
  app/models/miq_server/worker_management/monitor/quiesce.rb
  lib/container_orchestrator.rb
Labels: core/workers, enhancement, gaprindashvili/no

#16938 [Changelog] Update for Sprint 78 and Gaprindashvili release
  CHANGELOG.md
Labels: documentation

#16996 Rename new guest device pages
  app/models/guest_device.rb
  app/models/physical_server.rb
  locale/en.yml
Labels: enhancement, providers/physical

#17016 Display thresholds in evm_status for workers
  lib/tasks/evm_application.rb
Labels: enhancement, tools

#16690 Support Automate Git repos without master branch
  lib/git_worktree.rb
  spec/fixtures/git_repos/no_master.git/HEAD
  spec/fixtures/git_repos/no_master.git/config
  spec/fixtures/git_repos/no_master.git/objects/43/0ff1dcee43d2e8a12c3ba36f5ff20e46136152
  spec/fixtures/git_repos/no_master.git/objects/44/f84e202a8eb9d8d35fc183ae8637db3b003aa8
  spec/fixtures/git_repos/no_master.git/objects/78/3878cb3ed5964c75767141176c80f7d528abb5
  spec/fixtures/git_repos/no_master.git/objects/95/99fdeb034597d90d72d2f58396dee096885b79
  spec/fixtures/git_repos/no_master.git/objects/ae/fde3a01f6e10d72fd4899ce14c8b2654d3eb45
  spec/fixtures/git_repos/no_master.git/objects/e3/16f7d7548ea8f874c872ff3be04f4e9849833b
  spec/fixtures/git_repos/no_master.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  spec/fixtures/git_repos/no_master.git/objects/fd/b4bc8c22f4b3ca8279c2e1eb92670893473d05
  spec/fixtures/git_repos/no_master.git/packed-refs
  spec/fixtures/git_repos/no_master.git/refs/.gitkeep
  spec/fixtures/git_repos/no_master.git/refs/tags/tag1
  spec/fixtures/git_repos/no_master.git/refs/tags/tag2
  spec/lib/git_worktree_spec.rb
Labels: automate, bug

#17050 test realtime metrics purging
  spec/models/metric/purging_spec.rb
Labels: core, providers/metrics, test

#17037 Raise a notification when registration fails
  Gemfile
  app/models/miq_server/update_management.rb
  db/fixtures/notification_types.yml
  spec/models/miq_server/update_management_spec.rb
Labels: bug, core, dependencies, gaprindashvili/yes

#17054 Fix rake `evm:status` and `evm:status_full`
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: bug

#17057 Enhance logging around remove snapshot operations
  app/models/vm_or_template/operations/snapshot.rb
Labels: fine/yes, gaprindashvili/yes, providers

#17049 Make Taggable of AutomationManager's authentications/playbooks/repos
  app/models/manageiq/providers/automation_manager/authentication.rb
  app/models/manageiq/providers/automation_manager/configuration_script_payload.rb
  app/models/manageiq/providers/automation_manager/configuration_script_source.rb
Labels: enhancement, providers/ansible_tower

#17060 [EUWE] Workaround failed VCR for vCloud NetworkManager
  spec/models/manageiq/providers/vmware/network_manager/refresher_spec.rb
Labels: test

#16957 Loosen kubeclient to >=2.4 <3.0
  Gemfile
Labels: bug, dependencies, gaprindashvili/yes

#17048 Add title display message and factory for Vault Credentials
  locale/en.yml
  spec/factories/authentication.rb
Labels: automate, enhancement, gaprindashvili/no

#16942 Make db restore more reliable
  lib/evm_database_ops.rb
  lib/tasks/evm_dba.rake
  spec/lib/evm_database_ops_spec.rb
Labels: bug, core, dependencies, gaprindashvili/yes

#17051 Allow individual tables to be specified for metrics
  app/models/metric.rb
  spec/models/metric_spec.rb
Labels: bug, enhancement, providers/metrics

#17029 Automatically fetch the right unique index
  app/models/manager_refresh/save_collection/saver/base.rb
  app/models/manager_refresh/save_collection/saver/sql_helper.rb
  app/models/vm_or_template.rb
Labels: enhancement, providers/inventory

#17053 Silence replicator spec puts
  spec/tools/server_settings_replicator/server_settings_replicator_spec.rb
Labels: test
