Repository ManageIQ/manageiq, pull requests merged in 2018-06, with the labels that each got.

#17497 Extend support from memberof to other multi-value attribute for group membership
  config/settings.yml
  lib/miq_ldap.rb
  spec/lib/miq_ldap_spec.rb
Labels: authentication, bug

#17498 Specs for Vm#{used_storage,provisioned_storage}
  spec/models/vm_or_template_spec.rb
Labels: test

#17509 Create a virtual column for `archived` for using in the API
  app/models/service_template.rb
Labels: enhancement

#17439 Add feature to allow downloading private keys
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/cloud

#17189 Refactor MiqReport#_generate_table
  app/models/miq_report.rb
  app/models/miq_report/generator.rb
  app/models/miq_report/generator/trend.rb
Labels: refactoring, reporting

#17376 NOR covers 30 days
  app/models/metric/long_term_averages.rb
  app/models/vm_or_template/right_sizing.rb
  spec/models/metric_spec.rb
  spec/models/vm_or_template_spec.rb
Labels: bug, providers/metrics

#17510 Change DBA tool to use the adapter extensions
  tools/dba.rb
Labels: technical debt, tools

#17380 Save Physical Storage Model
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/physical_storage.rb
Labels: enhancement, providers/physical

#17508 Raise an event on failed login attempt
  app/models/authenticator/base.rb
  db/fixtures/miq_event_definition_sets.csv
  db/fixtures/miq_event_definitions.csv
  spec/models/authenticator/database_spec.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/authenticator/ldap_spec.rb
  spec/models/authenticator_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#17511 Ancestry Patch updates/fixes
  app/models/tenant.rb
  lib/patches/ancestry_patch.rb
  spec/models/tenant_spec.rb
Labels: bug

#17512 Join object and block storage under ems_storage in the features tree
  db/fixtures/miq_product_features.yml
Labels: rbac

#17515 Remove ansible_tower_client version dependency
  Gemfile
Labels: dependencies

#17526 Explicitly shortcut "everything" for privileges
  app/models/miq_user_role.rb
Labels: core, rbac

#17529 [GAPRINDASHVILI] v2v plugin for GAPRINDASHVILI
  Gemfile
Labels: dependencies

#17539 move #my_zone from ArchivedMixin to OldEmsMixin
  app/models/container.rb
  app/models/container_group.rb
  app/models/container_image.rb
  app/models/container_node.rb
  app/models/container_project.rb
  app/models/mixins/archived_mixin.rb
  app/models/mixins/old_ems_mixin.rb
Labels: bug, gaprindashvili/yes

#17537 Add Flavor model to :tag_classes: section in miq_expression.yml.
  config/miq_expression.yml
Labels: bug

#17348 Inventory Collection Builder
  app/models/manager_refresh/inventory/persister.rb
  app/models/manager_refresh/inventory_collection.rb
  app/models/manager_refresh/inventory_collection/builder.rb
  app/models/manager_refresh/inventory_collection/builder/automation_manager.rb
  app/models/manager_refresh/inventory_collection/builder/cloud_manager.rb
  app/models/manager_refresh/inventory_collection/builder/infra_manager.rb
  app/models/manager_refresh/inventory_collection/builder/network_manager.rb
  app/models/manager_refresh/inventory_collection/builder/persister_helper.rb
  app/models/manager_refresh/inventory_collection/builder/shared.rb
  app/models/manager_refresh/inventory_collection/builder/storage_manager.rb
  app/models/manager_refresh/inventory_object.rb
  spec/models/manager_refresh/inventory_collection/builder_spec.rb
Labels: providers/inventory, refactoring

#17440 Integrate with external Tower Workflow
  app/models/configuration_workflow.rb
  app/models/manageiq/providers/automation_manager.rb
  app/models/manageiq/providers/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/embedded_automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/external_automation_manager.rb
  app/models/manageiq/providers/external_automation_manager/configuration_workflow.rb
  app/models/manager_refresh/inventory/automation_manager.rb
  app/models/manager_refresh/inventory/core.rb
  spec/factories/configuration_script.rb
  spec/factories/ext_management_system.rb
Labels: enhancement, providers/ansible_tower

#17525 Fix multiple parents error moving vm to new folder
  app/models/ems_refresh/link_inventory.rb
  spec/models/ems_refresh/link_inventory_spec.rb
Labels: bug, providers/vmware/infra

#17548 Adding miq_feature to Physical Switch restart
  db/fixtures/miq_product_features.yml
Labels: enhancement, gaprindashvili/no, providers/physical

#17554 LdapRegion, LdapDomain and LdapServer models are gone
  app/models/zone.rb
  locale/en.yml
  spec/factories/ldap_region.rb
Labels: cleanup, core, gaprindashvili/no, technical debt

#17528 Add tests for rbac on ansible playbooks and authentications
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, providers/ansible_tower, test

#17541 Don't include MiqRequestMixin in the RSpec example group
  spec/models/miq_request_spec.rb
Labels: technical debt, test

#17550 Remove product features related to the unused old dialog editor
  db/fixtures/miq_product_features.yml
Labels: cleanup, gaprindashvili/no

#17533 [FINE] Support Unregister VM
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/operations.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb
Labels: enhancement, providers/rhevm

#17516 No event will be shown when a compliance policy is created for a Physical Infra
  db/fixtures/miq_event_definitions.csv
Labels: bug, providers/physical, providers/physical/lenovo

#17557 Add physical infra related default collections
  app/models/manager_refresh/inventory_collection_default/physical_infra_manager.rb
Labels: enhancement, providers/physical

#17570 Skip Vm reconnect if already reconnected
  app/models/manager_refresh/inventory_collection/builder/shared.rb
Labels: bug, providers/inventory

#17389 Add built in policy to prevent transformed VM from starting.
  app/models/service_template_transformation_plan_task.rb
  db/fixtures/classifications.yml
  product/policy/built_in_policies.yml
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, gaprindashvili/yes, transformation

#17569 Make user_timezone method for MiqReportResult public
  app/models/miq_report_result.rb
Labels: gaprindashvili/no, reporting

#17532 Add display name for Physical Server (Redfish)
  locale/en.yml
Labels: enhancement, gaprindashvili/no, providers/physical

#17405 Restrict Vm Operating System detection for XP
  app/models/operating_system.rb
Labels: bug, providers/inventory

#17571 Added IC Builder definition for Tower Workflow
  app/models/manager_refresh/inventory_collection/builder/automation_manager.rb
Labels: providers/ansible_tower, providers/inventory

#17390 Fixing the refresh to remove all physical switches.
  app/models/ems_refresh/save_inventory_infra.rb
Labels: bug, providers/inventory

#17562 Allow models to include methods for MiqExpression sql evaluation
  app/models/hardware.rb
  app/models/vm_or_template.rb
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
  spec/models/vm_or_template_spec.rb
Labels: blocker, gaprindashvili/yes

#17572 Add display name for Credential (RHV)
  app/models/manageiq/providers/embedded_ansible/automation_manager/rhv_credential.rb
Labels: gaprindashvili/no, internationalization

#17544 Allow duplicate nil pxe_image_types during seed (for the current region)
  app/models/customization_template.rb
  spec/lib/unique_within_region_validator_spec.rb
  spec/models/customization_template_spec.rb
Labels: bug

#17538 Replace remove duplicate timestamp by sql version for chargeback
  app/models/chargeback/consumption_history.rb
  app/models/chargeback/report_options.rb
Labels: blocker

#17552 Get rid off query "All in One" in Chargeback
  app/models/chargeback/consumption_history.rb
  spec/models/chargeback_vm_spec.rb
Labels: blocker, chargeback, performance

#17543 [FINE] Shouldn't be able to submit required field without a value
  app/models/dialog_field.rb
  app/models/dialog_field_sorted_item.rb
  spec/models/dialog_field_spec.rb
Labels: blocker, bug

#17472 Move the EmsRefresherMixin into the base Refresher
  app/models/ems_refresh/refreshers/ems_refresher_mixin.rb
  app/models/manageiq/providers/base_manager/refresher.rb
Labels: providers/inventory, refactoring

#17555 Miscellaneous Factory cleanup
  spec/factories/auth_key_pair_amazon.rb
  spec/factories/auth_key_pair_cloud.rb
  spec/factories/auth_key_pair_openstack.rb
  spec/factories/authentication.rb
  spec/factories/automation_request.rb
  spec/factories/file_depot.rb
  spec/factories/file_depot_ftp.rb
  spec/factories/miq_database.rb
  spec/factories/miq_request.rb
  spec/factories/miq_schedule_worker.rb
  spec/factories/miq_template.rb
  spec/factories/miq_worker.rb
  spec/factories/template_azure.rb
  spec/factories/template_google.rb
  spec/factories/template_microsoft.rb
  spec/factories/template_redhat.rb
  spec/factories/template_vmware.rb
  spec/factories/template_vmware_cloud.rb
  spec/factories/vm_amazon.rb
  spec/factories/vm_azure.rb
  spec/factories/vm_google.rb
  spec/factories/vm_microsoft.rb
  spec/factories/vm_openstack.rb
  spec/factories/vm_or_template.rb
  spec/factories/vm_redhat.rb
  spec/factories/vm_vmware.rb
  spec/factories/vm_vmware_cloud.rb
Labels: cleanup, gaprindashvili/no, test

#17504 Fix to show vm/image related info in audit log when deleting vm/image
  app/models/mixins/process_tasks_mixin.rb
Labels: control, enhancement

#17523 Adds support for Physical Chassis in the UI
  app/models/physical_chassis.rb
  config/miq_expression.yml
  db/fixtures/miq_user_roles.yml
  locale/en.yml
Labels: enhancement, providers/physical, providers/physical/lenovo

#17585 Cash cloud volumes in ChargebackVm
  app/models/chargeback_vm.rb
  spec/lib/miq_expression_spec.rb
  spec/models/chargeback_vm_spec.rb
Labels: blocker, chargeback

#17564 Add simple wrapping code for running ansible-playbook
  lib/ansible/runner.rb
Labels: enhancement, providers

#17581 Add resource relation to MiqSchedule
  app/models/miq_schedule.rb
Labels: core, gaprindashvili/yes, refactoring

#17560 Use pluck on metric rollup query in chargeback
  app/models/chargeable_field.rb
  app/models/chargeback/consumption_history.rb
  app/models/chargeback/consumption_with_rollups.rb
  app/models/metric/chargeback_helper.rb
  app/models/metric_rollup.rb
  spec/models/chargeable_field_spec.rb
  spec/models/chargeback/consumption_with_rollups_spec.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/metric_rollup/chargeback_helper_spec.rb
Labels: blocker, bug, chargeback, gaprindashvili/yes

#17578 Add policy event host_failure.
  db/fixtures/miq_event_definitions.csv
Labels: control, enhancement, events, gaprindashvili/no

#17588 MiqSchedule call method directly if available
  app/models/miq_schedule.rb
  spec/models/miq_schedule_spec.rb
Labels: core, enhancement, gaprindashvili/yes

#17524 Added separate features for Requests subtabs
  db/fixtures/miq_product_features.yml
Labels: enhancement, gaprindashvili/no

#17597 Update Automate quota_helper spec test.
  spec/support/quota_helper.rb
Labels: automate

#17590 Add faster MiqReportResult helper methods for viewing saved report results
  app/models/miq_report_result.rb
Labels: enhancement, reporting

#17589 Add tool to remove grouping from report results
  tools/remove_grouping_from_report_results.rb
Labels: enhancement, gaprindashvili/yes, tools

#17598 Add save hooks on MiqReportResult to remove groupings
  app/models/miq_report_result.rb
  spec/models/miq_report_result_spec.rb
Labels: blocker, enhancement, gaprindashvili/yes, reporting

#17605 Add `nil` check for report.extras on save hooks
  app/models/miq_report_result.rb
Labels: blocker, gaprindashvili/yes, reporting

#17596 Add RBAC feature for Migration (v2v).
  db/fixtures/miq_product_features.yml
Labels: enhancement, rbac

#17418 convert tag.category to a regular association
  app/models/tag.rb
  spec/models/ems_refresh/save_inventory/save_tags_inventory_spec.rb
  spec/models/tag_spec.rb
Labels: refactoring

#17612 Rename the v2v plugin gem name
  Gemfile
Labels: bug, dependencies

#17451 Keep track of the server ids where the automate task has been processed.
  app/models/miq_provision/state_machine.rb
  app/models/miq_request_task/state_machine.rb
  app/models/mixins/miq_request_mixin.rb
  spec/models/service_template_provision_task_spec.rb
Labels: automate, enhancement, gaprindashvili/no

#17553 Fixed the virtual columns to be able to use in the API with `filter[]`
  app/models/mixins/archived_mixin.rb
  app/models/service_template.rb
Labels: bug, gaprindashvili/yes, services

#17606 Remove conversion to UTC in Chargeback
  app/models/chargeback/report_options.rb
Labels: blocker, bug, chargeback, fine/yes, gaprindashvili/yes

#17602 Fixed InventoryCollection Vm and Template
  app/models/manager_refresh/inventory_collection/builder/shared.rb
Labels: bug, providers/inventory

#17607 Reject empty button groups from the result of #custom_actions
  app/models/mixins/custom_actions_mixin.rb
  spec/models/mixins/custom_actions_mixin_spec.rb
Labels: api, bug, core

#17594 Scheduling catalog items
  app/models/service_template.rb
  spec/models/miq_schedule_spec.rb
  spec/models/service_template_spec.rb
Labels: enhancement

#17618 Remove useless EmsRefresherMixin
  app/models/ems_refresh/refreshers/ems_refresher_mixin.rb
  app/models/manageiq/providers/base_manager/manager_refresher.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/refresher.rb
  app/models/manageiq/providers/storage_manager/cinder_manager/refresher.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresher.rb
  lib/generators/provider/templates/app/models/manageiq/providers/%provider_name%/cloud_manager/refresher.rb
Labels: cleanup, providers/inventory, refactoring

#17615 Changes custom_attribute virtual_attributes to support AREL/SQL
  app/models/miq_report.rb
  app/models/miq_report/generator.rb
  app/models/mixins/custom_attribute_mixin.rb
Labels: blocker, core, enhancement

#17481 [GAPRINDASHVILI] Add ArchivedMixin to ServiceTemplate
  app/models/mixins/archived_mixin.rb
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: blocker, enhancement

#17625 Ensure sorting does not happen when sort_by is set to "none"
  app/models/dialog_field_sorted_item.rb
  spec/models/dialog_field_sorted_item_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#17519 Support moving a VM to another folder during VM Migrate.
  app/models/vm_migrate_task.rb
  app/models/vm_or_template/operations/relocation.rb
  product/dialogs/miq_dialogs/vm_migrate_dialogs.yaml
  spec/models/vm_migrate_task_spec.rb
Labels: enhancement, gaprindashvili/no

#17622 [RFE]Added 64 and 128gb to provision dialogs
  product/dialogs/miq_dialogs/miq_provision_dialogs.yaml
  product/dialogs/miq_dialogs/miq_provision_microsoft_dialogs_template.yaml
  product/dialogs/miq_dialogs/miq_provision_redhat_dialogs_clone_to_vm.yaml
  product/dialogs/miq_dialogs/miq_provision_redhat_dialogs_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_cluster_dialogs_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_dialogs_clone_to_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_dialogs_clone_to_vm.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_dialogs_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_folder_dialogs_template.yaml
Labels: enhancement, providers/microsoft/infra, providers/rhevm, providers/vmware/infra, provisioning

#17635 Extract Vmdb::Loggers::Instrument to its own file
  lib/vmdb/loggers.rb
  lib/vmdb/loggers/instrument.rb
Labels: refactoring

#17586 Adjusting ManageIQ core to enable PhysicalStorage API endpoint
  app/models/physical_storage.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
Labels: enhancement

#17631 Set value of static text box to default when default exists
  app/models/dialog_field.rb
  spec/models/dialog_field_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#17629 [GAPRINDASHVILI] Use AREL for custom_attributes virtual_attributes in MiqReport ONLY
  app/models/miq_report.rb
  app/models/miq_report/generator.rb
  app/models/mixins/custom_attribute_mixin.rb
Labels: blocker, core, enhancement, fine/yes

#17563 Remove <<reset_all>> magic value from Settings
  lib/vmdb/settings.rb
  spec/lib/vmdb/settings_spec.rb
Labels: refactoring

#17633 Add a method to remove a disk from a VM
  app/models/vm_or_template/operations/configuration.rb
  spec/models/vm_or_template/operations/configuration_spec.rb
Labels: enhancement, providers/vmware/infra

#17639 [GAPRINDASHVILI] Filter relevant fields also according to chargeback class in Chargeback
  app/models/chargeable_field.rb
  app/models/chargeback.rb
  app/models/chargeback_rate.rb
  app/models/chargeback_rate_detail.rb
  spec/models/chargeback_rate_spec.rb
  spec/models/chargeback_vm_spec.rb
Labels: blocker, bug, chargeback

#17620 Fix ordering of metric rollups in consumption history
  app/models/chargeback/consumption_history.rb
Labels: gaprindashvili/yes

#17290 Add configuration_script_sources.last_update_error
  app/models/manager_refresh/inventory/core.rb
Labels: enhancement, providers/ansible_tower

#17637 Add array support to configure_server_settings.rb
  tools/configure_server_settings.rb
Labels: enhancement, tools

#17634 Add an ansible_tower_log to vmdb loggers
  lib/vmdb/loggers.rb
Labels: enhancement, providers/ansible_tower

#17644 Use Hash lookup for MiqTask.human_status
  app/models/miq_task.rb
Labels: refactoring

#17609 Add Polish to chargeback currencies
  db/fixtures/chargeback_rate_detail_currencies.yml
Labels: chargeback, enhancement

#17651 Adding title and cve's to openscap_rule_result creation
  app/models/openscap_result.rb
  spec/models/openscap_result_spec.rb
Labels: enhancement

#17643 Add Vmdb::Plugins#asset_paths and #load_inflections
  app/models/dialog.rb
  app/models/miq_dialog.rb
  app/models/miq_report/import_export.rb
  config/application.rb
  lib/embedded_ansible.rb
  lib/vmdb/inflections.rb
  lib/vmdb/plugins.rb
  lib/vmdb/plugins/ansible_content.rb
  lib/vmdb/plugins/asset_path.rb
  lib/vmdb/settings.rb
  spec/lib/vmdb/plugins_spec.rb
  spec/models/dialog_spec.rb
  spec/models/ems_event_spec.rb
  spec/models/miq_dialog_spec.rb
Labels: refactoring

#17654 Add factory :ansible_tower_workflow_job.
  spec/factories/orchestration_stack.rb
Labels: enhancement, services

#17647 Change reconfigure setup to include values configured with originally
  app/models/dialog.rb
  app/models/dialog_field.rb
  app/models/dialog_field_drop_down_list.rb
  app/models/dialog_field_sorted_item.rb
  app/models/resource_action_workflow.rb
  app/models/service.rb
  spec/models/dialog_field_drop_down_list_spec.rb
  spec/models/dialog_field_radio_button_spec.rb
  spec/models/dialog_field_sorted_item_spec.rb
  spec/models/dialog_field_spec.rb
  spec/models/dialog_spec.rb
  spec/models/resource_action_workflow_spec.rb
  spec/models/service_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#17632 Return with HTML table instead of PDF in the saved report async task
  app/models/miq_report_result.rb
Labels: enhancement, gaprindashvili/no, reporting

#17656 Remove Request taggable and prevent tag filtering
  app/models/miq_request.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes, rbac

#17650 Fixes undefined method `name` error during CSV validation required for v2v migration
  app/models/transformation_mapping.rb
  app/models/vm.rb
  spec/models/transformation_mapping_spec.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#17311 Adding connection b/w physical servers and physical switches
  app/models/computer_system.rb
  app/models/guest_device.rb
  app/models/hardware.rb
  app/models/physical_network_port.rb
  app/models/physical_server.rb
Labels: enhancement, providers/physical, providers/physical/lenovo
