Repository ManageIQ/manageiq, pull requests merged in 2018-09, with the labels that each got.

#17937 Always return 0 for missing num_cpu
  app/models/vm_or_template.rb
Labels: bug, providers/inventory

#17706 Save Canister Model
  app/models/canister.rb
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/manageiq/providers/inventory/persister/builder/physical_infra_manager.rb
  app/models/physical_storage.rb
Labels: enhancement, providers/physical

#17939 Add product feature for displaying custom button events
  db/fixtures/miq_product_features.yml
Labels: enhancement, gaprindashvili/no, rbac

#17934 Remove leftovers about metering column from chargeback
  app/models/chargeback_container_image.rb
  app/models/chargeback_container_project.rb
  db/fixtures/miq_report_formats.yml
  spec/factories/chargeback_rate.rb
  spec/factories/chargeback_rate_detail.rb
  spec/models/chargeback_container_image_spec.rb
  spec/models/chargeback_container_project_spec.rb
  spec/models/chargeback_vm_spec.rb
Labels: chargeback, technical debt

#17942 Fix of inventory building and refactoring
  app/models/manageiq/providers/base_manager/refresher.rb
  app/models/manageiq/providers/inventory.rb
Labels: bug, providers/inventory

#17945 Fixing Computer System relationship on Physical Storage
  app/models/physical_storage.rb
Labels: bug, providers/physical

#17918 Do not duplicate same notification if user belongs to several groups
  app/models/notification_type.rb
  spec/models/notification_spec.rb
  spec/models/notification_type_spec.rb
Labels: bug, core

#17847 rake locale:plugin:find fixes
  lib/tasks/locale.rake
Labels: gaprindashvili/no, internationalization

#17926 Add method to allow access for tenant quotas
  app/models/mixins/tenant_quotas_mixin.rb
  app/models/tenant.rb
  spec/models/mixins/tenant_quotas_mixin_spec.rb
Labels: bug, gaprindashvili/no

#16799 Service retirement values from dialog
  app/models/service.rb
  app/models/service/dialog_properties.rb
  app/models/service/dialog_properties/retirement.rb
  app/models/service_template.rb
  spec/models/service/dialog_properties/retirement_spec.rb
  spec/models/service/dialog_properties_spec.rb
  spec/models/service_template_spec.rb
Labels: blocker, enhancement, fine/yes, gaprindashvili/yes, services

#17941 Add physical chassis details builder
  app/models/manageiq/providers/inventory/persister/builder/physical_infra_manager.rb
Labels: enhancement, providers/inventory, providers/physical

#17930 fix: with_role_excluding has bad subquery
  app/models/miq_group.rb
  app/models/miq_user_role.rb
  app/models/user.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/miq_group_spec.rb
  spec/models/miq_user_role_spec.rb
  spec/models/user_spec.rb
Labels: bug, rbac

#17837 Configure and start the failover monitor from the core app
  Gemfile
  app/models/miq_server/role_management.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/pglogical_subscription.rb
  lib/evm_database.rb
  spec/lib/evm_database_spec.rb
  spec/models/pglogical_subscription_spec.rb
Labels: blocker, core, dependencies, enhancement, gaprindashvili/no

#17914 [FINE] Fog google upgrade (to 1.3.3)
  Gemfile
  app/models/manageiq/providers/google/cloud_manager/event_catcher/stream.rb
  app/models/manageiq/providers/google/cloud_manager/event_parser.rb
  app/models/manageiq/providers/google/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/google/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/google/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/google/event_catcher_mixin.rb
  app/models/manageiq/providers/google/network_manager/refresh_parser.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/google/cloud_manager/event_catcher/event_data/GceOperationDone_compute.instances.delete.json
  spec/models/manageiq/providers/google/cloud_manager/event_catcher/event_data/GceOperationDone_compute.instances.insert.json
  spec/models/manageiq/providers/google/cloud_manager/event_catcher/event_data/GceOperationDone_compute.instances.start.json
  spec/models/manageiq/providers/google/cloud_manager/event_catcher/event_data/GceOperationDone_compute.instances.stop.json
  spec/models/manageiq/providers/google/cloud_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/google/cloud_manager/event_parser_spec.rb
  spec/models/manageiq/providers/google/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/google/event_catcher_mixin_spec.rb
  spec/models/manageiq/providers/google/network_manager/refresh_parser_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/google/cloud_manager/refresher.yml
Labels: blocker, dependencies, enhancement

#17940 Add accessors for physical chassis tree
  app/models/physical_chassis.rb
Labels: enhancement, providers/physical

#17962 Remove useless columns from ChargebackVm#report_options
  app/models/chargeback_vm.rb
Labels: chargeback, gaprindashvili/no, technical debt

#17936 [FINE] fog google upgrade 1.5.0
  Gemfile
  app/models/manageiq/providers/google/network_manager/refresh_parser.rb
  spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/google/cloud_manager/refresher.yml
Labels: dependencies, providers/google, providers/inventory

#17965 Add an alias for InventoryRefresh -> ManagerRefresh
  app/models/aliases/inventory_refresh.rb
Labels: enhancement, providers/inventory

#17828 Add Cloud Volume Type features
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/openstack/cloud

#17927 Memoize cols_on_metric_rollup in chargeback
  app/models/chargeable_field.rb
Labels: chargeback, performance

#17960 Update rugged to v0.27.0 for ruby 2.5
  Gemfile
Labels: dependencies

#17948 Removing of Inventory::Builder
  app/models/manageiq/providers/base_manager/manager_refresher.rb
Labels: cleanup, providers/inventory

#17975 virtual column for `default_security_group` to make it accessible via the API
  app/models/cloud_tenant.rb
Labels: enhancement, transformation

#17957 Consolidate production env checks
  lib/vmdb/deprecation.rb
Labels: bug, core

#17974 Remove line from metering_container_image_spec and FIX CI failure
  spec/models/metering_container_image_spec.rb
Labels: bug/sporadic test failure, chargeback

#17933 Shared persistor definitions plus adding ServiceInstance
  app/models/ext_management_system.rb
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
  app/models/service_instance.rb
  app/models/service_offering.rb
  app/models/service_parameters_set.rb
Labels: enhancement

#17973 Load all the values along with their key names into the field update method
  app/models/dialog.rb
  app/models/resource_action_workflow.rb
  spec/models/dialog_spec.rb
Labels: bug

#17956 Add replication set-up methods to be queued on UI side
  app/models/pglogical_subscription.rb
  lib/miq_pglogical.rb
  spec/models/pglogical_subscription_spec.rb
  spec/replication/util/miq_pglogical_spec.rb
Labels: bug, core, replication

#17980 Add ability to run tagged core specs in plugin repos.
  lib/generators/provider/templates/lib/tasks_private/spec.rake
  lib/tasks/test_providers_common.rake
  spec/models/event_stream_spec.rb
Labels: test

#17981 Remove backtick from dialog_properties_spec.rb
  spec/models/service/dialog_properties_spec.rb
Labels: bug, test

#17976 virtual column for parent blue folder path with excluded non-display folders
  app/models/transformation_mapping.rb
  app/models/vm_or_template.rb
Labels: enhancement, transformation

#17983 Fix spec failure that depends on dialog fields being sorted
  spec/models/resource_action_workflow_spec.rb
Labels: bug/sporadic test failure, test

#17964 Add Switch model to RBAC
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, rbac

#17825 Enable cancel operation for service template transformation plan request
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/service_template_provision_request.rb
  app/models/service_template_transformation_plan_request.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_request_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, transformation

#17986 Add regex for dialog password fields.
  app/models/miq_request_workflow.rb
  spec/models/miq_request_workflow_spec.rb
Labels: automate, bug, gaprindashvili/yes

#17959 Allow ems to terminate connection after use
  app/models/ext_management_system.rb
Labels: enhancement, providers

#17731 Add Ownership and Tenancy Mixins to Authentication
  app/models/authentication.rb
  app/models/miq_group.rb
  app/models/tenant.rb
  app/models/user.rb
Labels: blocker, bug, providers/openstack/cloud

#17987 Prevent queueing things for a zone that doesn't exist in the region
  app/models/miq_queue.rb
  spec/lib/extensions/ar_nested_count_by_spec.rb
  spec/lib/tasks/evm_application_spec.rb
  spec/models/miq_action_spec.rb
  spec/models/miq_queue_spec.rb
  spec/models/miq_request_spec.rb
  spec/models/miq_task_spec.rb
  spec/models/mixins/authentication_mixin_spec.rb
Labels: bug, core/queue

#17636 Add sysprep support for oVirt provider
  db/fixtures/customization_templates.yml
  product/dialogs/miq_dialogs/miq_provision_redhat_dialogs_clone_to_vm.yaml
  product/dialogs/miq_dialogs/miq_provision_redhat_dialogs_template.yaml
  tmp/.gitkeep
Labels: enhancement, gaprindashvili/no, providers/rhevm

#17894 Add file splitting to evm:db tasks (V2)
  lib/evm_database_ops.rb
  lib/tasks/evm_dba.rake
  spec/lib/evm_database_ops_spec.rb
Labels: core, enhancement, gaprindashvili/no

#17994 Fixed spelling error
  lib/vmdb/config/validator.rb
Labels: gaprindashvili/yes

#17972 Fix Physical Disks save inventory
  app/models/ems_refresh/save_inventory_physical_infra.rb
Labels: bug, providers/physical/lenovo

#17998 Failing to set_tenant
  app/models/ems_refresh/save_inventory.rb
Labels: bug, providers/inventory

#17881 [GAPRINDASHVILI] Remove doubled call to retire service parts in bundle
  app/models/service/retirement_management.rb
  spec/models/service/retirement_management_spec.rb
Labels: blocker, bug

#17995 Fix to handle the case when default value of internal is nil
  app/models/service_template.rb
Labels: bug

#17985 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#17364 Add VmMigrationValidator.
  app/models/transformation_mapping.rb
  app/models/transformation_mapping/vm_migration_validator.rb
  app/models/vm.rb
  spec/models/transformation_mapping_spec.rb
Labels: enhancement, transformation

#17999 Fixed error with replication setup when default exclude list used
  lib/miq_pglogical.rb
  spec/replication/util/miq_pglogical_spec.rb
Labels: bug, core, gaprindashvili/no, replication

#18006 Added access to MyTasks to self_service roles
  db/fixtures/miq_user_roles.yml
Labels: bug

#18007 Lock Gemfile to tag reference for release builds
  lib/tasks/release.rake
Labels: gaprindashvili/yes

#18008 Removed TODO: as no longer needed.
  lib/vmdb/util.rb
Labels: cleanup, core, gaprindashvili/no

#18009 Fix possible spec failure due to array ordering
  spec/lib/tasks/evm_application_spec.rb
Labels: bug/sporadic test failure

#18011 Add ems_cluster_id to vms returned by validator
  app/models/transformation_mapping/vm_migration_validator.rb
  spec/models/transformation_mapping_spec.rb
Labels: enhancement, transformation

#18010 Establish a new connection instead of reconnect!
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_server.rb
  app/models/miq_server/environment_management.rb
  app/models/miq_server/queue_management.rb
Labels: bug, core, gaprindashvili/no

#18000 Add :cinder_volume_types to SupportsFeatureMixin
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/openstack/cloud

#17938 Add CPU, CPU cores and MEMORY metering allocation to Metering reports
  app/models/chargeback/consumption_with_rollups.rb
  app/models/chargeback/consumption_without_rollups.rb
  app/models/metering.rb
  app/models/metering_container_image.rb
  app/models/metering_container_project.rb
  app/models/metering_vm.rb
  db/fixtures/chargeable_fields.yml
  spec/models/metering_container_image_spec.rb
  spec/models/metering_container_project_spec.rb
  spec/models/metering_vm_spec.rb
Labels: enhancement

#18013 Add Redfish event catcher
  lib/workers/miq_worker_types.rb
Labels: enhancement, providers/physical/redfish

#17954 Add scope in model ability to RBAC
  app/models/custom_button_event.rb
  app/models/generic_object.rb
  app/models/mixins/custom_actions_mixin.rb
  lib/rbac/filterer.rb
  spec/models/mixins/custom_actions_mixin_spec.rb
Labels: enhancement, rbac

#18003 ActiveRecord::Base models must have tables
  app/models/compute_node.rb
  spec/automated_review/ar_models_must_have_tables_spec.rb
Labels: providers/physical, technical debt

#17996 update attribute_builder for rails change
  lib/extensions/ar_virtual.rb
  spec/lib/extensions/ar_virtual_spec.rb
Labels: bug, core, rails5

#18017 Rescue NoMethodError to prevent requeueing something that won't work
  app/models/mixins/process_tasks_mixin.rb
  spec/models/mixins/process_tasks_mixin_spec.rb
Labels: bug, hammer/yes

#18019 Remove todo with virtual attr inclusion in attr list
  app/models/service_retire_task.rb
Labels: cleanup

#18024 Prepare compat for vmdb config removal
  app/models/miq_server/configuration_management.rb
  app/models/miq_server/ntp_management.rb
  app/models/miq_worker.rb
  app/models/miq_worker/runner.rb
  lib/tasks/evm_settings.rake
  lib/vmdb/config.rb
  lib/vmdb/settings.rb
  lib/vmdb/settings/activator.rb
  lib/vmdb/settings/validator.rb
  spec/lib/vmdb/settings/validator_spec.rb
  spec/models/miq_server/configuration_management_spec.rb
  spec/tools/miqldap_to_sssd/configure_appliance_settings_spec.rb
  tools/change_server_zone.rb
  tools/configure_server_settings.rb
Labels: core, hammer/no, technical debt

#17919 Add a patch to ActiveRecord::Migration for tracking replicated migrations
  app/models/miq_region.rb
  lib/extensions/ar_migration.rb
  spec/lib/extensions/ar_migration_spec.rb
  spec/models/miq_region_spec.rb
Labels: blocker, bug, core, hammer/yes

#17842 Detect and log long running http(s) requests
  app/models/mixins/miq_web_server_runner_mixin.rb
  config/application.rb
  lib/request_started_on_middleware.rb
  spec/lib/request_started_on_middleware_spec.rb
Labels: core, enhancement, gaprindashvili/yes

#18025 Properly create tenant default group for population
  app/models/miq_group.rb
  spec/models/tenant_spec.rb
Labels: bug, hammer/yes, tenancy

#18028 Hide the password values in the log messages.
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
Labels: bug, gaprindashvili/yes, services

#18021 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#18027 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation

#18031 Do not double encrypt a protected password dialog text field
  app/models/dialog_field_text_box.rb
  spec/models/dialog_field_text_box_spec.rb
Labels: bug, hammer/yes

#18032 Validate towhat policy field
  app/models/miq_policy.rb
  spec/models/miq_policy_spec.rb
Labels: bug, hammer/yes
