Repository ManageIQ/manageiq, pull requests merged in 2018-10, with the labels that each got.

#18020 Fixed MiqExpression evaluation on tagged Services
  app/models/condition.rb
  spec/models/condition_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#18018 Updates for Ivanchuk
  app/models/miq_worker.rb
  lib/vmdb/appliance.rb
  lib/vmdb/deprecation.rb
Labels: enhancement, hammer/no

#17989 Fix ServiceTemplateTransformationPlan edit action
  app/models/service_template_transformation_plan.rb
  app/models/service_template_transformation_plan/validate_config_info.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: hammer/yes

#18041 Queue reporting work for any zone
  app/models/miq_queue.rb
  app/models/miq_report/generator.rb
  app/models/miq_report/generator/async.rb
  app/models/miq_widget.rb
  spec/models/miq_report/async_spec.rb
  spec/models/miq_report/generator_spec.rb
  spec/models/miq_widget_spec.rb
Labels: bug, core/queue, gaprindashvili/yes, hammer/yes

#18042 Create custom button events for each object in target list
  app/models/custom_button.rb
  spec/models/custom_button_spec.rb
Labels: bug, hammer/yes

#18036 Currently on a successful ActionResult (start / stop) we return nil
  app/models/mixins/inter_region_api_method_relay.rb
  spec/models/mixins/inter_region_api_method_relay_spec.rb
Labels: bug, core, gaprindashvili/yes, hammer/yes

#18048 Remove unused association
  app/models/manageiq/providers/cloud_manager.rb
Labels: refactoring

#18047 Fix typo in message if VM has no provider
  app/models/vm_or_template/operations.rb
Labels: bug, hammer/yes, providers/vmware/infra

#17988 [GAPRINDASHVILI] Add log messages to chargeback
  app/models/chargeback.rb
  app/models/chargeback/consumption_history.rb
  app/models/chargeback_rate_detail.rb
  app/models/mixins/assignment_mixin.rb
Labels: blocker, chargeback, enhancement

#18049 Fix ordering in list of custom buttons
  app/models/custom_button_set.rb
  spec/models/custom_button_set_spec.rb
Labels: gaprindashvili/yes, hammer/yes

#18051 Don't start memcached in any container runtime
  lib/miq_environment.rb
Labels: bug, core, hammer/yes

#17978 [GAPRINDASHVILI] Scope ui and api server searches to recently active servers
  app/models/miq_region.rb
  app/models/miq_server.rb
  spec/models/miq_region_spec.rb
Labels: blocker, bug, core

#18023 Properly serialize OrchestrationStack class name for MiqRetireTask.request_type
  app/models/service_retire_task.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#17963 Removing unused method for action's support testing
  app/models/storage.rb
  spec/models/storage_spec.rb
Labels: rbac, technical debt

#18045 Add OSP attributes to VM ServiceResource options
  app/models/service_template_transformation_plan/validate_config_info.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: hammer/yes

#18054 Removed experimental uri method type
  app/models/miq_ae_method.rb
Labels: technical debt

#17638 [GAPRINDASHVILI] Update gettext catalogs for gaprindashvili update
  locale/manageiq.pot
Labels: internationalization

#18033 Add methods to conversion_host to build virt-v2v wrapper options
  app/models/conversion_host.rb
  app/models/service_template_transformation_plan_task.rb
  config/settings.yml
  spec/models/conversion_host_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: technical debt, transformation

#18056 Force targets to be an array so we can each them in cb run on multiple objects
  app/models/custom_button.rb
  spec/models/custom_button_spec.rb
Labels: bug, hammer/yes

#18014 Move from apache module mod_auth_kerb to mod_auth_gssapi
  spec/tools/miqldap_to_sssd/configure_apache_spec.rb
  tools/miqldap_to_sssd/configure_apache.rb
Labels: enhancement

#18067 Don't use interpolation in gettext strings
  app/models/miq_request.rb
  app/models/miq_request_task.rb
Labels: hammer/yes, internationalization

#18069 Don't translate FileDepot types
  app/models/file_depot.rb
Labels: hammer/yes, internationalization

#18040 [HAMMER] Update i18n catalog for hammer
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/manageiq.pot
  locale/zanata.xml
  locale/zh_CN/manageiq.po
Labels: internationalization

#17514 Add delete notification types for Network Router
  db/fixtures/notification_types.yml
Labels: enhancement, providers/network

#17971 Conversion script for mapped tags/classification from remote regions to global
  tools/convert_mapped_tags.rb
Labels: enhancement, tools

#18071 Bower cleanup
  .gitignore
  .gitlab-ci.yml
  bin/setup
  bin/update
  lib/manageiq/environment.rb
Labels: dependencies, hammer/yes, ui

#18073 Handle a blank value for the http_proxy host
  lib/vmdb/util.rb
  spec/lib/vmdb/util_spec.rb
Labels: bug, core

#18075 show VmClonedEvent in timelines
  config/settings.yml
Labels: enhancement, events, providers/vmware/infra

#17851 Add tenant filtering for templates in provisioning and summary pages
  app/models/manageiq/providers/cloud_manager/template.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/manageiq/providers/cloud_manager/template_spec.rb
Labels: blocker, gaprindashvili/yes, hammer/yes

#18060 Order custom buttons by array of ids
  app/models/custom_button.rb
  app/models/custom_button_set.rb
  spec/models/custom_button_set_spec.rb
  spec/models/custom_button_spec.rb
Labels: gaprindashvili/yes, hammer/yes

#18068 [GAPRINDASHVILI] Prevent queueing things for a zone that doesn't exist in the region
  app/models/miq_queue.rb
  spec/lib/extensions/ar_nested_count_by_spec.rb
  spec/models/miq_action_spec.rb
  spec/models/miq_queue_spec.rb
  spec/models/miq_request_spec.rb
  spec/models/miq_task_spec.rb
  spec/models/mixins/authentication_mixin_spec.rb
Labels: blocker, bug

#18070 Add `virtual_has_one` for `transformation_mapping` for API accessibility
  app/models/service_template_transformation_plan.rb
Labels: hammer/yes

#18084 Parse automation attrs correctly
  app/models/miq_retire_task.rb
Labels: bug, gaprindashvili/yes, hammer/yes

#18064 Backport methods from Automate to conversion_host - part2
  app/models/conversion_host.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/conversion_host_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: hammer/yes, technical debt, transformation

#18066 Script to copy reports access from group to role
  spec/tools/copy_reports_structure_spec.rb
  tools/copy_reports_structure.rb
  tools/copy_reports_structure/report_structure.rb
Labels: enhancement, gaprindashvili/yes, hammer/yes, tools

#18077 Rails 5.1/5.0 compatibility: Use constant since string/symbol was removed
  config/application.rb
Labels: hammer/no, rails5.1

#18092 Don't use special characters in ansible passwords
  lib/embedded_ansible.rb
  spec/lib/embedded_ansible_spec.rb
Labels: blocker, bug, core, hammer/yes

#18079 Rails 5.0/5.1 Use o.reload.assoc, assoc(true) is gone
  app/models/service_template_ansible_tower.rb
Labels: hammer/no, rails5.1

#18078 Rails 5.0/5.1 prepare_binds_for_database is gone
  lib/miq_expression.rb
Labels: hammer/no, rails5.1

#18080 Rails 5.0/5.1 compatibility: Define through association before has many through
  app/models/storage.rb
  app/models/vm.rb
Labels: hammer/no, rails5.1

#18061 Add flag for init of defaults in fields
  app/models/resource_action_workflow.rb
  app/models/service_template.rb
  config/settings.yml
  spec/models/resource_action_workflow_spec.rb
  spec/models/service_template_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#18058 For database dumps don't modify the directory name
  lib/evm_database_ops.rb
  lib/tasks/evm_dba.rake
Labels: enhancement, hammer/yes

#18096 [GAPRINDASHVILI] Skip tags without classification assigments
  app/models/mixins/assignment_mixin.rb
  spec/models/mixins/assignment_mixin_spec.rb
Labels: blocker, bug, chargeback

#18099 [GAPRINDASHVILI] Add flag for init of defaults in fields on g
  app/models/resource_action_workflow.rb
  app/models/service_template.rb
  config/settings.yml
  spec/models/resource_action_workflow_spec.rb
  spec/models/service_template_spec.rb
Labels: blocker, bug

#18097 Add ext_management_system method to conversion host
  app/models/conversion_host.rb
Labels: enhancement, hammer/yes, transformation

#17944 [GAPRINDASHVILI] Add requester info to log message
  app/models/mixins/retirement_mixin.rb
Labels: bug

#18089 Disable transactions in locking examples
  spec/models/vmdb_database_connection_spec.rb
Labels: hammer/no, rails5.1

#18094 [HAMMER] [Changelog] Update for beta1.1
  CHANGELOG.md
Labels: documentation

#18072 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#18103 Conversion Host - Try hostname for SSH and fix MiqSshUtil args
  app/models/conversion_host.rb
Labels: enhancement, hammer/yes, transformation

#18101 Add resource ems_ref and ip addresses to virt-v2v options hash
  app/models/conversion_host.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, hammer/yes, transformation, unmergeable

#18105 RestClient: Support percent encoded proxy user/pass
  lib/patches/rest_client_patch.rb
  lib/vmdb_helper.rb
Labels: blocker, bug, core, gaprindashvili/no, hammer/yes

#18029 Add product setting default for allowing API service ordering
  config/settings.yml
Labels: blocker, bug

#18113 Add object retirement_requester
  app/models/mixins/retirement_mixin.rb
  spec/models/orchestration_stack/retirement_management_spec.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#18117 Don't need the name, since it's mixed in...
  app/models/mixins/retirement_mixin.rb
Labels: bug

#18118 Fix specs using Zone.first instead of creating a zone
  app/models/container_deployment.rb
  spec/factories/ext_management_system.rb
  spec/factories/provider.rb
  spec/models/job_proxy_dispatcher_embedded_scan_spec.rb
  spec/models/job_proxy_dispatcher_spec.rb
  spec/models/job_proxy_dispatcher_vm_miq_server_proxies_spec.rb
  spec/models/metric/statistic_spec.rb
  spec/support/job_proxy_dispatcher_helper.rb
Labels: bug, test

#18065 Adjust VM validity correctly while editing a ServiceTemplate record
  app/models/transformation_mapping.rb
  app/models/transformation_mapping/vm_migration_validator.rb
  spec/models/transformation_mapping_spec.rb
Labels: hammer/yes

#18012 Backend-initiated notifications in v2v for Successful and Failed Requests
  app/models/service_template_transformation_plan_request.rb
  db/fixtures/notification_types.yml
Labels: hammer/yes, transformation

#18104 Retire Task deliver_to_automate now uses tenant_identity
  app/models/miq_retire_task.rb
Labels: bug, hammer/yes

#18131 Fix Exception due to missing #merged_uri parameters in FileDepot parent class
  app/models/file_depot.rb
  spec/models/file_depot_ftp_spec.rb
  spec/models/file_depot_nfs_spec.rb
Labels: bug, core, hammer/yes

#18136 Fix typo in get_conversion_log method
  app/models/conversion_host.rb
Labels: bug, hammer/yes, transformation

#18126 [RFE] Implement normalized_state as a virtual_attribute for reporting
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: enhancement

#17884 Add template methods needed for provision report
  app/models/miq_template.rb
Labels: blocker, hammer/yes

#18102 Dynamic product features according to tenants
  app/models/miq_product_feature.rb
  app/models/tenant.rb
  db/fixtures/miq_product_features.yml
  lib/rbac/authorizer.rb
  spec/models/miq_product_feature_spec.rb
  spec/models/miq_user_role_spec.rb
  spec/models/tenant_spec.rb
  spec/support/evm_spec_helper.rb
Labels: enhancement, rbac, tenancy

#18148 Use images to get registry pods using the registry instead of running it.
  app/models/container_image_registry.rb
Labels: blocker, bug, providers/containers

#18108 Add support for using run_role_async
  app/models/manageiq/providers/ansible_playbook_workflow.rb
  app/models/manageiq/providers/ansible_role_workflow.rb
  app/models/manageiq/providers/ansible_runner_workflow.rb
  spec/models/manageiq/providers/ansible_playbook_workflow_spec.rb
  spec/models/manageiq/providers/ansible_role_workflow_spec.rb
Labels: enhancement, providers

#18147 Fix flavor and security group collection
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: blocker, bug, hammer/yes, transformation

#18135 Add a validation for conversion hosts
  app/models/ext_management_system.rb
  app/models/service_template_transformation_plan_request.rb
  spec/models/service_template_transformation_plan_request_spec.rb
Labels: blocker, enhancement, hammer/yes, transformation

#18030 Adding ansible tags option through cmdline
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: enhancement, providers

#18153 This shouldn't be hardcoded, thanks Keenan...
  app/models/mixins/retirement_mixin.rb
Labels: hammer/yes
