Repository ManageIQ/manageiq, pull requests merged in 2018-04, with the labels that each got.

#17195 Cache MiqExpression.get_col_type in MiqReport::Formatting
  app/models/miq_report/formatting.rb
Labels: performance, reporting

#17240 Log Vm or Template for Create/Update
  app/models/ems_refresh/save_inventory.rb
Labels: providers/inventory

#17200 Add support for non-binary WebMKS websocket
  lib/websocket_proxy.rb
  lib/websocket_webmks_uint8utf8.rb
  spec/lib/websocket_proxy_spec.rb
Labels: enhancement, gaprindashvili/yes

#17244 Fix editing Ansible Credential/Repository for restricted user
  app/models/authentication.rb
  app/models/configuration_script_payload.rb
  app/models/configuration_script_source.rb
  app/models/manageiq/providers/automation_manager/authentication.rb
  app/models/manageiq/providers/automation_manager/configuration_script_payload.rb
  app/models/manageiq/providers/automation_manager/configuration_script_source.rb
Labels: blocker, bug, gaprindashvili/yes

#17222 Resolve string handling for "https://" or "http://" in update_rhsm_conf
  app/models/registration_system.rb
  spec/models/registration_system_spec.rb
Labels: blocker, bug, core

#17229 Providers discovery without unspecified discovery types (FIX)
  lib/manageiq/network_discovery/discovery.rb
Labels: bug, providers

#17235 Fix update_attributes to take right number of args
  app/models/miq_retire_task.rb
Labels: bug, retirement

#17168 Accept non symbol values from settings
  app/models/manager_refresh/inventory_collection.rb
  app/models/manager_refresh/save_inventory.rb
Labels: bug

#17247 Give more information on a failed configuration validation.
  app/models/authenticator.rb
  app/models/authenticator/ldap.rb
  lib/vmdb/config/validator.rb
  lib/vmdb/settings.rb
  spec/lib/vmdb/settings_spec.rb
Labels: bug

#16853 Add a Physical Rack model
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/physical_rack.rb
  app/models/physical_server.rb
Labels: enhancement, providers/physical

#17213 Add remote console feature for physical servers
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/physical

#17089 Add image_create to product features
  db/fixtures/miq_product_features.yml
Labels: enhancement, gaprindashvili/no

#17242 Add has_many :miq_requests in ServiceTemplate
  app/models/service_template.rb
Labels: enhancement, transformation

#17157 Use handled_list to get Cinder backups for all accessible tenants
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_parser.rb
Labels: blocker, bug, storage

#17215 Fixed error with dialog expression when virtual column involved
  lib/miq_expression/subst_mixin.rb
  spec/lib/miq_expression/subst_mixin_spec.rb
Labels: bug, gaprindashvili/yes

#17250 Add a setting for ansible job data retention
  Gemfile
  app/models/embedded_ansible_worker/runner.rb
  config/settings.yml
  lib/embedded_ansible.rb
  spec/lib/embedded_ansible_spec.rb
  spec/models/embedded_ansible_worker/runner_spec.rb
Labels: blocker, bug, core, dependencies, gaprindashvili/yes

#17256 Use constant to store ServiceResource status.
  app/models/service_resource.rb
  app/models/service_template_transformation_plan.rb
  app/models/service_template_transformation_plan_request.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_request_spec.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, transformation

#17188 Refactor ensure_nondefault method for chargeback rate
  app/models/chargeback_rate.rb
Labels: bug, gaprindashvili/yes

#17257 Use ENV instead of REGION file when creating db
  lib/tasks/evm_dba.rake
Labels: appliance/console, technical debt

#17204 Add 'breakable' optional argument to report_build_html_table method
  lib/vmdb/global_methods.rb
Labels: bug

#17248 Shift qpid_proton version to 0.22.0
  Gemfile
Labels: dependencies, enhancement, gaprindashvili/yes

#17246 convert Vm#miq_provision_template to has_one
  app/models/vm_or_template.rb
  lib/miq_expression.rb
  lib/miq_expression/field.rb
  spec/lib/miq_expression/field_spec.rb
  spec/models/miq_report/search_spec.rb
  spec/models/vm_or_template_spec.rb
Labels: bug, core, gaprindashvili/yes, reporting

#17260 Removed redundant entries from start up drop down.
  db/fixtures/miq_shortcuts.yml
Labels: bug, gaprindashvili/yes, ui

#17185 Seed plugin ansible playbooks
  app/models/embedded_ansible_worker/object_management.rb
  app/models/manageiq/providers/embedded_ansible/provider/default_ansible_objects.rb
  lib/vmdb/plugins.rb
  spec/models/embedded_ansible_worker_spec.rb
Labels: enhancement, gaprindashvili/yes

#17172 Add product files for physical server dashboard widgets
  app/models/physical_server.rb
  product/dashboard/widgets/chart_server_availability.yaml
  product/dashboard/widgets/chart_server_health.yaml
  product/dashboard/widgets/rss_newest_servers.yaml
  product/reports/190_Configuration Management - Physical Servers/010_Newest Servers.yaml
  product/reports/190_Configuration Management - Physical Servers/020_Server Health.yaml
  product/reports/190_Configuration Management - Physical Servers/030_Server Availability.yaml
  spec/models/miq_report/seeding_spec.rb
  spec/models/miq_widget_spec.rb
Labels: providers/physical

#17267 Set DRb conn pool to [] after closing connections
  app/models/miq_worker.rb
Labels: bug, core/workers

#17269 Require dalli before using it
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_worker/runner.rb
Labels: bug, gaprindashvili/yes

#17265 Add timeout knob for monitoring server roles
  app/models/miq_server/role_management.rb
  config/settings.yml
Labels: enhancement, fine/yes, gaprindashvili/yes

#17261 refactoring let
  spec/models/guest_device_spec.rb
Labels: technical debt

#17263 Upgrade hamlit for compatibility with ruby 2.5.
  Gemfile
Labels: dependencies, developer, gaprindashvili/no

#17232 Improve end of life of resource in metering/chargeback reports
  app/models/chargeback/consumption.rb
  spec/models/metering_vm_spec.rb
Labels: bug, chargeback

#17271 Add cloud volumes for selecting assigned tagged resources
  app/models/chargeback/consumption_without_rollups.rb
  spec/models/chargeback_vm_spec.rb
Labels: bug, chargeback, gaprindashvili/yes

#17181 [GAPRINDASHVILI] Updated translations for gaprindashvili update
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization

#17183 Filter out archived and orphaned VMs in 'Running VMs' filter
  db/fixtures/miq_searches.yml
Labels: bug, fine/yes, gaprindashvili/yes, reporting

#17178 Do not show archived and orphaned VMs on report 'Online VMs (Powered On)'
  product/reports/400_Operations- Virtual Machines/020_Online VMs.yaml
Labels: bug, fine/yes, gaprindashvili/yes, reporting

#17264 Adding scan action with userid to container_image
  app/models/container_image.rb
  app/models/ems_cluster.rb
  app/models/miq_schedule.rb
Labels: bug, gaprindashvili/yes

#17270 Add `:transformation` under product and set it to `true` by default
  config/settings.yml
Labels: enhancement, transformation

#17278 Don't format PersistentVolume-capacity as bytes
  app/models/miq_report/formats.rb
  db/fixtures/miq_report_formats.yml
  spec/models/miq_report/formats_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#17266 Add association of service_templates to TransformationMapping.
  app/models/transformation_mapping.rb
  spec/models/transformation_mapping_spec.rb
Labels: enhancement, transformation

#17279 [EUWE] Change VMware console api detection from vCenter to ESXi Host
  app/helpers/application_helper/toolbar_builder.rb
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: blocker, bug

#17233 Initialize MiqQueue.miq_task_id column when queuing ems-refresh task
  app/models/ems_refresh.rb
  spec/models/ems_refresh_spec.rb
Labels: core, enhancement

#17284 [EUWE] Lock fog-vcloud-director gem to 0.1.8
  Gemfile
Labels: dependencies

#17291 [EUWE] Rerecord Disk Specs
  gems/pending/spec/disk/miq_disk_spec.rb
  gems/pending/spec/recordings/dos_partitions.yml
  gems/pending/spec/recordings/no_partitions.yml
Labels: test

#17283 [FINE] Update bower.json to match ui-classic
  bower.json
Labels: dependencies, ui

#17298 Add method retire_now to container OrchestrationStack.
  app/models/manageiq/providers/container_manager/orchestration_stack.rb
  spec/factories/orchestration_stack.rb
  spec/models/manageiq/providers/container_manager/orchestration_stack_spec.rb
Labels: bug, gaprindashvili/yes

#17299 [FINE] Bump more_core_extensions to 3.5
  Gemfile
Labels: bug, dependencies

#16895 Adding method to change password of a provider on its client
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/mixins/supports_feature_mixin.rb
  spec/models/manageiq/providers/physical_infra_manager/physical_infra_manager_spec.rb
Labels: control, enhancement

#17245 [FINE] Add ownership for MiqRequest in RBAC
  app/models/miq_request.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: blocker, bug

#17294 [FINE] Adds purging for notifications
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/notification.rb
  app/models/notification/purging.rb
  config/settings.yml
  spec/models/notification/purging_spec.rb
Labels: core, performance

#17237 Handle non-existant tag category id when importing a service dialog
  app/models/dialog_field_importer.rb
  spec/models/dialog_field_importer_spec.rb
Labels: bug, gaprindashvili/yes

#14889 Use credential callback to set credentials
  app/models/git_repository.rb
  lib/git_worktree.rb
  lib/git_worktree_exception.rb
  spec/lib/git_worktree_spec.rb
  spec/models/git_repository_spec.rb
Labels: automate, bug, fine/yes, gaprindashvili/yes

#17212 Azure labeling and tagging support
  app/models/container_label_tag_mapping.rb
Labels: blocker, enhancement, fine/yes, gaprindashvili/yes, providers/cloud

#17272 Forcing default_value to an array, if the dynamic dropdown is multiselect
  app/models/dialog_field_radio_button.rb
  app/models/dialog_field_sorted_item.rb
  spec/models/dialog_field_sorted_item_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#16983 Add support for exporting and importing tags
  lib/task_helpers/exports/tags.rb
  lib/task_helpers/imports/tags.rb
  lib/tasks/evm_export_import.rake
  spec/lib/task_helpers/exports/tags_spec.rb
  spec/lib/task_helpers/imports/data/tags/Import_Test.yaml
  spec/lib/task_helpers/imports/data/tags/Location.yaml
  spec/lib/task_helpers/imports/data/tags/Tag_Test_Fail_Cat.yml
  spec/lib/task_helpers/imports/data/tags/Tag_Test_Fail_Cat_Yaml.yml
  spec/lib/task_helpers/imports/data/tags/Tag_Test_Fail_Entry.yml
  spec/lib/task_helpers/imports/data/tags/User_roles.yaml
  spec/lib/task_helpers/imports/tags_spec.rb
Labels: tools

#17255 Fix call to process_tasks to run the right thing
  app/models/mixins/process_tasks_mixin.rb
  app/models/mixins/retirement_mixin.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, retirement

#17234 Add child retirement task methods
  app/models/service_retire_task.rb
  spec/factories/miq_request_task.rb
  spec/models/service_retire_task_spec.rb
Labels: enhancement, retirement

#17308 Fixes for create action in Template model
  app/models/manageiq/providers/cloud_manager/template.rb
Labels: bug, providers/cloud

#17236 Save Physical Chassis
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/physical_chassis.rb
  app/models/physical_rack.rb
  app/models/physical_server.rb
  lib/vmdb/inflections.rb
Labels: enhancement, providers/physical

#17301 Initialize MiqQueue.miq_task_id column when queuing metric capture task
  app/models/metric/ci_mixin/capture.rb
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: core, enhancement

#17309 [FINE] convert Vm#miq_provision_template to has_one
  app/models/vm_or_template.rb
  lib/miq_expression.rb
  lib/miq_expression/field.rb
  lib/miq_expression/tag.rb
  lib/miq_expression/where_extraction_visitor.rb
  spec/lib/miq_expression/field_spec.rb
  spec/models/miq_report/search_spec.rb
  spec/models/vm_or_template_spec.rb
Labels: blocker, bug

#17313 Check for the existence of credentials.
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_spec.rb
Labels: automate, bug, gaprindashvili/yes

#17314 [FINE] fix failing api specs
  spec/requests/api/config_spec.rb
  spec/requests/api/service_dialogs_spec.rb
Labels: api, blocker, bug, test

#17280 Add lock to retire_now start
  app/models/mixins/retirement_mixin.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: retirement

#17297 Change the role for Service provisioning create_request_tasks MiqQueue.put.
  app/models/miq_request.rb
  spec/models/miq_request_spec.rb
Labels: bug, gaprindashvili/yes, provisioning, services

#17322 Revert "Merge pull request #15367"
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, rbac

#17324 Fix infra inventory collections for targeted refresh
  app/models/manager_refresh/inventory_collection_default/infra_manager.rb
Labels: bug, providers/inventory

#17302 Load config/coverage_hook.rb at process creation
  app/models/miq_worker.rb
  config/preinitializer.rb
  lib/code_coverage.rb
Labels: developer, test

#17326 Refactoring of my_role to allow passing 'action' parameter.
  app/models/automation_request.rb
  app/models/miq_host_provision_request.rb
  app/models/miq_provision_configured_system_request.rb
  app/models/miq_provision_request.rb
  app/models/miq_request.rb
  app/models/service_reconfigure_request.rb
  app/models/service_template_provision_request.rb
  app/models/vm_cloud_reconfigure_request.rb
  app/models/vm_migrate_request.rb
  app/models/vm_reconfigure_request.rb
Labels: refactoring

#17319 Don't use _() in model constants
  app/models/service_template.rb
Labels: bug, internationalization

#17335 Provide base graph refresh attributes for ::Snapshot
  app/models/manager_refresh/inventory_collection_default/cloud_manager.rb
Labels: enhancement, gaprindashvili/yes

#17292 [FINE] add tenant to rbac and fix user and miq group
  app/models/miq_group.rb
  app/models/user.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
  spec/lib/services/resource_sharer_spec.rb
  spec/requests/api/collections_spec.rb
  spec/requests/api/groups_spec.rb
  spec/requests/api/services_spec.rb
  spec/requests/api/users_spec.rb
Labels: blocker

#17340 Add logging and update upgrade_message for successful registration
  app/models/miq_server/update_management.rb
Labels: core, enhancement, gaprindashvili/yes

#17312 Add a tool to process logs looking for frequency of method calls
  tools/log_processing/method_call_processor.rb
Labels: core, enhancement, gaprindashvili/no, tools

#17332 GuestDevice model updates for support of storage devices
  app/models/guest_device.rb
  locale/en.yml
Labels: providers/physical

#17343 Removed XClarity Client gem requirement for tests
  spec/models/manageiq/providers/physical_infra_manager/physical_infra_manager_spec.rb
Labels: test

#17350 Add an entry for guest device to en.yml
  locale/en.yml
Labels: internationalization

#17353 Skip playbook seeding for containers
  app/models/embedded_ansible_worker/object_management.rb
  spec/models/embedded_ansible_worker_spec.rb
Labels: bug, core, gaprindashvili/yes

#17177 Add TransformationMapping#validate_vms method
  app/models/transformation_mapping.rb
  app/models/vm.rb
  spec/models/transformation_mapping_spec.rb
Labels: enhancement, transformation

#17334 Add reporting session threshold options in settings
  config/settings.yml
Labels: enhancement, fine/yes, gaprindashvili/yes, ui

#17363 Change dialog import to only use auto_refresh if new triggers are blank
  lib/services/dialog_import_service.rb
  spec/lib/services/dialog_import_service_spec.rb
Labels: bug, gaprindashvili/yes

#17355 Memoize _log.prefix calls
  app/models/miq_request_workflow.rb
Labels: performance

#17351 Add Openstack Cinder EventCatcher worker
  lib/workers/miq_worker_types.rb
Labels: blocker, gaprindashvili/yes

#17366 Add a memcached bind address for tower
  lib/embedded_ansible/appliance_embedded_ansible.rb
  spec/lib/embedded_ansible/appliance_embedded_ansible_spec.rb
Labels: blocker, core, enhancement, gaprindashvili/yes

#17337 Convert backslashes to forward slashes for Azure factory
  spec/factories/vm_azure.rb
Labels: refactoring

#17367 [FINE] Use Settings directly for getting the memcached server address
  lib/embedded_ansible.rb
  spec/lib/embedded_ansible_spec.rb
Labels: blocker, core, enhancement

#17369 Change branch to `alpha` for the nightly builds
  Gemfile
Labels: dependencies, transformation
