Repository ManageIQ/manageiq, pull requests merged in 2018-07, with the labels that each got.

#17658 Add the ability to rename a VM
  app/models/mixins/supports_feature_mixin.rb
  app/models/vm_or_template/operations.rb
Labels: enhancement, providers/vmware/infra

#17058 Make all public images be visible for provisioning.
  app/models/manageiq/providers/cloud_manager/template.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/manageiq/providers/cloud_manager/template_spec.rb
Labels: enhancement, providers

#17593 Extracting physical ports of a switch to a new page
  app/models/physical_network_port.rb
Labels: enhancement, providers/inventory, providers/physical/lenovo

#17614 Normal Operating Range cpu/mem usage rate to use avg (instead of max) values
  app/models/metric/long_term_averages.rb
  app/models/vm_or_template/right_sizing.rb
  spec/models/metric_spec.rb
Labels: bug

#17666 Provider generator: Persister update
  lib/generators/provider/templates/app/models/manageiq/providers/%provider_name%/inventory/persister.rb
  lib/generators/provider/templates/app/models/manageiq/providers/%provider_name%/inventory/persister/cloud_manager.rb
  lib/generators/provider/templates/app/models/manageiq/providers/%provider_name%/inventory/persister/definitions/cloud_collections.rb
Labels: enhancement, providers

#17627 Support for v2v pre/post Ansible playbook service.
  app/models/service_template_transformation_plan.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, transformation

#17662 Miq server zone description
  app/models/miq_server.rb
  spec/models/miq_server_spec.rb
Labels: bug, core

#17668 Adding miq_feature to chassis LED operation
  db/fixtures/miq_product_features.yml
Labels: enhancement, gaprindashvili/no, providers/physical/lenovo

#17672 Add ServiceTemplate#miq_schedules relation
  app/models/service_template.rb
Labels: blocker, core, enhancement, gaprindashvili/yes

#17642 Reuse dialog values so we don't have to reload dialog
  app/models/resource_action_workflow.rb
  app/models/service_template.rb
  spec/models/resource_action_workflow_spec.rb
  spec/models/service_template_spec.rb
Labels: bug, performance

#17677 Validate name uniqueness for Transformation Plans
  app/models/service_template_transformation_plan.rb
  spec/factories/service_template.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: enhancement, services

#17674 The vm_id coming in from API is a string.
  app/models/service_template_transformation_plan.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#17682 Upgrade to use version of openscap gem 0.4.8
  Gemfile
Labels: dependencies

#17670 Scope ui and api server searches to recently active servers
  app/models/miq_region.rb
  app/models/miq_server.rb
  spec/models/miq_region_spec.rb
Labels: bug, core, gaprindashvili/yes

#17679 Remove generic object from all related services before destroy
  app/models/generic_object.rb
  spec/models/generic_object_spec.rb
Labels: bug

#17683 Network Subnet total_vms work correctly
  app/models/cloud_subnet.rb
Labels: bug, ui

#17686 fix MiqGroup#miq_user_role_name
  app/models/entitlement.rb
  app/models/miq_group.rb
  spec/models/miq_group_spec.rb
Labels: bug, core

#17621 InventoryCollection Builder improvements
  app/models/manager_refresh/inventory_collection/builder.rb
  app/models/manager_refresh/inventory_collection/builder/automation_manager.rb
  app/models/manager_refresh/inventory_collection/builder/cloud_manager.rb
  app/models/manager_refresh/inventory_collection/builder/container_manager.rb
  app/models/manager_refresh/inventory_collection/builder/infra_manager.rb
  app/models/manager_refresh/inventory_collection/builder/network_manager.rb
  app/models/manager_refresh/inventory_collection/builder/persister_helper.rb
  app/models/manager_refresh/inventory_collection/builder/physical_infra_manager.rb
  app/models/manager_refresh/inventory_collection/builder/shared.rb
  spec/models/manager_refresh/inventory_collection/builder_spec.rb
Labels: enhancement, gaprindashvili/no, providers/inventory

#17641 [GAPRINDASHVILI] Add option to prov workflow to not rerun methods
  app/models/resource_action_workflow.rb
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: blocker, bug, performance

#17680 Persister: Specs changes for add_collection() interface
  spec/models/manager_refresh/persister/local_db_finders_spec.rb
  spec/models/manager_refresh/persister/test_persister.rb
Labels: providers/inventory, test

#17694 automation_manager should use :manager(_id) instead of :ems_id
  app/models/manager_refresh/inventory_collection/builder/automation_manager.rb
Labels: bug, providers/ansible_tower

#17687 Support cancellation for miq_request and miq_request_task
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/service_template_transformation_plan_request.rb
  app/models/service_template_transformation_plan_task.rb
Labels: enhancement, gaprindashvili/yes, transformation

#17611 Add a new event group level
  app/models/event_stream.rb
  spec/models/ems_event_spec.rb
Labels: enhancement, events

#17695 Stop falling back to old_ems_id, drop OldEmsMixin
  app/models/chargeback_container_image.rb
  app/models/chargeback_container_project.rb
  app/models/container.rb
  app/models/container_group.rb
  app/models/container_image.rb
  app/models/container_node.rb
  app/models/container_project.rb
  app/models/metric/ci_mixin/capture.rb
  app/models/mixins/old_ems_mixin.rb
Labels: gaprindashvili/no, technical debt

#17604 Remove references to host provisioning
  app/models/miq_dialog.rb
  app/models/miq_host_provision.rb
  app/models/miq_host_provision/configuration.rb
  app/models/miq_host_provision/ipmi.rb
  app/models/miq_host_provision/options_helper.rb
  app/models/miq_host_provision/placement.rb
  app/models/miq_host_provision/post_install_callback.rb
  app/models/miq_host_provision/pxe.rb
  app/models/miq_host_provision/rediscovery.rb
  app/models/miq_host_provision/state_machine.rb
  app/models/miq_host_provision/tagging.rb
  app/models/miq_host_provision_request.rb
  app/models/miq_host_provision_workflow.rb
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/miq_request_workflow.rb
  db/fixtures/miq_event_definitions.csv
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  db/fixtures/notification_types.yml
  product/dialogs/miq_dialogs/miq_host_provision_dialogs.yaml
  spec/factories/miq_dialog.rb
  spec/factories/miq_request.rb
  spec/factories/miq_request_task.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/miq_dialog_spec.rb
  spec/models/miq_host_provision_request_spec.rb
  spec/models/miq_host_provision_spec.rb
  spec/models/miq_host_provision_workflow_spec.rb
  spec/models/miq_request_spec.rb
  spec/models/miq_request_task/post_install_callback_spec.rb
Labels: provisioning, technical debt

#17697 Fix import export smartstate analysis
  lib/task_helpers/exports/scan_profiles.rb
Labels: bug, core

#17696 Ensure MiqSchedule#name is unique for ServiceTemplate orders
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: blocker, bug, enhancement, gaprindashvili/yes, provisioning

#17708 Followup to #17695
  app/models/container.rb
  app/models/container_group.rb
  app/models/container_image.rb
  app/models/container_node.rb
  app/models/container_project.rb
Labels: gaprindashvili/no

#17713 Maintenance must run VACUUM to avoid long held locks
  lib/extensions/ar_base.rb
  spec/lib/extensions/ar_base_spec.rb
Labels: bug, core, fine/no, gaprindashvili/yes

#17705 Add a method to queue an Ansible::Runner.run
  lib/ansible/runner.rb
Labels: enhancement, providers

#17717 Fix class name for queueing
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: bug, gaprindashvili/yes, provisioning

#17690 Force user_type to UPN when username is a UPN
  lib/miq_ldap.rb
  spec/lib/miq_ldap_spec.rb
Labels: authentication, blocker, bug, gaprindashvili/yes

#17718 Fix detection of an EMS to use for Storage#scan
  app/models/storage.rb
Labels: bug, providers/vmware/infra

#17719 Remove unmaintained and unused env_probe scripts
  tools/env_probe
  tools/env_probe_README
  tools/env_probe_event_catcher.rb
  tools/env_probe_vc_inv.rb
Labels: technical debt

#17616 Adding PhysicalStorage into PhysicalChassis
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/physical_chassis.rb
  app/models/physical_rack.rb
  app/models/physical_storage.rb
Labels: enhancement, providers/physical, providers/physical/lenovo

#17703 Return custom buttons for service having nil service template
  app/models/service.rb
  spec/models/service_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#17722 Fix ServiceTemplateTransformationPlanTask factory
  spec/factories/miq_request_task.rb
Labels: provisioning, test

#17692 Adding flavor as a has one on VM
  app/models/vm_or_template.rb
Labels: api, bug

#17667 Fill out missing parent_inventory_collections definitions
  app/models/manager_refresh/inventory_collection/builder/infra_manager.rb
Labels: cleanup, providers/inventory

#17712 Service AnsibleTower and EmbeddedAnsible UI parity
  app/models/manageiq/providers/embedded_ansible/automation_manager/job.rb
  app/models/service_ansible_tower.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
Labels: automate, enhancement, providers/ansible_tower

#17729 InventoryCollection definitions for vmware infra
  app/models/manager_refresh/inventory_collection/builder.rb
  app/models/manager_refresh/inventory_collection/builder/infra_manager.rb
Labels: enhancement, providers/inventory

#17730 Fix spec test to resolve sporadic test failure.
  spec/models/orchestration_stack/retirement_management_spec.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug/sporadic test failure, retirement

#17711 Remove Settings.product.transformation - v2v no longer conditional on product feature
  config/settings.yml
Labels: gaprindashvili/no, transformation

#17734 Replace custom_attributes by ems_custom_attributes
  app/models/manageiq/providers/infra_manager.rb
  app/models/manager_refresh/inventory_collection/builder/infra_manager.rb
Labels: enhancement

#17733 [GAPRINDASHVILI] Set Settings.product.transformation to true
  config/settings.yml
Labels: blocker, transformation

#17505 Add host_guest_devices association and inv_collection
  app/models/manageiq/providers/infra_manager.rb
  app/models/manager_refresh/inventory_collection/builder/infra_manager.rb
  app/models/manager_refresh/inventory_collection_default/infra_manager.rb
Labels: enhancement, providers/inventory

#17702 Add support to show Group Level of an event in the timeline page.
  product/timelines/miq_reports/tl_events_daily.yaml
  product/timelines/miq_reports/tl_events_hourly.yaml
Labels: enhancement

#17574 Missing embedded ansible persisters dependencies
  app/models/manageiq/providers/embedded_ansible/inventory/persister/automation_manager.rb
  app/models/manageiq/providers/embedded_ansible/inventory/persister/configuration_script_source.rb
  app/models/manager_refresh/inventory_collection/builder.rb
Labels: bug, providers/ansible_tower

#17725 locale:po_to_json: add support for including catalogs from javascript plugins
  lib/tasks/locale.rake
Labels: gaprindashvili/no

#17744 Start the drb server with a unix socket
  app/models/miq_cockpit_ws_worker/runner.rb
  app/models/miq_server/worker_management.rb
Labels: bug, fine/yes, gaprindashvili/yes, security

#17736 Removing add_inventory_collection and has_inventory interfaces
  app/models/manager_refresh/inventory/automation_manager.rb
  app/models/manager_refresh/inventory/cloud_manager.rb
  app/models/manager_refresh/inventory/core.rb
  app/models/manager_refresh/inventory/middleware_manager.rb
  app/models/manager_refresh/inventory/persister.rb
  app/models/manager_refresh/inventory_collection/builder/automation_manager.rb
  app/models/manager_refresh/inventory_collection_default.rb
  app/models/manager_refresh/inventory_collection_default/cloud_manager.rb
  app/models/manager_refresh/inventory_collection_default/infra_manager.rb
  app/models/manager_refresh/inventory_collection_default/network_manager.rb
  app/models/manager_refresh/inventory_collection_default/physical_infra_manager.rb
  app/models/manager_refresh/inventory_collection_default/storage_manager.rb
  spec/models/manager_refresh/save_inventory/init_data_helper.rb
Labels: cleanup, providers/inventory

#17661 Add relationship between [physical switch and physical chassis] and event stream
  app/models/event_stream.rb
  app/models/physical_chassis.rb
  app/models/physical_switch.rb
Labels: enhancement, events, providers/physical, providers/physical/lenovo

#17753 Added Physical Server view to OOTB Security role.
  db/fixtures/miq_user_roles.yml
Labels: bug, gaprindashvili/yes

#16567 Enable OpenID-Connect in the appliance console.
  lib/tasks/evm_settings.rake
  spec/lib/tasks/evm_settings_spec.rb
Labels: authentication, enhancement, gaprindashvili/no

#17610 Add Cloud Volume Type model
  app/models/cloud_volume_type.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/storage_manager/block_mixin.rb
Labels: enhancement, providers/storage

#17750 Empty project dir no longer needed
  lib/ansible/runner.rb
Labels: enhancement

#17699 Add rake task to export custom buttons
  lib/task_helpers/exports/custom_buttons.rb
  lib/tasks/evm_export_import.rake
  spec/lib/task_helpers/exports/custom_buttons_spec.rb
Labels: enhancement

#17756 Remove useless line in ConsumptionHistory
  app/models/chargeback/consumption_history.rb
Labels: chargeback, technical debt

#17356 Add Memoization to LogProxy.prefix results
  lib/vmdb/logging.rb
Labels: performance

#17735 Connecting physical switch to computer systems
  app/models/guest_device.rb
  app/models/physical_network_port.rb
  app/models/physical_switch.rb
Labels: enhancement, providers/physical, providers/physical/lenovo

#17765 [GAPRINDASHVILI] Scheduling catalog items
  app/models/service_template.rb
  spec/models/miq_schedule_spec.rb
  spec/models/service_template_spec.rb
Labels: enhancement, transformation

#17681 Refactor service_type to use constants
  app/models/mixins/miq_provision_quota_mixin.rb
  app/models/service_template.rb
  app/models/service_template_ansible_playbook.rb
  app/models/service_template_container_template.rb
  app/models/service_template_transformation_plan.rb
  spec/models/service_template_spec.rb
Labels: refactoring, technical debt

#17775 Add pt_BR.yml for Brazilian Portuguese
  locale/pt_BR.yml
Labels: blocker, gaprindashvili/yes, internationalization

#17759 Add a state machine for long ansible operations
  app/models/manageiq/providers/ansible_runner_workflow.rb
  spec/models/manageiq/providers/ansible_runner_workflow_spec.rb
Labels: enhancement, providers

#17728 Add support for new physical server alert
  app/models/ext_management_system.rb
  app/models/miq_alert.rb
  app/models/mixins/assignment_mixin.rb
  app/models/physical_server.rb
  app/models/zone.rb
  db/fixtures/miq_alerts.yml
Labels: enhancement, providers/physical

#17720 ConfigurationWorkflow to exist only in AutomationManager space
  app/models/configuration_workflow.rb
  app/models/manageiq/providers/automation_manager.rb
  app/models/manageiq/providers/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/embedded_automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/external_automation_manager/configuration_workflow.rb
  locale/en.yml
  spec/factories/configuration_script.rb
Labels: providers/ansible_tower

#17783 Options hash should not contain AR objects
  spec/support/quota_helper.rb
  spec/support/service_template_helper.rb
Labels: test
