Repository ManageIQ/manageiq, pull requests merged in 2018-12, with the labels that each got.

#18257 Fix miq request ownership
  app/models/miq_group.rb
  app/models/miq_request.rb
  app/models/user.rb
  spec/models/miq_group_spec.rb
  spec/models/miq_request_spec.rb
  spec/models/user_spec.rb
Labels: automate, bug

#18245 [WIP] Support multiple regions querying user and group owned miq_requests
  app/models/miq_group.rb
  app/models/miq_request.rb
  app/models/user.rb
Labels: automate, bug, wip

#18256 Bump kubeclient to 4.0
  Gemfile
Labels: dependencies

#18259 evm:status always displays status
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: blocker, bug, tools

#18236 Do not rely on the asset pipeline when calling backend PDF generation
  lib/asset_writer.rb
  lib/pdf_generator/prince_pdf_generator.rb
Labels: blocker, bug, gaprindashvili/no, hammer/yes

#18265 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#18093 Use the spinlock-free surro-gate gem for websocket proxying
  Gemfile
  lib/remote_console.rb
  lib/remote_console/adapter.rb
  lib/remote_console/regular_socket.rb
  lib/remote_console/ssl_socket.rb
  lib/remote_console/web_mks.rb
  lib/remote_console/web_mks_legacy.rb
  lib/websocket_adapter.rb
  lib/websocket_adapter/legacy.rb
  lib/websocket_adapter/standard.rb
  lib/websocket_proxy.rb
  lib/websocket_right.rb
  lib/websocket_server.rb
  lib/websocket_socket.rb
  lib/websocket_ssl_socket.rb
  lib/websocket_webmks.rb
  lib/websocket_webmks_uint8utf8.rb
  spec/lib/remote_console/web_mks_legacy_spec.rb
  spec/lib/remote_console/web_mks_spec.rb
  spec/lib/remote_console_spec.rb
  spec/lib/websocket_adapter_spec.rb
  spec/lib/websocket_proxy_spec.rb
  spec/lib/websocket_server_spec.rb
Labels: dependencies, gaprindashvili/no, hammer/no, performance, providers/console

#18272 Synchronize provider with server when zone changes
  app/models/embedded_ansible_worker/runner.rb
  config/settings.yml
  spec/models/embedded_ansible_worker/runner_spec.rb
Labels: bug, changelog/yes, hammer/yes

#18273 Consume surro-gate from github as this way the gemspec gets evaluated
  Gemfile
Labels: dependencies

#18276 Update surro-gate to 1.0.4 to fix compilation issues on OSX
  Gemfile
Labels: dependencies

#18277 Add ConversionHost validations
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, transformation

#18278 Suppress output to stdout and stderr in copy_report_structure_spec.rb
  spec/tools/copy_reports_structure_spec.rb
Labels: gaprindashvili/yes, hammer/yes, test

#18288 [HAMMER] Add FactoryBot alias for FactoryGirl
  spec/support/factory_girl_helper.rb
Labels: gaprindashvili/yes, test

#18287 Remove the FIXME related to URL building in websocket adapter
  lib/websocket_adapter/standard.rb
Labels: question

#18290 Raise a notification for each repo that fails to enable
  app/models/miq_server/update_management.rb
  db/fixtures/notification_types.yml
  spec/models/miq_server/update_management_spec.rb
Labels: blocker, bug, hammer/yes

#18292 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#18274 Change fix_auth database.yml status display
  tools/fix_auth/models.rb
Labels: bug, tools

#18267 Make evm:status common columns more obvious
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: blocker, bug, hammer/yes, tools

#18294 Generator: Use master branch for travis status
  lib/generators/provider/templates/README.md
Labels: test

#18289 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#18225 Virtual attribute reports
  app/models/miq_ae_class.rb
  app/models/provider.rb
  spec/models/container_image_spec.rb
  spec/models/manageiq/providers/base_manager_spec.rb
Labels: reporting

#18299 Fix bad error message
  lib/vmdb/plugins/automate_domain.rb
Labels: enhancement

#17452 Suspend providers
  app/models/ext_management_system.rb
  app/models/miq_queue.rb
  app/models/miq_region.rb
  app/models/miq_server.rb
  app/models/zone.rb
  spec/models/automation_request_spec.rb
  spec/models/custom_button_spec.rb
  spec/models/ext_management_system_spec.rb
  spec/models/miq_queue_spec.rb
  spec/models/miq_server/update_management_spec.rb
  spec/models/miq_server_spec.rb
  spec/models/orchestration_stack_retire_task_spec.rb
  spec/models/service_retire_task_spec.rb
  spec/models/vm_retire_task_spec.rb
  spec/models/zone_spec.rb
  spec/tools/environment_builders/openstack/helper_methods.rb
Labels: enhancement, hammer/yes, providers

#18263 Tenancy for central admin
  app/models/tenant.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, rbac

#18297 Use join_key while building relation sql
  lib/extensions/ar_virtual.rb
  lib/extensions/virtual_total.rb
  spec/lib/extensions/virtual_total_spec.rb
Labels: core, refactoring

#18269 Add byebug gem
  Gemfile
Labels: dependencies, enhancement

#18286 Don't seed tenant product features for tenant from remote region
  app/models/miq_product_feature.rb
  spec/models/miq_product_feature_spec.rb
Labels: blocker, gaprindashvili/yes, hammer/yes

#18284 Add support for exporting and importing reports
  lib/task_helpers/exports/reports.rb
  lib/task_helpers/imports.rb
  lib/task_helpers/imports/reports.rb
  lib/tasks/evm_export_import.rake
  spec/lib/task_helpers/exports/reports_spec.rb
  spec/lib/task_helpers/imports/data/reports/Test_Report.yaml
  spec/lib/task_helpers/imports/data/reports/Test_Report_-_Chargeback.yaml
  spec/lib/task_helpers/imports/data/reports/Test_Report_attr_error.yml
  spec/lib/task_helpers/imports/data/reports/Test_Report_runtime_error.yml
  spec/lib/task_helpers/imports/data/reports/Test_Report_update.yml
  spec/lib/task_helpers/imports/reports_spec.rb
Labels: enhancement, tools

#18281 i18n.fallbacks - update for i18n 1.1
  config/environments/production.rb
Labels: cleanup, core

#18302 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#18261 De-dup git fetches for override_gem
  Gemfile
Labels: dependencies

#17377 edit ManageIQ license info so that GitHub recognizes it
  LICENSE.txt
  README.md
Labels: documentation
