Repository ManageIQ/manageiq, pull requests merged in 2019-10, with the labels that each got.

#19345 Remove scope with_ems in VmOrTemplate
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: technical debt

#19334 Add filtering according to more fields for report result's result set
  app/models/miq_report.rb
  app/models/miq_report_result/result_set_operations.rb
  spec/models/miq_report_result/result_set_operations_spec.rb
Labels: api, enhancement

#19348 Bump rubyzip to 1.3.0 for CVE-2019-16892
  Gemfile
Labels: dependencies

#19346 Add a verify_credentials_task method
  app/models/ext_management_system.rb
  app/models/mixins/authentication_mixin.rb
  app/models/mixins/verify_credentials_mixin.rb
Labels: enhancement, providers/pluggability

#19323 [Ansible::Runner] Add extra ptyhon3 path to PYTHONPATH
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: blocker, embedded ansible, ivanchuk/yes

#19343 CloudNetwork, NetworkPort and SecurityGroup belong to a ResourceGroup
  app/models/cloud_network.rb
  app/models/network_port.rb
  app/models/resource_group.rb
  app/models/security_group.rb
  spec/models/resource_group_spec.rb
Labels: enhancement

#19211 Service display has been renamed to visible.
  app/models/service.rb
  app/models/service_template.rb
Labels: bug, changelog/yes, ivanchuk/no

#19257 Add schedule import specs
  spec/models/miq_schedule_spec.rb
Labels: test

#19352 Remove deprecation warning about virtual custom attributes from report_spec.rb
  spec/models/miq_report_spec.rb
Labels: technical debt

#19355 Move method set_tenant_from_group to OwnershipMixin
  app/models/authentication.rb
  app/models/mixins/ownership_mixin.rb
  app/models/orchestration_stack.rb
  app/models/service.rb
  app/models/vm_or_template.rb
Labels: technical debt, tenancy

#19354 Remove OwnershipMixin from ServiceMixin
  app/models/mixins/service_mixin.rb
Labels: technical debt

#19358 Don't pass a block to expect
  spec/models/authenticator/database_spec.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/authenticator/ldap_spec.rb
  spec/models/user/user_ldap_methods_spec.rb
Labels: test

#19359 Parenthesize .to change {} to prevent ambiguity
  spec/mailers/generic_mailer_spec.rb
  spec/models/authenticator/database_spec.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/authenticator/ldap_spec.rb
  spec/models/custom_button_spec.rb
  spec/models/job_spec.rb
  spec/models/miq_group_spec.rb
  spec/models/service_template/copy_spec.rb
  spec/models/session_spec.rb
  spec/models/vmdb_metric_spec.rb
Labels: test

#19347 Don't use _() in model constants
  app/models/miq_dialog.rb
Labels: bug, internationalization, ivanchuk/yes

#19303 Remove pot file if it exists
  lib/tasks/locale.rake
Labels: bug, internationalization, ivanchuk/yes

#19353 DialogField: Don't use gettext in model constants
  app/models/dialog_field.rb
Labels: bug, internationalization, ivanchuk/yes

#19360 Set zip validate_entry_sizes to true for rubyzip 1.3.0
  lib/vmdb/util.rb
  spec/lib/vmdb/util_spec.rb
Labels: security

#19338 Update factory_bot and timecop
  Gemfile
Labels: dependencies, test

#19318 Rbac no references array
  app/models/application_record.rb
  app/models/miq_report/generator.rb
  lib/acts_as_ar_model.rb
  lib/extensions/ar_references.rb
  lib/rbac/filterer.rb
  spec/lib/extensions/ar_references_spec.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, rails5.2, rbac

#19362 Display is deprecated, use visible
  app/models/service.rb
  spec/models/service_spec.rb
  spec/models/service_template_spec.rb
Labels: services, technical debt

#19229 [HAMMER] log_backtrace won't print backtrace for MiqException errors
  app/models/manageiq/providers/embedded_ansible/provider.rb
Labels: bug

#19364 Don't use raw SQL conditions for WHERE in Hardware model (and fix bugs)
  app/models/hardware.rb
  spec/models/miq_report_spec.rb
Labels: bug, refactoring

#19367 Reload stale source_tenant after destroying self (rails 5.2)
  app/models/manageiq/providers/cloud_manager.rb
  app/models/tenant.rb
Labels: enhancement, rails5.2

#19369 Implicit arel delegation is deprecated, make it explicit (rails 5.2)
  app/models/mixins/purging_mixin.rb
  lib/extensions/ar_taggable.rb
Labels: enhancement, rails5.2

#19366 Convert unsafe SQL to pure active record methods (rails 5.2)
  app/models/mixins/compliance_mixin.rb
  app/models/storage.rb
Labels: enhancement, rails5.2

#19365 Update order of relations in VmOrTemplate.rb
  app/models/vm_or_template.rb
Labels: technical debt

#19371 [V2V] Remove handover from shutdown_vm transition
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: bug, ivanchuk/yes, transformation

#19373 [V2V] Extend InfraConversionJob timeout
  app/models/infra_conversion_job.rb
Labels: bug, ivanchuk/yes, transformation

#19351 [Changelog] Update for Sprint 121
  CHANGELOG.md
Labels: documentation

#19370 Update default_value_for rails 5.2/6 support
  Gemfile
Labels: dependencies, enhancement, rails5.2

#19375 [V2V] Fix progress percentage calculation
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: bug, ivanchuk/yes, transformation

#19372 MiqReport::Generator -- don't use gettext in model constants
  app/models/miq_report/generator.rb
Labels: bug, internationalization, ivanchuk/yes

#19379 Pin sprockets to ~>3.0 to fix missing manifest.js errors
  Gemfile
Labels: core, dependencies

#19376 Removing groups changes users current group
  app/models/miq_group.rb
  spec/models/miq_group_spec.rb
  spec/models/miq_widget_set_spec.rb
Labels: enhancement, rails5.2

#19339 remove pg warning from tests
  lib/extensions/ar_adapter/ar_dba.rb
Labels: core, refactoring

#19127 Improve references
  app/models/miq_report/generator.rb
  app/models/miq_report/search.rb
  app/models/vim_performance_analysis.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: core, ivanchuk/no, performance, rails5.2, rbac, refactoring

#19387 Upgrade to rspec 3.9
  Gemfile
Labels: dependencies

#19356 Adding Volume Snapshot (CloudVolumeSnapshot) to RBAC
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes

#19386 fix schedule_settings
  app/models/miq_schedule_worker/runner.rb
Labels: bug, core, ivanchuk/yes

#19382 ChargebackRateDetail: don't use gettext in model constants
  app/models/chargeback_rate_detail.rb
Labels: bug, internationalization, ivanchuk/yes

#19381 Set default OrchestrationTemplateRunner timeout to 100 minutes.
  app/models/manageiq/providers/cloud_manager/orchestration_template_runner.rb
Labels: bug

#19388 Pluggable ScanItems
  app/models/scan_item.rb
  app/models/scan_item/seeding.rb
  spec/models/scan_item/data/product/scan_items/testing_scan_item.yaml
  spec/models/scan_item/seeding_spec.rb
Labels: enhancement, refactoring

#19235 Make destroying guest_devices faster
  tools/cleanup_duplicate_host_guest_devices.rb
Labels: hammer/yes, ivanchuk/yes, tools

#19393 Generate perfomance reports in specific date range
  app/models/miq_report/generator.rb
  spec/models/miq_report_spec.rb
Labels: enhancement, reporting

#19399 Update sys-filesystem gem to 1.3.1
  Gemfile
Labels: dependencies, hammer/no, ivanchuk/no

#19398 Generate retire requests from the base class name
  app/models/mixins/retirement_mixin.rb
  spec/models/service/retirement_management_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes, retirement

#19408 Adding Volume Type (CloudVolumeType) to RBAC
  lib/rbac/filterer.rb
Labels: bug

#19409 Enumerable#reverse_each is faster than Enumerable#reverse.each
  app/models/miq_action.rb
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: performance, refactoring

#19402 Use add_metric_rollup in generator_spec.rb
  spec/models/miq_report/generator_spec.rb
  spec/support/chargeback_helper.rb
Labels: reporting, technical debt, test

#19404 Remove zanata-related stuff from manageiq
  README.md
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/README.md
  lib/generators/manageiq/plugin/templates/zanata.xml
Labels: internationalization, technical debt

#19134 Utility function to update PxeMenu list
  app/models/pxe_server.rb
  spec/models/pxe_server_spec.rb
Labels: bug, ivanchuk/yes

#19405 Save the updated widget timestamp
  app/models/miq_widget.rb
  spec/models/miq_widget/report_content_spec.rb
Labels: bug

#19389 Update puma to latest. Be less conservative.
  Gemfile
Labels: core, dependencies

#19413 Remove unused Service::RetirementManagement.retire_service_resources method
  app/models/service/retirement_management.rb
  spec/models/service/retirement_management_spec.rb
Labels: technical debt

#19414 Update rubies we test with to latest 2.5 and 2.6.
  .travis.yml
  Gemfile
  spec/lib/ruby_require_leak_spec.rb
Labels: dependencies, ruby2.5, ruby2.6, test

#19416 [V2V] Pin InfraConversionJob to first server where it runs
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: enhancement, ivanchuk/yes, transformation

#19400 Output constant must match the constantized class name
  app/models/miq_server/worker_management/monitor.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
Labels: bug, core/workers

#19411 require specific aws gems
  app/models/file_depot_s3.rb
Labels: dependencies, providers/amazon

#19421 Remove invalid partial from InfraConversionJob specs
  spec/models/infra_conversion_job_spec.rb
Labels: refactoring, test

#19397 Arel-ize vm#num_cpus
  app/models/hardware.rb
  app/models/vm_or_template.rb
  spec/models/hardware_spec.rb
  spec/models/miq_report/generator_spec.rb
  spec/models/vm_or_template_spec.rb
Labels: core, enhancement, ivanchuk/no, performance

#19418 Update to config gem 2.0.0
  Gemfile
  lib/vmdb/settings.rb
Labels: core, dependencies, technical debt

#19422 [IVANCHUK] Lock amazon_ssa_support to ivanchuk branch
  Gemfile
Labels: dependencies

#19423 [HAMMER] Lock amazon_ssa_support to hammer branch
  Gemfile
Labels: dependencies

#19424 [GAPRINDASHVILI] Lock amazon_ssa_support to gaprindashvili branch
  Gemfile
Labels: dependencies

#19412 Prefer block version of File.open to ensure file handle gets automatically closed
  lib/task_helpers/imports/reports.rb
  lib/task_helpers/imports/widgets.rb
Labels: refactoring

#19427 Revert "Prefer block version of File.open to ensure file handle gets automatically closed"
  lib/task_helpers/imports/reports.rb
  lib/task_helpers/imports/widgets.rb
Labels: refactoring

#19391 Allow plugins to bring their own miq_reports
  app/models/miq_report/seeding.rb
Labels: enhancement, providers/pluggability

#19425 Fix MiqSchedule spec with arguments
  spec/models/miq_schedule_spec.rb
Labels: refactoring, test

#19426 Remove(completely) get_col_type from MiqExpression
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: technical debt

#19407 Passes result_format when automate workspace is not expected
  app/models/custom_button.rb
  app/models/resource_action.rb
  spec/models/resource_action_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes

#19428 Remove call of parse_field_or_tag from MiqExpression#operands2rubyvalue
  lib/miq_expression.rb
Labels: technical debt

#19415 Fixed sorting in TenantQuotas report
  app/models/tenant_quota.rb
  product/reports/780_Tenants - Tenant Quotas/001_Tenant Quotas.yaml
  spec/models/tenant_quota_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes, reporting

#19383 Cleanup after Ansible runner.
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/job.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
  app/models/mixins/ansible_playbook_mixin.rb
  app/models/service_ansible_playbook.rb
  app/models/service_template_ansible_playbook.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_spec.rb
  spec/models/service_ansible_playbook_spec.rb
  spec/models/service_template_ansible_playbook_spec.rb
Labels: changelog/yes, enhancement, hammer/no, ivanchuk/yes, services

#19432 Remove require_nested ConfigurationScript
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
Labels: bug

#19436 Reduce the number of gems for AWS SDK usage
  Gemfile
Labels: dependencies

#19438 Update MiqQueue so that partials are valid
  spec/models/miq_queue_spec.rb
Labels: refactoring, test

#19420 Cu schedule collector by ems
  app/models/metric/capture.rb
  app/models/metric/targets.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/zone.rb
  spec/models/metric_spec.rb
Labels: enhancement, performance, providers/metrics

#19401 [V2V] Add VM validation for warm migration eligibility and updated specs to …
  app/models/mixins/supports_feature_mixin.rb
  app/models/service_template_transformation_plan/validate_config_info.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: transformation

#19228 Add support to automate external auth config for ldap
  spec/tools/miq_config_sssd_ldap/auth_establish_spec.rb
  spec/tools/miq_config_sssd_ldap/cli_config_spec.rb
  spec/tools/miq_config_sssd_ldap/cli_convert_spec.rb
  spec/tools/miq_config_sssd_ldap/configure_apache_spec.rb
  spec/tools/miq_config_sssd_ldap/configure_appliance_settings_spec.rb
  spec/tools/miq_config_sssd_ldap/configure_selinux_spec.rb
  spec/tools/miq_config_sssd_ldap/configure_sssd_rules_spec.rb
  spec/tools/miq_config_sssd_ldap/miqldap_configuration_spec.rb
  spec/tools/miq_config_sssd_ldap/sssd_conf_spec.rb
  spec/tools/miqldap_to_sssd/configure_selinux_spec.rb
  tools/miq_config_sssd_ldap.rb
  tools/miq_config_sssd_ldap/auth_establish.rb
  tools/miq_config_sssd_ldap/auth_template_files.rb
  tools/miq_config_sssd_ldap/cli.rb
  tools/miq_config_sssd_ldap/cli_config.rb
  tools/miq_config_sssd_ldap/cli_convert.rb
  tools/miq_config_sssd_ldap/configure_apache.rb
  tools/miq_config_sssd_ldap/configure_appliance_settings.rb
  tools/miq_config_sssd_ldap/configure_database.rb
  tools/miq_config_sssd_ldap/configure_selinux.rb
  tools/miq_config_sssd_ldap/configure_sssd_rules.rb
  tools/miq_config_sssd_ldap/converter.rb
  tools/miq_config_sssd_ldap/miqldap_configuration.rb
  tools/miq_config_sssd_ldap/services.rb
  tools/miq_config_sssd_ldap/sssd_conf.rb
  tools/miq_config_sssd_ldap/sssd_conf/common.rb
  tools/miq_config_sssd_ldap/sssd_conf/domain.rb
  tools/miq_config_sssd_ldap/sssd_conf/ifp.rb
  tools/miq_config_sssd_ldap/sssd_conf/pam.rb
  tools/miq_config_sssd_ldap/sssd_conf/sssd.rb
Labels: authentication, enhancement

#19442 Sprint 122 and 123
  CHANGELOG.md
Labels: documentation

#19450 Disable bundling rubies less than 2.5.3 on master
  Gemfile
Labels: core, dependencies, ruby2.5
