Repository ManageIQ/manageiq, pull requests merged in 2019-04, with the labels that each got.

#18349 simplify MiqWorker.server_scope
  app/models/miq_worker.rb
  spec/models/miq_worker_spec.rb
Labels: core/workers, hammer/no, refactoring

#18611 Fix rbac filterer spec failure on Hammer
  spec/lib/rbac/filterer_spec.rb
Labels: bug/sporadic test failure, hammer/yes, test

#18609 Add retireable check to service ansible playbooks
  app/models/service_ansible_playbook.rb
  app/models/service_retire_task.rb
  spec/models/service_ansible_playbook_spec.rb
  spec/models/service_retire_task_spec.rb
Labels: bug, hammer/yes

#18614 Move vmware provisioning dialogs to vmware repo
  product/dialogs/miq_dialogs/miq_provision_vmware_cluster_dialogs_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_dialogs_clone_to_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_dialogs_clone_to_vm.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_dialogs_template.yaml
  product/dialogs/miq_dialogs/miq_provision_vmware_folder_dialogs_template.yaml
  spec/models/miq_dialog/seeding_spec.rb
Labels: cleanup

#18607 Remove Discover Cloud Providers option in toolbar drop-down
  db/fixtures/miq_product_features.yml
  locale/manageiq.pot
Labels: bug, hammer/yes, technical debt

#18615 Add a tool to assist in reconnecting vms
  tools/reconnect_vms.rb
Labels: providers/inventory, tools

#18622 Update rails to 5.0.7.2
  Gemfile
Labels: dependencies, gaprindashvili/yes, hammer/yes, security

#18623 fix: swap makes vms out of disk space report false positive
  product/reports/100_Configuration Management - Virtual Machines/028_VMs with Volume Free Space -= 20%.yaml
Labels: bug, hammer/yes, reporting

#18621 Fix the save_inventory_spec contexts
  spec/models/ems_refresh/save_inventory_spec.rb
Labels: providers/inventory, test

#18610 [V2V] Allow the ConversionHost#address field to be empty
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: refactoring, transformation

#18620 [HAMMER] Add create_subtasks method to service_retire_task for ansible playbooks
  app/models/service_ansible_playbook.rb
  app/models/service_retire_task.rb
  spec/models/service_ansible_playbook_spec.rb
  spec/models/service_retire_task_spec.rb
Labels: bug

#18630 Use lambda, if validation with a string is deprecated
  app/models/tenant_quota.rb
Labels: rails5.1

#18629 Use string class name instead of hitting autoload
  app/models/cloud_network.rb
  app/models/container_group.rb
  app/models/container_group_performance.rb
  app/models/container_image.rb
  app/models/container_node.rb
  app/models/container_node_performance.rb
  app/models/container_performance.rb
  app/models/container_project_performance.rb
  app/models/container_template.rb
  app/models/conversion_host.rb
  app/models/notification.rb
Labels: core, rails5.1

#18628 Use sanitize_sql to fix deprecation on _conditions
  app/models/miq_region.rb
Labels: core, rails5.1

#18631 fix_auth now handles recursive settings
  lib/vmdb/settings_walker.rb
  spec/lib/vmdb/settings_spec.rb
Labels: bug, tools

#18396 Extract virtual attributes
  Gemfile
  lib/acts_as_ar_model.rb
  lib/extensions/ar_virtual.rb
  lib/extensions/arel_groups.rb
  lib/extensions/virtual_total.rb
  spec/lib/extensions/ar_virtual_spec.rb
  spec/lib/extensions/virtual_total_spec.rb
  spec/support/custom_matchers/have_virtual_column.rb
  spec/support/virtual_attribute_helper.rb
Labels: dependencies, rails5.1

#18600 Dialog fields - make load_values_on_init independent of show_refresh_button
  app/models/dialog_field.rb
  app/models/dialog_field_sorted_item.rb
  app/models/dialog_field_text_box.rb
  spec/models/dialog_field_sorted_item_spec.rb
  spec/models/dialog_field_text_box_spec.rb
Labels: hammer/no

#18638 Retirement - remove auto_approve flag on request creation.
  app/models/mixins/retirement_mixin.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, hammer/yes

#18619 [Changelog] Update for Sprint 108
  CHANGELOG.md
Labels: documentation

#18646 [GAPRINDASHVILI] Lock ansible_tower_client to 0.17.0
  Gemfile
Labels: dependencies

#18636 Check that reconfigure is supported before we try it
  app/models/service.rb
  spec/models/service_spec.rb
Labels: bug, hammer/yes

#18650 Fix for incorrect key sent back for dynamic non sorted items
  app/models/dialog_field_serializer.rb
  spec/models/dialog_field_serializer_spec.rb
Labels: bug, hammer/yes

#18633 Fix Key Pairs from refresh being returned with provider AuthPrivateKeys
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/cloud_manager/auth_key_pair.rb
  app/models/manageiq/providers/cloud_manager/provision/options_helper.rb
  spec/models/manageiq/providers/cloud_manager/provision_workflow_spec.rb
Labels: bug, providers/cloud

#18616 Check ems_ref before uid_ems when saving VMs
  app/models/ems_refresh/save_inventory.rb
  spec/models/ems_refresh/save_inventory_spec.rb
Labels: bug, providers/inventory

#18652 [HAMMER] Fix for incorrect key sent back for dynamic non sorted items
  app/models/dialog_field_serializer.rb
  spec/models/dialog_field_serializer_spec.rb
Labels: bug

#18641 Change simulate_queue_worker for quiet polling
  lib/vmdb/console_methods.rb
Labels: developer

#18654 Fix Container* belongsto filter in Rbac::Filterer
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug

#18653 Fix typos in log messages for InfraConversionThrottler
  lib/infra_conversion_throttler.rb
Labels: technical debt

#18642 Schedule metrics purge with database operations role
  app/models/miq_schedule_worker/runner.rb
  spec/models/miq_schedule_worker/runner_spec.rb
Labels: core, enhancement

#18658 [Changelog] Update for Sprint 109
  CHANGELOG.md
Labels: documentation

#18613 [V2V] Run the playbook on the appliance with the conversion host in inventory
  app/models/conversion_host.rb
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host_spec.rb
Labels: bug, hammer/yes, transformation

#18662 Remove new chargeback spec support
  spec/models/chargeback_container_image_spec.rb
  spec/models/chargeback_container_project_spec.rb
  spec/models/chargeback_vm_spec.rb
Labels: technical debt

#18649 Fix: convert string representation of sizes to numbers when generating SQL for expression
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: bug, hammer/yes, reporting

#18576 [V2V] Add CPU and network throttling in model
  app/models/conversion_host.rb
  app/models/job_proxy_dispatcher.rb
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
  spec/models/conversion_host_spec.rb
Labels: enhancement, hammer/yes, transformation

#18665 [Changelog] Update for Hammer-5
  CHANGELOG.md
Labels: documentation, hammer/yes

#18663 Use admin user in get_user for service show if user's deleted
  app/models/mixins/miq_request_mixin.rb
  spec/models/miq_request_spec.rb
Labels: bug

#18667 Fix sporadic failure on rbac filter array matcher
  spec/lib/rbac/filterer_spec.rb
Labels: bug/sporadic test failure, test

#18637 Retirement warn in days only
  app/models/service/dialog_properties/retirement.rb
  spec/models/service/dialog_properties/retirement_spec.rb
Labels: bug

#18668 Add ProviderObject mixin to the PhysicalServer
  app/models/physical_server.rb
Labels: enhancement

#18669 Move GIT_REPO_DIRECTORY constant from MiqAeDatastore
  app/models/git_repository.rb
  spec/models/git_repository_spec.rb
Labels: refactoring

#18483 [HAMMER] Add check for evm_owner being nil when id is still set
  app/models/mixins/retirement_mixin.rb
  spec/models/orchestration_stack/retirement_management_spec.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug

#18369 Remove value2tag for count field in MiqExpression
  lib/miq_expression.rb
  lib/miq_expression/count_field.rb
  spec/lib/miq_expression_spec.rb
Labels: refactoring, reporting

#18554 Add adhoc tenancy sharing for service templates
  app/models/mixins/tenancy_common_mixin.rb
  app/models/service_template.rb
  app/models/service_template_tenant.rb
  app/models/tenant.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, rbac

#18661 Update fast_gettext to 2.0.1
  Gemfile
Labels: dependencies

#18675 Upgrade gem virtual attributes to 1.1
  Gemfile
Labels: dependencies, rails5.1

#18660 Miscellaneous warning fixes
  app/models/condition.rb
  app/models/miq_request_workflow.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_snmp.rb
  app/models/vm_or_template.rb
  spec/models/miq_queue_spec.rb
Labels: refactoring

#18674 Handle picture correctly on service template update/create
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: bug, hammer/yes

#18666 Add method to list supported providers for create
  app/models/ext_management_system.rb
  app/models/manageiq/providers/embedded_automation_manager.rb
Labels: enhancement, providers

#18677 Fix EmbeddedAutomationManager supported_for_create
  app/models/manageiq/providers/embedded_automation_manager.rb
Labels: bug

#18592 Bump inventory_refresh to v0.2.0
  Gemfile
Labels: dependencies

#18682 Use the released version of manageiq-messaging
  Gemfile
Labels: dependencies

#18160 Support for automate ansible job/workflow template method.
  app/models/miq_ae_method.rb
Labels: enhancement

#18685 Add factory for service retire request
  spec/factories/miq_request.rb
Labels: bug, hammer/yes, test

#18690 [V2V] Fix allowing address to be blank for the ConversionHost model, and update spec.
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: bug, hammer/yes, transformation

#18691 [V2V] Provide placeholder params for the ConversionHost#disable method
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host/configurations_spec.rb
Labels: bug, hammer/yes, transformation

#18696 Update provider generator - travis.yml and Gemfile
  lib/generators/provider/templates/.travis.yml
  lib/generators/provider/templates/Gemfile
Labels: dependencies

#18695 Remove useless self. from MiqEnvrionment
  lib/miq_environment.rb
Labels: cleanup, core

#18694 [V2V] Add V2V spec tags
  spec/models/conversion_host/configurations_spec.rb
  spec/models/conversion_host_spec.rb
  spec/models/infra_conversion_job_spec.rb
  spec/models/service_template_transformation_plan_request_spec.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
  spec/models/transformation_mapping_spec.rb
Labels: refactoring, test

#18647 [GAPRINDASHVILI] Lock dry-validation to 0.11.1
  Gemfile
Labels: dependencies

#18573 Physical server provisioning with internal state machine
  app/models/physical_server.rb
  app/models/physical_server_provision_request.rb
  app/models/physical_server_provision_task.rb
  app/models/physical_server_provision_task/state_machine.rb
  spec/factories/miq_request.rb
  spec/factories/miq_request_task.rb
  spec/models/physical_server_provision_request_spec.rb
  spec/models/physical_server_provision_task/state_machine_spec.rb
  spec/models/physical_server_provision_task_spec.rb
Labels: enhancement

#18689 Service template picture
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: bug, hammer/yes

#18706 Don't do anything in a function meant for override
  app/models/physical_server_provision_task/state_machine.rb
Labels: enhancement

#18678 Move relationship save blocks out of vmware to core
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: refactoring

#18693 Move EmsRefresh spec helper methods to core
  spec/support/ems_refresh_helper.rb
Labels: providers, test

#18707 Rename Configuration feature to Main Configuration
  db/fixtures/miq_product_features.yml
Labels: bug, changelog/yes, hammer/no

#18710 Add scope to region validation and use it to fix miq_dialog seed
  app/models/miq_dialog.rb
  lib/unique_within_region_validator.rb
  spec/lib/unique_within_region_validator_spec.rb
Labels: bug
