Repository ManageIQ/manageiq, pull requests merged in 2019-05, with the labels that each got.

#18711 Drop id_region dependency and let manageiq-schema do it
  Gemfile
Labels: dependencies

#18702 Add metrics_base table to default excludes and remove rollups view
  config/default_replication_exclude_tables.yml
Labels: bug, replication

#18713 Move common collection overrides to core
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: cleanup, providers/inventory

#18688 Add support for exporting and importing generic object definitions
  app/models/generic_object_definition.rb
  app/models/generic_object_definition/import_export.rb
  lib/task_helpers/exports/generic_object_definitions.rb
  lib/task_helpers/imports/generic_object_definitions.rb
  lib/tasks/evm_export_import.rake
  spec/lib/task_helpers/exports/generic_object_definitions_spec.rb
  spec/lib/task_helpers/imports/data/generic_object_definitions/apep.yaml
  spec/lib/task_helpers/imports/data/generic_object_definitions/apep_update.yml
  spec/lib/task_helpers/imports/data/generic_object_definitions/apophis.yaml
  spec/lib/task_helpers/imports/data/generic_object_definitions/god_attr_error.yml
  spec/lib/task_helpers/imports/data/generic_object_definitions/god_runtime_error.yml
  spec/lib/task_helpers/imports/generic_object_definitions_spec.rb
Labels: enhancement

#18459 Refactor build_html_col
  app/models/miq_report/generator/html.rb
Labels: refactoring, reporting

#18709 Group AND expressions properly to account for nesting
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: bug, changelog/yes, hammer/yes

#18716 Save unsaved changes before locking
  app/models/service_template_transformation_plan_task.rb
Labels: rails5.1

#18389 Use stable_sort_by from more_core_extensions repo
  Gemfile
  lib/patches/ruport_patch.rb
Labels: dependencies, refactoring, reporting

#18588 Add option to load MiqReport with filename and save filename to extras
  app/models/miq_report/import_export.rb
  spec/models/miq_report/import_export_spec.rb
Labels: changelog/no, hammer/no

#18719 Fix test cases which are against the wrong subjects.
  spec/models/service_template_ansible_playbook_spec.rb
Labels: bug, changelog/no, test

#18720 Update core infra collections for ovirt
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: cleanup, providers/inventory

#18651 Doesn't count with selection of belongsto filter if any object doesn't exist in the filter sentence
  app/models/miq_filter.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, rbac

#18736 Make Classification.tag2human public as the UI depends on it
  app/models/classification.rb
Labels: bug, control, ui

#18737 Add a spec test for Classification.tag2human
  spec/models/classification_spec.rb
Labels: control, test

#18740 Rails i18n - sort our locale/*yml when adding to i18n.load_path
  config/initializers/fast_gettext.rb
Labels: bug, internationalization

#18738 Add source to retire request to parse in parse_prov_category in engine
  app/models/vm_retire_request.rb
  spec/models/miq_request_spec.rb
Labels: bug, hammer/yes

#18712 Add port groups to rbac
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, rbac

#18743 Allow textarea boxes to dynamically set validator type and rule
  app/models/dialog_field_text_area_box.rb
  spec/models/dialog_field_text_area_box_spec.rb
Labels: bug, hammer/yes

#18744 All our virtual delegates allow nil
  app/models/miq_server.rb
Labels: rails5.1, technical debt

#18724 [V2V] Add default credentials to ansible_playbook method
  app/models/conversion_host.rb
Labels: bug, hammer/yes, transformation

#18708 [Changelog] Update for Sprint 110
  CHANGELOG.md
Labels: documentation

#18726 Fix specs for MiqEnvironment.is_production? and update comments
  lib/miq_environment.rb
  spec/lib/miq_environment_spec.rb
Labels: bug, changelog/no, test

#18727 Update action_container_image_analyze specs for MiqAction
  spec/models/miq_action_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18729 Remove unnecessary allow_any_instance_of from LogFile specs
  spec/models/log_file_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18728 Remove partial double from ManageIQ::Providers::Inventory::Persister specs
  spec/models/manageiq/providers/inventory/persister/finders_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18731 Update source host factory in ServiceTemplateTransformationPlanTask specs to an esx host in
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: changelog/no, hammer/no, refactoring, test, transformation

#18732 Only use partial for the class that uses it in ToModelHash specs
  spec/lib/extensions/ar_to_model_hash_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18730 Remove unused partial in role management specs
  spec/models/miq_server/role_management_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18741 Add option to schedule automation requests via workflow
  app/models/automation_request.rb
  spec/models/automation_request_spec.rb
Labels: changelog/yes, enhancement

#18723 Add more common setup to plugin Engine
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/%plugin_name%.gemspec
  lib/generators/manageiq/plugin/templates/README.md
  lib/generators/manageiq/plugin/templates/lib/%plugin_path%/engine.rb
  lib/generators/manageiq/plugin/templates/spec/spec_helper.rb
Labels: dependencies, developer, enhancement

#18752 Minor rework of stub_server_settings_with_locale to deal with strict partials
  spec/lib/services/locale_resolver_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18758 Change plugin common methods to class methods
  lib/generators/manageiq/plugin/templates/lib/%plugin_path%/engine.rb
Labels: providers, refactoring

#18640 Add logging to standard output for report generator tool
  tools/generate_report.rb
Labels: changelog/yes, tools

#18759 Expect all plugins to implement .vmdb_plugin?
  lib/vmdb/plugins.rb
Labels: technical debt

#18492 Add validation so gids are really guids
  app/models/chargeback_rate.rb
  app/models/condition.rb
  app/models/custom_button.rb
  app/models/miq_alert.rb
  app/models/miq_policy.rb
  app/models/provider.rb
  app/models/service_template.rb
  lib/uuid_mixin.rb
  spec/factories/chargeback_rate.rb
  spec/factories/ext_management_system.rb
  spec/factories/miq_server.rb
  spec/factories/provider.rb
  spec/lib/task_helpers/imports/data/widgets/Test_Widget_Import.yaml
  spec/lib/task_helpers/imports/data/widgets/Test_Widget_attr_error.yml
  spec/lib/task_helpers/imports/data/widgets/Test_Widget_runtime_error.yml
  spec/lib/task_helpers/imports/data/widgets/Test_Widget_update.yml
  spec/lib/uuid_mixin_spec.rb
  spec/models/custom_button_spec.rb
Labels: enhancement

#18686 Use new replication gem
  Gemfile
  app/models/miq_region.rb
  app/models/pglogical_subscription.rb
  config/replication_exclude_tables.yml
  lib/evm_database.rb
  lib/evm_database_ops.rb
  lib/extensions/ar_migration.rb
  lib/miq_pglogical.rb
  lib/tasks/evm_dbsync.rake
  spec/lib/evm_database_spec.rb
  spec/lib/miq_pglogical_spec.rb
  spec/models/pglogical_subscription_spec.rb
  spec/replication/util/miq_pglogical_spec.rb
Labels: changelog/yes, core, dependencies, enhancement, replication

#18761 [Changelog] Update for Sprint 111
  CHANGELOG.md
Labels: documentation

#18767 Update rubocop to 0.69 and add rubocop-performance
  Gemfile
Labels: dependencies

#18441 Remove spec with false premise
  spec/lib/extensions/ar_dba_spec.rb
Labels: changelog/no, core, technical debt, test

#18747 [V2V] Add better logging to ConversionHost methods
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: refactoring, transformation

#18772 [V2V] Conversion Host - Use JSON format for extra vars
  app/models/conversion_host.rb
Labels: bug, hammer/yes, transformation

#18755 Add spec to ensure plugins implement .plugin_name
  spec/lib/vmdb/plugins_spec.rb
Labels: technical debt

#18756 Add db vs on disk version check for the Automate Engine to last_startup
  lib/vmdb/appliance.rb
Labels: enhancement

#18762 [V2V] Conversion Host - Handle CA bundle from UI
  app/models/conversion_host.rb
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host_spec.rb
Labels: bug, hammer/yes, transformation

#18753 Remove unused partial for provision_workflow_spec
  spec/models/manageiq/providers/cloud_manager/provision_workflow_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18779 Fix strict partial validation errors for InterRegionApiMethodRelay specs
  spec/models/mixins/inter_region_api_method_relay_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18771 [Changelog] Update for Hammer-6
  CHANGELOG.md
Labels: documentation, hammer/yes

#18745 [EvmDatabaseOps] Fix .validate_free_space target
  lib/evm_database_ops.rb
  spec/lib/evm_database_ops_spec.rb
Labels: bug, changelog/yes, core, hammer/yes

#18785 Use sys-filesystem for determining data disk in database seeding instead of MiqSystem
  Gemfile
  app/models/vmdb_database/seeding.rb
Labels: dependencies, hammer/no, refactoring

#18782 Remove unused partial for User instances in MiqProvisionRequest specs
  spec/models/miq_provision_request_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18781 Fix ServerMonitor specs to comply with strict partial validation
  spec/models/miq_server/server_monitor_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18754 Add currency to service template.
  app/models/service_template.rb
Labels: changelog/yes, enhancement, hammer/no, services

#18683 [HAMMER] Use the released version of manageiq-messaging
  Gemfile
Labels: dependencies

#18780 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#18751 Move authentication configuration to authselect in place of authconfig
  spec/tools/miqldap_to_sssd/auth_establish_spec.rb
  spec/tools/miqldap_to_sssd/authconfig_spec.rb
  spec/tools/miqldap_to_sssd/configure_apache_spec.rb
  spec/tools/miqldap_to_sssd/sssd_conf_spec.rb
  tools/miqldap_to_sssd.rb
  tools/miqldap_to_sssd/auth_establish.rb
  tools/miqldap_to_sssd/auth_template_files.rb
  tools/miqldap_to_sssd/configure_apache.rb
  tools/miqldap_to_sssd/converter.rb
  tools/miqldap_to_sssd/sssd_conf.rb
Labels: authentication, bug, enhancement, hammer/no

#18715 Add src_vm_or_dest_host_refresh_target.
  app/models/ems_event.rb
  spec/models/ems_event_spec.rb
Labels: bug, hammer/yes

#18768 [V2V] Add extra error handling for the ConversionHost#run_conversion method
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: hammer/yes, refactoring, transformation

#18792 Allow orch stacks, templates, cloud managers thru add_resource
  app/models/manageiq/providers/cloud_manager.rb
  app/models/orchestration_stack.rb
  app/models/orchestration_template.rb
  app/models/service_orchestration.rb
Labels: bug

#18787 Update VmdbDatabase::Seeding.seed_self error handling
  Gemfile
  app/models/vmdb_database/seeding.rb
  spec/models/vmdb_database/seeding_spec.rb
Labels: bug, dependencies, hammer/no

#18793 Remove invalid partial for local_db_finders_spec
  spec/models/manageiq/providers/inventory/persister/local_db_finders_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18770 Move 'region' and 'zone' product features out of Main Configuration
  db/fixtures/miq_product_features.yml
Labels: bug, changelog/no, core

#18805 Allow ssh auth for RHV
  app/models/conversion_host.rb
Labels: bug, hammer/yes, transformation

#18624 Remove deprecated Optimize Planning - shortcuts and user roles
  app/models/ems_cluster.rb
  app/models/ems_cluster/capacity_planning.rb
  app/models/vim_performance_analysis.rb
  app/models/vim_performance_planning.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  db/fixtures/miq_user_roles.yml
  locale/en.yml
  locale/manageiq.pot
  product/charts/layouts/planning_charts.yaml
  product/charts/miq_reports/vim_perf_planning.yaml
  spec/models/ems_cluster/capacity_planning_spec.rb
  spec/models/vim_performance_planning_spec.rb
Labels: changelog/yes, enhancement, hammer/no, ui

#18808 Bump rspec-rails to 3.8.0
  Gemfile
Labels: dependencies, test

#18798 specify virtual_delegate types to avoid deadlock
  Gemfile
  app/models/ems_cluster.rb
  app/models/entitlement.rb
  app/models/host.rb
  app/models/miq_group.rb
  app/models/miq_product_feature.rb
  app/models/miq_report_result.rb
  app/models/miq_server.rb
  app/models/miq_widget.rb
  app/models/mixins/authentication_mixin.rb
  app/models/mixins/compliance_mixin.rb
  app/models/mixins/drift_state_mixin.rb
  app/models/mixins/ownership_mixin.rb
  app/models/vm_or_template.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, dependencies

#18806 Make MiqProductFeature seeding pluggable
  app/models/miq_product_feature.rb
  app/models/miq_product_feature/seeding.rb
  app/models/tenant.rb
  spec/models/miq_product_feature_spec.rb
  spec/models/tenant_spec.rb
  spec/support/evm_spec_helper.rb
Labels: core, enhancement

#18811 Fix product features
  db/fixtures/miq_product_features.yml
  spec/models/miq_product_feature_spec.rb
Labels: bug, changelog/no

#18804 Remove invalid partial doubles from vm_spec.rb
  spec/models/vm_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18794 Remove invalid partial double in server_template_helper.rb.
  spec/support/service_template_helper.rb
Labels: changelog/no, hammer/no, refactoring, test

#18814 [Changelog] Update for Sprint 102
  CHANGELOG.md
Labels: documentation

#18815 Remove check for service template picture not being nil
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: bug, hammer/yes

#18820 Raise error on Ruby 2.6 until it is supported
  Gemfile
Labels: dependencies, enhancement, ruby2.6

#18721 Add feature detection for selecting AZs for cloud volumes
  app/models/ext_management_system.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/openstack/cloud

#18816 Add models and save_inventory code for EmsLicense and EmsExtension
  app/models/ems_extension.rb
  app/models/ems_license.rb
  app/models/ems_refresh/save_inventory_infra.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: enhancement, transformation

#18648 Allow use of systemd for worker management
  Gemfile
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/quiesce.rb
  app/models/miq_server/worker_management/monitor/stop.rb
  app/models/miq_worker.rb
  app/models/miq_worker/systemd_common.rb
  app/models/mixins/per_ems_worker_mixin.rb
  config/settings.yml
  lib/miq_environment.rb
  lib/vmdb/loggers.rb
  lib/workers/bin/run_single_worker.rb
Labels: changelog/yes, core, core/workers, dependencies, hammer/no

#18825 Remove Job.get_job_class method
  app/models/job.rb
Labels: technical debt

#18824 Fix bad virtual relations
  app/models/cloud_subnet.rb
  app/models/container_group.rb
  app/models/load_balancer_pool_member.rb
  app/models/service_template_transformation_plan.rb
  spec/models/container_group_spec.rb
Labels: bug, core

#18827 Replace class objects in query values with strings to fix a rails 5.0 deprecation
  app/models/cloud_tenant.rb
  app/models/manageiq/providers/cloud_manager/vm.rb
  app/models/mixins/authentication_mixin.rb
  app/models/mixins/miq_provision_quota_mixin.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/mixins/authentication_mixin_spec.rb
Labels: rails5.1

#18829 This scope accepts class objects, pass strings to where
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: changelog/no, core, rails5.1

#18742 Cleanup Classification warnings
  app/models/classification.rb
Labels: changelog/no, hammer/no, refactoring

#18828 Pluggable locale configuration
  config/locale_task_config.yaml
  lib/tasks/locale.rake
Labels: enhancement

#18831 Deprecate any uses of class_name with Class objects in put_or_update
  app/models/miq_queue.rb
  spec/models/miq_queue_spec.rb
Labels: rails5.1

#18823 [V2V] Added cluster validation for creating infra mapping
  app/models/transformation_mapping_item.rb
  spec/factories/ems_cluster.rb
  spec/models/service_template_transformation_plan_request_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
  spec/models/transformation_mapping_item_spec.rb
  spec/models/transformation_mapping_spec.rb
Labels: transformation

#18832 Correctly specify includes to fix a 5.0 deprecation
  lib/vmdb/appliance.rb
Labels: rails5.1
