Repository ManageIQ/manageiq, pull requests merged in 2019-11, with the labels that each got.

#19439 Remove `aws-sdk-ec2` dependency from core
  Gemfile
  app/models/file_depot_s3.rb
Labels: dependencies

#19435 Reduce MiqExpression#operands2rubyvalue
  config/miq_expression.yml
  lib/miq_expression.rb
Labels: refactoring

#19451 Enable workers as containers
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/system_limits.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  app/models/miq_ui_worker.rb
  app/models/miq_ui_worker/runner.rb
  app/models/miq_worker.rb
  app/models/miq_worker/container_common.rb
  app/models/miq_worker/service_worker.rb
  app/models/mixins/miq_web_server_worker_mixin.rb
  lib/container_orchestrator/object_definition.rb
Labels: core/workers, enhancement

#19455 [IVANCHUK] Retain parity with the retirement mixin master specs where possible
  spec/models/vm/retirement_management_spec.rb
Labels: test

#19458 Remove the check for a "current" snapshot
  app/models/vm_or_template/operations/snapshot.rb
Labels: bug, providers/vmware/infra

#19448 Cap&U Extract logic to determine queue items
  app/models/metric/capture.rb
  app/models/metric/ci_mixin/capture.rb
  app/models/metric/targets.rb
Labels: enhancement, providers/metrics

#19461 [V2V][IVANCHUK] Fix create_job in JobProxyDispatcher specs
  app/models/infra_conversion_job.rb
  spec/models/job_proxy_dispatcher_spec.rb
Labels: bug, transformation

#19443 Cap&U collector tests
  spec/models/metric/capture_spec.rb
  spec/models/metric/ci_mixin/capture_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
  spec/models/metric/finders_spec.rb
  spec/models/metric/helper_spec.rb
  spec/models/metric/targets_spec.rb
  spec/models/metric_rollup_spec.rb
  spec/models/metric_spec.rb
  spec/support/metric_helper.rb
Labels: enhancement, providers/metrics

#19457 Update the orchestrator for new database secret format
  lib/container_orchestrator/object_definition.rb
Labels: core, enhancement

#19463 Base monolithic container image on pods ui worker
  Dockerfile
  docker-assets/check-dependent-services.sh
  docker-assets/entrypoint
Labels: bug, core

#19470 Remove unused image labels
  Dockerfile
Labels: technical debt

#19467 [V2V] Added warm migration eligibility option to VM during its validation
  app/models/transformation_mapping/vm_migration_validator.rb
Labels: transformation

#19445 Return MiqTask id from MiqWidget.queue_generate_content
  app/models/miq_widget.rb
  spec/models/miq_widget_spec.rb
Labels: enhancement, ivanchuk/no

#19473 Return empty array for delegation with nil manager
  app/models/manageiq/providers/network_manager.rb
  spec/models/manageiq/providers/network_manager_spec.rb
Labels: bug

#19477 Remove the unused InventoryCollectorWorker
  app/models/manageiq/providers/base_manager/inventory_collector_worker.rb
  app/models/manageiq/providers/base_manager/inventory_collector_worker/runner.rb
  config/settings.yml
  lib/workers/miq_worker_types.rb
Labels: cleanup, providers

#19481 Optionally symlink a plugin's spec/manageiq
  lib/generators/manageiq/plugin/templates/bin/setup
Labels: enhancement, providers/pluggability

#19485 Fix or remove invalid partials for ConversionHost specs
  spec/models/conversion_host_spec.rb
Labels: hammer/no, ivanchuk/no, refactoring, test

#19486 Fix key_pair class lookup
  app/models/manageiq/providers/network_manager.rb
Labels: bug, providers/network

#19487 Add an interface for get_source_and_targets
  app/models/miq_request_workflow.rb
Labels: hammer/no, ivanchuk/no, refactoring

#19482 Subclass require_snapshot_for_scan? method
  app/models/vm_or_template/scanning.rb
Labels: providers/pluggability, refactoring

#19460 Condense attribute updates in miq_widget generate content methods
  app/models/miq_widget.rb
Labels: cleanup

#19447 [HAMMER] In active_record 5.0 join_keys takes a klass argument
  tools/cleanup_duplicate_host_guest_devices.rb
Labels: bug

#19480 Adding task error status to log management
  app/models/miq_server/log_management.rb
Labels: bug, hammer/yes, ivanchuk/yes

#19489 Fix AnsibleRunner specs on RHEL
  spec/lib/ansible/runner_spec.rb
Labels: test

#19493 Update linux_admin to 1.2.4
  Gemfile
Labels: dependencies

#19488 Add and subclass scan_timeout_adjustment_multiplier method
  app/models/miq_server/server_smart_proxy.rb
  app/models/vm_or_template/scanning.rb
Labels: providers/pluggability, refactoring, smart state

#19464 Allow for workers to be more specific in what they dequeue
  app/models/miq_queue_worker_base/runner.rb
Labels: core/queue, core/workers

#19494 Use the workers proc rather than overriding the method
  app/models/mixins/per_ems_type_worker_mixin.rb
  spec/factories/miq_worker.rb
  spec/models/mixins/per_ems_type_worker_mixin_spec.rb
Labels: bug, core/workers, ivanchuk/no

#19499 Fix IsoDatastore using OvirtServices::Strategies
  spec/models/iso_datastore_spec.rb
Labels: bug, test

#19498 Add specs to scan_timeout_adjustment_multiplier class and instance method for VmOrTemplate
  spec/models/vm_or_template/scanning_spec.rb
Labels: test

#19452 Extract raw_* vm operations to providers
  app/models/vm/operations/guest.rb
  app/models/vm_or_template.rb
  app/models/vm_or_template/operations.rb
  app/models/vm_or_template/operations/configuration.rb
  app/models/vm_or_template/operations/power.rb
  app/models/vm_or_template/operations/relocation.rb
  app/models/vm_or_template/operations/snapshot.rb
  spec/models/vm_migrate_task_spec.rb
  spec/models/vm_or_template/operations/configuration_spec.rb
Labels: providers, providers/pluggability, refactoring

#19456 Added missing product feature - "Rename VM"
  db/fixtures/miq_product_features.yml
Labels: bug, ivanchuk/yes, providers/vmware/infra

#19496 Sprint 124
  CHANGELOG.md
Labels: documentation

#19500 Kubernetes-ify the container orchestrator
  app/models/miq_worker/deployment_per_worker.rb
  app/models/miq_worker/replica_per_worker.rb
  app/models/miq_worker/service_worker.rb
  lib/container_orchestrator.rb
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
Labels: enhancement

#19497 Update MiqExpression#registry_data and add coverage
  app/models/condition.rb
  spec/models/condition_spec.rb
Labels: refactoring

#19508 Remove ovirt V3 api calls
  app/models/iso_datastore.rb
  spec/models/iso_datastore_spec.rb
Labels: bug, providers/rhevm

#19510 Move provider-specific parts of vm_scan_spec.rb from this repo to the provider repos
  spec/models/vm_scan_spec.rb
Labels: providers/pluggability, refactoring, smart state, test

#19513 Use ActiveSupport's parent method for the ems class
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_worker.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_worker.rb
  spec/models/manageiq/providers/storage_manager/cinder_manager/refresh_worker_spec.rb
  spec/models/manageiq/providers/storage_manager/swift_manager/refresh_worker_spec.rb
Labels: providers/storage, technical debt

#19505 Remove repmgr10 from the docker image
  Dockerfile
Labels: build/docker, core, technical debt

#19511 metrics_capture supports ems
  app/models/manageiq/providers/base_manager/metrics_capture.rb
Labels: enhancement, providers/metrics

#19466 Remove embedded ansible PlaybookRunner.
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner.rb
Labels: automate, changelog/yes, hammer/no, ivanchuk/yes, refactoring

#19504 Snapshot create notification should not be a warning message
  db/fixtures/notification_types.yml
Labels: bug, ivanchuk/yes, providers/openstack/infra, providers/vmware/infra

#19502 Display available disk in utilization
  product/charts/miq_reports/vim_perf_util_4_ts.yaml
Labels: hammer/yes, ivanchuk/yes

#19509 Add VmOrTemplate#scan_job_class method to allow for pluggability
  app/models/vm_or_template/scanning.rb
Labels: providers/pluggability, refactoring, smart state

#19517 Load graphql only in puma process bundler groups (api/ui)
  Gemfile
  lib/workers/miq_worker_types.rb
Labels: dependencies

#19514 Use secret_key_base to avoid rails 5.2 deprecation
  app/models/mixins/miq_web_server_worker_mixin.rb
  spec/models/mixins/miq_web_server_worker_mixin_spec.rb
Labels: rails5.2

#19357 Add notifications for Cloud Volume Backup actions
  db/fixtures/notification_types.yml
Labels: bug, providers/openstack/infra

#19519 introduce capture interval_priority
  app/models/metric/capture.rb
  app/models/metric/ci_mixin/capture.rb
  app/models/metric/ci_mixin/rollup.rb
Labels: providers/metrics, refactoring

#19516 Use parent as the default implementation of .ems_class
  app/models/manageiq/providers/base_manager/event_catcher.rb
  app/models/manageiq/providers/base_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/base_manager/refresh_worker.rb
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_worker.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_worker.rb
  app/models/mixins/per_ems_type_worker_mixin.rb
  app/models/mixins/per_ems_worker_mixin.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/cloud_manager/refresh_worker.rb
Labels: providers, refactoring, technical debt

#19522 metrics: set ems in metrics_capture object
  app/models/metric/ci_mixin/capture.rb
Labels: enhancement, providers/metrics

#19518 metrics simplify calc_targets_by_rollup
  app/models/metric/capture.rb
Labels: providers/metrics, providers/vmware/infra, refactoring

#19525 Adding ability to update additional authentication settings
  lib/tasks/evm_settings.rake
  spec/lib/tasks/evm_settings_spec.rb
Labels: enhancement

#19526 Fix typo
  spec/models/binary_blob_spec.rb
Labels: changelog/no, cleanup, developer, ivanchuk/no

#19528 Remove worker classes only the kill_order list
  lib/workers/miq_worker_types.rb
Labels: cleanup, core/workers

#19527 Rbac.filter: make sure the result is an array.
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, rbac

#19530 fix sporadic test with state_machine_spec
  spec/models/miq_provision/state_machine_spec.rb
Labels: bug/sporadic test failure

#19506 metrics capture gap by ems
  app/models/metric/capture.rb
  app/models/metric/ci_mixin/capture.rb
  app/models/metric/targets.rb
  spec/models/metric/capture_spec.rb
  tools/metrics_capture_gap.rb
Labels: enhancement, providers/metrics

#19529 Subclass ResourcePools
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/infra_manager/resource_pool.rb
  app/models/resource_pool.rb
Labels: enhancement, providers

#19350 Use table currencies if exists in ChargebackRateDetailCurrency
  app/models/chargeback_rate_detail_currency.rb
  config/replication_exclude_tables.yml
Labels: technical debt

#19524 Address workers not present in worker list
  app/models/manageiq/providers/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_worker.rb
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/storage_manager/swift_manager.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_worker.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_worker/runner.rb
  config/settings.yml
  lib/workers/miq_worker_types.rb
  spec/lib/workers/miq_worker_types_spec.rb
  spec/models/manageiq/providers/storage_manager/cinder_manager/refresh_worker_spec.rb
  spec/models/manageiq/providers/storage_manager/swift_manager/refresh_worker_spec.rb
Labels: core/workers, providers, technical debt

#19539 Move ExtManagementSystem#vm_log_user_event method to VmOrTemplate#log_user_event
  app/models/ext_management_system.rb
  app/models/vm_or_template/operations.rb
  app/models/vm_scan.rb
Labels: providers/pluggability, refactoring, smart state

#19537 Raise exception if nested file will never be found
  lib/extensions/require_nested.rb
Labels: bug

#19540 Initial set of codeowners for providers code
  .github/CODEOOWNERS
Labels: developer, providers

#19515 Don't convert user-type email to upn
  app/models/miq_request_workflow.rb
  lib/miq_ldap.rb
  spec/lib/miq_ldap_spec.rb
Labels: authentication, bug

#19545 Remove the Runner#message_restarted method
  app/models/miq_worker/runner.rb
Labels: core, technical debt

#19536 Add MiqWorkerType model
  app/models/manageiq/providers/base_manager/event_catcher.rb
  app/models/manageiq/providers/base_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/base_manager/operations_worker.rb
  app/models/manageiq/providers/base_manager/refresh_worker.rb
  app/models/miq_cockpit_ws_worker.rb
  app/models/miq_ems_metrics_processor_worker.rb
  app/models/miq_event_handler.rb
  app/models/miq_generic_worker.rb
  app/models/miq_priority_worker.rb
  app/models/miq_remote_console_worker.rb
  app/models/miq_reporting_worker.rb
  app/models/miq_schedule_worker.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/class_names.rb
  app/models/miq_server/worker_management/monitor/quiesce.rb
  app/models/miq_server/worker_management/monitor/settings.rb
  app/models/miq_server/worker_management/monitor/start.rb
  app/models/miq_smart_proxy_worker.rb
  app/models/miq_ui_worker.rb
  app/models/miq_web_service_worker.rb
  app/models/miq_worker.rb
  app/models/miq_worker/container_common.rb
  app/models/miq_worker/systemd_common.rb
  app/models/miq_worker_type.rb
  config/replication_exclude_tables.yml
  lib/evm_database.rb
  lib/generators/manageiq/provider/provider_generator.rb
  lib/workers/bin/run_single_worker.rb
  lib/workers/miq_worker_types.rb
  spec/lib/workers/miq_worker_types_spec.rb
  spec/models/message_timeout_handling_spec.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
  spec/models/miq_server/worker_monitor_spec.rb
  spec/models/miq_worker/container_common_spec.rb
  spec/models/miq_worker_type_spec.rb
Labels: core/workers, enhancement, providers/pluggability

#19542 Add currency model and factory
  app/models/currency.rb
  spec/factories/currency.rb
Labels: technical debt

#19535 Remove seed on rails server start in development.
  app/models/mixins/miq_web_server_worker_mixin.rb
  lib/evm_database.rb
  lib/vmdb/initializer.rb
  spec/lib/evm_database_spec.rb
Labels: performance, technical debt

#19378 Hawkular removal
  app/models/event_stream.rb
  app/models/middleware_datasource.rb
  app/models/middleware_datasource_performance.rb
  app/models/middleware_deployment.rb
  app/models/middleware_diagnostic_report.rb
  app/models/middleware_domain.rb
  app/models/middleware_messaging.rb
  app/models/middleware_performance.rb
  app/models/middleware_server.rb
  app/models/middleware_server_group.rb
  app/models/middleware_server_performance.rb
  product/live_metrics/middleware_datasource.yaml
  product/live_metrics/middleware_messaging_jms_queue.yaml
  product/live_metrics/middleware_messaging_jms_topic.yaml
  product/live_metrics/middleware_server.yaml
  spec/factories/middleware_datasource.rb
  spec/factories/middleware_deployment.rb
  spec/factories/middleware_domain.rb
  spec/factories/middleware_messaging.rb
  spec/factories/middleware_server_group.rb
  spec/factories/middleware_servers.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/live_metric_spec.rb
  spec/models/middleware_server_spec.rb
Labels: refactoring

#19549 Make GuestDevice taggable
  app/models/guest_device.rb
Labels: enhancement, ivanchuk/yes, transformation

#19430 Remove ems_ref_obj
  app/models/ems_cluster.rb
  app/models/ems_folder.rb
  app/models/host.rb
  app/models/mixins/serialized_ems_ref_obj_mixin.rb
  app/models/resource_pool.rb
  app/models/snapshot.rb
  app/models/storage.rb
  app/models/vm_or_template.rb
  spec/factories/ems_folder.rb
  spec/factories/host.rb
  spec/factories/storage.rb
  spec/factories/vm_or_template.rb
  spec/models/ems_refresh/save_inventory_spec.rb
  spec/models/ems_refresh_spec.rb
Labels: cleanup, providers

#19479 Allow MiqRequests to set a queue_name
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/miq_request_task/state_machine.rb
  spec/models/service_template_provision_task_spec.rb
Labels: enhancement, providers

#19541 Cu capture object zone
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/capture.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/metric/capture_spec.rb
  spec/support/metric_helper.rb
Labels: providers/metrics, refactoring

#19551 Don't require VMwareWebService/MiqVimVm in Snapshot
  app/models/miq_action.rb
  app/models/snapshot.rb
Labels: providers/pluggability, technical debt

#19552 Remove server capabilities serialized column
  app/models/miq_server.rb
  app/models/miq_server/configuration_management.rb
  app/models/miq_server/server_smart_proxy.rb
  spec/models/miq_server/server_smart_proxy_spec.rb
  spec/models/vm_scan_spec.rb
Labels: core, refactoring, technical debt

#19556 Drop support for forking workers, use spawn by default
  Gemfile
  app/models/miq_web_service_worker.rb
  app/models/miq_worker.rb
  lib/extensions/ar_application_name.rb
  lib/workers/bin/run_single_worker.rb
  spec/models/miq_worker_spec.rb
Labels: core/workers, dependencies, enhancement

#19394 [V2V] Add warm migration support
  app/models/conversion_host.rb
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan.rb
  app/models/service_template_transformation_plan/validate_config_info.rb
  app/models/service_template_transformation_plan_task.rb
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
  spec/models/conversion_host_spec.rb
  spec/models/infra_conversion_job_spec.rb
  spec/models/service_template_transformation_plan_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, transformation

#19559 Remove sync_blacklisted_event_names server queue message
  app/models/blacklisted_event.rb
  app/models/miq_server/configuration_management.rb
Labels: cleanup, events, technical debt

#19557 Look up worker by guid not pid
  app/models/miq_worker.rb
  app/models/miq_worker/runner.rb
  spec/factories/vmware_refresh_worker.rb
  spec/models/message_timeout_handling_spec.rb
  spec/models/miq_worker/runner_spec.rb
  spec/support/evm_spec_helper.rb
Labels: bug, core
