Repository ManageIQ/manageiq, pull requests merged in 2019-09, with the labels that each got.

#19239 Let `pxe_menu.pxe_images` use correct subclass
  app/models/pxe_menu_ipxe.rb
  app/models/pxe_menu_pxelinux.rb
  spec/models/pxe_menu_spec.rb
Labels: bug, ivanchuk/yes

#19223 [IVANCHUK] Add translations for ivanchuk
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization

#19237 Workflow cloud_tenant fix
  app/models/miq_provision_virt_workflow.rb
Labels: blocker, bug, ivanchuk/yes

#19245 Bump SSA to 0.3.1
  Gemfile
Labels: blocker, bug, dependencies, ivanchuk/yes, providers/rhevm

#19227 Update the button order on copy
  app/models/custom_button_set.rb
  app/models/service_template/copy.rb
  spec/models/service_template/copy_spec.rb
Labels: bug, ivanchuk/yes

#19206 Add copying tag as optional choice
  app/models/service_template/copy.rb
  spec/models/service_template/copy_spec.rb
Labels: changelog/yes, enhancement, ivanchuk/yes, services

#19246 [Changelog] Update for Sprint 119
  CHANGELOG.md
Labels: documentation

#19247 Fix Embedded Ansible Plays in the Job UI (v2/rebased with master)
  app/models/manageiq/providers/embedded_ansible/automation_manager/job.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
Labels: bug, embedded ansible, ivanchuk/yes

#19244 Fix regex for finding regex interpolations
  spec/shared/i18n/placeholders.rb
Labels: internationalization, ivanchuk/yes, test

#19243 Remove zanata.xml
  locale/zanata.xml
Labels: internationalization, ivanchuk/no

#19209 Test that each lang catalog has properly set locale_name
  spec/i18n/locale_name_spec.rb
Labels: internationalization, ivanchuk/yes, test

#19253 Add config file for Transifex
  .tx/config
Labels: internationalization, ivanchuk/no

#19250 [Changelog] Update for Hammer-11
  CHANGELOG.md
Labels: documentation, hammer/yes

#19252 Reconfigure: edit vlan for nic
  app/models/vm_reconfigure_task.rb
Labels: enhancement, providers/vmware/infra

#19251 Skip already reconnected object
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
Labels: bug

#19234 Do not attempt to calculate backlog unless subscription status is "replicating"
  app/models/pglogical_subscription.rb
  spec/models/pglogical_subscription_spec.rb
Labels: bug, changelog/yes, core, ivanchuk/yes

#19120 Add a common validate_credentials API and method for getting all provider create params
  app/models/ext_management_system.rb
Labels: enhancement, providers, providers/pluggability

#19262 Add distributed_virtual_lans for infra_manager
  app/models/manageiq/providers/infra_manager.rb
Labels: enhancement, providers, providers/rhevm

#19263 [V2V] Removed a duplicate variable for ems_openstack from transformation_mapping_item_spec.
  spec/models/transformation_mapping_item_spec.rb
Labels: hammer/yes, ivanchuk/yes, transformation

#19259 Update translations for master (to become Jansa)
  config/human_locale_names.yaml
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization, ivanchuk/no

#19254 [HAMMER]Do not calculate backlog when subscription not active
  app/models/pglogical_subscription.rb
  spec/models/pglogical_subscription_spec.rb
Labels: bug, changelog/yes, core

#19267 BigDecimal.new deprecated in v1.3.3 which ruby 2.5 uses
  app/models/chargeback_rate_detail_measure.rb
Labels: dependencies

#19269 VMware Content Library refresh
  app/models/manageiq/providers/infra_manager.rb
Labels: enhancement, providers, providers/vmware/infra

#19271 [Changelog] Update for Ivanchuk-1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#19273 Moving orchestration_template builder property to core infra builder
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: providers/inventory, refactoring

#19265 Don't require Job.create_job to pass in the class name
  app/models/infra_conversion_job.rb
  app/models/job.rb
  app/models/manageiq/providers/ansible_runner_workflow.rb
  app/models/manageiq/providers/cloud_manager/orchestration_template_runner.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner.rb
  app/models/manageiq/providers/ems_refresh_workflow.rb
  app/models/vm_or_template/scanning.rb
  spec/models/job_proxy_dispatcher_spec.rb
  spec/models/job_spec.rb
  spec/models/miq_task/purging_spec.rb
  spec/models/miq_task_spec.rb
Labels: core, refactoring

#19266 [Hammer] Revert "Fix sporadic failure now that distinct remembers the order"
  spec/lib/rbac/filterer_spec.rb
Labels: bug

#19264 Schedule compliance purging
  app/models/compliance.rb
  app/models/compliance/purging.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  config/settings.yml
  spec/models/compliance/purging_spec.rb
Labels: bug, performance

#19238 [V2V] Add applying_right_sizing state to InfraConversionJob
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan/validate_config_info.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/infra_conversion_job_spec.rb
Labels: ivanchuk/yes, refactoring, transformation

#19240 [V2V] Add restoring_vm_attributes state to InfraConversionJob
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: ivanchuk/yes, refactoring, transformation

#19275 Remove value2tag
  lib/miq_expression.rb
  spec/lib/miq_expression/field_spec.rb
  spec/lib/miq_expression/tag_spec.rb
  spec/lib/miq_expression_spec.rb
Labels: refactoring

#19241 [V2V] Add powering_on_vm state to InfraConversionJob
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: ivanchuk/yes, refactoring, transformation

#19280 Don't raise error when tenant is not find in chargeback VM
  app/models/chargeback_vm.rb
  spec/models/chargeback_vm_spec.rb
Labels: bug, chargeback, hammer/yes, ivanchuk/yes

#19242 [V2V] Add transition for powering_on to running_migration_playbook in InfraConversionJob
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: ivanchuk/yes, refactoring, transformation

#19279 Set default playbook service timeout to 100 minutes
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_spec.rb
Labels: blocker, bug, changelog/yes, ivanchuk/yes

#19258 remove already initialized warning
  spec/models/miq_report_spec.rb
Labels: technical debt, test

#19285 Check for user timezone on report first for display formatting
  app/models/miq_report.rb
  spec/models/miq_report_spec.rb
Labels: bug

#19302 Translation corrections from ivanchuk
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization, ivanchuk/no

#19306 Add distributed_virtual_lans to persister
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: enhancement, providers/inventory

#19299 Remove unnecessary log message.
  app/models/miq_event.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes

#19261 Raise exception if plugin string extraction fails
  lib/tasks/locale.rake
Labels: developer, internationalization, ivanchuk/yes

#19268 Add tests for human locale names
  spec/i18n/locale_name_spec.rb
Labels: internationalization, ivanchuk/yes, test

#19270 Set result_format to ignore for all custom buttons.
  app/models/resource_action.rb
  spec/models/resource_action_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes

#19307 eliminate useless spec
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager_spec.rb
  spec/spec_helper.rb
Labels: cleanup, test

#19309 Add check for nil group to system_context_requester
  app/models/mixins/retirement_mixin.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, changelog/yes, hammer/yes, retirement

#19314 requests without sources are invalid
  spec/models/miq_provision_request_spec.rb
Labels: automate, test

#19304 Removed advanced config option to switch between "puma" and "thin"
  app/models/mixins/miq_web_server_worker_mixin.rb
  config/settings.yml
Labels: changelog/yes, core, ivanchuk/yes, technical debt

#19320 [EmbeddedAnsible] Fix job_plays for API
  app/models/manageiq/providers/embedded_ansible/automation_manager/job.rb
Labels: bug, embedded ansible, ivanchuk/yes

#19315 Variable name typo in miq_schedule import
  app/models/miq_schedule/import_export.rb
Labels: bug, ivanchuk/yes

#19321 Fix category/classification sporadic test failure
  spec/factories/categories.rb
Labels: bug/sporadic test failure, core

#19138 Make automation request scheduling granular
  app/models/automation_request.rb
  spec/models/automation_request_spec.rb
Labels: bug

#19301 [IVANCHUK] Update translations for ivanchuk
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/zh_CN/manageiq.po
Labels: blocker, bug, internationalization

#19295 Fix references pass 1
  app/models/flavor.rb
  app/models/mixins/cloud_tenancy_mixin.rb
  app/models/service_template.rb
  spec/models/container_group_spec.rb
  spec/models/metric_rollup_spec.rb
Labels: enhancement, ivanchuk/no, rails5.2, rbac

#19319 [HAMMER] Users without groups should use admin retirement
  app/models/mixins/retirement_mixin.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, changelog/yes, retirement

#19310 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation

#19325 Check whether belongsto association exists before usage
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, hammer/yes, rbac

#19292 Simplify expression in MiqReport#get_time_zone
  app/models/miq_report/generator.rb
Labels: refactoring

#19326 Fix an exception calling compliance_purge_timer
  app/models/miq_schedule_worker/runner.rb
Labels: bug, core

#19329 [V2V] adding validations for migration plans
  app/models/service_template_transformation_plan/validate_config_info.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: enhancement, transformation

#19331 Drop load balancer from the custom buttons tree in automate
  app/models/custom_button.rb
Labels: automate, bug, changelog/yes, ivanchuk/yes

#19322 Use user from command's argument for schedule import
  app/models/miq_schedule/import_export.rb
  tools/import_export_schedules.rb
Labels: bug, ivanchuk/yes

#19330 [wip] clean up and moving factory objects to their own repo
  spec/factories/configuration_script.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager_spec.rb
Labels: wip

#19327 Add MiqServer#server_role_names=
  app/models/miq_server/role_management.rb
  spec/models/miq_server/role_management_spec.rb
Labels: core, enhancement

#19290 Allow user-queued full-refreshes when streaming
  app/models/ems_event/automate.rb
  app/models/ems_refresh.rb
  app/models/miq_queue.rb
  app/models/miq_queue_worker_base/runner.rb
  spec/models/ems_refresh_spec.rb
Labels: enhancement, providers/inventory

#19335 Update the vcr gems
  Gemfile
Labels: dependencies, technical debt, test

#19333 Fix typo
  db/fixtures/miq_shortcuts.yml
Labels: cleanup

#19324 Add CloudObject* to RBAC
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug

#19336 Add ems presence check
  app/models/ems_event/automate.rb
Labels: bug, events

#19328 Add a --role argument to run_single_worker
  lib/workers/bin/run_single_worker.rb
Labels: developer, enhancement

#19340 remove rhn deprecation warnings from test suite
  spec/models/registration_system_spec.rb
Labels: technical debt, test

#19342 Use leaf classes for ems type validation
  spec/factories/ext_management_system.rb
Labels: bug, test

#19313 Deprecate find_by_* methods
  app/models/authenticator/base.rb
  app/models/chargeback_vm.rb
  app/models/classification.rb
  app/models/custom_button.rb
  app/models/dialog_field_importer.rb
  app/models/miq_ae_class.rb
  app/models/miq_ae_field.rb
  app/models/miq_ae_instance.rb
  app/models/miq_ae_method.rb
  app/models/miq_ae_namespace.rb
  app/models/miq_approval.rb
  app/models/miq_compare.rb
  app/models/miq_provision/tagging.rb
  app/models/miq_provision_request_template.rb
  app/models/miq_provision_virt_workflow.rb
  app/models/miq_report/generator.rb
  app/models/miq_report/generator/trend.rb
  app/models/miq_report/import_export.rb
  app/models/miq_report/notification.rb
  app/models/miq_report_result.rb
  app/models/miq_request_workflow.rb
  app/models/miq_request_workflow/dialog_field_validation.rb
  app/models/miq_schedule.rb
  app/models/mixins/filterable_mixin.rb
  app/models/mixins/miq_provision_mixin.rb
  app/models/mixins/miq_request_mixin.rb
  app/models/mixins/per_ems_worker_mixin.rb
  app/models/pglogical_subscription.rb
  app/models/tag.rb
  app/models/user.rb
  app/models/vm_or_template.rb
  lib/miq_expression.rb
  lib/miq_ldap.rb
  lib/rbac/filterer.rb
  lib/task_helpers/imports/tags.rb
  lib/tasks/evm_automate.rake
  spec/lib/miq_ldap_spec.rb
  spec/lib/task_helpers/imports/tags_spec.rb
  spec/models/authenticator/database_spec.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/authenticator/ldap_spec.rb
  spec/models/classification_spec.rb
  spec/models/miq_ae_class_spec.rb
  spec/models/miq_ae_field_spec.rb
  spec/models/miq_ae_instance_spec.rb
  spec/models/miq_ae_method_spec.rb
  spec/models/miq_ae_namespace_spec.rb
  spec/models/miq_provision_workflow_spec.rb
  spec/models/mixins/assignment_mixin_spec.rb
  spec/models/mixins/per_ems_worker_mixin_spec.rb
  spec/models/pglogical_subscription_spec.rb
  spec/models/tag_spec.rb
  spec/models/user_spec.rb
  spec/models/vm_or_template_spec.rb
  spec/support/automation_helper.rb
  spec/support/evm_spec_helper.rb
  spec/support/quota_helper.rb
  tools/miqldap_to_sssd/configure_database.rb
  tools/reset_admin_password.rb
Labels: changelog/yes, ivanchuk/no, refactoring, services

#19305 Delete dynamic list type from DialogField as it no longer exists
  app/models/dialog_field.rb
Labels: cleanup, ivanchuk/no
