Repository ManageIQ/manageiq, pull requests merged in 2019-03, with the labels that each got.

#18507 Fix the metric rollup spec changing the timestamp
  spec/models/metric_rollup_spec.rb
Labels: bug/sporadic test failure, test

#18478 Deprecating RSS Feeds
  Gemfile
  app/models/miq_widget.rb
  app/models/miq_widget/rss_content.rb
  app/models/rss_feed.rb
  app/models/rss_feed/import_export.rb
  config/default_replication_exclude_tables.yml
  lib/evm_database.rb
  lib/resource_feeder/README
  lib/resource_feeder/Rakefile
  lib/resource_feeder/lib/resource_feeder.rb
  lib/resource_feeder/lib/resource_feeder/atom.rb
  lib/resource_feeder/lib/resource_feeder/common.rb
  lib/resource_feeder/lib/resource_feeder/rss.rb
  lib/resource_feeder/test/atom_feed_test.rb
  lib/resource_feeder/test/rss_feed_test.rb
  lib/resource_feeder/test/test_helper.rb
  spec/models/miq_widget/chart_content_spec.rb
  spec/models/miq_widget/import_from_hash_spec.rb
  spec/models/miq_widget/rss_content_spec.rb
  spec/models/miq_widget_spec.rb
  spec/models/rss_feed/data/newest_hosts.yml
  spec/models/rss_feed/data/newest_vms.yml
  spec/models/rss_feed/import_export_spec.rb
  spec/models/rss_feed/rss_feed_spec.rb
Labels: dependencies

#18493 Use throw :abort in MiqAction#before_destroy
  app/models/miq_action.rb
  spec/models/miq_action_spec.rb
Labels: technical debt

#18513 Only run preprocess_targets_manager_refresh when doing graph refresh and add specs
  app/models/manageiq/providers/base_manager/refresher.rb
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: bug, providers/inventory

#18511 Fix the dynamic service task naming generation for subclasses
  app/models/service_retire_task.rb
  spec/models/service_retire_task_spec.rb
Labels: bug, hammer/yes

#18500 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes

#18497 default merged_uri should return the parameter not the attribute
  app/models/file_depot.rb
  spec/factories/file_depot.rb
  spec/models/file_depot_ftp_spec.rb
  spec/models/file_depot_nfs_spec.rb
  spec/models/miq_schedule_spec.rb
Labels: bug, core, hammer/yes

#18488 Delegate vms_and_templates and miq_templates to parent_manager
  app/models/manageiq/providers/network_manager.rb
  spec/models/manageiq/providers/network_manager_spec.rb
Labels: bug

#18496 [V2V] Remove fatal nil IP check in preflight check
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, hammer/yes, transformation

#18506 [V2V] Allow downloading wrapper log file
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, hammer/yes, transformation

#18524 [V2V] Use default queue priority for log download
  app/models/service_template_transformation_plan_task.rb
Labels: bug, hammer/yes, transformation

#18505 Tag associated resource for conversion hosts
  app/models/conversion_host.rb
  spec/models/conversion_host/configurations_spec.rb
Labels: enhancement, hammer/yes, transformation

#18374 Add OrchestrationTemplateRunner to queue up orchestration stack deployment
  app/models/manageiq/providers/cloud_manager/orchestration_template_runner.rb
  app/models/service_orchestration.rb
  spec/models/service_orchestration_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes, orchestration, services

#18461 Extract override_gem to the bundler-inject plugin gem
  Gemfile
Labels: dependencies

#18473 ems_infra_pause/resume features to miq_product_feature_identifiers
  db/fixtures/miq_user_roles.yml
Labels: core, enhancement

#18523 dynamic DatePicker value isn't being set correctly
  app/models/dialog_field_date_control.rb
  spec/models/dialog_field_date_control_spec.rb
Labels: bug, hammer/yes

#18525 Add the resource name to the task action for conversion hosts
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host/configurations_spec.rb
Labels: enhancement, hammer/yes, transformation

#18528 [V2V] Add default setting for CPU and network limits per conversion host, and max concurrent tasks per EMS
  config/settings.yml
Labels: enhancement, hammer/yes, transformation

#18531 Update to bundler-inject 1.1.0
  Gemfile
Labels: dependencies

#18527 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#18516 Default to resource name for conversion hosts
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: enhancement, hammer/yes, transformation

#18469 Fix for inability to see dialog details passed to catalog after upgrade from 5.9.4 to 5.9.6
  app/models/dialog.rb
  spec/models/dialog_spec.rb
Labels: bug, hammer/yes

#18526 Remove unused system_automate_domains cause it's not called anymore
  lib/vmdb/plugins.rb
  spec/lib/vmdb/plugins_spec.rb
Labels: cleanup, technical debt

#18539 [V2V] Throttler - Replace class constant with global setting
  lib/infra_conversion_throttler.rb
Labels: enhancement, hammer/yes, transformation

#18544 Shift Nuage's qpid_proton dependency to 0.26.0
  Gemfile
Labels: dependencies

#18468 Updates for postgres 10
  .travis.yml
  app/models/vmdb_database_connection.rb
  lib/extensions/ar_adapter/ar_dba.rb
  spec/models/vmdb_database_connection_spec.rb
  spec/models/vmdb_database_spec.rb
  spec/replication/util/miq_pglogical_spec.rb
Labels: changelog/yes, core, dependencies, enhancement, hammer/no

#18371 Add volume multiattachment capability
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/openstack/cloud

#18548 Don't set version restriction for 'pg' gem
  Gemfile
Labels: dependencies, hammer/no

#18549 use like (vs ilike) for service query
  app/models/service/aggregation.rb
Labels: enhancement, performance

#18560 Add Volume Resizing capability to SupportsFeatureMixin
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/openstack/cloud

#18515 Remove container deployment code
  Gemfile
  app/models/authentication_allow_all.rb
  app/models/authentication_github.rb
  app/models/authentication_google.rb
  app/models/authentication_htpasswd.rb
  app/models/authentication_ldap.rb
  app/models/authentication_open_id.rb
  app/models/authentication_request_header.rb
  app/models/authentication_rhsm.rb
  app/models/automation_task.rb
  app/models/container_deployment.rb
  app/models/container_deployment/automate.rb
  app/models/container_deployment_node.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/container_manager.rb
  app/models/miq_cockpit_ws_worker/authenticator.rb
  app/models/vm.rb
  db/fixtures/miq_product_features.yml
  lib/services/container_deployment_service.rb
  spec/factories/authentication.rb
  spec/lib/services/container_deployment_service_spec.rb
  spec/models/container_deployment_spec.rb
  spec/models/miq_cockpit_ws_worker/authenticator_spec.rb
Labels: dependencies, hammer/no, technical debt

#18561 Move ALLOWED_FIELD_SUFFIXES to core in Chargeback and MeteringReport
  app/models/chargeback.rb
  app/models/metering.rb
  lib/miq_expression.rb
Labels: refactoring

#18555 Added ability to destroy all users dashboards
  app/models/miq_widget_set.rb
  spec/models/miq_widget_set_spec.rb
Labels: enhancement

#18542 Fix: started_on and state attributes for task linked to chargeback for service
  app/models/service.rb
  spec/models/service_spec.rb
Labels: bug

#18534 Use throw :abort in Tenant#before_destroy
  app/models/tenant.rb
  spec/models/tenant_spec.rb
Labels: changelog/no, core, hammer/no, technical debt

#18522 Use throw :abort in MiqUserRole#before_destroy
  app/models/miq_user_role.rb
  spec/models/miq_user_role_spec.rb
Labels: changelog/no, core, hammer/no, technical debt

#18518 Use throw :abort in MiqSearch#before_destroy
  app/models/miq_search.rb
  spec/models/miq_search_spec.rb
Labels: changelog/no, core, hammer/no, technical debt

#18550 Added MiqWidgetSet.copy_dashboard
  app/models/miq_widget_set.rb
  spec/models/miq_widget_set_spec.rb
Labels: enhancement

#18477 Fix graph refresh overwriting smartstate OS info
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: providers/inventory

#18514 Use throw :abort in MiqGroup#before_destroy
  app/models/miq_group.rb
  spec/models/miq_group_spec.rb
  spec/models/miq_widget_set_spec.rb
Labels: changelog/no, core, hammer/no, technical debt

#18557 update infra_migration_job when polling to prevent timing out
  app/models/infra_conversion_job.rb
Labels: blocker, bug, hammer/yes, transformation

#18444 Don't print the release codename in production mode
  config/application.rb
Labels: bug, core, hammer/yes

#18564 [V2V] Expose virt-v2v-wrapper error message in options hash
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, hammer/yes, transformation

#18538 Deprecate invalid custom attribute names
  app/models/mixins/custom_attribute_mixin.rb
  spec/models/mixins/custom_attribute_mixin_spec.rb
Labels: core, enhancement

#18570 [V2V] Fix ConversionHost active_tasks method to use state == 'migrate'
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: blocker, bug, hammer/yes, transformation

#18571 Fix a sporadic failure caused by array matching
  spec/models/chargeback_rate_detail_currency_spec.rb
Labels: bug/sporadic test failure, test

#18504 Fix saving network manager in belongsto filter
  app/models/ext_management_system.rb
  app/models/manageiq/providers/network_manager.rb
  app/models/miq_filter.rb
  spec/models/miq_filter_spec.rb
Labels: bug

#18566 Use manageiq-password RSpec matchers
  Gemfile
  spec/spec_helper.rb
  spec/tools/fix_auth/auth_model_spec.rb
Labels: dependencies, technical debt

#18567 Remove references to MiqPassword
  app/models/authenticator/base.rb
  app/models/automate_workspace.rb
  app/models/dialog_field_text_box.rb
  app/models/file_depot_s3.rb
  app/models/miq_queue.rb
  app/models/miq_region.rb
  app/models/miq_request_workflow.rb
  app/models/mixins/password_mixin.rb
  app/models/mixins/service_orchestration_options_mixin.rb
  app/models/pglogical_subscription.rb
  app/models/registration_system.rb
  app/models/service_ansible_playbook.rb
  app/models/service_ansible_tower.rb
  app/models/service_orchestration/option_converter.rb
  app/models/vm_scan.rb
  config/application.rb
  db/fixtures/customization_templates.yml
  lib/generators/provider/templates/app/models/manageiq/providers/%provider_name%/cloud_manager.rb
  lib/tasks/evm_application.rb
  lib/tasks/evm_dba.rake
  lib/vmdb/settings_walker.rb
  spec/lib/task_helpers/exports/customization_templates_spec.rb
  spec/lib/task_helpers/imports/data/customization_templates/existing_ct_and_pit.yaml
  spec/lib/task_helpers/imports/data/customization_templates/invalid_pit_pt.yml
  spec/lib/task_helpers/imports/data/customization_templates/new_ct_and_pit.yaml
  spec/lib/task_helpers/imports/data/customization_templates/no_pit_name.yml
  spec/lib/task_helpers/imports/data/customization_templates/pit_existing_name_new_pt.yml
  spec/lib/task_helpers/imports/data/customization_templates/system_ct.yml
  spec/lib/task_helpers/imports/data/customization_templates/update_existing.yml
  spec/lib/vmdb/settings_spec.rb
  spec/models/automate_workspace_spec.rb
  spec/models/dialog_field_text_box_spec.rb
  spec/models/miq_provision_workflow_spec.rb
  spec/models/miq_region_spec.rb
  spec/models/service_ansible_playbook_spec.rb
  spec/models/service_ansible_tower_spec.rb
  spec/models/service_orchestration_spec.rb
  spec/tools/fix_auth/auth_config_model_spec.rb
  spec/tools/fix_auth/auth_model_spec.rb
  tools/fix_auth/auth_model.rb
  tools/fix_auth/fix_auth.rb
  tools/pg_inspector/inspect_pg.rb
  tools/pg_inspector/inspect_pg_server.rb
Labels: dependencies

#18562 Update surro-gate to v1.0.5
  Gemfile
Labels: bug, dependencies, hammer/no

#18572 Drop the MiqEnterprise#is_enterprise? method
  app/models/miq_enterprise.rb
Labels: cleanup

#18578 Refactor the MiqTask#generic_action_with_callback method
  app/models/miq_task.rb
Labels: core, refactoring

#18579 Upgrade ripper_ruby_parser to 1.5.1
  Gemfile
Labels: dependencies, ruby2.6

#18563 Require the api client gem before using it
  app/models/mixins/process_tasks_mixin.rb
Labels: bug/sporadic test failure, technical debt

#18512 Add region checking for all user schedules
  app/models/miq_schedule_worker/runner.rb
Labels: bug, core

#18574 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#18543 Rbac virtual attributes
  app/models/miq_report/generator.rb
  app/models/miq_report/search.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, hammer/yes, performance, rbac

#18487 Speed up Service access
  app/models/service.rb
Labels: bug, performance

#18583 Don't start another refresh worker while another is stopping
  app/models/manageiq/providers/base_manager/refresh_worker.rb
Labels: bug, core/workers, providers

#18591 [ruby_require_leak_spec.rb] Better CI Ruby check
  spec/lib/ruby_require_leak_spec.rb
Labels: ruby2.5, test

#18569 Add report interval date and report generation to Chargeback reports
  app/models/chargeback.rb
  app/models/chargeback/consumption.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/metering_vm_spec.rb
Labels: chargeback, enhancement

#18309 [V2V] Refactor ConversionHost to use AuthenticationMixin
  app/models/conversion_host.rb
  app/models/conversion_host/configurations.rb
  app/models/mixins/authentication_mixin.rb
  spec/models/conversion_host/configurations_spec.rb
  spec/models/conversion_host_spec.rb
Labels: enhancement, hammer/yes, transformation

#18593 Make remote console worker dependencies optionally loaded
  Gemfile
  lib/remote_console/client_adapter/web_mks.rb
  lib/remote_console/rack_server.rb
  lib/remote_console/server_adapter/websocket_binary.rb
Labels: dependencies, providers/console

#18258 Add more robust error handling to ConversionHost#get_conversion_state
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: refactoring, transformation

#18595 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation, hammer/yes

#18565 ProcessTasksMixinin.invoke_tasks_remote should not send AuditEvent(:success) if invocation failed
  app/models/mixins/process_tasks_mixin.rb
  spec/models/mixins/process_tasks_mixin_spec.rb
Labels: bug, core, hammer/yes

#18604 Conversion host base class
  app/models/conversion_host.rb
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host/configurations_spec.rb
Labels: bug, hammer/yes, transformation

#18597 updating infra conversion job polling timers
  app/models/infra_conversion_job.rb
  config/settings.yml
  spec/models/infra_conversion_job_spec.rb
Labels: enhancement, hammer/yes, transformation

#18599 Remove references to MiqStats
  app/models/miq_report/generator/trend.rb
  app/models/vim_performance_analysis.rb
  app/models/vim_performance_trend.rb
Labels: refactoring, technical debt

#18601 Add zone to service provisioning.
  app/models/mixins/miq_request_mixin.rb
  app/models/service_template.rb
  app/models/service_template_provision_request.rb
  app/models/service_template_provision_task.rb
  spec/models/service_template_provision_task_spec.rb
Labels: enhancement, services
