Repository ManageIQ/manageiq, pull requests merged in 2019-07, with the labels that each got.

#18733 Add scope to list service templates from ancestor tenants
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: changelog/yes, enhancement

#18916 [Changelog] Update for Sprint 114
  CHANGELOG.md
Labels: documentation

#18911 [HAMMER] Add a tool to purge archived storages
  tools/purge_archived_storages.rb
Labels: bug, providers

#18536 [V2V] Add validation on VM name based on destination EMS
  app/models/transformation_mapping/vm_migration_validator.rb
  spec/models/transformation_mapping_spec.rb
Labels: enhancement, hammer/yes, transformation

#18934 Fix spec OpenStack Cloud factory
  spec/factories/ext_management_system.rb
Labels: bug, test

#18735 Add scope to list providers from ancestor tenants
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: changelog/yes, enhancement

#18929 [V2V] Enhance throttler logging
  app/models/conversion_host.rb
  lib/infra_conversion_throttler.rb
Labels: enhancement, hammer/yes, transformation

#18849 Support for opening URL from the UI through automate.
  app/models/cloud_tenant.rb
  app/models/external_url.rb
  app/models/generic_object.rb
  app/models/miq_group.rb
  app/models/mixins/external_url_mixin.rb
  app/models/provider.rb
  app/models/service.rb
  app/models/tenant.rb
  app/models/user.rb
  app/models/vm.rb
  config/replication_exclude_tables.yml
  spec/models/mixins/external_url_spec.rb
Labels: enhancement

#18935 Ensure NotificationType#subscriber_ids always returns non-nil
  app/models/notification_type.rb
  spec/models/notification_type_spec.rb
Labels: bug/sporadic test failure, core

#18939 Put back bundler >=1.15
  Gemfile
Labels: dependencies

#18941 Use the leaf class for creating the default credential
  app/models/manageiq/providers/embedded_ansible/seeding.rb
  spec/models/manageiq/providers/embedded_ansible_spec.rb
Labels: bug, changelog/no, core, embedded ansible

#18936 default inline_sql_views (aka turbo button) off
  app/models/miq_report.rb
  app/models/miq_report/generator.rb
  app/models/miq_report/search.rb
Labels: bug, services

#18930 [Changelog] Update for Hammer-8
  CHANGELOG.md
Labels: documentation, hammer/yes

#18942 [HAMMER][V2V] Add validation on VM name based on destination EMS
  app/models/transformation_mapping/vm_migration_validator.rb
  spec/models/transformation_mapping_spec.rb
Labels: enhancement, transformation

#18918 Remove Networks Load Balancer menu
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  db/fixtures/miq_user_roles.yml
  lib/rbac/filterer.rb
  locale/en.yml
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, hammer/no, providers/network, technical debt

#18944 Add ext_management_system.id to Migration Readiness summary reports
  product/reports/300_Migration Readiness - Virtual Machines/030_VMware VM Summary.yaml
  product/reports/310_Migration Readiness - Providers/010_VMware Environment Summary.yaml
Labels: enhancement

#18889 Save playbook set_stats data for successive playbook methods
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner_spec.rb
Labels: automate, enhancement

#18937 Refactor service template
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: changelog/no, cleanup, refactoring

#18880 [V2V] Use authentication_check instead of verify credentials
  app/models/conversion_host.rb
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
  spec/models/conversion_host_spec.rb
Labels: changelog/yes, hammer/no, transformation

#18932 Move AnsibleTowerJobTemplateDialogService from UI
  app/models/dialog/ansible_tower_job_template_dialog_service.rb
  spec/models/dialog/ansible_tower_job_template_dialog_service_spec.rb
Labels: changelog/no, hammer/no, providers/ansible_tower, technical debt

#18812 Modify method to hide columns dynamically in GTL list
  app/models/miq_report.rb
  spec/models/miq_report_spec.rb
Labels: enhancement

#18945 Allow specifying hosts to ansible runner
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: changelog/yes, core, embedded ansible, enhancement

#18626 Use admin to auto approve a request.
  app/models/miq_request.rb
  spec/models/automation_request_spec.rb
  spec/models/miq_request_spec.rb
  spec/models/miq_schedule_spec.rb
Labels: bug

#18951 Dialog import should check for blank file
  app/models/dialog_import_validator.rb
  spec/models/dialog_import_validator_spec.rb
Labels: bug

#18953 Move common physical infra code from Lenovo provider
  app/models/hardware.rb
  app/models/manageiq/providers/inventory/persister/builder/physical_infra_manager.rb
  app/models/manageiq/providers/physical_infra_manager.rb
Labels: providers/physical, providers/physical/lenovo, refactoring

#18952 reduce query count for chargeback currency seed
  app/models/chargeback_rate_detail_currency.rb
Labels: enhancement, performance

#18946 Pass hosts to runner from services
  app/models/manageiq/providers/ansible_playbook_workflow.rb
  app/models/manageiq/providers/ansible_role_workflow.rb
  app/models/manageiq/providers/ansible_runner_workflow.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script.rb
  app/models/service_ansible_playbook.rb
  spec/models/manageiq/providers/ansible_playbook_workflow_spec.rb
  spec/models/service_ansible_playbook_spec.rb
Labels: embedded ansible, enhancement, services

#18960 When copying ServiceTemplate copy only direct_custom_buttons
  app/models/service_template/copy.rb
  spec/models/service_template_spec.rb
Labels: bug, services

#18957 Pass hosts to runner from automate
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/inventory.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner_spec.rb
Labels: automate, embedded ansible, enhancement

#18958 Create multiple requests for multiple service retirement
  app/models/miq_retire_task.rb
  app/models/mixins/process_tasks_mixin.rb
  spec/models/mixins/process_tasks_mixin_spec.rb
  spec/models/orchestration_stack_retire_task_spec.rb
  spec/models/service_retire_task_spec.rb
  spec/models/vm_retire_task_spec.rb
Labels: bug, hammer/yes

#18964 Add doc comments and hosts to *_queue methods in Ansible::Runner
  lib/ansible/runner.rb
Labels: core, embedded ansible, enhancement

#18909 Allow order fields to be subqueries with order
  lib/extensions/ar_order.rb
  spec/lib/extensions/ar_order_spec.rb
Labels: bug, core, ui

#18965 Remove unused partial in RequestStartedOnMiddleware specs
  spec/lib/request_started_on_middleware_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#18801 Introduce Request and Task for firmware update
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/manageiq/providers/physical_infra_manager/firmware_update_task.rb
  app/models/miq_request.rb
  app/models/physical_server_firmware_update_request.rb
  app/models/physical_server_firmware_update_task.rb
  app/models/physical_server_firmware_update_task/state_machine.rb
  spec/factories/miq_request.rb
  spec/factories/miq_request_task.rb
  spec/models/miq_request_spec.rb
  spec/models/physical_server_firmware_update_request_spec.rb
  spec/models/physical_server_firmware_update_task/state_machine_spec.rb
  spec/models/physical_server_firmware_update_task_spec.rb
Labels: enhancement

#18843 Introduce AzureStack cloud & network provider
  Gemfile
  app/models/vm_or_template.rb
  config/permissions.tmpl.yml
  config/settings.yml
  lib/vmdb/loggers.rb
  lib/workers/miq_worker_types.rb
  spec/models/ext_management_system_spec.rb
  spec/models/manageiq/providers/cloud_manager_spec.rb
Labels: dependencies, enhancement, providers

#18966 provider url has a uniqueness validation so the factory should reflect that
  spec/factories/provider.rb
Labels: bug, test

#18906 Add VM SmartState Analysis policies to default policy set
  db/fixtures/miq_policy_sets.yml
Labels: enhancement

#18959 [V2V] Add uniqueness constraint to conversion host resource id
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: transformation

#18968 Add credential handling to Ansible::Runner
  lib/ansible/runner.rb
  lib/ansible/runner/credential.rb
  lib/ansible/runner/credential/generic_credential.rb
  lib/ansible/runner/credential/machine_credential.rb
  spec/lib/ansible/runner/credential/generic_credential_spec.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
  spec/lib/ansible/runner/credential_spec.rb
Labels: changelog/yes, core, embedded ansible, enhancement

#18974 Rename the "Cloud Intel" menu item to "Overview"
  db/fixtures/miq_shortcuts.yml
Labels: enhancement, hammer/no

#18956 Mark text for translation
  app/mailers/generic_mailer.rb
  spec/mailers/generic_mailer_spec.rb
Labels: bug, internationalization, ui

#18972 [EmbeddedAnsible] Fix manager ref for credentials
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/credential_spec.rb
Labels: bug, embedded ansible

#18975 Add a role for appliance internet connectivity
  db/fixtures/server_roles.csv
  spec/models/server_role_spec.rb
Labels: core, enhancement

#18962 Log only unique servers id used to process miq_request
  app/models/mixins/miq_request_mixin.rb
  spec/models/service_template_provision_task_spec.rb
Labels: changelog/yes, core, hammer/yes, technical debt

#18969 Pass credentials to ansible runner from services
  app/models/manageiq/providers/ansible_playbook_workflow.rb
  app/models/manageiq/providers/ansible_role_workflow.rb
  app/models/manageiq/providers/ansible_runner_workflow.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script.rb
  app/models/service_ansible_playbook.rb
  lib/ansible/runner/credential/machine_credential.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
  spec/models/service_ansible_playbook_spec.rb
Labels: changelog/yes, embedded ansible, enhancement, services

#18985 Don't use string interpolation inside gettext calls
  app/models/conversion_host.rb
  app/models/dialog.rb
  app/models/miq_report.rb
Labels: bug, internationalization

#18947 Set task's state to "finished" eventually
  app/models/physical_server_provision_task/state_machine.rb
Labels: enhancement

#18982 Allow modification of "Create new Picture" product feature on a role.
  db/fixtures/miq_product_features.yml
Labels: bug, hammer/yes

#18546 Add List Retired/Orphaned/Archived RBAC featuers
  app/models/vm_or_template.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, hammer/no

#18973 Include resource_actions and picture in service_template copy
  app/models/service_template/copy.rb
  spec/models/service_template/copy_spec.rb
  spec/models/service_template_spec.rb
Labels: changelog/yes, enhancement, hammer/no

#18984 [EmbeddedAnsible] Fix key unlock machine creds
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
  lib/ansible/runner/credential/machine_credential.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
Labels: core, embedded ansible, enhancement

#18927 Unify the HTML5 canvas-based remote consoles under a single endpoint
  app/models/mixins/supports_feature_mixin.rb
  app/models/vm.rb
  app/models/vm/operations.rb
  config/settings.yml
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
  spec/models/vm/operations_spec.rb
  spec/models/vm_spec.rb
Labels: changelog/yes, enhancement, hammer/no, providers/console

#18971 Update virtual attribute version
  Gemfile
Labels: dependencies

#18990 Adding tenant stuff to service template copy
  app/models/service_template/copy.rb
  spec/models/service_template/copy_spec.rb
Labels: changelog/yes, enhancement, hammer/no, services

#18308 Add orchestration stacks to RBAC
  app/models/orchestration_stack.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: hammer/no, orchestration, rbac

#18991 Adds cloud credentials to AnsibleRunner (for EmbeddedAnsible)
  lib/ansible/runner.rb
  lib/ansible/runner/credential.rb
  lib/ansible/runner/credential/amazon_credential.rb
  lib/ansible/runner/credential/azure_credential.rb
  lib/ansible/runner/credential/google_credential.rb
  lib/ansible/runner/credential/machine_credential.rb
  lib/ansible/runner/credential/openstack_credential.rb
  lib/ansible/runner/credential/rhv_credential.rb
  lib/ansible/runner/credential/vmware_credential.rb
  spec/factories/authentication.rb
  spec/lib/ansible/runner/credential/amazon_credential_spec.rb
  spec/lib/ansible/runner/credential/azure_credential_spec.rb
  spec/lib/ansible/runner/credential/generic_credential_spec.rb
  spec/lib/ansible/runner/credential/google_credential_spec.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
  spec/lib/ansible/runner/credential/openstack_credential_spec.rb
  spec/lib/ansible/runner/credential/rhv_credential_spec.rb
  spec/lib/ansible/runner/credential/vmware_credential_spec.rb
Labels: changelog/yes, core, embedded ansible, enhancement

#18921 Update webmocks
  Gemfile
Labels: dependencies

#18978 Random refactoring and cleanup
  app/models/service.rb
Labels: technical debt

#18992 Add missing shortcuts for v2v pages
  db/fixtures/miq_shortcuts.yml
Labels: bug, transformation

#18988 Restore ServiceAnsiblePlaybook#postprocess method
  app/models/service_ansible_playbook.rb
Labels: bug, embedded ansible, services

#19006 Encrypt passwords before putting them on the queue as args
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  app/models/manageiq/providers/embedded_ansible/crud_common.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/credential_spec.rb
Labels: bug, changelog/no, embedded ansible

#18989 Make embedded ansible verbosity and execution_ttl work
  app/models/manageiq/providers/ansible_playbook_workflow.rb
  app/models/manageiq/providers/ansible_role_workflow.rb
  app/models/manageiq/providers/ansible_runner_workflow.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner.rb
  app/models/service_ansible_playbook.rb
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
  spec/models/manageiq/providers/ansible_playbook_workflow_spec.rb
  spec/models/manageiq/providers/ansible_role_workflow_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_runner_spec.rb
  spec/models/service_ansible_playbook_spec.rb
Labels: changelog/yes, embedded ansible, enhancement, services

#18955 [Changelog] Update for Sprint 115
  CHANGELOG.md
Labels: documentation

#19009 [Changelog] Update for Hammer-9
  CHANGELOG.md
Labels: documentation, hammer/yes

#19008 Tool for exporting and importing schedules
  app/models/authentication.rb
  app/models/authentication/import_export.rb
  app/models/file_depot.rb
  app/models/file_depot/import_export.rb
  app/models/miq_schedule.rb
  app/models/miq_schedule/import_export.rb
  app/models/miq_search.rb
  app/models/miq_search/import_export.rb
  spec/models/miq_schedule_spec.rb
  tools/import_export_schedules.rb
Labels: enhancement

#19005 Fix for Default service dialog values not included in EVM when 'refresh_dialog_fields' action invoked
  app/models/dialog.rb
  app/models/dialog_field.rb
  app/models/resource_action_workflow.rb
  spec/models/dialog_field_spec.rb
  spec/models/dialog_spec.rb
  spec/models/resource_action_workflow_spec.rb
Labels: bug

#19007 [ansible_runner] Add NetworkCredential for Ansible::Runner lib
  app/models/manageiq/providers/embedded_ansible/automation_manager/network_credential.rb
  lib/ansible/runner/credential.rb
  lib/ansible/runner/credential/machine_credential.rb
  lib/ansible/runner/credential/network_credential.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
  spec/lib/ansible/runner/credential/network_credential_spec.rb
Labels: changelog/yes, core, embedded ansible, enhancement

#19010 Remove the worker restart_interval
  app/models/miq_server/worker_management/monitor/settings.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  config/settings.yml
  spec/models/miq_server/worker_monitor_spec.rb
Labels: cleanup, core/workers, technical debt

#18997 Parse days in integer value correctly for automation request scheduling
  app/models/automation_request.rb
  spec/models/automation_request_spec.rb
Labels: bug, hammer/no

#18976 locale rake tasks updates
  lib/tasks/locale.rake
Labels: internationalization

#19018 Add product "Release" info
  lib/vmdb/appliance.rb
Labels: enhancement

#19015 Fix rails 5.2 RecordNotSaved when trying to save a model association before the model
  app/models/service_template.rb
  spec/models/import_file_upload_spec.rb
Labels: bug, rails5.2

#19016 Don't pass class objects as values to where
  app/models/manageiq/providers/cloud_manager/vm_or_template.rb
  app/models/manageiq/providers/infra_manager/vm_or_template.rb
Labels: rails5.2

#19014 Rails 5.2 raises an error for missing attribute default_tenant_role (miq_group never had it)
  app/models/miq_group.rb
Labels: bug, rails5.2

#18981 Don't update playbook templates unless config_info is present
  app/models/service_template_ansible_playbook.rb
Labels: bug

#18928 Fix turbo order
  lib/rbac/filterer.rb
Labels: bug, core

#19019 Count the number of files for (compare) reports when testing seed
  spec/models/miq_report/seeding_spec.rb
Labels: hammer/no, reporting, test

#19020 Fix Embedded Ansible Respository refresh
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
Labels: bug, embedded ansible

#18987 Copy template spec refactoring
  spec/models/service_template/copy_spec.rb
Labels: changelog/no, refactoring, services

#19024 Fix Embedded Ansible Respository refresh
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
Labels: bug, embedded ansible

#19023 [HAMMER] Service retire task description dash was removed
  spec/models/service_retire_task_spec.rb
Labels: test

#19017 Remove the old ask_*_on_launch options
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
  app/models/service_template_ansible_playbook.rb
Labels: embedded ansible

#19013 Replace embedded ansible git repos with GitRepository
  app/models/git_repository.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
  lib/git_worktree.rb
  lib/git_worktree_exception.rb
  spec/models/git_repository_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
  spec/models/manageiq/providers/embedded_ansible_spec.rb
Labels: embedded ansible

#19028 Count the number of files for widgets when testing seed
  spec/models/miq_widget_spec.rb
Labels: hammer/no, reporting, test

#19030 Add missing `@` before pid to prevent cockpit worker from crashing
  app/models/miq_cockpit_ws_worker/runner.rb
Labels: bug, bugzilla needed

#19031 set vm name on reconnect
  app/models/vm_or_template.rb
Labels: bug, events, providers

#19034 Update! rather than update_attrs and save for scan items
  app/models/scan_item.rb
Labels: cleanup, performance

#19021 Cleanup sync_from_hash widget save
  app/models/miq_widget.rb
Labels: cleanup, performance

#19026 Don't update_attrs and then save on widget sets either
  app/models/miq_widget_set.rb
Labels: cleanup, performance

#19032 We don't need two calls for save in seeding chargeback rate detail measures
  app/models/chargeback_rate_detail_measure.rb
Labels: cleanup, performance

#19035 Change: ovirt_metrics dependency version
  Gemfile
Labels: bug, dependencies, providers/rhevm

#19040 J-release codename
  lib/vmdb/appliance.rb
Labels: ivanchuk/no

#19022 Cleanup seed_from_array product feature things
  app/models/miq_user_role.rb
Labels: cleanup, performance

#19033 Cleanup the save for notification type seeding
  app/models/notification_type.rb
Labels: cleanup, performance

#19039 Use the released version of manageiq-loggers
  Gemfile
Labels: core, dependencies, ivanchuk/yes

#19041 Oops. Fix broken widget set seed.
  app/models/miq_widget_set.rb
Labels: bug, ivanchuk/yes

#19045 No fuzzy merging in locale files
  lib/tasks/locale.rake
  locale/en/manageiq.po
Labels: internationalization, ivanchuk/yes

#19047 cbr is a hash, so we need the merge
  app/models/chargeback_rate_detail_measure.rb
Labels: bug, ivanchuk/yes

#19044 Remove the AnsibleAuthentications mixin
  app/models/miq_database.rb
  app/models/mixins/ansible_authentications.rb
Labels: core, embedded ansible, ivanchuk/yes, technical debt

#19043 Don't start httpd when the embedded ansible role is assigned
  app/models/miq_server/role_management.rb
Labels: bug, core, embedded ansible, ivanchuk/yes

#19053 Convert Vmdb::PermissionsStore to a blacklist
  config/permissions.tmpl.yml
  lib/vmdb/permission_stores/yaml.rb
  spec/lib/vmdb/permission_stores_spec.rb
  spec/models/ext_management_system_spec.rb
Labels: appliance, enhancement, ivanchuk/yes

#19056 Don't create the embedded ansible default project
  app/models/manageiq/providers/embedded_ansible/seeding.rb
  spec/models/manageiq/providers/embedded_ansible_spec.rb
Labels: changelog/yes, core, embedded ansible, ivanchuk/yes, technical debt

#19042 Don't restrict the zone to the embedded ansible manager zone for CRUD
  app/models/manageiq/providers/embedded_ansible/crud_common.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/credential_spec.rb
Labels: bug, embedded ansible, ivanchuk/yes

#19050 [IVANCHUK] Only ruby >= 2.5.3, < 2.6.0 is supported on ivanchuk
  .travis.yml
  Gemfile
  spec/lib/ruby_require_leak_spec.rb
Labels: dependencies, ruby2.5

#19049 Do not run the remote console proxy with the UI by default in dev
  config/routes.rb
Labels: changelog/yes, developer, ivanchuk/no, providers/console

#19054 [Changelog] Update for Sprint 116
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#19065 Send nil explicitly when queueing embedded ansible CRUD
  app/models/manageiq/providers/embedded_ansible/crud_common.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/credential_spec.rb
Labels: bug, changelog/no, embedded ansible, ivanchuk/yes

#19055 Queue ServiceAnsiblePlaybook#execute for the embedded_ansible role
  app/models/service_ansible_playbook.rb
  spec/models/service_ansible_playbook_spec.rb
Labels: bug, changelog/yes, embedded ansible, ivanchuk/yes, services

#19066 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#19048 [IVANCHUK] Update gettext catalogs for ivanchuk
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization

#19061 [EmbeddedAnsible] Better handle ConfigurationScriptSource status/last_updated_on/last_update_error
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
Labels: changelog/yes, core, embedded ansible, enhancement, ivanchuk/yes

#19072 Caching and threads... fun
  app/models/miq_server.rb
  spec/models/miq_server_spec.rb
Labels: bug/sporadic test failure, core, test

#19077 Do not get stuck on destroy
  app/models/ext_management_system.rb
Labels: bug

#19078 Create instance methods for miq_task status checking
  app/models/miq_task.rb
  spec/models/miq_task_spec.rb
Labels: bug, changelog/no, core, embedded ansible, ivanchuk/yes

#19075 [V2V] Store the conversion host name in the task options
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
Labels: enhancement, ivanchuk/yes, transformation

#19070 Add missing display names for some Azure provider models
  locale/en.yml
Labels: bug, ivanchuk/yes

#19076 Add `has_many :through` association for `switches` in `EmsCluster`
  app/models/ems_cluster.rb
Labels: bug, hammer/yes, ivanchuk/yes

#18938 Expand value to hash format with styling information for Report result API
  app/models/miq_report.rb
  app/models/miq_report_result/result_set_operations.rb
Labels: api, enhancement, reporting

#18986 [V2V] Update the transformation mapping specs.
  spec/models/transformation_mapping_spec.rb
Labels: test, transformation

#19069 FirmwareRegistry create
  app/models/firmware_registry.rb
  app/models/firmware_registry/rest_api_depot.rb
  spec/models/firmware_registry/rest_api_depot_spec.rb
  spec/models/firmware_registry_spec.rb
Labels: enhancement, providers/physical, providers/physical/redfish
