Repository ManageIQ/manageiq, pull requests merged in 2019-12, with the labels that each got.

#19563 Rename max_concurrent_tasks_per_host setting
  app/models/conversion_host.rb
  config/settings.yml
  lib/infra_conversion_throttler.rb
  spec/models/conversion_host_spec.rb
Labels: enhancement, transformation

#19567 Fix currency list on new money gem
  Gemfile
  app/models/chargeback_rate_detail_currency.rb
  spec/models/chargeback_rate_detail_currency_spec.rb
Labels: bug, dependencies

#19568 Add queue_name to queued method options for Flavor model
  app/models/flavor.rb
  spec/models/flavor_spec.rb
Labels: enhancement, providers/pluggability

#19570 Add queue_name to queued method options for CloudVolume model
  app/models/cloud_volume.rb
  spec/models/cloud_volume_spec.rb
Labels: enhancement, providers/pluggability

#19569 storage2hosts was unused as of 681518f6ad
  app/models/vm_or_template.rb
  spec/models/job_proxy_dispatcher_vm_storage2hosts_spec.rb
Labels: cleanup

#19571 Make the spec for `workers_quiesced?` make a bit more sense
  spec/models/miq_server_spec.rb
Labels: core/workers, test

#19577 [IVANCHUK] Lock 'money' gem to 6.13.4
  Gemfile
Labels: dependencies

#19410 [Gem] Virtual Attributes 1.5
  Gemfile
  app/models/security_group.rb
  spec/models/security_group_spec.rb
Labels: core, dependencies, enhancement

#19575 Simplify MiqServer#monitor_workers
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/quiesce.rb
  spec/models/miq_server/worker_monitor_spec.rb
Labels: core/workers, technical debt

#19561 Remove to_a call in all_ems_in_zone, fix rubocop warnings
  app/models/mixins/per_ems_worker_mixin.rb
Labels: technical debt

#19566 Add detailed RBAC features for VM and Image reconfigure.
  db/fixtures/miq_product_features.yml
Labels: changelog/yes, enhancement, providers/vmware/infra

#19580 Remove unused server options parsing
  lib/workers/bin/evm_server.rb
  lib/workers/evm_server.rb
Labels: cleanup, core

#19593 Remove unused worker OPTIONS_PARSER_SETTINGS
  app/models/manageiq/providers/base_manager/event_catcher/runner.rb
  app/models/manageiq/providers/base_manager/operations_worker/runner.rb
  app/models/manageiq/providers/base_manager/refresh_worker/runner.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_worker/runner.rb
Labels: cleanup, core/workers

#19578 Remove OrchestrationStack#update_stack_queue
  app/models/orchestration_stack.rb
Labels: cleanup, providers/cloud

#19579 Add queue_name to CloudVolumeBack ems operations, plus specs
  app/models/cloud_volume_backup.rb
  spec/models/cloud_volume_backup_spec.rb
Labels: enhancement, providers/cloud

#19599 Cu capture move capture queue
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/capture.rb
  app/models/metric/ci_mixin/capture.rb
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: enhancement, providers/metrics, refactoring

#19601 Add a queue_name to the CloudVolumeSnapshot#delete_snapshot_queue method
  app/models/cloud_volume_snapshot.rb
  spec/models/cloud_volume_snapshot_spec.rb
Labels: enhancement, providers/cloud

#19602 Add queue_name to queued method options for CloudTenant model
  app/models/cloud_tenant.rb
  spec/models/cloud_tenant_spec.rb
Labels: enhancement, providers/cloud

#19603 Add queue_name to queued method options for CloudObjectStoreContainer model
  app/models/cloud_object_store_container.rb
  spec/models/cloud_object_store_container_spec.rb
Labels: enhancement, providers/cloud

#19604 Add a queue_name to the IsoDatastore#synchronize_advertised_images_queue method
  app/models/iso_datastore.rb
  spec/models/iso_datastore_spec.rb
Labels: enhancement, providers/virtual

#19606 Test the RefreshWorker not the EmsRefreshCoreWorker
  spec/models/mixins/per_ems_worker_mixin_spec.rb
Labels: core/workers, test

#19605 Remove waiting_for_stop_before_restart monitor status
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/stop.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  spec/models/miq_server/worker_monitor_spec.rb
Labels: core, technical debt

#19574 Dialog#destroy should ignore resource actions linking nonexisting entities
  app/models/dialog.rb
  spec/models/dialog_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, ui/service

#19573 CustomButtonSet - handle deleted custom buttons still in button_order
  app/models/custom_button_set.rb
  spec/lib/task_helpers/exports/custom_buttons_spec.rb
  spec/models/custom_button_set_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, ui/service

#19555 Improve the error handling of OrchestrationTemplateRunner
  app/models/manageiq/providers/cloud_manager/orchestration_template_runner.rb
  app/models/service_orchestration.rb
  spec/models/service_orchestration_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, orchestration

#19178 Update service dialog options when reconfigure finishes well.
  app/models/service_reconfigure_task.rb
  spec/models/service_reconfigure_task_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes

#19558 Use automate timeout for service.execute when execution_ttl is not set for a service
  app/models/manageiq/providers/embedded_ansible/automation_manager/playbook.rb
  app/models/service.rb
  app/models/service_ansible_playbook.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_spec.rb
  spec/models/service_ansible_playbook_spec.rb
Labels: changelog/yes, embedded ansible, enhancement

#19600 Rename method to avoid name conflict with AR#update.
  app/models/manageiq/providers/cloud_manager/orchestration_template_runner.rb
  app/models/service_orchestration.rb
  spec/models/service_orchestration_spec.rb
Labels: bug

#19538 Rename: ChargebackRateDetailCurrency -> Currency
  app/models/chargeback_rate.rb
  app/models/chargeback_rate_detail.rb
  app/models/currency.rb
  app/models/service_template.rb
  lib/evm_database.rb
  spec/factories/chargeback_rate_detail.rb
  spec/factories/chargeback_rate_detail_currency.rb
  spec/models/chargeback_rate_detail_spec.rb
  spec/models/chargeback_rate_spec.rb
  spec/models/currency_spec.rb
Labels: technical debt

#19619 Add migration analytics files to default ssa profile
  product/scan_items/scan_item_file.yaml
Labels: enhancement, ivanchuk/yes

#19609 Move the important parts of monitoring workers into #monitor_workers
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  spec/models/miq_server/worker_management/heartbeat_spec.rb
  spec/models/miq_server/worker_monitor_spec.rb
Labels: core, refactoring

#19564 Switch from git source to rubygems.manageiq.org
  Gemfile
Labels: dependencies

#19560 Add a console helper method to set up a $evm variable
  lib/vmdb/console_methods.rb
Labels: developer, enhancement

#19621 Allow provider subclasses of Storage
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/infra_manager/storage.rb
  app/models/storage.rb
Labels: enhancement, providers/pluggability

#19624 [IVANCHUK] Ivanchuk-2 changelog
  CHANGELOG.md
Labels: documentation

#19626 Add tool to visualize Jobs in graphviz dot format
  app/models/job/state_machine.rb
  tools/job_to_svg.rb
Labels: tools

#19628 Fix run_command_via_queue without arguments
  app/models/vm_or_template.rb
  spec/models/vm_or_template/operations/power_spec.rb
Labels: bug, providers

#19625 Add queue name to ManageIQ::Providers::CloudManager::Vm queue methods
  app/models/manageiq/providers/cloud_manager/vm.rb
  spec/models/manageiq/providers/cloud_manager/vm_spec.rb
Labels: enhancement, providers/cloud

#19631 Reduce number of cockpit selinux changes
  app/models/miq_cockpit_ws_worker/runner.rb
  lib/miq_cockpit.rb
  spec/lib/miq_cockpit_spec.rb
  tools/cockpit/cockpit-auth-miq
Labels: blocker, bug, core, ivanchuk/yes

#19630 Add trait with_storages_redhat to ems.
  spec/factories/ext_management_system.rb
Labels: test

#19629 Update rubyzip to 2.0.0
  Gemfile
  lib/vmdb/util.rb
  spec/lib/vmdb/util_spec.rb
Labels: dependencies, security

#19639 Bump linux_admin to v2.0.0
  Gemfile
Labels: dependencies

#19610 Cap&U subclass MetricsCapture
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/manageiq/providers/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/container_manager/metrics_capture.rb
  app/models/manageiq/providers/infra_manager/metrics_capture.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/container_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/infra_manager/metrics_capture_spec.rb
  spec/models/metric/ci_mixin/capture_spec.rb
  spec/models/metric/targets_spec.rb
  spec/support/metric_helper.rb
Labels: enhancement, providers/metrics

#19585 Schedule the check for timed out queue messages once for the region
  app/models/miq_queue.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/validation.rb
  config/settings.yml
  spec/models/miq_queue_spec.rb
  spec/models/miq_server/worker_monitor_spec.rb
  spec/models/miq_server_spec.rb
Labels: core, refactoring

#19635 [WIP] OrchestrationTemplateRunner#queue_signal queue name
  app/models/manageiq/providers/cloud_manager/orchestration_template_runner.rb
  spec/models/manageiq/providers/cloud_manager/orchestration_template_runner_spec.rb
Labels: wip

#19644 [HAMMER] Lock money gem to 6.13.1
  Gemfile
Labels: dependencies

#19646 [HAMMER] dialog_spec#destroy - move dialog creation into a let
  spec/models/dialog_spec.rb
Labels: test

#19643 [HAMMER] Add policy check to Vm retirement.
  app/models/vm_or_template.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, changelog/yes, retirement

#19647 [IVANCHUK] Add policy check to Vm retirement.
  app/models/vm_or_template.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, changelog/yes, retirement

#19634 Add queue_name to the ConversionHost.queue_configuration singleton method
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host_spec.rb
Labels: enhancement, transformation

#19651 Add queue_name to ems operations for ManageIQ::Providers::CloudManager::AuthKeyPair
  app/models/manageiq/providers/cloud_manager/auth_key_pair.rb
  spec/models/manageiq/providers/cloud_manager/auth_key_pair_spec.rb
Labels: enhancement, providers/cloud

#19642 Remove useless stub in the iso datastore specs
  spec/models/iso_datastore_spec.rb
Labels: refactoring, test

#19534 Subclass Folders, Datacenters, and StorageClusters
  app/models/ems_folder.rb
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/infra_manager/datacenter.rb
  app/models/manageiq/providers/infra_manager/folder.rb
  app/models/manageiq/providers/infra_manager/storage_cluster.rb
  spec/factories/ems_folder.rb
Labels: enhancement, providers/pluggability

#19648 Use TERM signals instead of an exit message over drb to stop workers
  app/models/miq_server/worker_management/monitor/stop.rb
  app/models/miq_worker/runner.rb
  app/models/mixins/miq_web_server_runner_mixin.rb
  app/models/mixins/miq_web_server_worker_mixin.rb
  lib/workers/bin/run_single_worker.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
  spec/models/miq_server/worker_monitor_spec.rb
  spec/models/miq_worker/runner_spec.rb
Labels: core/workers, refactoring

#19658 Remove unused highline gem
  Gemfile
  tools/pg_inspector/util.rb
Labels: changelog/no, core, dependencies, technical debt

#19641 Use a relation for groups when testing current region specs
  spec/models/miq_widget_spec.rb
Labels: refactoring, test

#19661 Remove invalid 'mock' partial in ManageIQ::Providers::Inventory::Persister specs
  spec/models/manageiq/providers/inventory/persister/serializing_spec.rb
Labels: technical debt, test

#19663 Use data_source_exists? instead of table_exists? in ArPglogicalMigrationHelper
  spec/lib/extensions/ar_migration_spec.rb
Labels: core, test

#19623 Cap&U capture interval tests
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/metric/ci_mixin/capture_spec.rb
  spec/support/metric_helper.rb
Labels: providers/metrics, refactoring, test

#19671 Remove bogus stub for JobProxyDispatcherVmProxies4Job
  spec/models/job_proxy_dispatcher_vm_proxies4job_spec.rb
Labels: refactoring, test

#19672 Remove unused partial in zone specs
  spec/models/zone_spec.rb
Labels: refactoring, test
