Repository ManageIQ/manageiq, pull requests merged in 2020-04, with the labels that each got.

#20030 initialize_type_map now expects 1 argument
  lib/extensions/ar_types.rb
Labels: rails5.2

#20029 With rails 5.2, where clauses will no longer cast Class objects as Strings
  app/models/miq_report_result.rb
Labels: rails5.2

#20024 Serverid not required if all_servers is used
  tools/configure_server_settings.rb
Labels: bug, tools

#20038 fix storage profile ems foreign key
  app/models/storage_profile.rb
Labels: bug, core, core/storage, rails5.2

#20037 fix report formatter deprecation warning
  app/models/miq_report/formatters/text.rb
Labels: refactoring, ui

#20040 Ensure signal is queued in poll_transform_vm_complete also for warm migration
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, v2v

#19824 MiqAeNamespace should use ancestry instead of acts_as_tree
  app/models/miq_ae_class.rb
  app/models/miq_ae_namespace.rb
  spec/models/miq_ae_class_spec.rb
  spec/models/miq_ae_field_spec.rb
  spec/models/miq_ae_instance_spec.rb
  spec/models/miq_ae_namespace_spec.rb
Labels: automate, performance

#20036 fix order warnings
  app/models/custom_button.rb
  app/models/miq_report_result.rb
  app/models/mixins/process_tasks_mixin.rb
  db/fixtures/tools/create_customization_templates_fixture.rb
  db/fixtures/tools/create_pxe_image_types_fixture.rb
  spec/models/classification_spec.rb
  tools/db_printers/print_network.rb
  tools/db_printers/print_scsi.rb
Labels: cleanup, jansa/yes?, rails5.2

#20044 fix rubocop gone bad
  app/models/miq_ae_class.rb
Labels: bug, core

#20025 [IVANCHUK] Update manageiq-smartstate Gem to 0.3.6
  Gemfile
Labels: dependencies

#20045 [TimeProfile] Fix "Dangerous query method" warning
  app/models/time_profile.rb
Labels: jansa/yes?, rails5.2

#20046 Remote namespace#parent_id from specs
  spec/models/miq_ae_class_spec.rb
  spec/models/miq_ae_method_spec.rb
Labels: automate/model, test

#19987 Syndicate metrics to Kafka
  app/models/ems_event.rb
  app/models/metric/ci_mixin/processing.rb
  app/models/miq_queue.rb
  config/settings.yml
Labels: enhancement

#20054 Pluggable config/supported_locales.yml
  lib/vmdb/fast_gettext_helper.rb
Labels: enhancement

#20056 Remove unnecessary test tag that is no longer used
  config/database.pg.yml
Labels: cleanup, core, jansa/yes?

#20053 Simplify Vmdb::PermissionsStore and make it pluggable
  config/initializers/permissions_repository.rb
  lib/vmdb/permission_stores.rb
  lib/vmdb/permission_stores/null.rb
  lib/vmdb/permission_stores/yaml.rb
  spec/lib/vmdb/permission_stores_spec.rb
  spec/models/ext_management_system_spec.rb
  spec/support/vmdb_permission_store_helper.rb
Labels: jansa/yes?, technical debt

#20049 Move messaging options from Settings to files
  .gitignore
  app/models/miq_queue.rb
  config/messaging.artemis.yml
  config/messaging.kafka.yml
  config/settings.yml
  lib/manageiq/environment.rb
  spec/models/miq_queue_spec.rb
Labels: enhancement, jansa/yes, refactoring

#20055 Skip empty Volumes in VM provisioning
  app/models/manageiq/providers/cloud_manager/provision/state_machine.rb
Labels: enhancement, lifecycle/provisioning

#20011 Allow two-phase migration for SSH transport method
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/infra_conversion_job_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, jansa/yes?, v2v

#20060 Add the resource's ems_type to the metric payload
  app/models/metric/ci_mixin/processing.rb
Labels: enhancement, providers/metrics

#20016 Relax qpid_proton requirement
  Gemfile
Labels: dependencies, providers

#20058 Fix a bug when running Rbac on VimPerformanceDaily
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, core/rbac

#20062 Fix messaging_client exception if no ENV and no yaml are present
  app/models/miq_queue.rb
Labels: bug, core/queue

#20061 Add an ExtManagementSystem#refresh instance method
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: enhancement

#20063 fix typo on query
  app/models/mixins/miq_provision_quota_mixin.rb
Labels: bug

#19930 Enhance acts_as_miq_set to add the corresponding has_many for set members based on the table name of the model
  lib/extensions/ar_miq_set.rb
  spec/models/miq_policy_spec.rb
Labels: bug

#20039 Only show catalog types for supported EMSs
  app/models/ext_management_system.rb
  app/models/manageiq/providers/base_manager.rb
  app/models/manageiq/providers/embedded_automation_manager.rb
  app/models/manageiq/providers/network_manager.rb
  app/models/service_template.rb
  spec/models/ext_management_system_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager_spec.rb
Labels: core/embedded ansible, enhancement

#19843 Switch core code to use manageiq-ssh-util instead of gems-pending
  Gemfile
  app/models/conversion_host.rb
  app/models/host.rb
  spec/models/conversion_host_spec.rb
Labels: dependencies, hammer/no, ivanchuk/no, refactoring

#20067 Fix a missing permission stub in a spec
  spec/models/ext_management_system_spec.rb
Labels: bug, test

#20066 [IVANCHUK] Update manageiq-smartstate Gem to 0.3.7
  Gemfile
Labels: dependencies

#20015 update to bundler 2.1
  Gemfile
Labels: dependencies

#20069 [IVANCHUK] Allow overriding ESXi IP address with a custom attribute
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, v2v

#20068 [IVANCHUK] Allow job to continue if kill_virtv2v raises an execption
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/infra_conversion_job_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, v2v

#20072 Eager load collection constants to avoid constant loading problems.
  app/models/miq_web_service_worker.rb
  spec/models/miq_web_server_worker_spec.rb
Labels: api, bug, ivanchuk/yes, jansa/yes?

#20073 Add Sprint review 134
  CHANGELOG.md
Labels: documentation

#20052 delete MiqExpression#merge_where_clauses
  app/models/miq_report/generator.rb
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
  spec/models/miq_report/generator_spec.rb
Labels: core/reporting, rails5.2

#20070 Add an owner reference to the orchestrator pod for all created objects
  lib/container_orchestrator/object_definition.rb
Labels: bug, core, jansa/yes?

#20074 Offer default formatters for MiqReport
  app/models/miq_report.rb
Labels: api, bug, ui

#20082 Document unique_within_region
  lib/unique_within_region_validator.rb
Labels: documentation

#20080 Add compliance_policies to ComplianceMixin
  app/models/mixins/compliance_mixin.rb
Labels: enhancement, providers

#20078 Specs for MiqReport#col_format_with_defaults
  spec/models/miq_report_spec.rb
Labels: jansa/yes?, test

#20077 Fixed cockpit process starting
  app/models/miq_cockpit_ws_worker/runner.rb
  lib/miq_cockpit.rb
Labels: bug, core, ivanchuk/yes, jansa/yes?

#20093 [V2V] Prevent removing active conversion host
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host/configurations_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, v2v

#20081 Updated vm_reconfigure_task in app/models to add disk Type information.
  app/models/vm_reconfigure_task.rb
  spec/models/vm_reconfigure_task_spec.rb
Labels: bug

#20098 Add {created,updated}_at to global skip attributes
  spec/support/ems_refresh_helper.rb
Labels: test

#20094 Use CONTAINER_IMAGE_TAG for worker deployment tag
  app/models/miq_worker/container_common.rb
Labels: bug, core, jansa/yes

#20100 Allow plugins to bring I18n yaml files
  config/initializers/fast_gettext.rb
Labels: enhancement, pluggability

#20096 Add scopes for VMs from Cloud/Infra Managers
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: enhancement, providers

#20097 Handle user create race condition
  app/models/authenticator/base.rb
  spec/models/authenticator/httpd_spec.rb
Labels: bug

#20095 Don't run worker pods as root
  lib/container_orchestrator/object_definition.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: core, enhancement, jansa/yes?

#20109 MiqReport: add skip_references attribute back
  app/models/miq_report.rb
Labels: bug, core/reporting, jansa/yes?

#20112 Add Sprint review 135
  CHANGELOG.md
Labels: documentation

#20102 [V2V] Add fixed SSH key file path for virt-v2v-wrapper
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, v2v

#20110 Modify MiqExpression Contains to work for Rails 5.2
  lib/miq_expression.rb
  lib/miq_expression/where_extraction_visitor.rb
  spec/lib/miq_expression_spec.rb
Labels: core/reporting, enhancement, jansa/yes?, rails5.2

#20117 Remove deprecated method (Host.host_discovery_types) now that it is no longer used
  app/models/host.rb
Labels: cleanup

#20079 Validate according to cols for MiqReportResult#result_set_for_reporting
  app/models/miq_report.rb
  app/models/miq_report_result/result_set_operations.rb
  spec/models/miq_report_result/result_set_operations_spec.rb
Labels: bug, jansa/yes?

#20111 Add parts needed for the NSX-T provider
  app/models/cloud_network.rb
  app/models/cloud_tenant.rb
  app/models/custom_button.rb
  app/models/manageiq/providers/inventory/persister/builder/network_manager.rb
  app/models/manageiq/providers/network_manager.rb
  app/models/mixins/has_network_manager_mixin.rb
  app/models/network_service.rb
  app/models/network_service_entry.rb
  app/models/security_group.rb
  app/models/security_policy.rb
  app/models/security_policy_rule.rb
  app/models/security_policy_rule_destination_security_group.rb
  app/models/security_policy_rule_network_service.rb
  app/models/security_policy_rule_source_security_group.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement
