Repository ManageIQ/manageiq, pull requests merged in 2020-06, with the labels that each got.

#20190 Chargeback Reports De-Explorization support
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement

#20230 Fix NetworkManager.display_name
  app/models/manageiq/providers/network_manager.rb
Labels: bug, providers/network

#20233 Fix metrics rollup floating point precision error
  spec/models/metric/ci_mixin/rollup_spec.rb
Labels: bug, providers/metrics, test

#20228 Better formatting for rate columns in chargeback reports
  app/models/chargeback_rate_detail.rb
  spec/models/chargeback_vm_spec.rb
Labels: core/chargeback, enhancement, jansa/yes?

#20236 Bump the worker liveness check timeout to avoid false failures
  lib/container_orchestrator/object_definition.rb
Labels: core, enhancement, jansa/yes?

#20242 Fix targets_archived_from after refactoring to MetricsCapture
  app/models/manageiq/providers/container_manager/metrics_capture.rb
Labels: bug, jansa/yes?, providers/metrics

#20249 Bump virtual_attributes gem to 2.0
  Gemfile
Labels: dependencies, enhancement

#20240 Fixed seeding order for Chargeback Rates
  lib/evm_database.rb
Labels: bug, jansa/yes?

#20241 Bump to psych 3.1.0 to fix invalid yaml parsing
  Gemfile
Labels: bug, dependencies, providers/automation

#20256 Fix `rake locale:extract_locale_names` by providing environment
  lib/tasks/locale.rake
Labels: bug, developer, internationalization, jansa/yes?

#20266 Add Sprint review 138
  CHANGELOG.md
Labels: documentation

#20259 add a test for the genealogy setting in vm_or_template
  spec/models/vm_or_template_spec.rb
Labels: test

#20270 Use `N_()` notation to convert strings in UI when locale is changed
  app/models/miq_alert.rb
Labels: bug, internationalization, jansa/yes

#20231 Automate RelativePath mixin
  app/models/miq_ae_class.rb
  app/models/miq_ae_instance.rb
  app/models/miq_ae_method.rb
  app/models/miq_ae_namespace.rb
  app/models/mixins/relative_path_mixin.rb
Labels: automate/model, jansa/yes?, refactoring

#20269 Added NSX-T spec factories and some settings
  .rubocop_local.yml
  spec/factories/cloud_network.rb
  spec/factories/cloud_subnet.rb
  spec/factories/cloud_tenants.rb
  spec/factories/ext_management_system.rb
  spec/factories/network_port.rb
  spec/factories/network_router.rb
  spec/factories/network_service.rb
  spec/factories/network_service_entry.rb
  spec/factories/security_group.rb
  spec/factories/security_policy.rb
  spec/factories/security_policy_rule.rb
  spec/lib/vmdb/loggers_spec.rb
Labels: enhancement, providers/network

#20271 Update miq_alert_spec.rb
  spec/models/miq_alert_spec.rb
Labels: test

#20254 Fix Service assignment in ServiceOrchestration reconnection script
  tools/reconnect_service_orchestration_stacks.rb
Labels: bug, providers/cloud, tools

#20272 Add spec that checks for group switching limitations
  spec/models/user_spec.rb
Labels: enhancement, jansa/yes?, test

#20250 Removing as Xen VMs were never implemented
  app/models/vm_xen.rb
Labels: cleanup

#20265 Translation code fixes
  lib/vmdb/fast_gettext_helper.rb
  spec/i18n/locale_name_spec.rb
  spec/shared/i18n/placeholders.rb
Labels: bug, internationalization

#20277 Explicitly disable systemd support in podified env
  lib/miq_environment.rb
  spec/lib/miq_environment_spec.rb
Labels: appliance, bug, jansa/yes?

#20279 Don't rely on the default value for ImagePullPolicy
  app/models/miq_worker/container_common.rb
Labels: bug, core, jansa/yes?

#20280 Remove extra vm_xen reference from factories
  app/models/template_xen.rb
  spec/factories/vm_or_template.rb
Labels: cleanup

#20137 add dialog info when import/export custom buttons
  lib/task_helpers/exports/custom_buttons.rb
  lib/task_helpers/imports.rb
  lib/task_helpers/imports/custom_buttons.rb
  spec/lib/task_helpers/imports/custom_buttons_spec.rb
  spec/lib/task_helpers/imports/data/custom_buttons/CustomButtons.yaml
Labels: enhancement

#20216 Provide message when tag assignment failed
  app/models/classification.rb
  spec/models/classification_spec.rb
Labels: enhancement

#20199 MiqExpression#contains improvement
  lib/miq_expression.rb
  lib/miq_expression/field.rb
  lib/miq_expression/tag.rb
  lib/miq_expression/target.rb
  spec/lib/miq_expression/field_spec.rb
  spec/lib/miq_expression/tag_spec.rb
  spec/lib/miq_expression_spec.rb
Labels: core/reporting, enhancement, jansa/no

#20282 [Ansible::Runner] Fix --ask-become-method for machine credentials
  lib/ansible/runner.rb
  lib/ansible/runner/credential/machine_credential.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
  spec/lib/ansible/runner_spec.rb
Labels: bug

#20287 Update Service OrchestrationStack reconnection script
  tools/reconnect_service_orchestration_stacks.rb
Labels: refactoring, tools

#20292 Do targeted refresh when waiting for IP address
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: enhancement, ivanchuk/yes, jansa/yes?, v2v

#20291 Change the Settings cache check in tests to improve performance
  spec/support/evm_spec_helper.rb
Labels: jansa/yes?, performance, test

#20295 Fix REGEX for virtual custom attributes in MiqExpression::Field
  lib/miq_expression/field.rb
  spec/lib/miq_expression/field_spec.rb
Labels: bug, jansa/yes?

#20297 Create env vars to override the full worker image ref
  app/models/miq_ui_worker.rb
  app/models/miq_worker/container_common.rb
  app/models/miq_worker/service_worker.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: core, enhancement, jansa/yes?

#20302 Combine child managers' RefreshWorkers
  app/models/ems_refresh.rb
  app/models/manageiq/providers/base_manager/refresh_worker.rb
Labels: providers, refactoring

#20283 remove extra selects from the persister builder cloud manager queries
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
Labels: bug

#20306 Add Sprint review 139
  CHANGELOG.md
Labels: documentation

#20304 refactor with_rel_type genealogy setter
  app/models/ems_refresh/save_inventory.rb
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  app/models/vm_or_template.rb
Labels: jansa/no, refactoring

#20290 Ensure ems workers are killed by their server/orchestrator pod
  app/models/ext_management_system.rb
  app/models/miq_worker.rb
  spec/models/ext_management_system_spec.rb
  spec/models/miq_worker_spec.rb
Labels: appliance/workers, bug

#20305 Remove the miq_workers table from the reindex list
  config/settings.yml
Labels: bug, core, jansa/yes?

#20293 bump linux_admin
  Gemfile
Labels: dependencies, ivanchuk/yes, jansa/yes?

#20312 Fix issue where the square brackets are being created as directories in docker
  .dockerignore
  Dockerfile
Labels: bug, build/docker

#19276 [EmbeddedAnsible] TODO Cleanup
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job/status_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
Labels: cleanup, core/embedded ansible

#20311 rename relationship ancestry method to clarify that it's for relationships
  app/models/miq_filter.rb
  app/models/mixins/relationship_mixin.rb
Labels: cleanup, jansa/no

#20310 remove arguments we're not using from relationship ancestry methods
  app/models/mixins/relationship_mixin.rb
Labels: cleanup, jansa/no

#20308 update parent setting test in vm_or_template to use update!
  spec/models/vm_or_template_spec.rb
Labels: jansa/no, test

#20314 Add supports feature mixin to container templates
  app/models/container_template.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/containers

#20313 Destroying a provider doesn't destroy its parent manager
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: bug, providers

#20299 Fixed Settings hierarchy on Global region
  app/models/miq_server.rb
  spec/lib/vmdb/settings_spec.rb
  spec/models/miq_server_spec.rb
Labels: bug, core, ivanchuk/yes, jansa/yes?

#20317 Revert dependent destroy of provider from EMS
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: bug, providers

#19751 Remove unused conditional from class_for_platform in MiqProvisionWorkflow
  app/models/miq_provision_workflow.rb
Labels: refactoring
