Repository ManageIQ/manageiq, pull requests merged in 2020-07, with the labels that each got.

#20323 Double the initial delay and timeout for worker container liveness probes
  lib/container_orchestrator/object_definition.rb
Labels: bug, core, jansa/yes?

#20325 Gemfile: Secure connection to https://rubygems.manageiq.org
  Gemfile
Labels: dependencies

#20327 [JANSA] Translation files update
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: bug, internationalization

#20321 Move the systemd env var check into the systemd_worker? method
  app/models/miq_worker.rb
Labels: appliance/workers, bug, jansa/yes?

#20330 Fix foreman provider missing url in specs
  spec/factories/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: bug, providers/configuration, test

#20328 Rename term to unsupported for clarity
  lib/vmdb/permission_stores.rb
Labels: cleanup

#20193 Add a memory and cpu limits on deployments
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_worker/container_common.rb
  config/settings.yml
  spec/models/miq_worker/container_common_spec.rb
Labels: core, enhancement, jansa/yes?

#20329 [JANSA] Move the systemd env var check into the systemd_worker? method
  app/models/miq_worker.rb
  config/settings.yml
Labels: appliance/workers, bug

#20322 [ansible/runner.rb] Add additional python3 module path for Centos8 support
  lib/ansible/runner.rb
Labels: bug, core/embedded ansible

#20336 Remove the extra env var for systemd configuration
  app/models/miq_worker.rb
Labels: appliance/workers

#20333 fix miq_request typo
  app/models/miq_request.rb
Labels: cleanup

#20332 Move supports :create out of base Flavor model
  app/models/flavor.rb
Labels: bug, jansa/yes?, providers/cloud

#20339 Add Sprint review 140
  CHANGELOG.md
Labels: documentation

#20315 Added support for optional auth debugging
  app/models/authenticator/base.rb
  app/models/authenticator/httpd.rb
  config/settings.yml
Labels: enhancement, jansa/yes?

#20337 Use chargeback model in columns for report editor
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: jansa/yes

#20342 Use the passed service account for worker deployments
  lib/container_orchestrator/object_definition.rb
Labels: core, enhancement

#20344 Do NOT print message when using memcache (default)
  config/initializers/session_store.rb
Labels: developer, enhancement

#20341 Remove MiqSockUtil and just use Socket
  app/models/miq_server/environment_management.rb
  lib/miq_environment.rb
  spec/lib/miq_environment_spec.rb
  spec/models/miq_server/environment_manager_spec.rb
  tools/show_host_file_entries_for_vnc.rb
Labels: refactoring

#20340 [HAMMER] Lock manageiq-messaging to 0.1.2
  Gemfile
Labels: dependencies

#20338 Add the VMware NSX-t Provider plugin to Gemfile
  Gemfile
  spec/models/ext_management_system_spec.rb
Labels: dependencies, enhancement, providers/network

#20347 Remove unused Host#rediscover method
  app/models/host.rb
Labels: cleanup

#20319 add a request template subclass post-create in miq_request_workflow
  app/models/miq_provision_request_template.rb
  spec/models/miq_provision_request_template_spec.rb
Labels: bug, jansa/yes?

#20348 Use Host#uid_ems to link host records to ems_events
  app/models/ems_event.rb
  spec/models/ems_event_spec.rb
Labels: core/events, enhancement, providers

#20351 Add assigment_type_description to ChargebackRate#assigned_to
  app/models/chargeback_rate.rb
  spec/models/chargeback_rate_spec.rb
Labels: enhancement

#20316 bump more core extensions
  Gemfile
Labels: dependencies

#20353 [JANSA] Updated Translation Files from 2020-07-11
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: bug, internationalization

#20352 Allow the user to specify the provider type to create when using the provider generator
  lib/generators/manageiq/provider/USAGE
  lib/generators/manageiq/provider/provider_generator.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/event_catcher.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/event_catcher/runner.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/event_catcher/stream.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/metrics_capture.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/metrics_collector_worker.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/metrics_collector_worker/runner.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/refresh_worker.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/refresh_worker/runner.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/refresher.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%/vm.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/cloud_manager/event_catcher.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/cloud_manager/metrics_collector_worker/runner.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/cloud_manager/refresh_worker.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/cloud_manager/refresh_worker/runner.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/cloud_manager/refresher.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/collector.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/collector/%manager_path%.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/parser/%manager_path%.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/persister.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/persister/%manager_path%.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/parser.rb
Labels: enhancement, pluggability/providers

#20356 Add '::EmsStorage' alias
  app/models/aliases/ems_storage.rb
Labels: enhancement, providers/storage

#20238 [V2V] Allow OpenStack public networks in transformation mappings
  app/models/transformation_mapping_item.rb
  spec/models/transformation_mapping_item_spec.rb
Labels: bug, ivanchuk/yes, v2v

#20361 Ensure remaining models are translated but not through rails' titleize
  app/models/miq_compare.rb
  spec/models/miq_compare_spec.rb
Labels: bug, internationalization, jansa/yes?

#20359 Prefer Array.wrap over Object#to_miq_a
  app/models/compliance.rb
  app/models/dialog_field_radio_button.rb
  app/models/dialog_field_sorted_item.rb
  app/models/manageiq/providers/base_manager/event_catcher/runner.rb
  app/models/metric/rollup.rb
  app/models/miq_compare.rb
  app/models/miq_provision_virt_workflow.rb
  app/models/miq_request.rb
  app/models/miq_request_workflow.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_server/worker_management/dequeue.rb
  app/models/mixins/assignment_mixin.rb
  app/models/mixins/async_delete_mixin.rb
  app/models/mixins/authentication_mixin.rb
  app/models/mixins/miq_request_mixin.rb
  app/models/mixins/scanning_mixin.rb
  app/models/storage.rb
  app/models/vim_performance_analysis.rb
  app/models/vm_reconfigure_request.rb
  lib/extensions/ar_to_model_hash.rb
  lib/miq_ldap.rb
  tools/ldap_ping.rb
Labels: technical debt

#20358 PERF_ROLLUP_CHILDREN should be an Array, fix and remove calls to #to_miq_a
  app/models/availability_zone.rb
  app/models/container.rb
  app/models/container_group.rb
  app/models/container_node.rb
  app/models/container_project.rb
  app/models/container_replicator.rb
  app/models/container_service.rb
  app/models/ems_cluster.rb
  app/models/ext_management_system.rb
  app/models/host.rb
  app/models/host_aggregate.rb
  app/models/metric/rollup.rb
  app/models/service.rb
  app/models/storage.rb
  app/models/vm_or_template.rb
Labels: technical debt

#20364 Update import_export.rb
  app/models/generic_object_definition/import_export.rb
Labels: cleanup

#20363 Split extra vars for Ansible playbooks
  app/models/conversion_host.rb
Labels: blocker, bug, jansa/yes?, v2v

#20369 Remove seed limit from seeding specs
  spec/models/miq_database_spec.rb
  spec/models/miq_dialog/seeding_spec.rb
  spec/models/miq_enterprise_spec.rb
  spec/models/miq_region_spec.rb
  spec/models/miq_report/seeding_spec.rb
  spec/models/miq_server_spec.rb
  spec/models/miq_widget_spec.rb
  spec/models/scan_item/seeding_spec.rb
  spec/models/tenant_spec.rb
  spec/models/user_spec.rb
  spec/support/examples_group/shared_examples_for_seeding.rb
Labels: cleanup, test

#20362 Fix missing Inventory::* classes in plugin generator
  lib/generators/manageiq/provider/provider_generator.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/collector.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/collector/%manager_path%.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/parser.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/parser/%manager_path%.rb
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/inventory/persister.rb
  lib/generators/manageiq/provider/templates/config/settings.yml
Labels: bug, pluggability/providers

#20373 Fix the evm_application_spec for updated tabelize
  spec/lib/tasks/evm_application_spec.rb
Labels: bug, core, test

#20368 Don't display report results without group
  app/models/miq_report_result.rb
  spec/models/miq_report_result_spec.rb
Labels: bug, jansa/yes?

#20376 Add Sprint review 141
  CHANGELOG.md
Labels: documentation

#20374 Use OpenStruct over MiqHashStruct
  app/models/miq_provision_virt_workflow.rb
  app/models/miq_request_workflow.rb
  spec/models/manageiq/providers/cloud_manager/provision_workflow_spec.rb
  spec/models/miq_provision_virt_workflow_spec.rb
  spec/models/miq_request_workflow_spec.rb
Labels: performance

#20380 Add IBM vendor type
  app/models/vm_or_template.rb
Labels: enhancement, providers

#20384 The tower provider was moved to the base factory
  spec/models/service_template_ansible_tower_spec.rb
Labels: bug, providers/automation, test

#20383 Bump the memory limits for metrics and queue workers
  config/settings.yml
Labels: appliance/workers, bug, jansa/yes?

#20385 Update evm_application_spec.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: cleanup

#20379 Clean up remaining #to_miq_a callers that are covered by tests
  app/models/miq_alert.rb
  app/models/miq_report/generator/aggregation.rb
  app/models/miq_report/generator/sorting.rb
  app/models/miq_request_task/dumping.rb
  app/models/mixins/relationship_mixin.rb
  lib/miq_expression.rb
Labels: technical debt

#20388 Fix template directory due to RPM build changes
  tools/miq_config_sssd_ldap/auth_template_files.rb
Labels: bug, jansa/yes

#20386 Use db query limit gem for custom query matchers
  Gemfile
  spec/lib/extensions/ar_number_of_spec.rb
  spec/lib/extensions/ar_region_spec.rb
  spec/lib/miq_preloader_spec.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/container_group_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
  spec/models/miq_product_feature_spec.rb
  spec/models/miq_provision_virt_workflow_spec.rb
  spec/models/mixins/authentication_mixin_spec.rb
  spec/models/mixins/compliance_mixin_spec.rb
  spec/models/mixins/drift_state_mixin_spec.rb
  spec/models/mixins/relationship_mixin_spec.rb
  spec/models/notification_spec.rb
  spec/models/vm_or_template_spec.rb
  spec/support/custom_matchers/exceed_query_limit.rb
  spec/support/custom_matchers/match_query_limit_of.rb
  spec/support/examples_group/shared_examples_for_aggregation_mixin.rb
Labels: dependencies

#20393 The cloud_volumes inv collection was missing
  app/models/manageiq/providers/inventory/persister/builder/storage_manager.rb
Labels: enhancement, providers/inventory, providers/storage

#20395 Allow providers to override provider_module
  app/models/manageiq/providers/inventory/persister.rb
  app/models/manageiq/providers/inventory/persister/builder.rb
Labels: enhancement, providers/inventory

#20399 Add APP_PATH to allow using Rails directly in plugin generator
  lib/generators/manageiq/plugin/templates/bin/rails
Labels: developer, enhancement, pluggability

#20402 Update CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#20396 Rename the key_pairs collection to match model name
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  spec/models/manageiq/providers/inventory/persister/local_db_finders_spec.rb
  spec/models/manageiq/providers/inventory/persister/serializing_spec.rb
  spec/models/manageiq/providers/inventory/persister/test_persister.rb
Labels: providers/inventory, refactoring
