Repository ManageIQ/manageiq, pull requests merged in 2020-10, with the labels that each got.

#20616 Enable adding storage managers
  app/models/manageiq/providers/storage_manager.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/storage

#20605 Enable PhysicalStorage creation and editing
  app/models/physical_storage.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/storage

#20634 Added Missing Button Groups from model in en.yml
  locale/en.yml
Labels: bug, internationalization

#20638 Fixed broken links for provider documentation and added missing link for the Storage Manager
  config/settings.yml
Labels: bug, documentation

#20644 Add missing model display names
  app/models/cloud_object_store_container.rb
  app/models/container_volume.rb
  app/models/network_service.rb
  app/models/security_policy.rb
  app/models/security_policy_rule.rb
Labels: enhancement, pluggability

#20345 Delegate queue_name for refresh to parent manager instead of queue_name arrays
  app/models/ems_refresh.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/base_manager/refresh_worker.rb
  app/models/manageiq/providers/network_manager.rb
  app/models/manageiq/providers/storage_manager.rb
  app/models/miq_queue.rb
  app/models/miq_worker.rb
  app/models/mixins/per_ems_worker_mixin.rb
Labels: bug, core/queue, providers

#20643 use uniqueness_when_changed validation for miq ae class
  app/models/miq_ae_class.rb
  spec/models/miq_ae_class_spec.rb
Labels: performance

#20637 use uniqueness_when_changed validator for miq ae instance
  app/models/miq_ae_instance.rb
  spec/models/miq_ae_instance_spec.rb
Labels: performance

#20626 use uniqueness when changed for miq ae method
  app/models/miq_ae_method.rb
  spec/models/miq_ae_method_spec.rb
Labels: performance

#20632 Filtered the auth key in api.log
  config/application.rb
Labels: bug

#20641 add schemaless option to rspec config to not match schema queries
  spec/support/db_query_matchers.rb
Labels: test

#20648 use uniqueness when changed for service template transformation plan
  app/models/service_template_transformation_plan.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: performance

#20650 use uniqueness_when_changed for miq ae namespace
  app/models/miq_ae_namespace.rb
  spec/models/miq_ae_namespace_spec.rb
Labels: performance

#20649 use uniqueness_when_changed validation for service template catalog
  app/models/service_template_catalog.rb
  spec/models/service_template_catalog_spec.rb
Labels: performance

#20651 use unique when changed validation for service order
  app/models/service_order.rb
  spec/models/service_order_spec.rb
Labels: performance

#20635 Initialize Authentication record with correct class from create_from_params
  app/models/authentication.rb
  app/models/mixins/authentication_mixin.rb
  spec/models/ext_management_system_spec.rb
Labels: bug, providers

#20646 Add RBAC for Configuration Profile console
  db/fixtures/miq_product_features.yml
Labels: enhancement

#20630 Remove PasswordMixin in favor of the one in manageiq-password
  app/models/authentication.rb
  app/models/miq_database.rb
  app/models/mixins/password_mixin.rb
  config/application.rb
  spec/models/auth_userid_password_spec.rb
  spec/models/authentication_spec.rb
  spec/models/miq_database_spec.rb
Labels: technical debt

#20653 manageiq-smartstate gem version 0.6.1
  Gemfile
Labels: dependencies

#20657 fix service_order_spec typo
  spec/models/service_order_spec.rb
Labels: cleanup, test

#20656 [IVANCHUK] Bump manageiq-smartstate gem to 0.3.10
  Gemfile
Labels: dependencies

#20647 Drop support for v0/v1 keys
  lib/tasks/evm_dba.rake
  spec/tools/fix_auth/auth_config_model_spec.rb
  spec/tools/fix_auth/auth_model_spec.rb
  tools/fix_auth/fix_auth.rb
Labels: technical debt

#20623 remove ntp from core
  app/models/miq_server.rb
  app/models/miq_server/configuration_management.rb
  app/models/miq_server/ntp_management.rb
  app/models/miq_server/queue_management.rb
  app/models/zone.rb
  config/settings.yml
  lib/workers/evm_server.rb
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  spec/models/miq_server/queue_management_spec.rb
  spec/models/miq_server_spec.rb
  spec/models/zone_spec.rb
  tools/configure_server_settings.rb
Labels: appliance, cleanup

#20654 Fix Authentication.new with non-hash arguments
  app/models/authentication.rb
Labels: bug

#20629 Integrate with autosde-provider
  Gemfile
  spec/factories/ext_management_system.rb
Labels: dependencies, enhancement

#20655 [JANSA] Bump manageiq-smartstate gem to 0.5.10 for Jansa
  Gemfile
Labels: dependencies

#20588 Hosts should be disconnected rather than deleted
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: bug, providers/inventory

#20640 [IVANCHUK] Native console support for ivanchuk
  app/models/mixins/supports_feature_mixin.rb
  app/models/vm.rb
  app/models/vm/operations.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
  spec/models/vm/operations_spec.rb
  spec/models/vm_spec.rb
Labels: enhancement

#20663 Memcache client
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_worker/runner.rb
  lib/manageiq/session/mem_cache_store_adapter.rb
  lib/miq_memcached.rb
  lib/token_store.rb
Labels: core/security, refactoring

#20547 Fix translations for utilization chart headers
  config/locale_task_config.yaml
Labels: bug, internationalization

#20666 Use inotify to wait for ansible-runner pid file creation
  Gemfile
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: bug, core/embedded ansible, dependencies

#20668 use uniqueness when changed for ems name
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: performance

#20670 [JANSA][Ansible::Runner] wait on artifacts/ to exist
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: bug, jansa/yes

#20407 Handle system errors in workers
  app/models/miq_worker/runner.rb
  lib/workers/bin/run_single_worker.rb
Labels: bug

#20636 Add MiqProvisionOrchWorkflow for content library template.
  app/models/miq_provision_orch_workflow.rb
  spec/factories/miq_request_workflow.rb
  spec/models/miq_provision_orch_workflow_spec.rb
Labels: changelog/yes, enhancement, jansa/no

#20675 Filter 'apikey' in ProviderSdkLogger
  lib/vmdb/loggers/provider_sdk_logger.rb
Labels: bug, providers

#20633 Add revoke_session to miq_product_features.yml
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
Labels: enhancement

#20671 use unique when changed for conversion host addresses
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: performance

#20601 Add User.revoke_sessions
  app/models/user.rb
  lib/token_manager.rb
  lib/token_store.rb
  lib/token_store/sql_store.rb
Labels: enhancement

#20674 Update the Ansible::Runner wait_for timeout
  lib/ansible/runner.rb
Labels: bug, core/embedded ansible

#20678 use unique within region validator for classification
  app/models/classification.rb
  spec/models/classification_spec.rb
Labels: bug

#20681 remove unused location uniqueness validation from storage
  app/models/storage.rb
Labels: cleanup

#20661 Add a memory and cpu limits on deployments
  app/models/miq_worker/container_common.rb
  config/settings.yml
  spec/models/miq_worker/container_common_spec.rb
Labels: enhancement

#20684 Add orchestration stack reference to configured system
  app/models/configured_system.rb
Labels: enhancement, providers/configuration

#20688 Add Sprint review 147
  CHANGELOG.md
Labels: documentation

#20686 Add RBAC for Configured System console access
  db/fixtures/miq_product_features.yml
Labels: enhancement

#20690 remove unneeded travis yaml lines
  .travis.yml
Labels: cleanup, developer

#20696 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#20694 Delete duplicate reconnect blocks from persister
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: cleanup, providers/inventory

#20693 Add ui_dependencies back to base worker to avoid load errors
  app/models/miq_worker.rb
Labels: bug

#20695 Gracefully handle pod monitor exceptions
  app/models/miq_server/worker_management/monitor/kubernetes.rb
Labels: bug, core/pods

#20698 Added volume_availability_zones and cloud_tenants to storage_manager
  app/models/manageiq/providers/storage_manager.rb
Labels: enhancement, providers/storage

#20702 remove the default distro setting
  .travis.yml
Labels: cleanup

#20709 Remove the VMware specific assign_ems_created_on method
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: refactoring

#20692 Display revoke_user_sessions permission for roles
  db/fixtures/miq_product_features.yml
Labels: enhancement

#20706 fix sporadic nested tag entries order failure
  spec/lib/task_helpers/exports/tags_spec.rb
Labels: bug/sporadic test failure

#20714 Add ibm and vmware to Tag Mapper tag_prefixes
  app/models/provider_tag_mapping.rb
Labels: enhancement

#20716 remove miq_array require
  lib/miq_apache/control.rb
Labels: bug

#20715 bump smartstate version
  Gemfile
Labels: dependencies

#20442 address discrepancies between array wrap and miq to_a
  app/models/miq_provision_virt_workflow.rb
  app/models/miq_report_result.rb
  app/models/miq_request_workflow/dialog_field_validation.rb
  app/models/mixins/miq_provision_mixin.rb
  app/models/relationship.rb
  lib/workers/evm_server.rb
Labels: bug

#20717 Added path to delegates of default_endpoint in ext_management_system
  app/models/ext_management_system.rb
Labels: enhancement, providers

#20718 Update i18n message catalog
  locale/manageiq.pot
Labels: internationalization

#20712 Remove the EmsRefresh find_host reconnect logic
  app/models/ems_refresh/save_inventory_infra.rb
  spec/models/ems_refresh/save_inventory_infra_spec.rb
Labels: cleanup, providers/virtual

#20720 update memoist for googleauth version min for faraday update
  Gemfile
Labels: dependencies

#20185 Use manageiq-style for both rubocop dependency and config
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  Gemfile
  lib/generators/manageiq/plugin/templates/%plugin_name%.gemspec
  lib/generators/manageiq/plugin/templates/.codeclimate.yml
  lib/generators/manageiq/plugin/templates/.rubocop.yml
  lib/generators/manageiq/plugin/templates/.rubocop_cc.yml
Labels: dependencies, developer

#20701 drop migration from models
  app/models/mixins/cinder_manager_mixin.rb
  app/models/mixins/swift_manager_mixin.rb
Labels: cleanup, providers/storage

#20723 configure db query matchers for all repos
  spec/shared/support/db_query_matchers.rb
Labels: bug/sporadic test failure, test

#20725 Add cloud_tenants supported feature into the supports mixin
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, providers/cloud

#20724 Load environment for store_dictionary_strings rake task
  lib/tasks/locale.rake
Labels: bug, internationalization

#20699 Marked Strings for Translation in Reports
  locale/en.yml
Labels: bug, internationalization

#20728 Make sure that all model -> name mappings are in singular
  locale/en.yml
Labels: bug

#20734 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#20736 rename most of remaining factorygirl to factorybot
  spec/factories/tenant.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/manageiq/providers/ansible_playbook_workflow_spec.rb
  spec/models/manageiq/providers/ansible_role_workflow_spec.rb
  spec/models/manageiq/providers/base_manager_spec.rb
  spec/models/manageiq/providers/cloud_manager/vm_or_template_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
  spec/models/miq_product_feature_spec.rb
  spec/models/miq_report/import_export_spec.rb
Labels: test

#20713 Implementing remove physical storage
  app/models/physical_storage.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/storage

#20737 remove more factory girl references
  spec/models/ext_management_system_spec.rb
  spec/models/tenant_spec.rb
Labels: test

#20568 Rewrote Ansible Credential Types using DDF
  app/models/manageiq/providers/embedded_ansible/automation_manager/amazon_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/azure_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/google_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/network_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/openstack_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/rhv_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/scm_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/vault_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/vmware_credential.rb
Labels: core/embedded ansible, refactoring

#20722 [rails6][Gemfile] Upgrade hamlit
  Gemfile
Labels: dependencies, kasparov/no, rails6

#20740 one more factorygirl replacement
  spec/support/factory_bot_helper.rb
Labels: test

#20742 remove last factory girl reference and alias
  spec/support/factory_bot_helper.rb
Labels: technical debt

#20747 Expose supports_create_flavor as an API-queryable virtual_column
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement

#20749 Update deprecation warnings for things that can be removed in M-release
  lib/vmdb/deprecation.rb
Labels: core, developer

#20750 Remove unused deprecated method
  app/models/mixins/per_ems_worker_mixin.rb
Labels: technical debt

#20608 bump virtual attributes to 3.0
  Gemfile
  spec/models/hardware_spec.rb
Labels: dependencies, enhancement

#20730 Add initial log line for run_single_worker
  lib/workers/bin/run_single_worker.rb
Labels: developer, enhancement

#20731 Add check for invalid roles in server_role_names=
  app/models/miq_server/role_management.rb
  spec/models/miq_alert_spec.rb
  spec/models/miq_server/configuration_management_spec.rb
  spec/models/miq_server/role_management_spec.rb
Labels: bug

#20733 Remove ServerRole.to_role
  app/models/miq_server/role_management.rb
  app/models/server_role.rb
  spec/models/miq_server/role_management_spec.rb
  spec/models/miq_server/server_monitor_spec.rb
  spec/models/vm_spec.rb
  spec/models/zone_spec.rb
  spec/support/evm_spec_helper.rb
Labels: technical debt

#20697 Use standard version of rugged
  Gemfile
  lib/git_worktree.rb
Labels: dependencies, jansa/no, kasparov/no, technical debt

#20758 Add a refresh_interval to provider generator
  lib/generators/manageiq/provider/templates/config/settings.yml
Labels: developer, providers
