Repository ManageIQ/manageiq, pull requests merged in 2020-02, with the labels that each got.

#19792 Remove the remaining methods about sending non-queue messages over drb
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_worker.rb
  spec/models/miq_server/worker_monitor_spec.rb
Labels: core, technical debt

#19796 Update MiqProvisionVirtWorkflow specs
  spec/factories/miq_request_workflow.rb
  spec/models/miq_provision_virt_workflow_spec.rb
Labels: refactoring, test

#19800 Define singleton method on MiqServer before attempting to stub it
  spec/models/miq_queue_spec.rb
Labels: refactoring, test

#19759 Allow unsetting previously set warm migration cutover datetime
  app/models/service_template_transformation_plan.rb
Labels: enhancement, v2v

#19799 Add nice display name for Amazon's EBS Manager
  locale/en.yml
Labels: bug, ivanchuk/yes, providers/cloud

#19801 Use .tabular_sort instead of .stable_sort_by
  app/models/miq_report_result/result_set_operations.rb
  lib/patches/ruport_patch.rb
Labels: technical debt

#19806 Fix the RegistrationSystem spec
  spec/models/registration_system_spec.rb
Labels: bug, test

#19807 Add Sprint review 129
  CHANGELOG.md
Labels: documentation

#19791 Add a connection timeout for remote region connections
  app/models/miq_region_remote.rb
  app/models/pglogical_subscription.rb
Labels: bug, core/replication, hammer/yes, ivanchuk/yes

#19808 Fix sporadic timing issue with spec
  spec/models/miq_server/log_management_spec.rb
Labels: bug/sporadic test failure

#19805 Add a method to resize a VM's disk
  app/models/vm_or_template/operations/configuration.rb
Labels: enhancement, providers

#19803 Kill workers before destroying child managers when destroying an EMS
  app/models/ext_management_system.rb
Labels: bug, providers

#19780 Fixing issues with field properties from tower templates
  app/models/dialog/ansible_tower_job_template_dialog_service.rb
  spec/models/dialog/ansible_tower_job_template_dialog_service_spec.rb
Labels: bug

#19811 [HAMMER] Fix embedded_ansible appliance spec
  spec/lib/embedded_ansible/appliance_embedded_ansible_spec.rb
Labels: bug, core/embedded_ansible, test

#19814 Fix the container common spec to use Ovirt Infra MetricsCaptureWorker
  spec/models/miq_worker/container_common_spec.rb
Labels: bug, test

#19789 Use the server's zone to determine a node selector when running in pods
  app/models/miq_server.rb
  app/models/miq_worker/container_common.rb
  app/models/zone.rb
  spec/models/miq_server_spec.rb
  spec/models/miq_worker/container_common_spec.rb
  spec/models/zone_spec.rb
Labels: core, enhancement

#19754 Remove storage references to multiple emses
  app/models/storage.rb
  spec/models/ems_refresh_spec.rb
  spec/models/storage_spec.rb
Labels: bug, core/storage, ivanchuk/no, providers

#19810 Force coveralls 0.8
  Gemfile
Labels: dependencies

#19817 [V2V] Fix InfraConversionThrottler.running_conversion_jobs
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19821 [HAMMER] Fix VM Retirement Error Message
  app/models/vm_or_template.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, changelog/yes, lifecycle/retirement

#19815 Add queue_name_for_ems_operations delegates for Automate
  app/models/cloud_volume.rb
  app/models/ems_cluster.rb
  app/models/ems_folder.rb
Labels: changelog/yes, enhancement, ivanchuk/no, providers

#19816 Fix smartproxy worker heartbeat thread
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_smart_proxy_worker/runner.rb
  spec/models/miq_smart_proxy_worker/runner_spec.rb
Labels: bug, core, core/smart state

#19798 Extend object to define exist? method in database configuration specs
  spec/lib/extensions/database_configuration_spec.rb
Labels: refactoring, test

#19804 Fixup polymorphic issues with MiqReport + Rbac
  app/models/miq_report/generator.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/miq_report/generator_spec.rb
  spec/models/miq_report_spec.rb
Labels: bug, core/rbac, core/reporting

#19822 [HAMMER] Lock gettext to < 3.3
  Gemfile
Labels: dependencies

#19825 Remove the deprecation warning on validate_credentials_task
  app/models/mixins/verify_credentials_mixin.rb
Labels: providers, technical debt

#19823 remaining pieces of skip_references
  app/models/miq_report.rb
  app/models/miq_report/search.rb
Labels: core/rbac, technical debt

#19833 VimHash and VimArray are VMware specific and shouldn't be in core specs
  spec/models/miq_request_task/dumping_spec.rb
Labels: cleanup, providers, test

#19832 Don't send VMware specific types from Core
  app/models/vm_migrate_task.rb
Labels: providers, providers/pluggability, technical debt

#19834 Remove the vmware_web_service gem from the core Gemfile
  Gemfile
  app/models/miq_event_handler/runner.rb
Labels: cleanup, dependencies, providers

#19830 Schedule a daily count of managed VMs and print result to audit log.
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_server.rb
  config/settings.yml
Labels: enhancement

#19835 Use a single query to get count of active VMs and Hosts
  app/models/host.rb
  app/models/miq_server.rb
  spec/models/miq_server_spec.rb
Labels: core, enhancement, performance

#19839 Add a comment to the snapshot factory
  spec/factories/snapshot.rb
Labels: refactoring, test

#19829 Only register queue workers using drb for dequeue
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_server/worker_management/dequeue.rb
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_worker/runner.rb
  spec/models/miq_queue_worker_base/runner_spec.rb
Labels: bug, core

#19841 Add Sprint review 130
  CHANGELOG.md
Labels: documentation

#19844 The foreman plugin now uses the released gem, drop dependency declaration
  Gemfile
Labels: dependencies, technical debt

#19846 Use built-in file over kube downward API for namespace
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
Labels: core, technical debt

#19847 Productize pods without product name
  lib/container_orchestrator/object_definition.rb
Labels: core, enhancement

#19850 Add zone delegation to ems_folder
  app/models/ems_folder.rb
Labels: bug, providers

#19856 Add the provided image pull secret to deployed worker containers
  lib/container_orchestrator/object_definition.rb
Labels: core, enhancement

#19859 Delay load kubeclient and it's exception.
  app/models/miq_worker/container_common.rb
  lib/container_orchestrator.rb
Labels: appliance/workers, performance

#19698 [V2V] Use podman with UCI image instead of virt-v2v-wrapper directly
  app/models/conversion_host.rb
  app/models/service_template_transformation_plan_task.rb
  config/settings.yml
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
  spec/models/conversion_host_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19861 Add associations for networks and nics on Vms
  app/models/vm_or_template.rb
Labels: enhancement, ivanchuk/yes, providers

#19820 [IVANCHUK] Fix VM Retirement Error Message
  app/models/vm_or_template.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, changelog/yes, lifecycle/retirement

#19852 Turn off gpg signing in git command
  spec/lib/vmdb/plugins_spec.rb
Labels: refactoring, test

#19849 Change disk options in oVirts provisioning dialog
  product/dialogs/miq_dialogs/miq_provision_redhat_dialogs_clone_to_vm.yaml
  product/dialogs/miq_dialogs/miq_provision_redhat_dialogs_template.yaml
Labels: enhancement, providers/provisioning

#19864 Split extra vars for Ansible playbooks
  app/models/conversion_host.rb
Labels: blocker, bug, ivanchuk/yes, v2v

#19854 Add a find interface method to ActsAsArModel
  lib/acts_as_ar_model.rb
Labels: refactoring

#19838 metrics: simplify dates on queue
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/ci_mixin/capture.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
Labels: enhancement, providers/metrics

#19857 Refactor log_under_management and audit_managed_resources
  app/models/miq_server.rb
  app/models/miq_server/at_startup.rb
  app/models/vm_or_template.rb
  spec/models/miq_server/at_startup_spec.rb
  spec/models/miq_server_spec.rb
Labels: core, refactoring

#19868 Fix perf_capture_realtime without a start_time
  app/models/metric/ci_mixin/capture.rb
Labels: bug

#19870 Set the default signal to 'TERM' in ConversionHost#kill_virtv2v
  app/models/conversion_host.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, hammer/no, ivanchuk/yes, v2v

#19871 Fix misspelled CODEOWNERS file, oops
  .github/CODEOWNERS
Labels: developer

#19851 Replace Bundler.environment with Bundler.load.
  lib/terminal_to_html.rb
  lib/vmdb/plugins.rb
  spec/lib/vmdb/plugins_spec.rb
Labels: build, refactoring, test

#19855 Call instance method for vm retire queuing
  app/models/vm_or_template.rb
Labels: bug, ivanchuk/yes

#19874 Make systemd the default for worker management
  config/settings.yml
Labels: appliance/workers, enhancement

#19875 Add an `InfraManager#host_virtual_lans` collection
  app/models/host.rb
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: enhancement, providers/inventory

#19873 Move report formatter and charting to core
  .github/CODEOWNERS
  app/models/miq_report/formatters/graph.rb
  app/models/miq_widget/chart_content.rb
  lib/charting.rb
  lib/manageiq/reporting/charting.rb
  lib/manageiq/reporting/charting/c3_charting.rb
  lib/manageiq/reporting/formatter.rb
  lib/manageiq/reporting/formatter/c3.rb
  lib/manageiq/reporting/formatter/c3_helper.rb
  lib/manageiq/reporting/formatter/c3_series.rb
  lib/manageiq/reporting/formatter/chart_common.rb
  lib/manageiq/reporting/formatter/converter.rb
  lib/manageiq/reporting/formatter/html.rb
  lib/manageiq/reporting/formatter/report_renderer.rb
  lib/manageiq/reporting/formatter/text.rb
  lib/manageiq/reporting/formatter/timeline.rb
  lib/manageiq/reporting/formatter/timeline_message.rb
  lib/report_formatter.rb
  spec/lib/manageiq/reporting/formatter/c3_spec.rb
  spec/lib/manageiq/reporting/formatter/chart_common_spec.rb
  spec/lib/manageiq/reporting/formatter/text_spec.rb
  spec/lib/manageiq/reporting/formatter/timeline_message_spec.rb
  spec/lib/manageiq/reporting/formatter/timeline_spec.rb
  spec/models/miq_report/charting_spec.rb
  spec/models/miq_report_result_spec.rb
  spec/models/miq_widget/chart_content_spec.rb
  spec/support/report_helper.rb
Labels: bug, core/reporting, refactoring

#19881 Drop support_website* keys from i18n yamls
  locale/en.yml
  locale/es.yml
  locale/fr.yml
  locale/ja.yml
  locale/pt_BR.yml
  locale/zh_CN.yml
Labels: refactoring

#19880 [V2V] Use two-phase migration only for warm migration
  app/models/service_template_transformation_plan_task.rb
Labels: bug, ivanchuk/yes, v2v

#19885 [control_spec.rb] Fix MiqUtil.runcmd expectations
  spec/lib/miq_apache/control_spec.rb
Labels: test

#19887 MiqRegion#migrations_ran column is no longer necessary
  app/models/miq_region.rb
  spec/models/miq_region_spec.rb
Labels: core/replication, technical debt

#19860 Delay load manageiq-api-client until needed
  app/models/mixins/inter_region_api_method_relay.rb
  app/models/mixins/process_tasks_mixin.rb
  spec/models/mixins/inter_region_api_method_relay_spec.rb
  spec/models/mixins/process_tasks_mixin_spec.rb
Labels: core, enhancement

#19884 Move DialogFieldVisibilityService and friends back to core
  lib/services/auto_placement_visibility_service.rb
  lib/services/customize_fields_visibility_service.rb
  lib/services/dialog_field_visibility_service.rb
  lib/services/linked_clone_visibility_service.rb
  lib/services/network_visibility_service.rb
  lib/services/number_of_vms_visibility_service.rb
  lib/services/pxe_iso_visibility_service.rb
  lib/services/request_type_visibility_service.rb
  lib/services/retirement_visibility_service.rb
  lib/services/service_template_fields_visibility_service.rb
  lib/services/sysprep_auto_logon_visibility_service.rb
  lib/services/sysprep_custom_spec_visibility_service.rb
  spec/lib/services/auto_placement_visibility_service_spec.rb
  spec/lib/services/customize_fields_visibility_service_spec.rb
  spec/lib/services/dialog_field_visibility_service_spec.rb
  spec/lib/services/linked_clone_visibility_service_spec.rb
  spec/lib/services/network_visibility_service_spec.rb
  spec/lib/services/number_of_vms_visibility_service_spec.rb
  spec/lib/services/pxe_iso_visibility_service_spec.rb
  spec/lib/services/request_type_visibility_service_spec.rb
  spec/lib/services/retirement_visibility_service_spec.rb
  spec/lib/services/service_template_fields_visibility_service_spec.rb
  spec/lib/services/sysprep_auto_logon_visibility_service_spec.rb
  spec/lib/services/sysprep_custom_spec_visibility_service_spec.rb
Labels: providers/provisioning, refactoring

#19891 [V2V] Fix UCI name building method
  app/models/conversion_host.rb
Labels: bug, ivanchuk/yes, v2v

#19892 The api calls exec_api_call directly from Api::Mixins::CentralAdmin
  app/models/mixins/inter_region_api_method_relay.rb
Labels: api, bug

#19883 [IVANCHUK] Ivanchuk-3 Updates
  CHANGELOG.md
Labels: documentation

#19893 Bump version of rake to >=12.3.3 for CVE-2020-8130
  Gemfile
Labels: bug, core/security, dependencies

#19889 [GitWorktree] Add instructions for ssh support
  lib/git_worktree.rb
Labels: documentation

#19890 [V2V] Filter out jobs.migration_task.conversion_host.nil? in InfraConversionThrottler.running_conversions
  app/models/infra_conversion_job.rb
  lib/infra_conversion_throttler.rb
  spec/lib/infra_conversion_throttler_spec.rb
Labels: bug, ivanchuk/yes, v2v
