Repository ManageIQ/manageiq, pull requests merged in 2020-03, with the labels that each got.

#19908 [V2V] Allow job to continue if kill_virtv2v raises an execption
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/infra_conversion_job_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19882 [V2V] Add VMware host credentials check to migration preflight check
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19909 Add display name for OpenStack Cinder Manager
  locale/en.yml
Labels: bug, ivanchuk/yes

#19912 Replace yum commands with dnf in the Dockerfile
  Dockerfile
Labels: core, enhancement, jansa/yes?

#18218 An EMS requires a zone, so I'm adding a validation for it
  app/models/ext_management_system.rb
  app/models/manageiq/providers/embedded_ansible/seeding.rb
  spec/factories/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: enhancement, gaprindashvili/no, hammer/no, providers

#19914 Add CloudTenant relationship in VM class
  app/models/manageiq/providers/cloud_manager/vm.rb
  app/models/vm_or_template.rb
Labels: bug, ivanchuk/yes, providers

#19911 [V2V] Preflight check: verify if a VM with same name already exists in destination
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19920 Make monolithic image work when built with buildah
  Dockerfile
Labels: bug, core

#19922 Update master codename
  lib/vmdb/appliance.rb
Labels: build

#19923 Remove no-longer used line from forever ago
  tools/classify_vms_by_folder
Labels: technical debt

#19918 Remove the odd policy migrate thing
  tools/migrate_policies
Labels: technical debt

#19924 Add permissions for ConfigurationProfiles
  db/fixtures/miq_product_features.yml
Labels: core/rbac, enhancement

#19921 Add Sprint review 131
  CHANGELOG.md
Labels: documentation

#19926 Move spec for radar mixin to spec folder
  spec/tools/radar/rollup_radar_mixin_spec.rb
Labels: cleanup

#19919 [IVANCHUK] Fix ivanchuk container image
  Dockerfile
  docker-assets/appliance-initialize.sh
Labels: bug, core

#19927 Configuration of conversion host without IP should fail early
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19928 Add API ConfiguredSystems product features
  db/fixtures/miq_product_features.yml
Labels: core/rbac, enhancement

#19917 Add missing script interpreters
  tools/ci/after_failure.sh
  tools/ci/before_install.sh
  tools/ci/setup_ruby_env.sh
  tools/ci/setup_vmdb_configs.sh
Labels: bug, ivanchuk/yes

#19933 Added /usr/java/latest/release
  product/scan_items/scan_item_file.yaml
Labels: enhancement, ivanchuk/yes

#19931 Add Configuration/Provisioning Persisters
  app/models/manageiq/providers/inventory/persister/builder/configuration_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/persister_helper.rb
  app/models/manageiq/providers/inventory/persister/builder/provisioning_manager.rb
Labels: enhancement, providers/configuration, providers/provisioning

#19795 Create ServiceOrder sub-classes
  app/models/service_order.rb
  app/models/service_order_cart.rb
  app/models/service_order_v2v.rb
  app/models/service_template_provision_request.rb
  app/models/service_template_transformation_plan_request.rb
  spec/factories/service_order.rb
  spec/models/service_order_spec.rb
  spec/models/service_template_provision_request_spec.rb
  spec/models/service_template_transformation_plan_request_spec.rb
Labels: enhancement, ivanchuk/no, lifecycle/services

#19937 Since the base class is no longer valid, create records of a subclass
  spec/factories/service_order.rb
Labels: ivanchuk/no, jansa/yes?, lifecycle/services

#19916 Added new section in product features to handle common UI features
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
Labels: core/rbac, enhancement

#19941 Remove invalid partials from presenter helper
  spec/support/presenter_helper.rb
Labels: refactoring, test

#19944 Reference ServiceOrder subclasses as root classes
  app/models/service_template_provision_request.rb
  app/models/service_template_transformation_plan_request.rb
Labels: bug, ivanchuk/no, jansa/yes?, lifecycle/services

#19934 metrics capture target
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/capture.rb
  app/models/metric/ci_mixin/capture.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
Labels: enhancement, providers/metrics

#19946 Add more provisioning manager Inventory Collections
  app/models/manageiq/providers/inventory/persister/builder/provisioning_manager.rb
Labels: enhancement, providers/inventory, providers/provisioning

#19947 Embedded ansible provider should allow creation in maintenance zone
  app/models/manageiq/providers/embedded_ansible/provider.rb
  spec/models/manageiq/providers/embedded_ansible/provider_spec.rb
Labels: bug, core/embedded_ansible

#19945 [V2V] ConversionHost - Validate resource is not already a conversion host
  app/models/conversion_host/configurations.rb
  spec/models/conversion_host/configurations_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19951 Change SERVICE_ORDER_CLASS to a string
  app/models/service_order.rb
  app/models/service_template_provision_request.rb
  app/models/service_template_transformation_plan_request.rb
  spec/models/service_template_provision_request_spec.rb
  spec/models/service_template_transformation_plan_request_spec.rb
Labels: bug, jansa/yes?, lifecycle/services

#19954 Allow overriding ESXi IP address with a custom attribute
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19953 Remove openstack Node / Deployment role logic from Host & EmsCluster
  app/models/ems_cluster.rb
  app/models/host.rb
  db/fixtures/miq_product_features.yml
  locale/en.yml
  spec/lib/miq_expression_spec.rb
  spec/models/ems_cluster_spec.rb
  spec/models/host_spec.rb
Labels: technical debt

#19936 Move API OIDC/OAuth2 support from API to ManageIQ core
  app/models/authenticator/httpd.rb
  app/models/authenticator/httpd/oauth2.rb
Labels: core/authentication, jansa/yes?, refactoring

#19939 [GitWorktree/GitRepository] Handle submodules
  app/models/git_repository.rb
  lib/git_worktree.rb
Labels: enhancement

#19958 Add inventory collections for Openstack Infra Graph Refresh
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: enhancement, providers/inventory

#19960 Move the OrchestrationStack ancestry to Persister::Shared
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: enhancement, providers/inventory

#19965 Remove timeline license as that code no longer exists
  LICENSE.txt
Labels: documentation, jansa/yes?

#19968 Add Sprint review 132
  CHANGELOG.md
Labels: documentation

#19961 Skip models that do not respond to :display_name
  lib/tasks/locale.rake
Labels: internationalization, jansa/yes?

#19971 Bump sys-filesystem version to 1.3.4
  Gemfile
Labels: dependencies

#19970 Rename private display_name method to avoid conflict
  app/models/vm_reconfigure_task.rb
Labels: changelog/no, ivanchuk/no, providers/virtual, technical debt

#19973 Add inventory_collections for container raise_creation_events
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
Labels: enhancement, providers/containers

#19974 Remove the Refresher#manager_refresh_post_processing method
  app/models/manageiq/providers/base_manager/refresher.rb
Labels: cleanup, providers/inventory

#19975 [Gemfile] Ensure manageiq-smartstate is 0.5.3
  Gemfile
Labels: dependencies

#19956 Don't queue things that need to run on the same worker container
  app/models/manageiq/providers/ansible_runner_workflow.rb
  spec/models/manageiq/providers/ansible_playbook_workflow_spec.rb
  spec/models/manageiq/providers/ansible_role_workflow_spec.rb
Labels: bug, core/embedded ansible, jansa/yes?

#19967 Move Third Party licenses to NOTICE.txt
  LICENSE.txt
  NOTICE.txt
Labels: documentation

#19741 Metrics - perf_capture_queue_targets
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
Labels: enhancement, providers/metrics

#19979 [V2V] Do not wait for IP address if no playbook is expected
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19978 [V2V] Add a state to pause disks precopy
  app/models/conversion_host.rb
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/infra_conversion_job_spec.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19972 remove all the cruft from the refresher
  app/models/manageiq/providers/base_manager/refresher.rb
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: cleanup, providers/inventory

#19980 Do not mount VDDK folder if transport method is SSH
  app/models/conversion_host.rb
  spec/models/conversion_host_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19981 add tests for preprocess_targets_manager_refresh
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: test

#19969 [IVANCHUK] Ivanchuk-4 Changelog
  CHANGELOG.md
Labels: documentation

#19988 Revert the inventory remove till the swift_manager is on graph refresh
  app/models/manageiq/providers/base_manager/refresher.rb
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: bug, providers/inventory

#19986 Bump deprecation notice to the next release
  lib/vmdb/deprecation.rb
Labels: enhancement

#19989 [V2V] Unpause disk precopy to run cutover
  app/models/conversion_host.rb
  app/models/infra_conversion_job.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/infra_conversion_job_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19990 Add graph refresh for SwiftManager
  app/models/manageiq/providers/inventory/persister/builder/storage_manager.rb
  app/models/manageiq/providers/storage_manager/inventory.rb
  app/models/manageiq/providers/storage_manager/inventory/collector.rb
  app/models/manageiq/providers/storage_manager/inventory/collector/swift_manager.rb
  app/models/manageiq/providers/storage_manager/inventory/parser.rb
  app/models/manageiq/providers/storage_manager/inventory/parser/swift_manager.rb
  app/models/manageiq/providers/storage_manager/inventory/persister.rb
  app/models/manageiq/providers/storage_manager/inventory/persister/swift_manager.rb
  app/models/manageiq/providers/storage_manager/swift_manager.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_parser.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_parser/cross_linkers.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresh_parser/cross_linkers/openstack.rb
  app/models/manageiq/providers/storage_manager/swift_manager/refresher.rb
Labels: enhancement, providers/storage

#19991 Remove inventory_obj_refresher
  app/models/manageiq/providers/base_manager/refresher.rb
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: cleanup, providers/inventory

#19982 take out all the rest of inventory_object_refresh
  app/models/ext_management_system.rb
  app/models/manageiq/providers/cloud_manager/provision/state_machine.rb
  app/models/orchestration_stack.rb
  config/settings.yml
Labels: cleanup, providers/inventory

#19995 Allow overriding ESXi IP address with a custom attribute - Part 2
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19996 Delete a number of old unused refresh parsers
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/physical_infra_manager/refresh_parser.rb
  app/models/manageiq/providers/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/storage_manager/cinder_manager/refresh_parser.rb
  app/models/manageiq/providers/storage_manager/swift_manager.rb
Labels: cleanup, providers/inventory

#19998 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#19962 [JANSA] Update source catalog for jansa release
  .tx/config
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization

#19932 [IVANCHUK] Update source gettext catalog for ivanchuk update
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ja/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization

#20004 Remove the journald logger to resolve segfaults
  lib/vmdb/loggers.rb
Labels: appliance, bug, jansa/yes

#20009 Include vendor and parent cluster info into C&U collection summary
  app/models/ems_cluster.rb
Labels: enhancement

#20012 Use --signal instead of -s to kill pods
  app/models/conversion_host.rb
Labels: enhancement, ivanchuk/yes, jansa/yes?, v2v

#20003 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#19848 Consolidate existing server setting CLI tools
  spec/tools/server_settings_replicator/server_settings_replicator_spec.rb
  tools/configure_server_settings.rb
  tools/server_settings_replicator/server_settings_replicator.rb
Labels: core, enhancement

#19955 Move git_based_domain_import to core
  lib/services/git_based_domain_import_service.rb
  spec/lib/services/git_based_domain_import_service_spec.rb
Labels: refactoring

#19976 Fix Full Pathname Stored in DB
  app/models/filesystem.rb
Labels: cleanup

#20010 Move core settings from ui
  config/settings.yml
Labels: technical debt

#20022 Remove unused ems_inv_to_hashes method
  app/models/manageiq/providers/base_manager/refresher.rb
  app/models/manageiq/providers/storage_manager/cinder_manager/refresher.rb
Labels: cleanup, providers/inventory

#20021 Force test:initialize to set RAILS_ENV=test
  lib/tasks/test.rake
Labels: test

#20019 Add additional privilege escalation methods
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
Labels: core/embedded ansible, enhancement

#19984 Add kafka as an option for prototype.queue_type
  app/models/ems_event.rb
  app/models/miq_event_handler/runner.rb
  app/models/miq_queue.rb
  config/settings.yml
  spec/models/ems_event_spec.rb
Labels: core/queue, enhancement

#20031 Set the provider attribute before hostname/ipaddress in EMS factory
  spec/factories/ext_management_system.rb
Labels: bug, providers, test
