Repository ManageIQ/manageiq, pull requests merged in 2020-11, with the labels that each got.

#20754 Add a supports feature for Vm pause
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement

#20770 Update Copyright year
  locale/en.yml
  locale/es.yml
  locale/fr.yml
  locale/ja.yml
  locale/pt_BR.yml
  locale/zh_CN.yml
Labels: bug, jansa/yes?, kasparov/yes?

#20771 [EmbeddedAnsible] Ensure newline for :ssh_key_data
  app/models/manageiq/providers/embedded_ansible/automation_manager/scm_credential.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/credential_spec.rb
Labels: bug, core/embedded ansible, jansa/yes?, kasparov/yes?

#20761 Introducing supports cloud_volume_create
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement

#20739 consistent child manager saves
  app/models/manageiq/providers/base_manager.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/storage_manager/cinder_manager.rb
  app/models/mixins/cinder_manager_mixin.rb
  app/models/mixins/has_infra_manager_mixin.rb
  app/models/mixins/has_monitoring_manager_mixin.rb
  app/models/mixins/has_network_manager_mixin.rb
  app/models/mixins/swift_manager_mixin.rb
Labels: kasparov/yes?, pluggability/providers, providers/cloud

#20759 Add git remote connection check code
  app/models/git_repository.rb
  app/models/service_ansible_playbook.rb
  app/models/service_template_ansible_playbook.rb
  spec/models/git_repository_spec.rb
Labels: enhancement

#20274 add binding to determine which method to use in relationship mixin
  app/models/mixins/relationship_mixin.rb
  spec/models/mixins/relationship_mixin_spec.rb
Labels: refactoring

#20762 Marked the Different Button Types for Translation
  app/models/custom_button.rb
Labels: enhancement, internationalization

#20769 locale_to_json: add automatic creation of datepicker webpack file
  lib/tasks/locale.rake
Labels: enhancement

#20774 Translations provided on 2020-11-02
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: enhancement, internationalization, kasparov/yes?

#20572 replace virtual_aggregate with virtual_sum
  app/models/ext_management_system.rb
  app/models/hardware.rb
  app/models/mixins/aggregation_mixin.rb
  spec/models/zone_spec.rb
Labels: refactoring

#20786 Updated Japanese Translation File from 2020-11-04
  locale/ja/manageiq.po
Labels: enhancement, internationalization, kasparov/yes?

#20784 Look in the correct places for migrations to determine the deployment_status
  lib/tasks/evm_application.rb
Labels: bug, jansa/yes?, kasparov/yes?

#20789 handle child_objs being nil in remove_child
  app/models/mixins/relationship_mixin.rb
Labels: bug

#20782 OpenStack CloudVolumes should live in the Storage Manager
  spec/factories/cloud_volume.rb
  spec/factories/cloud_volume_backup.rb
  spec/factories/cloud_volume_snapshot.rb
Labels: providers/cloud

#20794 [rails6][git_repository_spec.rb] Use .local_miq_server
  spec/models/git_repository_spec.rb
Labels: rails6, test

#20404 Do not allow to delete tenant which has children
  app/models/manageiq/providers/cloud_manager.rb
  app/models/tenant.rb
  spec/models/tenant_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, kasparov/yes?

#20791 don't call queue merge with objects
  app/models/ems_refresh.rb
  spec/models/ems_refresh_spec.rb
Labels: bug

#20775 Expose the auth_key_pair_create supports feature on EMSes
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement, kasparov/no

#20787 [rails6][service_template_ansible_playbook_spec.rb] Fix ems/provider lets
  spec/factories/ext_management_system.rb
  spec/models/service_template_ansible_playbook_spec.rb
Labels: rails6

#20796 Add Sprint review 149
  CHANGELOG.md
Labels: documentation

#20797 Eager load api collections classes in ui workers
  app/models/miq_ui_worker.rb
  spec/models/miq_ui_worker_spec.rb
  spec/models/miq_web_service_worker_spec.rb
Labels: bug, ui

#20793 Bump rspec-rails to v4.0.1
  Gemfile
  spec/spec_helper.rb
Labels: dependencies, test

#20685 Fix automate_output_value() for tag control
  app/models/dialog_field_tag_control.rb
Labels: bug

#20801 Don't override model_class in Container collections
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
Labels: providers/inventory, technical debt

#20792 Delete orphaned miq workers rows with no pods
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/kubernetes.rb
  lib/container_orchestrator.rb
  lib/tasks/evm_application.rb
  lib/workers/bin/run_single_worker.rb
  spec/lib/tasks/evm_application_spec.rb
  spec/models/miq_server/worker_management/monitor/kubernetes_spec.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
Labels: core/pods, enhancement, kasparov/yes?

#20800 Add `Instance (IBM)` to en.yml
  locale/en.yml
Labels: enhancement, internationalization

#20806 Add missing display names for 2 models
  locale/en.yml
Labels: bug, internationalization, ivanchuk/yes

#20807 Add display_name() for CloudVolumeType
  app/models/cloud_volume_type.rb
Labels: internationalization, providers/cloud

#20809 Ensure that options[:ems_id] is an Array when passed as an ENV var
  lib/workers/bin/run_single_worker.rb
Labels: appliance/workers, bug, kasparov/yes?

#20811 Added dictionary entry for OVF Templates
  locale/en.yml
Labels: enhancement

#20438 Feature changes to go with Control Explorer split
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  db/fixtures/miq_user_roles.yml
  spec/models/miq_user_role_spec.rb
Labels: enhancement

#20803 Expose supports_create_host_aggregate as a virtual attribute on EMS
  app/models/ext_management_system.rb
Labels: enhancement, kasparov/no

#20772 Tenant changes changes miq product features on all servers
  app/models/miq_product_feature.rb
  app/models/tenant.rb
  spec/models/host_spec.rb
Labels: api

#20814 [JANSA] Backport 20792 to jansa with no schema changes: delete orphaned miq workers rows with no pods
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/kubernetes.rb
  lib/container_orchestrator.rb
  lib/workers/bin/run_single_worker.rb
  spec/models/miq_server/worker_management/monitor/kubernetes_spec.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
Labels: bug

#20776 Pluggable provider mapping prefixes and targets
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
  app/models/provider_tag_mapping.rb
  spec/models/ext_management_system_spec.rb
Labels: pluggability/providers, refactoring

#20823 Cockpit is a monitor thread and is not a pod worker.
  app/models/miq_server/worker_management/monitor.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
Labels: bug, core/pods, kasparov/yes?

#20826 Add a warning if the ems.update fails within ManageIQ::Providers::BaseManager::Refresher
  app/models/manageiq/providers/base_manager/refresher.rb
Labels: enhancement, providers/inventory

#20825 Translations provided on 2020-11-17
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: bug, internationalization, kasparov/yes?

#20810 Call ResetFailedUnit when cleaning up failed services
  app/models/miq_server/worker_management/monitor/systemd.rb
  spec/models/miq_server/worker_management/monitor/systemd_spec.rb
Labels: appliance/workers, bug, kasparov/yes?

#20824 Auto-restart systemd workers results in duplicates
  app/models/miq_server/at_startup.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_worker/systemd_common.rb
  lib/workers/evm_server.rb
Labels: appliance/workers, bug, kasparov/yes?

#20827 [JANSA] Cockpit is a monitor thread and is not a pod worker. #20823 jansa backport
  app/models/miq_server/worker_management/monitor.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
Labels: bug, core/pods, jansa/yes

#20832 Translations provided on 2020-11-19
  locale/pt_BR/manageiq.po
Labels: bug, internationalization, kasparov/yes?

#20834 Use requests, not defaultRequest, in deploy definition
  app/models/miq_worker/container_common.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: bug, core/pods, jansa/yes?, kasparov/yes?

#20816 Disable :embedded_automation_manager_ansible factory
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/playbook_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager_spec.rb
  spec/models/service_template_ansible_playbook_spec.rb
Labels: core/embedded ansible, test

#20808 revert the 118n fallbacks change
  config/environments/production.rb
Labels: internationalization

#20839 Add Sprint review 150
  CHANGELOG.md
Labels: documentation

#20841 [rails6] Fix evm:dbsync:resync_excludes
  app/models/pglogical_subscription.rb
  lib/miq_pglogical.rb
Labels: rails6

#20821 Switch MiqRequestWorkflow dialogs accessor to writer only
  app/models/miq_request_workflow.rb
Labels: bug

#20815 Add tests for newlines in gettext catalogs
  locale/es/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/pt_BR/manageiq.po
  spec/i18n/newlines_spec.rb
  spec/shared/i18n/newlines.rb
Labels: internationalization, test

#20780 Added Missing Strings to yaml Files
  config/locale_task_config.yaml
  locale/en.yml
Labels: bug, internationalization

#20847 Adopt new memory/cpu request/limit(threshold) values
  config/settings.yml
Labels: core/pods, enhancement, jansa/yes?, kasparov/yes?, performance
