Repository ManageIQ/manageiq, pull requests merged in 2020-01, with the labels that each got.

#19653 Remove the EmsRefresh.init_console method
  app/models/ems_refresh.rb
Labels: cleanup, providers/inventory

#19665 Split the responsibilities of #worker_heartbeat into separate methods
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_worker/runner.rb
  spec/models/miq_server/worker_management/heartbeat_spec.rb
  spec/models/miq_server/worker_monitor_spec.rb
Labels: core/workers, refactoring

#19668 Fix current_authentication_settings spec for MiqLdapConfiguration
  spec/tools/miq_config_sssd_ldap/miqldap_configuration_spec.rb
Labels: refactoring, test

#19475 Reduce queries in tag name validation in Classification model
  app/models/classification.rb
Labels: refactoring

#19680 Fix typo in OperationsWorker worker_roles
  app/models/manageiq/providers/base_manager/operations_worker/runner.rb
Labels: bug, providers

#19679 Cu capture queue 1
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/infra_manager/metrics_capture_spec.rb
  spec/models/metric/capture_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
  spec/support/metric_helper.rb
Labels: providers/metrics, refactoring, test

#19683 Don't start every MetricsCollectorWorker
  app/models/mixins/per_ems_type_worker_mixin.rb
Labels: bug, core/workers

#19521 Clean up nil ternary issues
  app/models/condition.rb
  app/models/dialog_field_importer.rb
  app/models/ems_event.rb
  app/models/firewall_rule.rb
  app/models/host.rb
  app/models/miq_ae_instance.rb
  app/models/miq_alert_set.rb
  app/models/miq_cockpit_ws_worker/authenticator.rb
  app/models/miq_policy_set.rb
  app/models/miq_provision/automate.rb
  app/models/miq_provision_workflow.rb
  app/models/miq_report/generator.rb
  app/models/miq_server/worker_management/dequeue.rb
  app/models/miq_shortcut.rb
  app/models/mixins/miq_policy_mixin.rb
  app/models/policy_event.rb
  app/models/resource_pool.rb
  app/models/vim_performance_analysis.rb
  app/models/vim_performance_trend.rb
  app/models/vm.rb
  app/models/zone.rb
  lib/git_worktree.rb
  lib/tasks/evm_application.rb
  lib/vmdb/settings/database_source.rb
  tools/feature_support_matrix.rb
  tools/fix_auth/fix_auth.rb
  tools/miq_config_sssd_ldap/sssd_conf/domain.rb
Labels: technical debt

#19660 Move has_vix_disk_lib into vmware plugin as a seed
  app/models/miq_server.rb
  app/models/miq_server/server_smart_proxy.rb
  lib/evm_database.rb
  spec/lib/evm_database_spec.rb
Labels: enhancement, providers/pluggability, refactoring

#19682 Sync was extracted from std lib in ruby 2.7
  Gemfile
Labels: dependencies, ruby2.7

#19607 Simplified VmScan base class as all the provider logic has moved into relevant subclasses
  app/models/vm_scan.rb
  spec/models/vm_scan_spec.rb
Labels: providers/pluggability, refactoring, smart state

#19638 [IVANCHUK] Query current/starting miq_workers, bypassing cache/stale objects
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/mixins/miq_web_server_worker_mixin.rb
  spec/lib/workers/heartbeat_spec.rb
Labels: bug, core/workers

#19686 Fix service template provision request spec
  spec/models/miq_provision_spec.rb
Labels: refactoring, test

#19685 remove factories that have conditional perf_capture_enabled
  spec/factories/ems_cluster.rb
  spec/factories/host.rb
  spec/factories/storage.rb
  spec/factories/vm_or_template.rb
  spec/models/chargeback_vm/ongoing_time_period_spec.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/metering_container_project_spec.rb
  spec/models/metering_vm_spec.rb
  spec/models/metric_rollup/chargeback_helper_spec.rb
  spec/models/miq_report_spec.rb
  spec/models/vim_performance_analysis_spec.rb
Labels: providers/metrics, test

#19688 Fix running metrics_capture tests late at night
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
Labels: bug/sporadic test failure, providers/metrics, test

#19690 Update manageiq-smartstate gem to 0.3.4
  Gemfile
Labels: dependencies, ivanchuk/yes

#19691 [HAMMER] Update manageiq-smartstate gem to 0.2.18.2
  Gemfile
Labels: dependencies

#19667 Add an ext_management_system accessor to the anonymous class in the ProviderObjectMixin spec
  spec/models/mixins/provider_object_mixin_spec.rb
Labels: refactoring, test

#19684 Metrics capture hierarchy
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/container_manager.rb
  app/models/manageiq/providers/container_manager/metrics_capture.rb
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/infra_manager/metrics_capture.rb
  app/models/metric/targets.rb
  spec/models/manageiq/providers/infra_manager/metrics_capture_spec.rb
Labels: enhancement, providers/metrics

#19260 [IVANCHUK] Add human locale name for Brazilian Portuguese
  config/human_locale_names.yaml
Labels: bug, internationalization

#19293 [IVANCHUK] Add configuration for transifex
  .tx/config
Labels: developer, internationalization

#19695 Add Sprint review 127
  CHANGELOG.md
Labels: documentation

#19703 Add an interface method for raw_connect
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: refactoring

#19700 Pass some explicit arguments to raw_connect for ExtManagementSystem specs
  spec/models/ext_management_system_spec.rb
Labels: technical debt, test

#19701 Autoload Rails Models unless called from safe_load
  config/initializers/yaml_autoloader.rb
  spec/initializers/yaml_autoloader_spec.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, core, hammer/yes, ivanchuk/yes

#19704 Remove VMwareWebService from the main Gemfile
  Gemfile
Labels: dependencies, technical debt

#19708 Fix invalid partials for MiqRequestWorkflow specs
  spec/models/miq_request_workflow_spec.rb
Labels: refactoring, test

#19709 [IVANCHUK] Update manageiq-postgres_ha_admin to 3.1.1
  Gemfile
Labels: dependencies

#19696 DialogFieldTagControl - don't add <None> for multiselects
  app/models/dialog_field_tag_control.rb
  spec/models/dialog_field_tag_control_spec.rb
Labels: automate, bug

#19681 Updated vm_reconfigure_task in app/models to add disk size information.
  app/models/vm_reconfigure_task.rb
  spec/models/vm_reconfigure_task_spec.rb
Labels: bug

#19666 Always use file based heartbeat
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_server/worker_management/dequeue.rb
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_worker/runner.rb
  lib/workers/bin/run_single_worker.rb
  spec/models/miq_server/worker_management/heartbeat_spec.rb
  spec/models/miq_worker/runner_spec.rb
Labels: core/workers, enhancement, technical debt

#19662 Add tags to PxeImage
  app/models/pxe_image.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, ivanchuk/no, provisioning

#19712 Differentiate deployment names by server
  app/models/miq_worker/container_common.rb
  app/models/miq_worker/service_worker.rb
  lib/container_orchestrator.rb
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: core, enhancement

#19633 Allow for setting warm migration cutover datetime
  app/models/service_template_transformation_plan.rb
  spec/models/service_template_transformation_plan_spec.rb
Labels: enhancement

#19726 Remove unnecessary captures and greedy regex patterns in RegistrationSystem
  app/models/registration_system.rb
Labels: refactoring

#19693 Remove invalid partial from MiqConfigSssdLdap::ConfigureApplianceSettings specs
  spec/tools/miq_config_sssd_ldap/configure_appliance_settings_spec.rb
Labels: refactoring, test

#19649 Use automate timeout for orchestration service.
  app/models/service_orchestration.rb
  spec/models/service_orchestration_spec.rb
Labels: changelog/yes, enhancement

#19705 Set my_queue_name for MiqProvisionRequests
  app/models/miq_provision_request.rb
  app/models/miq_request_task/state_machine.rb
  spec/models/miq_provision_request_spec.rb
Labels: changelog/yes, enhancement, provisioning

#19735 Use a Kubernetes-specific factory for ServiceContainerTemplate specs
  app/models/container_template.rb
Labels: refactoring, test

#19737 Add PhysicalServer to RBAC Filterer
  lib/rbac/filterer.rb
Labels: bug, hammer/yes, ivanchuk/yes

#19740 Providers changelog for sprint 128
  CHANGELOG.md
Labels: documentation

#19736 Add my_queue_name to VmReconfigureRequest
  app/models/vm_reconfigure_request.rb
  spec/models/vm_reconfigure_request_spec.rb
Labels: changelog/yes, enhancement, providers/virtual

#19738 Add Sprint review 128
  CHANGELOG.md
Labels: documentation

#19710 Fix VM Retirement Error Message
  app/models/vm_or_template.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, retirement

#19706 Check for namespaced Datacenter classes
  app/models/miq_request_workflow.rb
  spec/models/miq_request_workflow_spec.rb
Labels: bug, provisioning

#19711 Add PxeServer, IsoImage, WindowsImage to RBAC with specs
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: bug, ivanchuk/no, test

#19744 Remove the unsafe cattr_accessor for my_guid_cache
  app/models/miq_server.rb
  spec/models/miq_server_spec.rb
Labels: core, enhancement

#19745 Commit the data directory rather than creating it when the server starts
  .gitignore
  app/models/miq_server.rb
  data/.gitkeep
Labels: enhancement

#19746 Move server start to EvmServer class
  app/models/miq_server.rb
  app/models/miq_server/environment_management.rb
  lib/workers/evm_server.rb
  spec/models/miq_server_spec.rb
Labels: enhancement, refactoring, unmergeable

#19749 Add back some missing state transitions to VmScan
  app/models/vm_scan.rb
Labels: bug, core/smart state

#19657 RBAC: Add sui_dashboard_show under sui_dashboard
  db/fixtures/miq_product_features.yml
Labels: bug

#19748 Set a queue_name for Host/Storage smartstate scans
  app/models/host.rb
  app/models/storage.rb
  spec/models/host_spec.rb
Labels: enhancement, providers

#19762 Bump smartstate to v0.5.0
  Gemfile
Labels: dependencies

#19758 Remove Vmdb::Settings last_loaded and simplify server settings reload
  app/models/miq_server/configuration_management.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_worker/runner.rb
  lib/patches/config_patch.rb
  lib/vmdb/settings.rb
  spec/lib/vmdb/settings_spec.rb
  spec/models/miq_server/configuration_management_spec.rb
  spec/support/evm_spec_helper.rb
Labels: core, enhancement

#19764 Allow Job#queue_signal to take a queue_name
  app/models/job/state_machine.rb
Labels: core/queue, enhancement

#19763 [V2V] Fix playbook invocation
  app/models/infra_conversion_job.rb
  spec/models/infra_conversion_job_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19752 Bump secure_headers gem to a more recent version
  Gemfile
Labels: core/security, dependencies, enhancement

#19673 Completely remove the MiqVimBrokerWorker
  app/models/ext_management_system.rb
  app/models/job_proxy_dispatcher.rb
  app/models/manageiq/providers/base_manager/metrics_collector_worker/runner.rb
  app/models/manageiq/providers/base_manager/refresh_worker/runner.rb
  app/models/miq_alert.rb
  app/models/miq_generic_worker/runner.rb
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_server/server_smart_proxy.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_smart_proxy_worker/runner.rb
  app/models/miq_worker/runner.rb
  app/models/vm_or_template.rb
  spec/models/job_proxy_dispatcher_embedded_scan_spec.rb
  spec/models/job_proxy_dispatcher_spec.rb
  spec/models/miq_action_spec.rb
Labels: dependencies, providers, technical debt

#19734 Monitor multiple servers when we're running in pods
  app/models/miq_worker.rb
  app/models/miq_worker/service_worker.rb
  lib/vmdb/settings.rb
  lib/workers/evm_server.rb
  spec/lib/workers/evm_server_spec.rb
Labels: core, enhancement

#19768 Remove unused EvmServer#monitoring_server? method
  lib/workers/evm_server.rb
Labels: cleanup, core

#19714 DRY up get_description method in VmReconfigureTask
  app/models/vm_reconfigure_task.rb
  spec/models/vm_reconfigure_task_spec.rb
Labels: changelog/no, ivanchuk/no, providers/virtual, refactoring

#19739 Add my_queue_name for ems_operations miq_requests
  app/models/configured_system.rb
  app/models/miq_provision_configured_system_request.rb
  app/models/physical_server.rb
  app/models/physical_server_firmware_update_request.rb
  app/models/physical_server_provision_request.rb
  app/models/vm_cloud_reconfigure_request.rb
  app/models/vm_migrate_request.rb
  spec/models/configured_system_spec.rb
  spec/models/physical_server_firmware_update_request_spec.rb
  spec/models/physical_server_provision_request_spec.rb
  spec/models/physical_server_spec.rb
Labels: enhancement, providers

#19775 Add verify_credentials_task to host
  app/models/host.rb
  spec/models/host_spec.rb
Labels: enhancement, providers

#19774 Fixing unknown unknowns
  app/models/miq_server/log_management.rb
  spec/models/miq_server/log_management_spec.rb
Labels: bug, core

#19769 The MiqEventHandler still needs VimTypes
  Gemfile
  app/models/miq_event_handler/runner.rb
Labels: bug, dependencies

#19781 Remove some leftover VimBroker settings
  config/settings.yml
Labels: cleanup, providers

#19776 First pass at adding code owners to ManageIQ/manageiq
  .github/CODEOOWNERS
Labels: changelog/no, documentation

#19533 Refactor authenticator spec
  app/models/authenticator/base.rb
  app/models/authenticator/ldap.rb
  spec/models/authenticator_spec.rb
Labels: refactoring, test

#19782 [V2V] Allow get_conversion_state to fail
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: enhancement, ivanchuk/yes, v2v

#19770 Map server to zone in pods
  app/models/miq_server.rb
  app/models/zone.rb
  spec/lib/workers/evm_server_spec.rb
  spec/models/miq_server/queue_management_spec.rb
  spec/models/miq_server_spec.rb
  spec/models/zone_spec.rb
Labels: core, enhancement

#19783 [V2V] Do not update disk percentage on cancellation
  app/models/service_template_transformation_plan_task.rb
  spec/models/service_template_transformation_plan_task_spec.rb
Labels: bug, ivanchuk/yes, v2v

#19785 Don't create the service for pods
  app/models/miq_worker/service_worker.rb
Labels: cleanup, core

#19784 Update sprockets for CVE-2018-3760
  Gemfile
Labels: core/security, dependencies

#19787 [V2V] Renaming openstack_tls_ca_cert variable
  app/models/conversion_host.rb
  app/models/conversion_host/configurations.rb
Labels: enhancement, ivanchuk/yes, v2v

#19757 Upgrade to config gem 2.2.1 for ruby 2.7 support
  Gemfile
Labels: core, dependencies, enhancement, ruby2.7

#19786 Cleanup some server methods
  app/models/miq_server/configuration_management.rb
  app/models/miq_server/worker_management/monitor.rb
  spec/models/miq_server/configuration_management_spec.rb
  spec/models/miq_server/worker_monitor_spec.rb
Labels: cleanup, core

#19779 Make External-facing networks available to all tenants
  app/models/cloud_network.rb
Labels: bug, providers/network

#19788 Remove process_messages_from_server from MiqWorker
  app/models/miq_worker/runner.rb
Labels: appliance/workers, cleanup

#19790 Still need to register worker with worker monitor
  app/models/miq_worker/runner.rb
Labels: bug
