Repository ManageIQ/manageiq, pull requests merged in 2020-12, with the labels that each got.

#20837 This change will enable the appliance_console to set the messaging_ty…
  lib/tasks/evm_settings.rake
  spec/lib/tasks/evm_settings_spec.rb
Labels: enhancement

#20845 [EmbeddedAnsible] Ensure newline for auth_key in MachineCredential
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/scm_credential.rb
  spec/lib/ansible/runner/credential/machine_credential_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/credential_spec.rb
Labels: bug, core/embedded ansible, ivanchuk/yes, jansa/yes?, kasparov/yes?

#20852 Add collect_running_processes supports feature
  app/models/mixins/supports_feature_mixin.rb
  app/models/vm/operations.rb
Labels: enhancement, pluggability

#20853 Move hawkular settings to OpenShift provider plugin
  config/settings.yml
Labels: providers/containers, technical debt

#20854 Remove remnants of MiqEmsRefreshCoreWorker
  Procfile.example
  app/models/miq_worker_type.rb
  config/settings.yml
  spec/factories/miq_ems_refresh_core_worker.rb
Labels: technical debt

#20862 Cleanup a useless next unless in worker monitor
  app/models/miq_server/worker_management/monitor.rb
Labels: appliance/workers, cleanup

#20856 [MiqPglogical] Add ConnectionHandling
  app/models/pglogical_subscription.rb
  lib/miq_pglogical.rb
  lib/miq_pglogical/connection_handling.rb
Labels: bug, rails6

#20844 Add a new hidden feature for viewing/listing shortcuts
  db/fixtures/miq_product_features.yml
Labels: enhancement

#20855 Move settings into plugins
  config/settings.yml
  lib/generators/manageiq/provider/templates/config/settings.yml
Labels: pluggability/providers, technical debt

#20868 Add ibm terraform logger
  lib/vmdb/loggers.rb
Labels: providers/provisioning

#20872 allow ibm_cloud and ibm_terraform global loggers
  .rubocop_local.yml
Labels: developer, providers

#20838 Strip label value in tag mapping
  app/models/provider_tag_mapping/mapper.rb
  spec/models/provider_tag_mapping_spec.rb
Labels: bug

#20877 Drop the no longer used MiqSchedule.run_adhoc_db_gc method
  app/models/miq_schedule.rb
  spec/models/miq_schedule_spec.rb
Labels: cleanup, kasparov/no

#20878 Add Sprint review 151
  CHANGELOG.md
Labels: documentation

#20863 Add display names for FileDepot models
  app/models/file_depot_nfs.rb
  app/models/file_depot_s3.rb
  app/models/file_depot_swift.rb
Labels: internationalization

#20848 Add scope by product features to Rbac::filterer
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: refactoring

#20879 Remove unused assignments
  app/models/chargeback_rate_detail_measure.rb
  app/models/manageiq/providers/embedded_ansible/crud_common.rb
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/miq_action.rb
  app/models/miq_retire_task.rb
  app/models/miq_shortcut.rb
Labels: core

#20664 Hide deprecated and duplicate attributes
  app/models/application_record.rb
  app/models/ext_management_system.rb
  app/models/mixins/deprecation_mixin.rb
  lib/acts_as_ar_model.rb
  lib/extensions/ar_visible_attribute.rb
  lib/miq_expression.rb
  spec/lib/extensions/ar_visible_attribute_spec.rb
  spec/models/mixins/deprecation_mixin_spec.rb
Labels: api, core/reporting, enhancement

#20880 [EmbeddedAnsible::CrudCommon] Fix manager validation
  app/models/manageiq/providers/embedded_ansible/crud_common.rb
Labels: core/embedded ansible

#20882 [Gemfile] Lock the config gem
  Gemfile
Labels: bug, dependencies, jansa/yes?, kasparov/yes?

#20883 Fix escaping of < and > in ContainerLogger
  lib/vmdb/loggers/container_logger.rb
  spec/lib/vmdb/loggers/container_logger_spec.rb
Labels: bug, kasparov/yes?

#20892 cleanup conditionals
  app/models/condition.rb
Labels: cleanup

#20867 Modified MiqReport::GROUPINGS to Include Plural Strings
  app/models/miq_report.rb
  app/models/miq_report/generator/html.rb
Labels: bug, internationalization

#20873 Factory(:miq_report_with_results): Add number_of_results
  spec/factories/miq_report.rb
Labels: test

#20456 remove deprecation warning about service display being renamed
  app/models/service.rb
Labels: technical debt

#20894 Decrypt all text fields as passwords may have different key names
  app/models/miq_queue.rb
  spec/models/miq_queue_spec.rb
Labels: enhancement

#20875 fixed MiqPolicySet.seed when Condition record with the same description or name but different guid already exists
  app/models/condition.rb
  spec/models/condition_spec.rb
Labels: bug, ivanchuk/yes

#20895 Support synchronized dialog fields when adding a new OVF service template
  app/models/miq_provision_orch_workflow.rb
Labels: enhancement, lifecycle/services

#20897 add a queue post service provision log message
  app/models/service_template_provision_task.rb
Labels: enhancement

#20865 Patch deployment resource constraints
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/kubernetes.rb
  app/models/miq_worker/container_common.rb
  lib/container_orchestrator.rb
  spec/models/miq_server/worker_management/monitor/kubernetes_spec.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: core/pods, enhancement

#20902 Bump the manageiq-messaging gem to 1.0
  Gemfile
Labels: dependencies, enhancement

#20903 add back the alias for all vms and templates
  app/models/mixins/aggregation_mixin.rb
Labels: bug

#20891 Honor zone setting when queuing launch_ansible_job.
  app/models/service_ansible_playbook.rb
  spec/models/service_ansible_playbook_spec.rb
Labels: bug, kasparov/yes?, lifecycle/services

#20904 Run MiqServer.status_update in server process
  app/models/miq_schedule_worker/jobs.rb
  spec/models/miq_schedule_worker/jobs_spec.rb
Labels: appliance/workers, bug, core/pods, jansa/yes?, kasparov/yes?

#20914 remove unused disk var
  spec/models/vm_or_template_spec.rb
Labels: cleanup

#20915 manageiq-style -i
  .codeclimate.yml
Labels: developer

#20886 [IVANCHUK] Tenant changes changes miq product features on all servers
  app/models/miq_product_feature.rb
  app/models/tenant.rb
  spec/models/host_spec.rb
Labels: bug

#20916 Partially revert "manageiq-style -i"
  .codeclimate.yml
Labels: developer
