Repository ManageIQ/manageiq, pull requests merged in 2020-08, with the labels that each got.

#20401 Remove MIQ_SPARTAN in favor of Foreman
  app/models/miq_generic_worker.rb
  app/models/miq_schedule_worker.rb
  app/models/miq_server/environment_management.rb
  app/models/miq_ui_worker.rb
  app/models/miq_worker.rb
  app/models/mixins/per_ems_type_worker_mixin.rb
  app/models/mixins/per_ems_worker_mixin.rb
  lib/workers/evm_server.rb
  spec/models/miq_server/environment_manager_spec.rb
Labels: technical debt

#20398 Call `column_type` on parsed field to get the actual column type
  app/models/miq_report/generator/sorting.rb
  spec/models/miq_report/generator_spec.rb
Labels: bug, jansa/yes?

#20403 Replace MiqUUID with Digest::UUID
  app/models/hardware.rb
Labels: technical debt

#20412 Add Sprint review 142
  CHANGELOG.md
Labels: documentation

#20008 Re-enable journald logger
  Gemfile
  lib/vmdb/loggers.rb
Labels: appliance, dependencies

#20414 minor grammatical nits in comments
  app/models/mixins/supports_feature_mixin.rb
Labels: test

#20413 Bump manageiq-smartstate to v0.6.0
  Gemfile
Labels: dependencies

#20410 Add cloud_databases to the cloud_manager persister
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
Labels: enhancement, providers/cloud

#20418 Initialize instance variables, use accessors, for miq_expression.rb
  lib/miq_expression.rb
Labels: cleanup

#20415 fix brakeman command injection warning
  app/models/system_console.rb
  config/brakeman.ignore
Labels: developer

#20381 Add has_policies virtual attribute
  app/models/container_group.rb
  app/models/container_image.rb
  app/models/container_node.rb
  app/models/container_project.rb
  app/models/container_replicator.rb
  app/models/miq_server.rb
  app/models/mixins/miq_policy_mixin.rb
  app/models/physical_server.rb
  lib/extensions/ar_taggable.rb
  spec/lib/extensions/ar_taggable_spec.rb
  spec/models/container_group_spec.rb
  spec/models/container_image_spec.rb
  spec/models/container_node_spec.rb
  spec/models/container_project_spec.rb
  spec/models/container_replicator_spec.rb
  spec/models/ems_cluster_spec.rb
  spec/models/ems_folder_spec.rb
  spec/models/ext_management_system_spec.rb
  spec/models/host_spec.rb
  spec/models/miq_enterprise_spec.rb
  spec/models/miq_region_spec.rb
  spec/models/miq_server_spec.rb
  spec/models/mixins/miq_policy_mixin_spec.rb
  spec/models/physical_server_spec.rb
  spec/models/resource_pool_spec.rb
  spec/models/vm_or_template_spec.rb
  spec/support/examples_group/shared_examples_for_miq_policy_mixin.rb
Labels: enhancement

#20125 update brakeman
  Gemfile
  config/brakeman.ignore
Labels: core/security, dependencies, developer

#20422 Remove miq-deep from FixAuth
  tools/fix_auth/models.rb
Labels: technical debt

#20355 Block attempt to create duplicate retire request
  app/models/mixins/retirement_mixin.rb
  app/models/orchestration_stack.rb
  app/models/service.rb
  app/models/vm.rb
  spec/factories/miq_request.rb
  spec/models/orchestration_stack/retirement_management_spec.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/vm/retirement_management_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?, lifecycle/retirement

#20426 Improvement to action_check_compliance to avoid infinite loop.
  app/models/miq_action.rb
  spec/models/miq_action_spec.rb
Labels: bug

#20428 [HAMMER] Use AwesomeSpawn for ConversionHost
  app/models/conversion_host.rb
Labels: bug

#20427 Replace thin MiqStats wrappers with Math extensions
  app/models/miq_report/generator/trend.rb
  app/models/vim_performance_analysis.rb
  app/models/vim_performance_trend.rb
Labels: refactoring

#20433 remove to_miq_a callers
  app/models/miq_alert.rb
  app/models/miq_provision_virt_workflow.rb
  app/models/miq_report.rb
  app/models/miq_report_result.rb
  app/models/miq_request_workflow/dialog_field_validation.rb
  app/models/miq_schedule.rb
  app/models/mixins/miq_provision_mixin.rb
  app/models/mixins/scanning_mixin.rb
  app/models/relationship.rb
  lib/workers/evm_server.rb
Labels: technical debt

#20429 Move SKIP_TEST_RESET to environment.rb
  bin/update
  lib/manageiq/environment.rb
Labels: developer, refactoring

#20439 Fix for vmware content-library missing ems_id
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: bug, providers/virtual

#20430 get_policies should maybe return policies in the set as well as the set itself
  app/models/mixins/miq_policy_mixin.rb
  spec/support/examples_group/shared_examples_for_miq_policy_mixin.rb
Labels: bug

#20440 Don't allow kafka exceptions to cause EmsEvent.add_queue to fail
  app/models/ems_event.rb
Labels: bug, core/events, jansa/yes?

#20437 Adding IBM "Aix" and "i" operating systems to the list of MIQ supported OSes
  app/models/operating_system.rb
Labels: enhancement

#20441 Don't disconnect resource pools in refresh_new_target
  app/models/ems_refresh/save_inventory_infra.rb
Labels: bug, ivanchuk/yes, jansa/yes?, providers/virtual

#20420 Cleanup failed systemd services
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/quiesce.rb
  app/models/miq_server/worker_management/monitor/systemd.rb
  spec/models/miq_server/worker_management/monitor/systemd_spec.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
Labels: appliance/workers, refactoring

#20436 fix resource pool not having all_hosts reference
  app/models/resource_pool.rb
  spec/models/resource_pool_spec.rb
Labels: bug, providers

#20445 fixed lower_relative_path typo
  app/models/mixins/relative_path_mixin.rb
Labels: bug

#20448 remove has_parent?
  app/models/service.rb
Labels: refactoring

#20443 Remove EmsRefresh.refresh_new_target
  app/models/ems_event/automate.rb
  app/models/ems_refresh.rb
  app/models/ems_refresh/link_inventory.rb
  app/models/ems_refresh/save_inventory.rb
  app/models/ems_refresh/save_inventory_cloud.rb
  app/models/ems_refresh/save_inventory_helper.rb
  app/models/ems_refresh/save_inventory_infra.rb
  spec/models/ems_refresh/link_inventory_spec.rb
  spec/models/ems_refresh/save_inventory_spec.rb
  spec/models/ems_refresh_spec.rb
Labels: cleanup, providers/inventory

#20450 added i18n default database
  config/database.pg.yml
Labels: developer, documentation

#20451 Add Sprint review 143
  CHANGELOG.md
Labels: documentation

#20421 remove unused dialog field type
  app/models/dialog_field.rb
  spec/factories/dialog_field.rb
  spec/models/dialog_spec.rb
Labels: technical debt

#20468 Allow services to set a queue_name for VM provisioning.
  app/models/miq_provision.rb
  spec/models/miq_provision_spec.rb
Labels: bug

#20446 widget generate_report_result should work regardless of whether the owner has a group
  app/models/miq_widget.rb
Labels: bug

#20485 update copyright date
  README.md
Labels: bug

#20483 Add the IBM Cloud provider plugin to the Gemfile
  Gemfile
  spec/models/ext_management_system_spec.rb
  spec/models/manageiq/providers/cloud_manager_spec.rb
Labels: dependencies, enhancement, providers/cloud

#20484 Add IBM Cloud to 'eligible_for_provisioning' list
  app/models/manageiq/providers/cloud_manager/template.rb
Labels: enhancement, lifecycle/provisioning, providers/cloud

#20232 enhance error handle for failing playbook clone
  app/models/manageiq/providers/ansible_runner_workflow.rb
Labels: bug

#20482 Add supports_create_security_group virtual attribute
  app/models/ext_management_system.rb
Labels: bug, ivanchuk/yes

#20478 Update plugin generator with CodeClimate and Travis updates
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/.travis.yml
  lib/generators/manageiq/plugin/templates/README.md
  lib/generators/manageiq/plugin/templates/bin/ci/after_script
  lib/manageiq/environment.rb
Labels: enhancement

#20486 Remove hardcoded types in favor of a supports feature check
  app/models/manageiq/providers/cloud_manager/template.rb
  app/models/manageiq/providers/infra_manager/template.rb
  app/models/miq_template.rb
Labels: enhancement, pluggability/providers

#20489 fix typo in job spec
  spec/models/job_spec.rb
Labels: test

#20490 Updates to provider plugin generator
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/README.md
  lib/generators/manageiq/plugin/templates/config/initializers/gettext.rb
  lib/generators/manageiq/plugin/templates/lib/tasks/%plugin_name%.rake
  lib/generators/manageiq/plugin/templates/lib/tasks/README.md
  lib/generators/manageiq/provider/provider_generator.rb
Labels: developer, enhancement, pluggability

#20487 Add IBM Terraform to the Gemfile
  Gemfile
  spec/models/ext_management_system_spec.rb
Labels: dependencies, enhancement, providers/configuration

#20492 Add agrare as code owner of the plugin generators
  .github/CODEOWNERS
Labels: developer, documentation

#20469 Remove unused save_inventory methods
  app/models/ems_refresh.rb
  app/models/ems_refresh/link_inventory.rb
  app/models/ems_refresh/metadata_relats.rb
  app/models/ems_refresh/save_inventory.rb
  app/models/ems_refresh/save_inventory_automation.rb
  app/models/ems_refresh/save_inventory_block_storage.rb
  app/models/ems_refresh/save_inventory_cloud.rb
  app/models/ems_refresh/save_inventory_configuration.rb
  app/models/ems_refresh/save_inventory_container.rb
  app/models/ems_refresh/save_inventory_infra.rb
  app/models/ems_refresh/save_inventory_network.rb
  app/models/ems_refresh/save_inventory_object_storage.rb
  app/models/ems_refresh/save_inventory_orchestration_stacks.rb
  app/models/ems_refresh/save_inventory_physical_infra.rb
  app/models/ems_refresh/save_inventory_provisioning.rb
  spec/models/ems_refresh/link_inventory_spec.rb
  spec/models/ems_refresh/metadata_relats_spec.rb
Labels: cleanup, providers/inventory

#20491 Add bundler.d to plugin generator
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/.gitignore
Labels: developer, enhancement

#20474 remove unused options[:select] from reports
  app/models/miq_report.rb
Labels: cleanup

#20493 Only write the .rubocop_local.yml the first time
  lib/generators/manageiq/plugin/plugin_generator.rb
Labels: developer, enhancement, pluggability

#20481 Add back Cloud Provider Load Balancer Menus
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  db/fixtures/miq_user_roles.yml
  lib/rbac/filterer.rb
  locale/en.yml
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, providers/network

#20466 remove dialog field list view
  app/models/dialog_field.rb
Labels: technical debt

#20498 fix miq ae namespace spec typo
  spec/models/miq_ae_namespace_spec.rb
Labels: test

#20499 Update ibm_cloud_power_virtual_servers spec description
  spec/models/ext_management_system_spec.rb
Labels: bug, providers/cloud

#20497 MiqSmartProxyWorker not running in Podified
  app/models/miq_smart_proxy_worker.rb
Labels: bug, core/pods, core/smart state, jansa/yes?

#20504 enable support for relative path in directory parameter for rake export
  lib/task_helpers/exports.rb
Labels: enhancement
