Repository ManageIQ/manageiq, pull requests merged in 2021-05, with the labels that each got.

#21203 fix the ides of may
  spec/models/event_stream/purging_spec.rb
Labels: bug/sporadic test failure, jansa/yes?, kasparov/yes?, lasker/yes?

#21207 Fix broken non admin login from missing product feature field
  app/models/miq_product_feature.rb
  db/fixtures/miq_product_features.yml
  spec/factories/miq_product_feature.rb
Labels: bug, core

#21206 use latest bundler-inject
  Gemfile
Labels: dependencies

#21214 Switch from postgresql.crt to root.crt
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
Labels: bug

#21212 Add IBM PowerVC provider
  Gemfile
Labels: dependencies, enhancement, providers

#21210 Use standard ruby for services
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_event_catcher@.service
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_metrics_collector@.service
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_refresh@.service
  systemd/manageiq-cockpit_ws@.service
  systemd/manageiq-ems_metrics_processor@.service
  systemd/manageiq-event_handler@.service
  systemd/manageiq-generic@.service
  systemd/manageiq-priority@.service
  systemd/manageiq-remote_console@.service
  systemd/manageiq-reporting@.service
  systemd/manageiq-schedule@.service
  systemd/manageiq-smart_proxy@.service
  systemd/manageiq-ui@.service
  systemd/manageiq-web_service@.service
Labels: enhancement, wip

#21217 Fix issue where all features may be filtered out
  spec/support/evm_spec_helper.rb
Labels: bug, test

#21218 Remove MiqVimBroker/MiqFaultTolerantVim from tools
  tools/vim_collect_inventory.rb
  tools/vim_collect_perf_history.rb
Labels: providers, technical-debt

#21219 Drop the VimBroker from the foreman Procfile.example
  Procfile.example
Labels: providers, technical debt

#21013 Add PxeServer.verify_depot_settings_queue
  app/models/mixins/file_depot_mixin.rb
Labels: enhancement, kasparov/no

#21220 Ensure specified product features were actually seeded and exist
  spec/lib/task_helpers/imports/roles_spec.rb
  spec/models/miq_user_role_spec.rb
  spec/support/evm_spec_helper.rb
Labels: enhancement, lasker/yes?, test

#21221 Add logging for each system schedule that is created
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_schedule_worker/scheduler.rb
  spec/models/miq_schedule_worker/scheduler_spec.rb
Labels: core, enhancement

#21224 Only queue perf_capture for supported providers
  app/models/ext_management_system.rb
  app/models/zone.rb
  spec/models/zone_spec.rb
Labels: bug, providers/metrics

#21225 Default to :local_db_find_missing_references strategy for targeted refresh
  app/models/manageiq/providers/inventory/persister.rb
Labels: enhancement, providers/inventory

#21222 Add missing features for existing routes
  db/fixtures/miq_product_features.yml
Labels: bug, core/rbac

#21169 Optionally publish inventory to kafka
  Gemfile
  app/models/manageiq/providers/base_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
  spec/support/ems_refresh_helper/test_persister.rb
Labels: dependencies, enhancement, providers/inventory

#21229 fix number miq_server formatting deprecation warning
  app/models/miq_server/environment_management.rb
  app/models/miq_server/status_management.rb
Labels: technical debt

#21231 Fix and add few broken routes and identifiers
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: bug

#20763 Add Filters mixin to schedules
  app/models/miq_schedule.rb
  app/models/miq_schedule/filters.rb
  spec/models/miq_schedule/filters_spec.rb
Labels: refactoring

#21230 Add pxe_tag feature to allow tagging of pxe_servers and all children that support it
  db/fixtures/miq_product_features.yml
Labels: bug, core/rbac

#21233 no longer dump settings
  lib/patches/config_patch.rb
  lib/vmdb/settings.rb
  spec/lib/vmdb/settings_spec.rb
Labels: enhancement

#21236 Bump AR session_store to 2.0 for CVE
  Gemfile
Labels: core/security, dependencies, lasker/yes?

#21238 Add some missing identifiers in product yaml
  db/fixtures/miq_product_features.yml
Labels: bug

#21239 Fix issue with fix_auth and rare key collision during recrypt
  spec/tools/fix_auth/auth_config_model_spec.rb
  spec/tools/fix_auth/auth_model_spec.rb
  tools/fix_auth/auth_model.rb
Labels: bug, bug/sporadic test failure

#21243 Add bundler audit to brakeman security suite
  .travis.yml
  Gemfile
  lib/tasks/test_brakeman.rake
  lib/tasks/test_security.rake
Labels: core/security, dependencies, developer, test, tools

#21213 Combine Block/Object Mixins into StorageManager
  app/models/manageiq/providers/storage_manager.rb
  app/models/manageiq/providers/storage_manager/block_mixin.rb
  app/models/manageiq/providers/storage_manager/object_mixin.rb
Labels: providers/storage, refactoring

#21242 Work-around for extraneous escapes in json catalogs
  lib/tasks/locale.rake
Labels: bug, developer, internationalization, tools

#21245 Patch PoToJson to emit strings with escapes properly
  lib/tasks/locale.rake
  lib/tasks/po_to_json_override.rb
Labels: developer, enhancement, internationalization, tools

#21247 Simplify the bundle-audit task
  lib/tasks/test_security.rake
Labels: cleanup, developer, tools
