Repository ManageIQ/manageiq, pull requests merged in 2021-03, with the labels that each got.

#21086 Fix ansible_runner content seeding
  lib/vmdb/plugins.rb
Labels: bug

#21076 Feature changes to support moving Configured Systems out of Ansible Tower Explorer
  app/models/aliases/automation_manager_configured_system.rb
  db/fixtures/miq_product_features.yml
  locale/en.yml
Labels: enhancement

#21087 Add Oracle Cloud provider
  Gemfile
  spec/models/ext_management_system_spec.rb
  spec/models/manageiq/providers/cloud_manager_spec.rb
Labels: dependencies, enhancement, providers/cloud

#21075 Container images rollups from container rollups
  app/models/container.rb
  app/models/container_image.rb
  app/models/manageiq/providers/container_manager/metrics_capture.rb
  app/models/metric/ci_mixin/state_finders.rb
  app/models/metric/processing.rb
  app/models/metric/rollup.rb
  app/models/vim_performance_state.rb
  app/models/vim_performance_tag_value.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
Labels: enhancement, lasker/yes

#21092 Add Sprint review 156
  CHANGELOG.md
Labels: documentation

#21089 Avoid seeding ansible content in production
  app/models/manageiq/providers/embedded_ansible/seeding.rb
  lib/ansible/content.rb
  lib/tasks/evm_ansible_runner.rake
  lib/vmdb/plugins.rb
Labels: core/embedded ansible, enhancement

#21094 Automatically set the miq_templates model_class
  app/models/manageiq/providers/inventory/persister/builder.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: enhancement, providers/inventory

#20930 Mark x axis labels as translations in Overview -> Utilization chart
  config/locale_task_config.yaml
  lib/manageiq/reporting/formatter/c3.rb
  lib/tasks/locale.rake
Labels: enhancement, internationalization, transformation

#21102 Update provider ddf scema testcase
  spec/lib/ddf_spec.rb
Labels: bug, lasker/yes?

#20980 Migrating Seeding Over to yml
  app/models/miq_event_definition.rb
  app/models/miq_event_definition_set.rb
  db/fixtures/miq_event_definition_events.yml
  db/fixtures/miq_event_definition_sets.csv
  db/fixtures/miq_event_definition_sets.yml
  db/fixtures/miq_event_definitions.csv
  spec/models/miq_event_definition_spec.rb
Labels: refactoring

#21104 Remove eval in favor of const_set
  app/models/miq_action.rb
Labels: bug, kasparov/yes?, lasker/yes?

#21105 Remove "script" option since it has not been supported in over a decade
  app/models/condition.rb
Labels: cleanup, lasker/yes?

#21046 Reworked SupportsFeatureMixin to remove QUERYABLE_FEATURES global
  app/models/cloud_volume.rb
  app/models/cloud_volume_backup.rb
  app/models/configuration_profile.rb
  app/models/configured_system.rb
  app/models/container_template.rb
  app/models/ext_management_system.rb
  app/models/floating_ip.rb
  app/models/host.rb
  app/models/host_aggregate.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/cloud_manager/vm.rb
  app/models/manageiq/providers/container_manager.rb
  app/models/manageiq/providers/network_manager.rb
  app/models/manageiq/providers/storage_manager.rb
  app/models/miq_template/operations.rb
  app/models/mixins/supports_feature_mixin.rb
  app/models/network_router.rb
  app/models/security_group.rb
  app/models/storage.rb
  app/models/vm/operations.rb
  app/models/vm/operations/guest.rb
  app/models/vm/operations/lifecycle.rb
  app/models/vm/operations/power.rb
  app/models/vm_or_template/operations.rb
  app/models/vm_or_template/operations/relocation.rb
  app/models/vm_or_template/operations/snapshot.rb
  app/models/vm_or_template/scanning.rb
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: lasker/no, refactoring

#21084 Added GUI cross-ref between host-initiator and cloud-volume.
  app/models/cloud_volume.rb
  app/models/host_initiator.rb
Labels: enhancement, providers/storage

#21106 adding support for importing images between providers
  app/models/manageiq/providers/cloud_manager/template.rb
Labels: enhancement, providers/cloud

#21110 Add Sprint review 157
  CHANGELOG.md
Labels: documentation

#21099 Improve core persister support for combined manager refresh
  app/models/manageiq/providers/inventory/persister.rb
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/network_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/persister_helper.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: providers/inventory

#21111 Add YAML Files to locale_task_config
  config/locale_task_config.yaml
Labels: enhancement, internationalization

#21113 Fix pie and donut type charts legend name
  lib/manageiq/reporting/formatter/chart_common.rb
Labels: bug

#21095 Add 2.7 support/drop 2.5
  .travis.yml
  Gemfile
Labels: dependencies, lasker/yes, ruby2.7

#21114 Set parent manager in properties for targeted/combined manager refresh
  app/models/manageiq/providers/inventory/persister/builder.rb
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/persister_helper.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: providers/inventory, refactoring

#21103 Lower the cpu request due to the simpler liveness probe
  config/settings.yml
Labels: core/pods, lasker/yes?, performance

#21115 Translations provided on 2021-03-12
  locale/de/manageiq.po
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: enhancement, internationalization, lasker/yes?

#21112 adding 'import_image' API-feature to miq_product_features.yml
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/cloud

#20983 Add static systemd unit files for workers
  build/systemd_units/manageiq-cockpit_ws.target
  build/systemd_units/manageiq-cockpit_ws@.service
  build/systemd_units/manageiq-ems_metrics_processor.target
  build/systemd_units/manageiq-ems_metrics_processor@.service
  build/systemd_units/manageiq-event_handler.target
  build/systemd_units/manageiq-event_handler@.service
  build/systemd_units/manageiq-generic.target
  build/systemd_units/manageiq-generic@.service
  build/systemd_units/manageiq-priority.target
  build/systemd_units/manageiq-priority@.service
  build/systemd_units/manageiq-remote_console.target
  build/systemd_units/manageiq-remote_console@.service
  build/systemd_units/manageiq-reporting.target
  build/systemd_units/manageiq-reporting@.service
  build/systemd_units/manageiq-schedule.target
  build/systemd_units/manageiq-schedule@.service
  build/systemd_units/manageiq-smart_proxy.target
  build/systemd_units/manageiq-smart_proxy@.service
  build/systemd_units/manageiq-ui.target
  build/systemd_units/manageiq-ui@.service
  build/systemd_units/manageiq-web_service.target
  build/systemd_units/manageiq-web_service@.service
  build/systemd_units/manageiq.target
  lib/generators/manageiq/provider/provider_generator.rb
  lib/generators/manageiq/provider/templates/build/systemd_units/%plugin_name%_%manager_path%_event_catcher.target
  lib/generators/manageiq/provider/templates/build/systemd_units/%plugin_name%_%manager_path%_event_catcher@.service
  lib/generators/manageiq/provider/templates/build/systemd_units/%plugin_name%_%manager_path%_metrics_collector.target
  lib/generators/manageiq/provider/templates/build/systemd_units/%plugin_name%_%manager_path%_metrics_collector@.service
  lib/generators/manageiq/provider/templates/build/systemd_units/%plugin_name%_%manager_path%_refresh.target
  lib/generators/manageiq/provider/templates/build/systemd_units/%plugin_name%_%manager_path%_refresh@.service
Labels: appliance/workers, dependencies, technical debt

#21119 Fixed value for Plural-Forms to match other language files
  locale/en/manageiq.po
Labels: bug, internationalization

#21122 Move build/systemd_units/ -> systemd/ due to BUILD file conflict
  systemd/manageiq-cockpit_ws.target
  systemd/manageiq-cockpit_ws@.service
  systemd/manageiq-ems_metrics_processor.target
  systemd/manageiq-ems_metrics_processor@.service
  systemd/manageiq-event_handler.target
  systemd/manageiq-event_handler@.service
  systemd/manageiq-generic.target
  systemd/manageiq-generic@.service
  systemd/manageiq-priority.target
  systemd/manageiq-priority@.service
  systemd/manageiq-remote_console.target
  systemd/manageiq-remote_console@.service
  systemd/manageiq-reporting.target
  systemd/manageiq-reporting@.service
  systemd/manageiq-schedule.target
  systemd/manageiq-schedule@.service
  systemd/manageiq-smart_proxy.target
  systemd/manageiq-smart_proxy@.service
  systemd/manageiq-ui.target
  systemd/manageiq-ui@.service
  systemd/manageiq-web_service.target
  systemd/manageiq-web_service@.service
  systemd/manageiq.target
Labels: bug

#21120 Don't dynamically write systemd unit files
  app/models/miq_server/at_startup.rb
  app/models/miq_worker.rb
  app/models/miq_worker/systemd_common.rb
  config/settings.yml
Labels: build, enhancement

#21125 Move the provider generator systemd files to ./systemd
  lib/generators/manageiq/provider/provider_generator.rb
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_event_catcher.target
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_event_catcher@.service
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_metrics_collector.target
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_metrics_collector@.service
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_refresh.target
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_refresh@.service
Labels: appliance/workers, bug, core

#21126 Add cloud_volume_types to storage manager persister
  app/models/manageiq/providers/inventory/persister/builder/storage_manager.rb
Labels: enhancement, providers/inventory

#21117 Fixes bug where filtering by tag was returning all metric rollups regardless of assigned tags
  app/models/chargeback_configured_system.rb
  app/models/chargeback_vm.rb
  app/models/metric/common.rb
  app/models/vim_performance_tag_value.rb
  lib/before_session_middleware.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/vim_performance_tag_value_spec.rb
Labels: bug, lasker/yes?

#21133 [KASPAROV] [session_extension.rb] Fix superclass mismatch
  lib/extensions/session_extension.rb
Labels: bug

#21134 Removing lib/before_session_middleware.rb
  lib/before_session_middleware.rb
Labels: bug, lasker/yes?

#21131 Updated Translations from 2021-03-27
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization, lasker/yes?

#21137 Add Sprint review 158
  CHANGELOG.md
Labels: documentation
