Repository ManageIQ/manageiq, pull requests merged in 2021-02, with the labels that each got.

#20947 [WIP] Features to support Event explorer De-explorization
  app/models/miq_event_definition.rb
  app/models/miq_policy.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, wip

#20992 Fix MiqEnvironment.local_ip_address to not prefer loopback
  lib/miq_environment.rb
  spec/lib/miq_environment_spec.rb
  spec/models/miq_server/environment_manager_spec.rb
Labels: bug, core

#20967 Filtering by multiple tags for chargebackVm and ContainerProjects
  app/models/chargeback_container_project.rb
  spec/models/chargeback_container_project_spec.rb
  spec/models/chargeback_vm_spec.rb
Labels: enhancement

#20993 Cleanup BinaryBlobPart filtering
  app/models/binary_blob_part.rb
  spec/models/binary_blob_part_spec.rb
Labels: bug

#20998 Added missing dictionary entry for 'miq_event'
  locale/en.yml
Labels: enhancement

#20999 WidgetSet - fix db:seed, don't blow up when set_data is a HashWithIndifferentAccess
  app/models/miq_widget_set.rb
  app/models/miq_widget_set/set_data.rb
  spec/models/miq_widget_set_spec.rb
Labels: bug

#20997 Organize Gemfile - 2021
  Gemfile
Labels: dependencies

#21007 Add Sprint review 154
  CHANGELOG.md
Labels: documentation

#20995 Bump manageiq-smartstate to 0.7.0
  Gemfile
Labels: dependencies

#21009 Fix spec failures/fallout from removing `MiqUtil.runcmd`
  spec/lib/evm_database_ops_spec.rb
Labels: bug, test

#20925 Added show_list/show features to support Policy de-explorization changes
  app/models/miq_policy.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement

#21006 Deprecate symbol suport for tools/configure_server_settings
  tools/configure_server_settings.rb
Labels: technical debt

#21010 Fix sporadic test failure when MiqEvent is not yet defined
  spec/lib/evm_database_ops_spec.rb
Labels: bug/sporadic test failure

#21011 Use wim_parser gem instead of manageiq-gems-pending
  Gemfile
  app/models/pxe_server.rb
Labels: dependencies

#20812 Add ARM64 jobs in Travis-CI
  .travis.yml
  bin/ci/before_install.sh
Labels: enhancement, test

#20948 Added show_list/show features for Conditions Explorer de-explorization
  app/models/condition.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement

#21005 Support Postgres with SSL certificates
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
Labels: enhancement

#21016 Renamed miq_event features and startpage url to miq_event_definition …
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement

#21020 Remove unused Vm.lookup_by_full_location method
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: technical debt

#20945 Added show_list/show features for Alert Profiles Explorer de-explorization
  app/models/miq_alert_set.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  locale/en.yml
Labels: enhancement

#21026 Make Host#refresh_firewall_rules operate via SupportsFeatureMixin
  app/models/host.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: refactoring

#21027 Make Host#refresh_advanced_settings operate via SupportsFeatureMixin
  app/models/host.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: refactoring

#21017 Introducing VolumeMapping
  app/models/cloud_volume.rb
  app/models/host_initiator.rb
  app/models/manageiq/providers/inventory/persister/builder/storage_manager.rb
  app/models/manageiq/providers/storage_manager/block_mixin.rb
  app/models/volume_mapping.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/storage

#21032 Make Host#refresh_logs operate via SupportsFeatureMixin
  app/models/host.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: refactoring

#21023 Support ruby 2.7 in the Gemfile
  Gemfile
Labels: dependencies, ruby2.7

#20946 Added show_list/show features for Alerts Explorer de-explorization
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  locale/en.yml
Labels: enhancement

#21037 Fix unintentional override of base adapter's database_version method
  lib/extensions/ar_adapter/ar_dba.rb
  lib/workers/evm_server.rb
Labels: bug, rails6

#21033 Remove unused method Host#refresh_ipmi_power_state
  app/models/host.rb
Labels: technical debt

#21031 Fix `uninitialized constant MiqEnvironment::Command::AwesomeSpawn`
  lib/miq_environment.rb
Labels: bug

#21039 remove disabling of hash alignment cop
  app/models/manageiq/providers/embedded_ansible/automation_manager/google_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/network_credential.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/scm_credential.rb
Labels: cleanup, core/embedded ansible

#21022 Remove unused method Vm#is_controllable?
  app/models/host.rb
  app/models/vm_or_template.rb
Labels: technical debt

#21024 Creating volume mapping
  app/models/cloud_volume.rb
  app/models/host_initiator.rb
  app/models/volume_mapping.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/storage

#21012 Fix needless assignment in if statement
  app/channels/application_cable/connection.rb
Labels: technical debt

#21043 Fixed wrong product features for volume_mapping
  db/fixtures/miq_product_features.yml
Labels: bug, providers/storage

#21019 Add chargeback report for Configured Systems
  app/models/chargeback/consumption_without_rollups.rb
  app/models/chargeback_configured_system.rb
  app/models/configured_system.rb
  config/miq_expression.yml
  locale/en.yml
  spec/models/chargeback_configured_system_spec.rb
Labels: enhancement

#21044 Prefer mocking invalid domains over VCR
  spec/models/firmware_registry/rest_api_depot_spec.rb
Labels: test

#21038 Use a more specific rescue to avoid hiding unexpected errors
  lib/vmdb/settings/database_source.rb
Labels: enhancement

#21021 Remove unused Vm.lookup_by_path method
  app/models/vm_or_template.rb
  spec/models/vm_or_template_spec.rb
Labels: technical debt

#21045 Add delegate for cpu/memory to Configured System
  app/models/configured_system.rb
Labels: enhancement, providers/configuration

#20944 Added show_list/show features to support MiqAction de-explorization changes
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
  locale/en.yml
Labels: enhancement

#21049 Added missing dictionary entries
  locale/en.yml
Labels: enhancement

#21050 Expose ems supports_cloud_subnet_create as an API queryable attribute
  app/models/ext_management_system.rb
  app/models/mixins/supports_feature_mixin.rb
Labels: enhancement

#21051 Lock down bundler to pre-2.2.10 and fix ManageIQ::Environment.bundler_version
  Gemfile
  lib/manageiq/environment.rb
Labels: dependencies

#21053 Change spec to use Tempfile with a block
  spec/models/miq_widget_set_spec.rb
Labels: bug/sporadic test failure

#21052 Remove Radar code as it's no longer used
  .gitignore
  Gemfile
  config/application.rb
  spec/tools/radar/rollup_radar_mixin_spec.rb
  tools/radar/capture_radar.rb
  tools/radar/report_radar.rb
  tools/radar/rollup_radar_mixin.rb
Labels: dependencies, technical debt

#21036 Ruby 2.7: Replace URI.escape/encode and unescape/decode with URI::DEFAULT_PARSER escape/unescape
  app/models/file_depot_ftp.rb
  app/models/log_file.rb
  app/models/mixins/file_depot_mixin.rb
  app/models/service_template_transformation_plan_task.rb
  spec/models/file_depot_ftp_spec.rb
Labels: dependencies, ruby2.7

#21058 Add Sprint review 155
  CHANGELOG.md
Labels: documentation

#21040 Loosen log message check in spec
  spec/models/mixins/process_tasks_mixin_spec.rb
Labels: test

#21057 Add iso_image_view.
  db/fixtures/miq_product_features.yml
Labels: enhancement, kasparov/no

#21060 Extract all_ems/all_valid_ems/any_valid? methods
  app/models/manageiq/providers/base_manager/event_catcher.rb
  app/models/manageiq/providers/base_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/base_manager/operations_worker.rb
  app/models/manageiq/providers/base_manager/refresh_worker.rb
  app/models/mixins/per_ems_type_worker_mixin.rb
  app/models/mixins/per_ems_worker_mixin.rb
  app/models/mixins/provider_worker_mixin.rb
Labels: providers, refactoring

#21048 Safe delete for cloud-volume
  app/models/cloud_volume.rb
  app/models/mixins/supports_feature_mixin.rb
  db/fixtures/miq_product_features.yml
  spec/factories/cloud_volume.rb
Labels: enhancement, providers/storage

#21062 Only set git user/email on CI
  bin/ci/before_install.sh
Labels: bug, test

#21064 database_connectivity? should handle not-running database
  lib/tasks/test.rake
  lib/vmdb/settings/database_source.rb
Labels: bug

#20941 DatabaseBackup.supported_depots: Use model names rather than prefixes
  app/models/database_backup.rb
  app/models/file_depot.rb
  spec/models/file_depot_spec.rb
Labels: refactoring

#21071 Fix Amazon-specific provider_tag_mapping_spec
  spec/models/provider_tag_mapping_spec.rb
Labels: bug, test

#21070 Fix issue with provider generator where logger names are wrong
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/config/settings.yml
  lib/generators/manageiq/plugin/templates/lib/%plugin_path%/engine.rb
  lib/generators/manageiq/provider/provider_generator.rb
Labels: bug

#21072 Use persister methods not inv_collection array
  spec/models/provider_tag_mapping_spec.rb
Labels: refactoring, test

#21068 If a system_uid already exists, update it, otherwise create it
  lib/workers/bin/run_single_worker.rb
Labels: bug, core/pods

#21073 Replace validate_destroy with supports feature
  app/models/host.rb
Labels: providers, refactoring

#21059 Prefer rollup records with tags to grouping in chargeback
  app/models/chargeback.rb
  app/models/chargeback/consumption.rb
  app/models/chargeback/consumption_with_rollups.rb
  spec/models/chargeback_vm_spec.rb
Labels: bug, core/chargeback

#21065 Moved and De-Explorized Templates accordion out of Ansible Tower Explorer
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement

#21080 Add Oracle as a vendor and OS Type
  app/models/operating_system.rb
  app/models/vm_or_template.rb
Labels: enhancement, providers/cloud

#21079 Heartbeat to file as unix time to avoid parsing
  app/models/miq_server/worker_management/heartbeat.rb
  app/models/miq_worker/runner.rb
  lib/workers/evm_server.rb
Labels: lasker/yes?, performance

#21069 Marked Status Strings For Translation
  app/models/miq_report_result.rb
  app/models/miq_task.rb
Labels: internationalization, lasker/yes?

#21081 heartbeat_check.rb and heartbeat.rb are no longer used.
  lib/workers/bin/heartbeat_check.rb
  lib/workers/heartbeat.rb
  spec/lib/workers/heartbeat_spec.rb
Labels: lasker/yes?, technical debt

#21082 Loosen bundler restrictions
  Gemfile
Labels: dependencies
