Repository ManageIQ/manageiq, pull requests merged in 2021-11, with the labels that each got.

#21529 update gem sys-filesystem
  Gemfile
Labels: bug, dependencies

#21527 Add volume mounts for httpd configuration
  app/models/miq_ui_worker.rb
  app/models/miq_web_service_worker.rb
Labels: enhancement

#21532 Only run kube_monitor threads on master MiqServer
  app/models/miq_server/worker_management/kubernetes.rb
  lib/workers/evm_server.rb
  spec/models/miq_server/worker_management/kubernetes_spec.rb
Labels: core/pods

#21537 Drop the graphql plugin and the references to it in the bundler group
  Gemfile
  app/models/miq_ui_worker.rb
  app/models/miq_web_service_worker.rb
  systemd/manageiq-ui@.service
  systemd/manageiq-web_service@.service
Labels: technical debt, dependencies

#21540 Ignore specs in CodeQL runs
  .github/codeql/codeql-config.yml
Labels: test

#21488 [Rbac] Rename include_for_find to references
  lib/rbac/filterer.rb
Labels: refactoring

#21533 Enhance check_compliance to handle has_compliance_policies
  app/models/container_image.rb
  app/models/host.rb
  app/models/mixins/compliance_mixin.rb
  app/models/physical_server.rb
  app/models/vm_or_template.rb
  spec/models/container_image_spec.rb
  spec/models/host_spec.rb
  spec/models/miq_template_spec.rb
  spec/models/physical_server_spec.rb
  spec/models/vm_spec.rb
  spec/support/examples_group/shared_examples_for_compliance_mixin.rb
Labels: enhancement, api

#21542 all child classes define supported_auth_types.
  app/models/ext_management_system.rb
Labels: refactoring

#21178 Remove ManageIQ::Password alt-keys usage from FixAuth
  Gemfile
  spec/models/miq_queue_spec.rb
  spec/tools/fix_auth/auth_config_model_spec.rb
  spec/tools/fix_auth/auth_model_spec.rb
  tools/fix_auth/auth_model.rb
  tools/fix_auth/fix_auth.rb
Labels: technical debt, dependencies

#21541 Convert server monitor to class
  app/models/miq_server.rb
  app/models/miq_server/server_monitor.rb
  lib/workers/evm_server.rb
  spec/models/miq_server/server_monitor_spec.rb
Labels: refactoring, core

#21384 Remove EvmDatabaseOps and related rake tasks
  lib/evm_database_ops.rb
  lib/tasks/evm_dba.rake
  spec/lib/evm_database_ops_spec.rb
Labels: technical debt

#21415 Remove DatabaseBackup
  app/models/database_backup.rb
  app/models/miq_region.rb
  app/models/miq_schedule.rb
  config/replication_exclude_tables.yml
  spec/factories/database_backup.rb
  spec/models/database_backup_spec.rb
  spec/models/miq_schedule_filter_spec.rb
  spec/models/miq_schedule_spec.rb
Labels: technical debt

#21544 Cache systemd services and processes in worker_management
  app/models/miq_server/worker_management/kubernetes.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/process.rb
  app/models/miq_server/worker_management/systemd.rb
  spec/models/miq_server/worker_management/process_spec.rb
  spec/models/miq_server/worker_management/systemd_spec.rb
Labels: enhancement, core

#21547 Handle ManageIQ::Password raising exception on plaintext
  tools/fix_auth/auth_model.rb
Labels: bug

#21549 Set the proper class_attribute default
  app/models/miq_policy.rb
  spec/models/miq_policy_spec.rb
Labels: bug

#21512 move EMS.supports :create_security_group to SecurityGroup.supports :create
  app/models/ext_management_system.rb
  app/models/ext_management_system/supports_attribute.rb
  spec/models/ext_management_system_spec.rb
Labels: refactoring, pluggability/providers

#21539 Remove LiveMetric and LiveMetricMixin
  app/models/live_metric.rb
  app/models/mixins/live_metrics_mixin.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/live_metric_spec.rb
  spec/models/mixins/live_metrics_mixin_spec.rb
Labels: cleanup, providers/metrics

#21513 Remove cockpit
  app/models/container_group.rb
  app/models/container_node.rb
  app/models/miq_cockpit_ws_worker.rb
  app/models/miq_cockpit_ws_worker/authenticator.rb
  app/models/miq_cockpit_ws_worker/runner.rb
  app/models/miq_server/role_management.rb
  app/models/miq_server/worker_management/kubernetes.rb
  app/models/miq_worker_type.rb
  app/models/mixins/cockpit_mixin.rb
  app/models/mixins/cockpit_support_mixin.rb
  app/models/vm.rb
  app/models/vm/operations.rb
  app/models/zone.rb
  config/settings.yml
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
  db/fixtures/server_roles.csv
  lib/miq_cockpit.rb
  lib/miq_environment.rb
  locale/en.yml
  locale/manageiq.pot
  spec/lib/miq_cockpit_spec.rb
  spec/lib/miq_environment_spec.rb
  spec/models/miq_cockpit_ws_worker/authenticator_spec.rb
  spec/models/miq_server/worker_management/kubernetes_spec.rb
  spec/models/mixins/cockpit_support_mixin_spec.rb
  spec/models/vm/operations_spec.rb
  spec/models/vm_spec.rb
  spec/models/zone_spec.rb
  systemd/manageiq-cockpit_ws.target
  systemd/manageiq-cockpit_ws@.service
Labels: technical debt

#21554 Removed subscription-manager
  Dockerfile
Labels: bug, morphy/yes?

#21550 Use standard CRUD supports features
  app/models/ext_management_system.rb
  app/models/host_aggregate.rb
Labels: refactoring, providers

#21556 Rename supported_subclasses to permitted_subclasses
  app/models/ext_management_system.rb
  app/models/manageiq/providers/network_manager.rb
  app/models/manageiq/providers/storage_manager.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/provider.rb
  spec/models/ext_management_system_spec.rb
Labels: refactoring

#21552 Add timeline_options to expose event_streams OPTIONS to the API
  app/models/ems_event.rb
  app/models/event_stream.rb
  app/models/miq_event.rb
  app/models/miq_policy.rb
  spec/models/event_stream_spec.rb
Labels: enhancement, api

#21564 Fix supports_attribute without a colname
  app/models/ext_management_system/supports_attribute.rb
Labels: bug

#21562 Remove usage of VMDBLogger#filename
  lib/vmdb/loggers.rb
Labels: technical debt

#21566 [MORPHY] Remove x86 references introduced in #21555
  Gemfile.lock.release
Labels: bug

#21563 Move VMDBLogger.contents into Vmdb::Loggers
  lib/vmdb/loggers.rb
  spec/lib/vmdb/data/miq_ascii.log
  spec/lib/vmdb/data/miq_empty.log
  spec/lib/vmdb/data/miq_utf8.log
  spec/lib/vmdb/data/redundant_utf8_byte_sequence.log
  spec/lib/vmdb/loggers_spec.rb
Labels: enhancement

#21568 Add Metric.metrics_in_range
  app/models/metric.rb
Labels: enhancement

#21558 Remove usage of VMDBLogger
  Gemfile
  lib/vmdb/appliance.rb
  lib/vmdb/loggers.rb
  lib/vmdb/loggers/audit_logger.rb
  lib/vmdb/loggers/fog_logger.rb
  lib/vmdb/loggers/provider_sdk_logger.rb
  lib/vmdb/settings/validator.rb
  spec/lib/vmdb/appliance_spec.rb
  spec/lib/vmdb/loggers/fog_logger_spec.rb
  spec/lib/vmdb/loggers_spec.rb
  spec/support/evm_spec_helper.rb
  tools/evm_dump.rb
  tools/generate_report.rb
  tools/ldap_ping.rb
  tools/purge_archived_vms.rb
  tools/purge_ems_events.rb
Labels: technical debt, dependencies

#21569 Fix group level and names for miq event
  app/models/ems_event.rb
  app/models/event_stream.rb
  app/models/miq_event.rb
  spec/models/event_stream_spec.rb
Labels: bug

#21571 Remove references to PostgresAdmin
  app/models/miq_server/log_management.rb
  lib/tasks/evm_dba.rake
Labels: technical debt

#21553 extract subclassess_supporting
  app/models/ext_management_system.rb
  app/models/miq_template.rb
  app/models/mixins/supports_feature_mixin.rb
  app/models/service_template.rb
  app/models/zone.rb
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: enhancement, core/rbac

#21548 [ruby3] KWArgs Roles
  app/models/user.rb
  lib/rbac.rb
  lib/rbac/authorizer.rb
Labels: enhancement, ruby3

#21572 Creation of host initiator group
  app/models/ext_management_system.rb
Labels: enhancement, providers/storage

#21574 Add common provider regions logic to core
  app/models/manageiq/providers/regions.rb
Labels: enhancement, providers

#21576 Extend timeout for destroying an EMS
  app/models/ext_management_system.rb
Labels: bug, morphy/yes?

#21578 Rename Regions from_file to from_source
  app/models/manageiq/providers/regions.rb
Labels: refactoring, providers
