Repository ManageIQ/manageiq, pull requests merged in 2021-08, with the labels that each got.

#21340 Split up JobProxyDispatcher
  app/models/infra_conversion_job.rb
  app/models/infra_conversion_job/dispatcher.rb
  app/models/job.rb
  app/models/job/dispatcher.rb
  app/models/job_proxy_dispatcher.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/vm_scan.rb
  app/models/vm_scan/dispatcher.rb
  config/settings.yml
  spec/models/infra_conversion_job/dispatcher_spec.rb
  spec/models/miq_schedule_worker/runner_spec.rb
  spec/models/vm_scan/dispatcher_embedded_scan_spec.rb
  spec/models/vm_scan/dispatcher_get_eligible_proxies_for_job_spec.rb
  spec/models/vm_scan/dispatcher_spec.rb
  spec/models/vm_scan/dispatcher_vm_miq_server_proxies_spec.rb
  spec/models/vm_scan/dispatcher_vm_proxies4job_spec.rb
  spec/models/vm_scan/dispatcher_vm_storage2proxies_spec.rb
Labels: refactoring, core

#21350 added two additional changes, one for pin policy and second for the IBMi Power License in Advanced Settings
  app/models/vm_or_template.rb
Labels: enhancement, providers/cloud

#21362 Use default HOME
  app/models/miq_worker/systemd_common.rb
Labels: bug, core/embedded ansible

#21355 add prod dirs via .gitkeep
  app/models/picture.rb
  data/git_repos/locks/.gitkeep
  public/pictures/.gitkeep
  public/upload/.gitkeep
Labels: enhancement, wip, appliance, build/podified

#21339 Fix start_servers starting servers twice
  lib/workers/evm_server.rb
  spec/factories/miq_server.rb
  spec/lib/workers/evm_server_spec.rb
Labels: bug, lasker/yes?

#21343 Only restart memcached when config changed
  app/models/miq_server/environment_management.rb
  lib/miq_memcached.rb
Labels: enhancement, appliance

#21367 Don't restart apache on evmserver startup
  lib/workers/evm_server.rb
Labels: technical debt, appliance/workers

#21368 Fix typo binery
  app/models/miq_schedule_worker/runner.rb
Labels: cleanup

#21344 Remove watchdog RegistrationSystem [formerly Watchdog columns]
  app/models/miq_database.rb
  app/models/registration_system.rb
  spec/models/miq_database_spec.rb
  spec/models/registration_system_spec.rb
Labels: enhancement

#21369 Add debugging for Ansible::Runner
  lib/ansible/runner.rb
  lib/ansible/runner/response.rb
  lib/ansible/runner/response_async.rb
  spec/lib/ansible/runner/response_spec.rb
  spec/lib/ansible/runner_spec.rb
Labels: enhancement

#21374 Add supports :check_compliance to ComplianceMixin
  app/models/container_image.rb
  app/models/mixins/compliance_mixin.rb
Labels: enhancement

#21375 Add supports :smartstate_analysis to EmsCluster
  app/models/ems_cluster.rb
Labels: enhancement

#21373 adding pvs <--pvc image import dispatcher to the schedule worker
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  config/settings.yml
Labels: enhancement, providers/cloud

#21382 [Ansible::Runner] Set ANSIBLE_STDOUT_CALLBACK
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: enhancement

#21383 Add supports_not for storage_manager
  app/models/ext_management_system.rb
Labels: enhancement, providers/cloud

#21388 Add a memcached_ping tool
  tools/memcached_ping.rb
Labels: tools

#21366 Remove writing of memcached config from evmserver
  app/models/miq_server/environment_management.rb
  config/settings.yml
  lib/workers/evm_server.rb
Labels: technical debt, core

#21391 Add volume mounts for httpd configuration
  app/models/miq_ui_worker.rb
  app/models/miq_worker/service_worker.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: enhancement

#21385 Fix Automate Git import if branch is symbolic ref
  lib/git_worktree.rb
  spec/fixtures/git_repos/branch_and_tag.git/refs/heads/symbolic
  spec/lib/git_worktree_spec.rb
Labels: bug, lasker/yes?

#21386 Add volume mount for root CA certificate
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
Labels: enhancement

#21387 added new supported items to EMS
  app/models/ext_management_system.rb
Labels: enhancement, providers/storage

#21394 Add branch release tasks
  lib/tasks/release.rake
Labels: enhancement, tools, morphy/yes

#21372 Gracefully handle non-superuser setting up replication
  app/models/miq_region.rb
  app/models/pglogical_subscription.rb
  lib/extensions/ar_migration.rb
  lib/miq_pglogical.rb
  lib/miq_pglogical/connection_handling.rb
  lib/task_helpers/development/replication.rb
  spec/lib/miq_pglogical_spec.rb
  spec/models/miq_region_spec.rb
Labels: bug, enhancement, core/replication, morphy/yes?

#21376 Remove locales for removed authentication columns
  locale/en.yml
  spec/database/data/id_column_whitelist.yml
Labels: technical debt
