Repository ManageIQ/manageiq, pull requests merged in 2021-06, with the labels that each got.

#21251 Fix spec issue after upgrade of mini_portile2
  spec/models/service_template_transformation_plan_spec.rb
Labels: bug, test

#21257 [miq_widget_spec.rb] Use add_member()
  spec/models/miq_widget_spec.rb
Labels: refactoring

#21250 Change belongsto2object_list to be more performant
  app/models/miq_filter.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/miq_filter_spec.rb
Labels: performance

#20942 MiqWidgetSet#find_with_same_order -> with_array_order
  app/models/miq_group.rb
  app/models/miq_widget_set.rb
  spec/models/miq_widget_set_spec.rb
Labels: refactoring

#21258 Extract belongsto2object_list call from the loop for performance
  app/models/miq_filter.rb
Labels: performance, refactoring

#21263 Bump brakeman to fix wrong loofah gem warning
  Gemfile
Labels: bug, dependencies

#21262 Validate requested FirmwareRegistry type
  app/models/firmware_registry.rb
  spec/models/firmware_registry_spec.rb
Labels: bug

#21265 Upgrade dalli past 2.7.7
  Gemfile
Labels: dependencies

#21255 [Exports::CustomButtons] Refactor/Simplify
  lib/task_helpers/exports/custom_buttons.rb
  spec/lib/task_helpers/exports/custom_buttons_spec.rb
  spec/lib/task_helpers/imports/custom_buttons_spec.rb
Labels: refactoring

#21266 Loosen dependency on dalli
  Gemfile
Labels: dependencies

#21260 Convert shelve operations to use SupportsFeatureMixin
  app/models/vm/operations/power.rb
  app/models/vm_or_template/operations.rb
Labels: providers/cloud, refactoring

#21268 Fix unsupported_reason_add with wrong the feature
  app/models/vm/operations/lifecycle.rb
  app/models/vm_or_template/operations/relocation.rb
Labels: bug, providers

#21261 Convert standby_guest operation to use SupportsFeatureMixin
  app/models/vm/operations/guest.rb
Labels: providers, refactoring

#21272 Set the `:manager` when building a TargetCollection
  app/models/manageiq/providers/base_manager/refresher.rb
Labels: enhancement, providers/inventory

#21267 Fix CSP fonts issue
  config/initializers/secure_headers.rb
Labels: bug

#21277 Allow nip.io for dev with external auth where hostnames are required
  config/environments/development.rb
Labels: enhancement

#21274 Convert validate_collect_running_processes to SupportsFeatureMixin syntax
  app/models/vm.rb
  app/models/vm/operations.rb
Labels: core/smart state, refactoring

#21279 Refactor MiqReport::Formats to remove the constants
  app/models/miq_report/formats.rb
  config/brakeman.ignore
Labels: core/security, refactoring

#21278 Convert Vm#validate_pause to SupportsFeatureMixin
  app/models/vm/operations/power.rb
Labels: refactoring

#21281 Improve the Spec::Support::EmsRefreshHelper
  spec/support/ems_refresh_helper.rb
Labels: enhancement, providers, test

#21259 Faster migrations
  lib/extensions/ar_migration.rb
Labels: performance, sql migration

#21273 Allow providers to override parsed_manager_name
  app/models/manageiq/providers/inventory.rb
Labels: enhancement, providers/inventory

#21271 Add rack-attack
  Gemfile
  config/initializers/rack_attack.rb
  config/settings.yml
  lib/vmdb/settings/validator.rb
  spec/lib/vmdb/settings/validator_spec.rb
Labels: dependencies

#21286 Publications better identify the replication_type
  app/models/miq_region.rb
  spec/models/miq_region_spec.rb
Labels: bug, core/replication

#21284 [EmbeddedAnsible::ConfigurationScriptSource] Add verify_ssl
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
Labels: core/embedded ansible, enhancement

#21182 Add new block storage capability
  app/models/ext_management_system.rb
Labels: enhancement, providers/storage

#21285 Add the progname to all loggers
  .rubocop_local.yml
  lib/vmdb/loggers.rb
  spec/lib/vmdb/loggers_spec.rb
Labels: enhancement

#21275 Convert Vm#validate_stop to SupportsFeatureMixin
  app/models/vm/operations/power.rb
Labels: providers, refactoring

#21291 Cascade pause! and resume! on all child_managers
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: enhancement

#21290 Remove unused VmOrTemplate#validate_scan
  app/models/vm_or_template/operations.rb
  app/models/vm_or_template/operations/smart_state.rb
Labels: core/smart state, technical debt

#21298 [EmbeddedAnsible::ConfigurationScriptSource] virtual_attribute :verify_ssl
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
Labels: core/embedded ansible

#21276 Queue provider pause with high priority before destroy
  app/models/ext_management_system.rb
  app/models/mixins/async_delete_mixin.rb
  spec/models/async_delete_mixin_spec.rb
  spec/models/ext_management_system_spec.rb
Labels: enhancement, providers

#21296 Allow providers to restart refresh worker when credentials or endpoint info changes
  app/models/ext_management_system.rb
Labels: bug, providers

#21303 Refactor delete subnet queue from providers
  app/models/cloud_subnet.rb
Labels: providers/network, refactoring

#21300 Dependent destroy child network_manager
  app/models/mixins/has_network_manager_mixin.rb
Labels: bug, providers

#21297 add missing view_data feature in miq_product_features yaml
  db/fixtures/miq_product_features.yml
Labels: bug, core/rbac, ui

#21226 update ancestry
  Gemfile
  app/models/mixins/relationship_mixin.rb
  spec/models/mixins/relationship_mixin_spec.rb
Labels: dependencies

#21289 Delete secrets.yml sample file
  config/secrets.yml.sample
Labels: cleanup, providers

#21306 adding shared processor and entitled processor fields in advanced setting for reporting.
  app/models/vm_or_template.rb
Labels: enhancement, providers

#21310 run basic services as manageiq user
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_event_catcher@.service
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_metrics_collector@.service
  lib/generators/manageiq/provider/templates/systemd/%plugin_name%_%manager_path%_refresh@.service
  systemd/manageiq-cockpit_ws@.service
  systemd/manageiq-ems_metrics_processor@.service
  systemd/manageiq-event_handler@.service
  systemd/manageiq-generic@.service
  systemd/manageiq-priority@.service
  systemd/manageiq-remote_console@.service
  systemd/manageiq-reporting@.service
  systemd/manageiq-schedule@.service
  systemd/manageiq-smart_proxy@.service
  systemd/manageiq-ui@.service
  systemd/manageiq-web_service@.service
Labels: enhancement

#21313 Refactor create cloud subnet queue from providers
  app/models/manageiq/providers/network_manager.rb
Labels: refactoring
