Repository ManageIQ/manageiq, pull requests merged in 2021-10, with the labels that each got.

#21458 Fix EvmRole-physical_storages_user role and EvmRole-physical_storages…
  db/fixtures/miq_user_roles.yml
Labels: bug, providers/storage, morphy/yes?

#21475 Add IBM Power HMC provider
  Gemfile
  spec/models/manageiq/providers/ems_infra_spec.rb
Labels: enhancement, dependencies, providers/virtual

#21477 Sort "Recently Discovered VMs" by discovery date
  product/reports/100_Configuration Management - Virtual Machines/070_Newest VMs.yaml
Labels: bug, morphy/yes?

#21457 Convert AuthKey operations to SupportsFeatureMixin
  app/models/ext_management_system.rb
  app/models/manageiq/providers/cloud_manager/auth_key_pair.rb
  app/models/manageiq/providers/cloud_manager/auth_key_pair/operations.rb
  spec/models/manageiq/providers/cloud_manager/auth_key_pair_spec.rb
Labels: technical debt

#21244 Fix missing routes in product.yaml
  db/fixtures/miq_product_features.yml
Labels: bug, lasker/yes?, morphy/yes?

#21470 Cleanup constantize of worker_class_names
  app/models/miq_server/worker_management/monitor.rb
  spec/models/miq_server/worker_management/monitor_spec.rb
  spec/models/miq_worker_type_spec.rb
Labels: technical debt, core

#21482 Add MiqWorkerType.worker_classes
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/settings.rb
  app/models/miq_server/worker_management/monitor/systemd.rb
  app/models/miq_worker_type.rb
  spec/models/miq_worker/systemd_common_spec.rb
Labels: refactoring, core

#21449 In containers, don't post process linking and copying
  Dockerfile
Labels: bug, build/podified

#21486 Fix Google factory ems_google_with_authentication missing_credentials?
  spec/factories/authentication.rb
  spec/factories/ext_management_system.rb
Labels: bug, test, morphy/yes
