Repository ManageIQ/manageiq, pull requests merged in 2021-07, with the labels that each got.

#21311 Fixed time profile days and hours fields for react form conversion
  app/models/time_profile.rb
  spec/models/time_profile_spec.rb
Labels: bug

#21315 Remove supports :migrate from base Vm class
  app/models/vm_or_template/operations/relocation.rb
Labels: bug, providers

#21316 Move profile= to live near the profile method
  app/models/time_profile.rb
Labels: cleanup

#21314 Prepend with_block, which was renamed from with_lock in Dalli 2.7.7
  lib/extensions/rack_session_dalli_patch.rb
  lib/manageiq/session.rb
Labels: bug, core

#21319 Remove autoload paths for code that was extracted to other repositories
  config/application.rb
Labels: technical debt

#21318 Add proper expectation stubs for slow MiqRegion.destroy_region
  spec/models/miq_region_spec.rb
  spec/models/pglogical_subscription_spec.rb
Labels: performance, test

#21292 Support local logical replication - Create the slot on the remote and the subscription on the global
  Gemfile
  app/models/miq_region.rb
  app/models/pglogical_subscription.rb
  lib/miq_pglogical.rb
  spec/models/pglogical_subscription_spec.rb
Labels: dependencies

#21322 Logical replication cleanup (use 1.2 with simpler interface)
  Gemfile
  app/models/pglogical_subscription.rb
  lib/tasks/evm_dbsync.rake
  spec/models/pglogical_subscription_spec.rb
Labels: core/replication, dependencies, enhancement

#21293 Remove progname override from audit log
  lib/vmdb/loggers/audit_logger.rb
Labels: technical debt

#21328 [KASPAROV] Handle brakeman failure by making method private
  tools/radar/rollup_radar_mixin.rb
Labels: bug, core/security

#21308 Add alias for flavor cpus and cpu_cores
  app/models/flavor.rb
Labels: refactoring

#21330 [Kasparov] update mimemagic
  Gemfile.lock.release
Labels: bug, dependencies

#21332 Add virtual_column for Flavor cpus/cpu_cores
  app/models/flavor.rb
Labels: bug, providers

#21241 [MiqSet] Rework to use miq_set_memberships
  app/models/miq_set_membership.rb
  app/models/mixins/custom_actions_mixin.rb
  app/models/mixins/relationship_mixin.rb
  lib/extensions/ar_miq_set.rb
  lib/task_helpers/exports/custom_buttons.rb
  spec/models/miq_event_definition_spec.rb
  spec/models/mixins/relationship_mixin_spec.rb
  spec/models/service_template_spec.rb
Labels: refactoring

#21336 [LASKER] Add Gemfile.lock from lasker-1 build
  Gemfile.lock.release
Labels: dependencies, enhancement

#21331 Remove psych now that ruby 2.6 is the min supported
  Gemfile
Labels: dependencies, technical debt

#21334 Updates for VMwareWebService 3.0
  Gemfile
  tools/list_evm_snapshots.rb
  tools/rm_evm_snapshots.rb
  tools/vim_collect_inventory.rb
  tools/vim_collect_perf_history.rb
Labels: dependencies, providers

#21335 [TokenStore] Use ActiveSupport::Cache::MemCacheStore
  lib/token_store.rb
Labels: enhancement

#21337 [JANSA] Fix jansa gemfile lock
  Gemfile.lock.release
Labels: bug

#21338 Restore log/.gitkeep
  lib/manageiq/environment.rb
  log/.gitkeep
Labels: technical debt

#21325 Declare httpd a requirement dependency of UI and API workers
  app/models/miq_server/environment_management.rb
  app/models/miq_server/role_management.rb
  app/models/miq_server/worker_management/monitor.rb
  spec/models/miq_server/role_management_spec.rb
  systemd/manageiq-cockpit_ws@.service
  systemd/manageiq-remote_console@.service
  systemd/manageiq-ui@.service
  systemd/manageiq-web_service@.service
Labels: appliance/workers, technical debt

#21333 Split 'ibm' vendor into 'ibm_cloud' and 'ibm_power_vc'
  app/models/vm_or_template.rb
Labels: providers/cloud, technical debt

#21146 Remove watchdog update management
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  app/models/miq_server.rb
  app/models/miq_server/update_management.rb
  config/settings.yml
  spec/models/miq_schedule_worker/runner_spec.rb
  spec/models/miq_server/update_management_spec.rb
Labels: cleanup

#21329 Add logical replication setup rake task
  lib/task_helpers/development/replication.rb
  lib/tasks/development_replication.rake
Labels: enhancement, tools

#21264 Allow kafka to be used for EmsEvents
  app/models/ems_event.rb
  app/models/miq_event_handler.rb
  app/models/miq_event_handler/runner.rb
  app/models/miq_queue_worker_base.rb
  app/models/miq_queue_worker_base/runner.rb
  spec/models/ems_event_spec.rb
Labels: enhancement

#21342 Add jpeg Extension to picture.rb
  app/models/picture.rb
  spec/models/picture_spec.rb
Labels: enhancement

#21347 Add MiqExpression#data_for_expression to support brakeman refactoring
  app/models/miq_ae_method.rb
  spec/models/miq_ae_method_spec.rb
Labels: lasker/yes?, refactoring

#21348 Add Product Features for Cloud Databases
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/cloud

#21349 Add more comprehensive brakeman coverage across all plugins
  config/brakeman.yml
  lib/tasks/test_security.rake
  lib/vmdb/global_methods.rb
  lib/vmdb/plugins.rb
Labels: core/security, enhancement

#21352 Add SKIP_UI_UPDATE option to bin/setup and bin/update
  bin/setup
  bin/update
  lib/manageiq/environment.rb
Labels: enhancement, lasker/yes?

#21353 Rename bundler_audit task to bundle_audit
  lib/tasks/test_security.rake
Labels: cleanup, lasker/yes?

#21354 Add more logging during test:security
  lib/tasks/test_security.rake
Labels: enhancement, lasker/yes?

#21356 Minor typos and output cleanup
  app/models/miq_queue.rb
  app/models/mixins/process_tasks_mixin.rb
  spec/models/miq_queue_spec.rb
  spec/models/mixins/process_tasks_mixin_spec.rb
Labels: cleanup
