Repository ManageIQ/manageiq, pull requests merged in 2022-09, with the labels that each got.

#22094 Use rails 6.1 friendly appliance console
  Gemfile
Labels: bug, rails6.1, oparin/yes?

#22095 [OPARIN] Bump manageiq-appliance_console to 7.1.1
  Gemfile.lock.release
Labels: dependencies

#22093 Update inventory_refresh
  Gemfile
  spec/models/manageiq/providers/inventory/persister/finders_spec.rb
Labels: dependencies, providers/inventory

#22100 Move provider cloud network factories out of core
  spec/factories/cloud_network.rb
  spec/factories/ext_management_system.rb
Labels: refactoring, test

#22082 GitHub Workflows security hardening
  .github/workflows/ci.yaml
Labels: test

#22106 Don't wait so long for primary/standby info and changes
  config/ha_admin.yml
Labels: enhancement, oparin/yes?

#22112 Use `unbundled_exec` when starting provider workers
  lib/workers/bin/provider_worker
Labels: bug

#22110 Add pluggable notification_types
  app/models/notification_type.rb
Labels: enhancement, providers, pluggability/providers

#21531 Support ruby 3
  .github/workflows/ci.yaml
  Gemfile
  spec/lib/acts_as_ar_model_spec.rb
  spec/lib/rbac/filterer_spec.rb
  spec/models/authenticator/database_spec.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/authenticator/ldap_spec.rb
  spec/models/firmware_registry_spec.rb
  spec/models/manageiq/providers/inventory/persister/local_db_finders_spec.rb
  spec/models/miq_provision_configured_system_request_spec.rb
  spec/models/miq_provision_spec.rb
  spec/models/mixins/per_ems_worker_mixin_spec.rb
  spec/models/orchestration_stack/retirement_management_spec.rb
  spec/models/physical_server_provision_request_spec.rb
  spec/models/resource_action_workflow_spec.rb
  spec/models/service/retirement_management_spec.rb
  spec/models/service_spec.rb
  spec/models/service_template_provision_task_spec.rb
  spec/models/service_template_spec.rb
  spec/models/vm/retirement_management_spec.rb
  spec/models/vm_or_template/operations/configuration_spec.rb
  spec/tools/fix_auth/fix_auth_spec.rb
Labels: dependencies, core, ruby3

#22114 Allow run_single_worker to start non-rails workers
  app/models/miq_worker.rb
  app/models/miq_worker/runner.rb
  lib/workers/bin/provider_worker
Labels: enhancement, core/workers

#22127 Identify RHCOS as 'linux_coreos' operating system
  app/models/operating_system.rb
  spec/models/operating_system_spec.rb
Labels: enhancement, providers

#22116 Call after_failover hook on successful failover, rely on manageiq-db-ready to restart services
  Gemfile
  lib/evm_database.rb
Labels: bug, dependencies, core, oparin/yes?

#22131 [OPARIN] Bump ibm_power_hmc and manageiq-postgres_has_admin gems
  Gemfile.lock.release
Labels: dependencies
