Repository ManageIQ/manageiq, pull requests merged in 2022-06, with the labels that each got.

#21899 Updated translations from June 1st
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: internationalization, najdorf/yes?

#21839 Features changes to support service de-explorization
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement

#21891 Delete AvailabilityMixin
  app/models/cloud_volume.rb
  app/models/ext_management_system.rb
  app/models/host.rb
  app/models/manageiq/providers/container_manager.rb
  app/models/manageiq/providers/infra_manager.rb
  app/models/mixins/availability_mixin.rb
  app/models/mixins/supports_feature_mixin.rb
  app/models/physical_server.rb
  app/models/storage.rb
  app/models/vm_or_template.rb
  spec/models/mixins/availability_mixin_spec.rb
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: refactoring

#21912 Host supports starting from standby
  app/models/host.rb
  spec/models/host_spec.rb
Labels: bug, providers/virtual

#21914 [NAJDORF] Update rack gem due to backport of #21887
  Gemfile.lock.release
Labels: dependencies

#21915 Replace Host#validate_ipmi with SupportsFeature
  app/models/host.rb
  spec/models/host_spec.rb
Labels: refactoring, providers

#21922 Fix Host calling run_ipmi_command before supports check
  app/models/host.rb
  spec/models/host_spec.rb
Labels: bug, providers/virtual

#21926 Translations for defect fixing string June 7
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: bug, internationalization

#21921 Alert profile length
  app/models/miq_alert.rb
Labels: bug, core

#21909 Add conditions to display Host CPU performance charts
  app/models/host.rb
  product/charts/layouts/daily_perf_charts/Host.yaml
  product/charts/layouts/hourly_perf_charts/Host.yaml
  product/charts/layouts/realtime_perf_charts/Host.yaml
Labels: enhancement, providers/metrics

#21930 Updated english pot and po after UI PR 8293
  locale/en/manageiq.po
  locale/manageiq.pot
Labels: bug, internationalization, najdorf/yes?

#21927 Fixed machine credentials console errors
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
Labels: bug, core/embedded ansible

#21902 condense supports and logging in host
  app/models/host.rb
Labels: refactoring

#21882 implemented validation storage system button
  app/models/physical_storage.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement

#21923 Add cloud volume clone feature
  app/models/cloud_volume.rb
  app/models/cloud_volume/operations.rb
  app/models/vm_or_template/operations/configuration.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/cloud

#21924 Fix machine credentials privilege escalation field
  app/models/manageiq/providers/embedded_ansible/automation_manager/machine_credential.rb
Labels: bug, core/embedded ansible

#21940 Update po and pot after ManageIQ/manageiq-ui-classic#8313
  locale/en/manageiq.po
  locale/manageiq.pot
Labels: bug, internationalization, najdorf/yes?

#21952 Lock down pg until 1.4.x is released
  Gemfile
Labels: dependencies

#21955 add supports_cloud_database
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: enhancement, core

#21948 Invoke the locale plugin rake tasks directly
  lib/tasks/locale.rake
Labels: performance, internationalization

#21953 Unlock the pg gem since 1.4.1 was released
  Gemfile
Labels: dependencies, najdorf/yes?

#21956 Bump master minimum pg to the latest
  Gemfile
Labels: dependencies

#21954 Add javascript boilerplate code to plugin generator
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/.yarn/releases/yarn-3.0.2.cjs
  lib/generators/manageiq/plugin/templates/.yarnrc.yml
  lib/generators/manageiq/plugin/templates/package.json
  lib/generators/manageiq/plugin/templates/yarn.lock
Labels: enhancement, dependencies, developer

#21964 convert external_logging to simple supports type
  app/models/container_node.rb
  app/models/manageiq/providers/container_manager.rb
Labels: refactoring, providers/containers

#21951 supports_not for new physical storage method (validate)
  app/models/physical_storage.rb
Labels: enhancement, providers/storage

#21967 Clear token store in tests
  spec/support/evm_spec_helper.rb
Labels: bug/sporadic test failure
