Repository ManageIQ/manageiq, pull requests merged in 2022-01, with the labels that each got.

#21638 Fix copyright year in locale files
  locale/de.yml
  locale/en.yml
  locale/es.yml
  locale/fr.yml
  locale/it.yml
  locale/ja.yml
  locale/ko.yml
  locale/pt_BR.yml
  locale/zh_CN.yml
  locale/zh_TW.yml
Labels: bug, test

#21637 Add missing cloud collections used by OpenStack
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
Labels: enhancement, providers/inventory

#21642 Fix supports?(:refresh_ems) after mixin refactoring
  app/models/mixins/ems_refresh_mixin.rb
Labels: bug

#21643 Fix global not initialized warning
  app/models/miq_queue.rb
Labels: technical debt, core/queue

#21645 Fix docs link for physical infra providers
  config/settings.yml
Labels: bug

#21646 Prevent vmdb/plugins_spec from hanging if git tag defaults to sign
  spec/lib/vmdb/plugins_spec.rb
Labels: bug, test

#21651 Require rails 6.0.4.2+ for CVE-2021-44528
  Gemfile
Labels: core/security, morphy/yes?

#21644 Remove references to MiddlewareManager
  app/models/miq_region.rb
  app/models/zone.rb
Labels: technical debt

#21658 Add whitesource config
  .whitesource
Labels: test

#21654 Add a common cross_link_vms inventory collection
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
Labels: enhancement, providers/inventory

#21597 Raise if model has sti but using base class
  app/models/application_record.rb
  app/models/manageiq/providers/inventory/persister/builder.rb
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/physical_infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/provisioning_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
  app/models/manageiq/providers/inventory/persister/builder/storage_manager.rb
  spec/models/manageiq/providers/inventory/persister/builder_spec.rb
  spec/models/manageiq/providers/inventory/persister/local_db_finders_spec.rb
  spec/models/manageiq/providers/inventory/persister/test_persister.rb
  spec/support/ems_refresh_helper/test_persister.rb
Labels: enhancement, providers/inventory

#21661 Fix release task to revert the Gemfile.lock.release as well
  lib/tasks/release.rake
Labels: bug, build, morphy/yes

#21662 [MORPHY] Update lockfile
  Gemfile.lock.release
Labels: dependencies, build

#21664 Explain why we still need to autoload from yaml/marshal
  config/initializers/marshal_autoloader.rb
  config/initializers/yaml_autoloader.rb
Labels: technical debt, documentation, developer

#21665 Revert "Merge pull request #21640 from Autosde/host_initiator_ui"
  app/models/volume_mapping.rb
Labels: bug

#21666 Add ability to get the container orchestrator's pod
  lib/container_orchestrator.rb
  spec/lib/container_orchestrator_spec.rb
Labels: enhancement, core/pods

#21668 fix Host#host_hardware relation
  app/models/host.rb
Labels: rails6.1

#18355 make Field/Target consistent with get_col_info
  lib/miq_expression.rb
  lib/miq_expression/tag.rb
  lib/miq_expression/target.rb
  spec/lib/miq_expression/tag_spec.rb
  spec/lib/miq_expression_spec.rb
Labels: bug, core

#21670 Minor cleanup for consistency
  .whitesource
Labels: test, cleanup

#21672 Cleanup OperatingSystem model
  app/models/operating_system.rb
Labels: cleanup

#21673 Deployment is still "new_deployment" if the database isn't seeded
  lib/tasks/evm_application.rb
  spec/lib/tasks/evm_application_spec.rb
Labels: bug, morphy/yes?
