Repository ManageIQ/manageiq, pull requests merged in 2022-12, with the labels that each got.

#22262 Fix Ruby 3 issue with AnsiblePlaybookWorkflow
  app/models/manageiq/providers/ansible_playbook_workflow.rb
  spec/models/manageiq/providers/ansible_playbook_workflow_spec.rb
  spec/models/manageiq/providers/ansible_role_workflow_spec.rb
Labels: bug, core/embedded ansible, ruby3, oparin/yes

#22257 allow deletion of VMs in infra manager
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/virtual

#22265 [OPARIN] Update lockfile for dalli 3.2.3
  Gemfile.lock.release
Labels: dependencies

#22264 Fix Ruby3 issue in ansible runner
  lib/ansible/runner.rb
  lib/ansible/runner/response_async.rb
  spec/lib/ansible/runner/response_async_spec.rb
Labels: bug, core/embedded ansible, ruby3, oparin/yes

#22263 Physical infr button classes
  app/models/custom_button.rb
  app/models/physical_chassis.rb
  app/models/physical_rack.rb
  app/models/physical_server.rb
Labels: enhancement, providers/physical

#22191 No longer lookup zones for every MiqQueue.create
  app/models/miq_queue.rb
  spec/models/miq_queue_spec.rb
Labels: performance

#22268 Provide the now required response object to the smtp exception
  spec/mailers/generic_mailer_spec.rb
Labels: test, dependencies, oparin/yes?

#22234 Non rails worker settings
  app/models/miq_worker.rb
  app/models/miq_worker/runner.rb
  spec/models/miq_worker_spec.rb
Labels: enhancement, core/workers

#22258 consolidate supported storage types
  app/models/manageiq/providers/infra_manager/metrics_capture.rb
  app/models/storage.rb
  app/models/vm_or_template.rb
  app/models/vm_scan/dispatcher.rb
  spec/models/manageiq/providers/infra_manager/metrics_capture_spec.rb
  spec/models/storage_spec.rb
  spec/models/vm_scan/dispatcher_embedded_scan_spec.rb
  spec/models/vm_scan/dispatcher_spec.rb
  spec/models/vm_scan/dispatcher_vm_storage2proxies_spec.rb
  spec/support/job_proxy_dispatcher_helper.rb
Labels: refactoring, providers

#22267 add vm_terminate to EvmRole-operator
  db/fixtures/miq_user_roles.yml
Labels: enhancement

#22251 add customizable disk_size to vm post-provision
  app/models/manageiq/providers/infra_manager/provision_workflow.rb
  spec/models/miq_provision_workflow_spec.rb
Labels: enhancement, providers/virtual

#22273 set a valid Storage.store_type
  spec/factories/storage.rb
Labels: test, core/storage

#22239 Move IsoDatastore from core
  app/models/ext_management_system.rb
  app/models/iso_datastore.rb
  app/models/iso_image.rb
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/miq_request_workflow.rb
  app/models/storage.rb
  locale/en.yml
  spec/models/iso_datastore_spec.rb
Labels: enhancement, technical debt, pluggability/providers

#22272 Update tokens for build_monolith workflow
  .github/workflows/build_monolith.yaml
Labels: developer

#22227 Add github action PR for locale:update_all
  .github/workflows/locale_update_all.yaml
Labels: internationalization, developer

#22277 [OPARIN] Update nokogiri to 1.13.10
  Gemfile.lock.release
Labels: dependencies
