Repository ManageIQ/manageiq, pull requests merged in 2022-07, with the labels that each got.

#21968 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
  lib/generators/manageiq/plugin/templates/.github/workflows/ci.yaml
Labels: developer

#21969 Translations for defect fixing string June31
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: bug, internationalization, ui

#21974 Including AsyncDeleteMixin
  app/models/cloud_database.rb
Labels: bug, providers/cloud

#21976 drop running tests in parallel
  Gemfile
  config/database.pg.yml
  lib/tasks/test_vmdb.rake
Labels: test, dependencies

#21978 fix incorrect translation in defect #29721
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
Labels: bug, internationalization, najdorf/yes?

#21986 Fix wwpn_candidate ext_management_system foreign_key
  app/models/wwpn_candidate.rb
Labels: bug, providers/inventory

#21980 Add miq_scsi_(targets,luns) to base InfraManager
  app/models/manageiq/providers/infra_manager.rb
Labels: enhancement, providers/virtual

#21656 Use persister directly in Builder class
  app/models/manageiq/providers/inventory/persister/builder.rb
  app/models/manageiq/providers/inventory/persister/builder/automation_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/configuration_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/network_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/persister_helper.rb
  app/models/manageiq/providers/inventory/persister/builder/physical_infra_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/provisioning_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/shared.rb
  spec/models/manageiq/providers/inventory/persister/builder_spec.rb
  spec/models/manageiq/providers/inventory/persister/local_db_finders_spec.rb
Labels: enhancement, refactoring, providers/inventory

#21988 Use yaml_unsafe_load to handle symbols
  Gemfile
  config/application.rb
Labels: bug, dependencies

#21995 resolved product name translation issue
  locale/zh_TW.yml
Labels: bug, internationalization, najdorf/yes?

#21996 Lockdown rugged to prior to v1.4.2 for ssh support
  Gemfile
Labels: bug, dependencies

#21977 Add cloud database server model
  app/models/cloud_database.rb
  app/models/cloud_database_server.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb
Labels: enhancement, providers/inventory

#21961 Move vmware Host power_state logic to vmware
  app/models/host.rb
Labels: refactoring

#21998 Migrate and seed db from plugin bin/update
  lib/manageiq/environment.rb
Labels: enhancement, developer

#21942 Add tool to unjson the podified logs
  tools/unjson_logs
Labels: enhancement, tools

#21991 convert from AvailabilityMixin to SupportsFeatureMixin
  app/models/host.rb
  app/models/manageiq/providers/cloud_manager.rb
  app/models/manageiq/providers/cloud_manager/template.rb
  app/models/manageiq/providers/container_manager.rb
  app/models/manageiq/providers/infra_manager.rb
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/physical_storage.rb
  app/models/vm_or_template/operations.rb
Labels: technical debt

#21982 Remove tasks that trigger a different test environment
  .github/workflows/ci.yaml
  lib/tasks/test_vmdb.rake
Labels: technical debt, test

#21981 use REGION env to set the db region
  lib/tasks/evm_dba.rake
Labels: enhancement, appliance/console

#22003 Undo complicated rake tasks no longer needed
  lib/tasks/evm_dba.rake
  lib/tasks/test.rake
Labels: technical debt

#22006 Bump rugged to v1.5.0 for ssh build support
  Gemfile
Labels: dependencies, core, najdorf/yes?

#21721 Move appliance dependencies into core Gemfile
  Gemfile
  lib/tasks/release.rake
Labels: technical debt, dependencies

#21917 Expand Supports syntax (part deux)
  app/models/host.rb
  app/models/metric/ci_mixin.rb
  app/models/mixins/compliance_mixin.rb
  app/models/mixins/supports_feature_mixin.rb
  app/models/service.rb
  app/models/service_template.rb
  app/models/storage.rb
  app/models/vm/operations.rb
  app/models/vm/operations/lifecycle.rb
  app/models/vm/operations/power.rb
  app/models/vm_or_template.rb
  app/models/vm_or_template/operations.rb
  app/models/vm_or_template/operations/snapshot.rb
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: enhancement, core/rbac

#22011 Add an active scope to CloudDatabaseFlavor
  app/models/cloud_database_flavor.rb
Labels: enhancement, providers/cloud

#22013 Don't memoize a class ivar containing a translation
  app/models/chargeback_container_image.rb
Labels: bug, internationalization, najdorf/yes?

#22014 Updated master branch English po/pot
  locale/en/manageiq.po
  locale/manageiq.pot
Labels: internationalization, najdorf/yes?

#22015 This hasn't been used in a long time ✂️ 🔥 🚽
  lib/patches/memcache_patch.rb
Labels: cleanup

#21698 Add RHV provider plugin
  Gemfile
  app/models/ext_management_system.rb
  app/models/host.rb
  app/models/iso_datastore.rb
  app/models/vm_or_template.rb
  spec/models/miq_provision_workflow_spec.rb
  spec/support/examples_group/shared_examples_for_provisioning_state_machine.rb
Labels: enhancement, dependencies, providers

#22008 display events for physical storage
  app/models/ems_event.rb
  app/models/event_stream.rb
  app/models/physical_storage.rb
  db/fixtures/miq_product_features.yml
  spec/factories/physical_storage.rb
  spec/models/ems_event_spec.rb
Labels: enhancement, providers/physical

#22019 Fix RBAC for Folders (descendent of VMs)
  app/models/entitlement.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, core/rbac, rails6.1

#22023 fix for physical storage monitoring page
  app/models/physical_storage.rb
Labels: bug, core/events, providers/storage
