Repository ManageIQ/manageiq, pull requests merged in 2022-02, with the labels that each got.

#21676 Remove Hakiri
  README.md
Labels: cleanup, developer

#21677 Remove Hakiri from plugin generator
  lib/generators/manageiq/plugin/templates/README.md
Labels: cleanup, developer

#21675 Update lockfile for oci gem
  Gemfile.lock.release
Labels: dependencies

#21674 add supports :create for scripts
  app/models/authentication.rb
  app/models/configuration_script_base.rb
  app/models/configuration_script_source.rb
  app/models/manageiq/providers/cloud_manager/auth_key_pair.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
Labels: enhancement, providers/automation, core/embedded ansible

#21682 Support GitHub Actions
  Gemfile
  lib/manageiq/environment.rb
  spec/spec_helper.rb
Labels: dependencies

#21683 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .gitignore
  .travis.yml
  README.md
  app/models/openscap_result.rb
  bin/before_install
  bin/ci/after_failure.sh
  bin/ci/before_install.rb
  bin/ci/before_install.sh
  bin/ci/before_script.sh
  bin/setup
  lib/manageiq/environment.rb
  spec/models/miq_database_spec.rb
  spec/spec_helper.rb
Labels: test, developer

#21685 Fix dependabot PRs made in the core/plugin repos
  bin/before_install
  lib/manageiq/environment.rb
Labels: bug, test

#21399 [BinaryBlob::Purging] Use created_at column
  app/models/binary_blob/purging.rb
  app/models/mixins/purging_mixin.rb
  config/settings.yml
  spec/models/binary_blob/purging_spec.rb
Labels: bug

#21690 fix_auth: bring back foreign key for ae model
  tools/fix_auth/models.rb
Labels: rails6.1

#21686 Update i18n message catalog
  locale/manageiq.pot
Labels: internationalization

#21697 Fix class_for_platform method
  app/models/miq_provision_workflow.rb
Labels: enhancement, providers, lifecycle/provisioning

#21694 Add oVirt factories and vendors
  app/models/host.rb
  app/models/vm_or_template.rb
  lib/manageiq/network_discovery/discovery.rb
  spec/factories/ext_management_system.rb
  spec/factories/host.rb
  spec/factories/miq_request_task.rb
  spec/factories/vm_or_template.rb
Labels: enhancement, providers

#21701 Fix IBM Power HMC vendor type
  app/models/vm_or_template.rb
Labels: bug, providers/virtual

#21706 Fix monolithic docker image README
  docker-assets/README.md
  lib/tasks/release.rake
Labels: documentation, build/docker

#21702 Explicitly set log file owner/permissions
  lib/miq_environment.rb
  lib/vmdb/loggers.rb
Labels: bug, appliance, core, najdorf/yes

#21707 [NAJDORF] Add initial Gemfile.lock.release
  Gemfile.lock.release
  bin/before_install
  lib/manageiq/environment.rb
  lib/tasks/release.rake
Labels: dependencies

#21711 Don't modify perms of log files on podified
  lib/vmdb/loggers.rb
Labels: bug, najdorf/yes?

#21713 Update to 6.0.4.6 for GHSA-wh98-p28r-vrc9 fix
  Gemfile
Labels: dependencies, rails6, morphy/yes?, security fix, najdorf/yes?

#21720 Bump fog kubevirt
  Gemfile.lock.release
Labels: dependencies

#21723 Require container_orchestrator for is_podified? check
  lib/miq_environment.rb
Labels: bug, najdorf/yes

#21724 Fix log file stat group check
  lib/vmdb/loggers.rb
  spec/lib/vmdb/loggers_spec.rb
Labels: bug, najdorf/yes

#21679 Remove #check_not_responding from common worker management
  app/models/miq_server/worker_management/monitor/quiesce.rb
  app/models/miq_server/worker_management/process.rb
  spec/models/miq_server_spec.rb
Labels: bug, morphy/yes?, najdorf/yes?

#21727 Don't call ContainerOrchestrator from MiqEnvironment
  lib/miq_environment.rb
  spec/lib/miq_environment_spec.rb
Labels: bug, najdorf/yes

#21726 Supports feature for iso_datastore
  app/models/ext_management_system.rb
Labels: enhancement, providers

#21728 Change documentation default target to new window
  config/settings.yml
Labels: bug, najdorf/yes?

#21718 Fix BinaryBlob purge_date exception
  app/models/binary_blob/purging.rb
  spec/models/binary_blob/purging_spec.rb
Labels: bug, najdorf/yes?

#21729 Update Model.supporting(feature) to check instances
  app/models/mixins/supports_feature_mixin.rb
  app/models/zone.rb
Labels: enhancement

#21730 limit length of User#userid and email
  app/models/user.rb
Labels: enhancement, morphy/yes?, najdorf/yes?

#21731 [Morphy] Properly purge StateVar Hash
  app/models/binary_blob/purging.rb
  app/models/mixins/purging_mixin.rb
  config/settings.yml
  spec/models/binary_blob/purging_spec.rb
Labels: enhancement

#21733 [NAJDORF] Bump ibm_power_hmc and rails gems
  Gemfile.lock.release
Labels: dependencies

#21681 Service request connected to Automation request
  app/models/automation_task.rb
  app/models/miq_request.rb
  app/models/service_template.rb
  spec/models/service_template_spec.rb
Labels: enhancement

#21736 Bump inventory_refresh to ~> 1.0
  Gemfile
Labels: dependencies, providers/inventory, najdorf/no

#21691 No longer delete dialog_tabs errors
  app/models/dialog.rb
  app/models/dialog_tab.rb
Labels: bug, ui, rails6.1

#21693 fix default_value_for(alias)
  app/models/miq_provision_request.rb
Labels: bug, rails6.1

#21737 Fix eligible_for_provisioning calling active on Array
  app/models/miq_template.rb
  spec/models/miq_template_spec.rb
Labels: bug

#21741 Provide a better error message for missing report file
  app/models/miq_report/import_export.rb
  spec/models/miq_report/import_export_spec.rb
Labels: bug

#21742 [MORPHY] Update lockfile for Rails 6.0.4.6
  Gemfile.lock.release
Labels: dependencies

#21709 Run CI daily
  .github/workflows/ci.yaml
Labels: test

#21744 Enable C&U worker roles by default
  config/settings.yml
Labels: enhancement, providers/metrics

#21748 Make dalli clients threadsafe, use a pool for session/token store
  lib/manageiq/session/mem_cache_store_adapter.rb
  lib/miq_memcached.rb
  lib/token_store.rb
Labels: bug, najdorf/yes?
