Repository ManageIQ/manageiq, pull requests merged in 2022-10, with the labels that each got.

#22138 Allow a Proc for self.rails_worker
  app/models/miq_worker.rb
Labels: enhancement, core/workers

#21177 Stop logging to files in production deployments
  lib/vmdb/loggers.rb
  spec/lib/vmdb/loggers_spec.rb
Labels: enhancement

#22113 manageiq-messaging-ready systemd support
  spec/models/miq_worker/systemd_common_spec.rb
  systemd/manageiq-messaging-ready.service
Labels: enhancement, core/workers

#22150 Fix call_automate_event argument error during provisioning
  app/models/mixins/miq_provision_mixin.rb
Labels: bug, lifecycle/provisioning, ruby3

#22151 Remove ANSIBLE_STDOUT_CALLBACK env var
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: bug

#22152 Fix rails_worker not defaulting to true in child classes
  app/models/miq_worker.rb
  spec/models/miq_worker_spec.rb
  spec/support/evm_spec_helper.rb
Labels: bug, core/workers

#22156 Update placement_group product view feature
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_shortcuts.yml
Labels: enhancement, providers

#22162 Raise an error on page load if dev and pending migrations
  config/environments/development.rb
Labels: enhancement, developer

#22161 Prevent deletion of widgets currently in a dashboard
  app/models/miq_widget.rb
  app/models/miq_widget_set/set_data.rb
  spec/models/miq_widget_spec.rb
Labels: bug, core, oparin/yes?

#22169 Remove 'placement_group' from advanced settings
  app/models/vm_or_template.rb
Labels: cleanup, providers

#22168 October 13 english translations
  locale/en/manageiq.po
  locale/manageiq.pot
Labels: internationalization

#22139 Helper method for MiqQueue.deliver and delivered duo
  app/models/miq_queue.rb
  lib/vmdb/console_methods.rb
  spec/models/async_delete_mixin_spec.rb
  spec/models/ext_management_system_spec.rb
  spec/models/host_spec.rb
  spec/models/job_spec.rb
  spec/models/log_file_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
  spec/models/miq_alert_spec.rb
  spec/models/miq_widget_spec.rb
  spec/models/mixins/authentication_mixin_spec.rb
  spec/models/vm/retirement_management_spec.rb
  spec/models/vm_scan_spec.rb
  spec/models/vm_spec.rb
Labels: test, core/embedded ansible

#22122 Refactoring vm resize option to work with DDF
  app/models/manageiq/providers/cloud_manager/vm.rb
  app/models/vm_cloud_reconfigure_task.rb
  db/fixtures/miq_product_features.yml
  spec/models/vm_cloud_reconfigure_request_spec.rb
Labels: enhancement, providers/cloud

#22167 Handle subscribing to a topic before creation
  Gemfile
Labels: bug, dependencies, core/queue

#22171 Store all messaging options in the messaging.yml file
  app/models/miq_queue.rb
  config/messaging.artemis.yml
  config/messaging.kafka.yml
  spec/models/miq_queue_spec.rb
Labels: enhancement, core/queue

#22184 Create MiqRegion for all tests
  spec/lib/extensions/ar_migration_spec.rb
  spec/lib/extensions/ar_region_spec.rb
  spec/lib/vmdb/settings_spec.rb
  spec/mailers/generic_mailer_spec.rb
  spec/models/automation_request_spec.rb
  spec/models/blacklisted_event_spec.rb
  spec/models/chargeback_configured_system_spec.rb
  spec/models/chargeback_container_image_spec.rb
  spec/models/chargeback_container_project_spec.rb
  spec/models/chargeback_vm/ongoing_time_period_spec.rb
  spec/models/chargeback_vm_spec.rb
  spec/models/custom_button_spec.rb
  spec/models/ext_management_system_spec.rb
  spec/models/file_depot_ftp_spec.rb
  spec/models/host_spec.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/job_spec.rb
  spec/models/manageiq/providers/embedded_ansible/provider_spec.rb
  spec/models/manageiq/providers/infra_manager/metrics_capture_spec.rb
  spec/models/metering_container_image_spec.rb
  spec/models/metering_container_project_spec.rb
  spec/models/metering_vm_spec.rb
  spec/models/metric/capture_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
  spec/models/metric/finders_spec.rb
  spec/models/metric_rollup/chargeback_helper_spec.rb
  spec/models/metric_spec.rb
  spec/models/miq_action_spec.rb
  spec/models/miq_compare_spec.rb
  spec/models/miq_enterprise_spec.rb
  spec/models/miq_product_feature_spec.rb
  spec/models/miq_provision_request_template_spec.rb
  spec/models/miq_queue_spec.rb
  spec/models/miq_region_spec.rb
  spec/models/miq_report_spec.rb
  spec/models/miq_request_task/post_install_callback_spec.rb
  spec/models/miq_schedule_worker/runner_spec.rb
  spec/models/miq_server/at_startup_spec.rb
  spec/models/miq_server/log_management_spec.rb
  spec/models/miq_server/role_management_spec.rb
  spec/models/miq_server/server_monitor_spec.rb
  spec/models/miq_server_spec.rb
  spec/models/orchestration_stack_retire_task_spec.rb
  spec/models/server_role_spec.rb
  spec/models/service_retire_task_spec.rb
  spec/models/tenant_spec.rb
  spec/models/vim_performance_analysis_spec.rb
  spec/models/vm_retire_task_spec.rb
  spec/models/zone_spec.rb
  spec/spec_helper.rb
Labels: test, core/embedded ansible

#22183 Bump manageiq-appliance_console to 8.0
  Gemfile
Labels: enhancement, dependencies

#22188 Add messaging-ready to evmserverd.service
  systemd/evmserverd.service
Labels: enhancement, core

#21997 Default to miq_messaging for event_handler
  app/models/ems_event.rb
  app/models/miq_queue.rb
  app/models/miq_queue_worker_base/runner.rb
  config/settings.yml
  spec/models/ems_event_spec.rb
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: enhancement, unmergeable

#22180 Translations for October 13 English po file #22168
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: enhancement, internationalization

#22193 Disable syndication of inventory/events/metrics by default now that we use kafka internally
  config/settings.yml
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: bug

#22198 Add a Settings.messaging config section
  app/models/miq_queue.rb
  config/settings.yml
  spec/models/ems_event_spec.rb
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: enhancement, core

#22204 October 27th rake locale:update_all English catalogs
  locale/en/manageiq.po
  locale/manageiq.pot
Labels: internationalization

#22199 Perf capture - better VimPerformanceState lookups
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/ci_mixin/capture.rb
  app/models/metric/ci_mixin/processing.rb
  app/models/metric/ci_mixin/state_finders.rb
  app/models/vim_performance_state.rb
Labels: enhancement, providers/metrics

#22175 Metrics C&U: Introduce batches
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/ci_mixin/capture.rb
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
  spec/support/metric_helper.rb
Labels: enhancement, performance, providers/metrics

#22197 Set auth_uri/token_uri in google_credential
  lib/ansible/runner/credential/google_credential.rb
  spec/lib/ansible/runner/credential/google_credential_spec.rb
Labels: bug, core/embedded ansible

#22187 Fix monolithic container HTTP config
  Dockerfile
  container-assets/README.md
  container-assets/entrypoint
Labels: bug, najdorf/yes?, oparin/yes?
