Repository ManageIQ/manageiq, pull requests merged in 2022-03, with the labels that each got.

#21746 for specs, ensure is_appliance is not cached
  lib/miq_environment.rb
Labels: test, bug/sporadic test failure

#21749 Add IBM PowerVS vendor type to support new icon
  app/models/vm_or_template.rb
Labels: enhancement, providers/cloud

#21751 Fix vendor/ engine paths requested but still excluded in brakeman 5.0+
  lib/extensions/brakeman_excludes_patch.rb
  lib/tasks/test_security.rake
Labels: bug, core/security, najdorf/yes?

#21754 Check if a storage has an EMS before checking authentication
  app/models/storage.rb
Labels: bug, providers/virtual, najdorf/yes?

#21755 Fix Storage#vm_ids_by_path when scanning a storage with no hosts mapped
  app/models/storage.rb
Labels: bug, providers/virtual, najdorf/yes?

#21739 use standard id_in_region in specs
  spec/models/time_profile_spec.rb
Labels: technical debt, test

#21758 set vmdb_session to samesite
  lib/manageiq/session/abstract_store_adapter.rb
Labels: bug

#21756 [NAJDORF] Update more_core_extensions and manageiq-appliance_console
  Gemfile.lock.release
Labels: dependencies

#21752 Remove Image Right-Size and Reconfigure Identifiers
  db/fixtures/miq_product_features.yml
Labels: bug, najdorf/yes?

#21759 AuthKeyPair.raw_create_key_pair should return a hash
  app/models/manageiq/providers/cloud_manager/auth_key_pair.rb
Labels: bug

#21763 [NAJDORF] Update lockfile for ibm_power_hmc 0.8.7
  Gemfile.lock.release
Labels: dependencies

#21764 Bump worker count of UI and API to 2
  config/settings.yml
  spec/models/miq_ui_worker_spec.rb
  spec/models/miq_web_service_worker_spec.rb
Labels: enhancement, najdorf/yes?

#21766 Switch service workers to probing /ping for liveness and readiness
  app/models/miq_worker/service_worker.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: enhancement

#21768 [NAJDORF] Bump ibm_cloud_activity_tracker gem to v0.1.1
  Gemfile.lock.release
Labels: dependencies

#21767 Use autoload for RipperRubyParser
  lib/extensions/descendant_loader.rb
Labels: performance

#21769 Translations provided on 2022-03-09
  locale/de/manageiq.po
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/manageiq.pot
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization, najdorf/yes?

#21773 Manual Fixes for ManageIQ/manageiq#21769
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
  spec/i18n/msgfmt_spec.rb
Labels: bug, internationalization, najdorf/yes

#21775 Add gettext to CI for msgfmt tests
  bin/before_install
Labels: test, najdorf/yes?

#21779 Check Msgfmt headers at PR time
  locale/en/manageiq.po
  spec/i18n/msgfmt_spec.rb
Labels: bug, najdorf/yes?

#21732 Extract remove_worker logic from MiqServer
  app/models/miq_server/worker_management.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/kill.rb
  app/models/miq_server/worker_management/monitor/quiesce.rb
  app/models/miq_server/worker_management/monitor/stop.rb
  app/models/miq_server/worker_management/process.rb
  app/models/miq_worker.rb
Labels: enhancement, lifecycle/orchestration

#21745 Use standard errors#add_error interface
  app/models/asset_tag_import.rb
  app/models/classification_import.rb
  app/models/generic_object_definition.rb
  app/models/orchestration_template.rb
  app/models/service_template_ansible_playbook.rb
  spec/models/chargeback_rate_detail_spec.rb
  spec/models/chargeback_rate_spec.rb
  spec/models/miq_bulk_import_spec.rb
  spec/models/miq_policy_spec.rb
  spec/models/miq_widget_set_spec.rb
Labels: enhancement, rails6.1

#21780 Add `supports?(:events)` to ExtManagementSystem
  app/models/ext_management_system.rb
Labels: enhancement, providers, pluggability/providers

#21783 Drop log_decorator
  Gemfile
  lib/vmdb/loggers.rb
Labels: technical debt, dependencies

#21782 Add msg_timeout option to Job#queue_signal
  app/models/job/state_machine.rb
Labels: enhancement

#21778 console_url is now available on both Physical Infra and Cloud Providers
  app/models/configuration_profile.rb
  app/models/configured_system.rb
  app/models/manageiq/providers/base_manager.rb
  app/models/manageiq/providers/physical_infra_manager.rb
  db/fixtures/miq_product_features.yml
  spec/models/manageiq/providers/physical_infra_manager/physical_infra_manager_spec.rb
Labels: enhancement, providers

#21784 Retry Translations Provided in March
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization

#21785 Copy locale/manageiq.pot to locale/en/manageiq.po (English locale only)
  locale/en/manageiq.po
Labels: internationalization

#21788 Redo manual rename of Ibm Cic to IBM CIC
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization

#21789 Delete a deployment with multiple failed pods only once
  app/models/miq_server/worker_management/kubernetes.rb
  spec/models/miq_server/worker_management/kubernetes_spec.rb
Labels: bug, core/pods, najdorf/yes?

#21787 added 'msg_timeout' param to the overriden 'queue_signal'
  app/models/manageiq/providers/ansible_runner_workflow.rb
Labels: enhancement, providers

#21692 User#in_all_regions
  app/models/miq_request.rb
  app/models/user.rb
  spec/models/user_spec.rb
Labels: bug, rails6.1

#21794 Fix openstack cloud object notification error
  db/fixtures/notification_types.yml
Labels: bug, providers/storage

#21791 Add supports cloud object store container create
  app/models/ext_management_system.rb
Labels: bug

#21753 Remove col3 from dashboard widgets
  app/models/miq_widget_set/set_data.rb
Labels: enhancement
