Repository ManageIQ/manageiq, pull requests merged in 2023-07, with the labels that each got.

#22598 Fix Authentication.build_credential_types
  app/models/authentication.rb
Labels: bug, petrosian/yes?

#22600 Allow `ResourceAction#fqname=nil` to clear `ae_*`
  app/models/resource_action.rb
  spec/models/resource_action_spec.rb
Labels: enhancement, core

#22601 [PETROSIAN] Update kubernetes reference since core specs depend on it
  Gemfile.lock.release
Labels: dependencies

#22594 Precache rollup values
  app/models/metric/ci_mixin/state_finders.rb
  app/models/metric/rollup.rb
  app/models/vim_performance_state.rb
  app/models/vim_performance_tag_value.rb
  lib/extensions/ar_preloader.rb
  lib/miq_preloader.rb
  spec/lib/miq_preloader_spec.rb
Labels: performance

#22573 Separate role access restrictions for catalog items
  app/models/miq_user_role.rb
  db/fixtures/miq_user_roles.yml
  lib/rbac/filterer.rb
Labels: enhancement, core

#22602 Added vm reload features
  db/fixtures/miq_product_features.yml
Labels: enhancement

#22605 VimPerformanceState#purge_timer for old records
  app/models/mixins/purging_mixin.rb
  app/models/vim_performance_state/purging.rb
  config/settings.yml
  spec/models/vim_performance_state/purging_spec.rb
Labels: enhancement, core

#22607 Specs for Vim Performance States
  spec/lib/miq_preloader_spec.rb
  spec/models/metric/ci_mixin/state_finders_spec.rb
  spec/models/vim_performance_state_spec.rb
Labels: enhancement, test

#22612 Added Workflow Credentials to ./spec/factories/authentication.rb
  spec/factories/authentication.rb
Labels: enhancement, test, core

#22578 Allow `supports?(feature)` to work without requiring `supports_not`
  app/models/mixins/supports_feature_mixin.rb
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: enhancement, core

#22614 Fix workflows operations queued on embedded_ansible
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  app/models/manageiq/providers/embedded_automation_manager/crud_common.rb
Labels: bug, core, core/embedded ansible, petrosian/yes?

#22587 Enable notifier role by default
  config/settings.yml
Labels: enhancement, core/workers

#22613 MiqUserRole restriction_type method fixup (Separate role access restrictions for catalog items)
  app/models/miq_user_role.rb
Labels: bug, core

#22603 Add docker and podman as known commands
  lib/miq_environment.rb
Labels: enhancement, core

#22610 Remove ContainerGroup#old_container_project_id
  app/models/container.rb
  app/models/container_group.rb
  app/models/container_project.rb
  spec/models/container_project/purging_spec.rb
  spec/models/container_project_spec.rb
  spec/models/metering_container_project_spec.rb
  spec/models/mixins/event_mixin_spec.rb
Labels: technical debt, providers/containers, petrosian/yes?

#22604 Precache rollup values
  app/models/metric/ci_mixin/state_finders.rb
  lib/miq_preloader.rb
  spec/lib/miq_preloader_spec.rb
  spec/models/metric/ci_mixin/state_finders_spec.rb
Labels: bug, performance, core/chargeback, providers/metrics, petrosian/yes?

#22620 Pre-zeitwerk - Add inflections and acronyms
  lib/vmdb/inflections.rb
Labels: enhancement, rails7

#22623 Translations for 2023-07-11 English po file updated #22543
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: enhancement, internationalization, petrosian/yes?

#22511 Allow ConfigurationScripts to be used for ServiceTemplateProvisionTasks
  app/models/miq_request_task.rb
  app/models/service_reconfigure_task.rb
  app/models/service_template_provision_task.rb
Labels: enhancement, lifecycle/services, petrosian/yes?

#22626 Fix migrations being run from a plugin
  lib/manageiq/environment.rb
Labels: bug, pluggability

#22627 Change plugin setup to more closely match core setup
  lib/manageiq/environment.rb
Labels: enhancement

#22615 add miqExpression::Target equality
  lib/miq_expression/target.rb
  spec/lib/miq_expression/target_spec.rb
Labels: test, core

#22625 Filter storages in the database rather than in ruby.
  app/models/miq_request_workflow.rb
Labels: bug, performance, morphy/yes?, petrosian/yes?

#22550 Upgrade i18n version
  Gemfile
  app/models/dictionary.rb
Labels: bug, dependencies

#22636 Fix undefined method reject! in allowed_storages
  app/models/miq_request_workflow.rb
  spec/models/miq_request_workflow_spec.rb
Labels: bug, providers, morphy/yes?, petrosian/yes?

#22637 Add import specs
  spec/models/miq_policy/import_export_spec.rb
  spec/models/miq_report/import_export_spec.rb
  spec/models/miq_widget/import_export_spec.rb
  spec/models/mixins/yaml_import_export_mixin_spec.rb
Labels: test, morphy/yes, petrosian/yes

#22632 externalizing GRAPH_MAX_COUNT to settings.yaml
  config/settings.yml
Labels: enhancement

#22639 Fix Workflows Service Entrypoint arguments
  app/models/miq_request_task.rb
Labels: bug, petrosian/yes

#22624 validate format for SettingsChange#key
  app/models/settings_change.rb
  spec/models/settings_change_spec.rb
Labels: enhancement
