Repository ManageIQ/manageiq, pull requests merged in 2023-02, with the labels that each got.

#22319 Update containerized non rails workers status to started
  app/models/miq_server/worker_management.rb
  app/models/miq_server/worker_management/kubernetes.rb
  app/models/miq_server/worker_management/monitor.rb
  app/models/miq_server/worker_management/monitor/start.rb
  app/models/miq_server/worker_management/process.rb
  app/models/miq_server/worker_management/systemd.rb
  app/models/miq_worker.rb
Labels: enhancement, core/workers, core

#22337 Add audit_events purging
  app/models/audit_event.rb
  app/models/audit_event/purging.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  config/settings.yml
  spec/models/audit_event/purging_spec.rb
Labels: enhancement, core

#22339 Remove redundant audit log mirroring
  lib/vmdb/loggers/audit_logger.rb
Labels: cleanup

#22342 Allow multiple simulate_queue_worker instances
  lib/vmdb/console_methods.rb
Labels: bug

#22331 storage service endpoint
  app/models/ext_management_system.rb
  app/models/physical_storage.rb
  app/models/storage_service.rb
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
Labels: enhancement, providers/storage

#22332 storage service resource attachment collection
  app/models/manageiq/providers/inventory/persister/builder/storage_manager.rb
Labels: enhancement

#22349 Consolidate Condition.subst_matches?
  app/models/condition.rb
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
  spec/models/condition_spec.rb
Labels: refactoring, core/policy

#22348 Remove broken conditional using an undefined inputs variable
  app/models/condition.rb
Labels: bug, core

#22305 Add caching of event_groups and pre-partition the event types
  app/models/event_stream.rb
  lib/vmdb/settings/activator.rb
  spec/support/evm_spec_helper.rb
Labels: performance

#22335 Host factory
  spec/factories/host.rb
  spec/factories/small_environment.rb
  spec/models/resource_pool_spec.rb
Labels: test

#22350 Remove TODOs
  app/models/event_stream.rb
Labels: cleanup

#22355 Properly parse MiqExpression::CountField
  lib/miq_expression/count_field.rb
  lib/miq_expression/target.rb
  spec/lib/miq_expression_spec.rb
Labels: bug

#22360 [OPARIN] Bump Gemfile.lock.release for bundler audit fixes
  Gemfile
  Gemfile.lock.release
Labels: dependencies

#22303 Reduce filtering for pagination in Rbac.search
  lib/rbac/filterer.rb
  spec/lib/miq_expression_spec.rb
Labels: enhancement, performance, api, petrosian/yes?

#22356 Extract MiqExpression#expression_prep from preprocess_for_sql
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: refactoring

#22358 MiqExpression#to_ruby Date bug fix and speed improvements
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: bug, performance, core, petrosian/yes?

#22334 Remove Host discovery from core
  app/models/ext_management_system.rb
  app/models/host.rb
  spec/models/ext_management_system_spec.rb
Labels: technical debt

#22375 Fix additional regions added via settings
  app/models/manageiq/providers/regions.rb
  spec/models/manageiq/providers/regions_spec.rb
Labels: bug, petrosian/yes?

#22372 Change password filtering/masking to support partial matches
  lib/vmdb/settings_walker.rb
  spec/lib/vmdb/appliance_spec.rb
  spec/lib/vmdb/settings_spec.rb
Labels: enhancement

#22374 Update lockfile for rails bump to 6.1.7.2
  Gemfile.lock.release
Labels: dependencies

#22361 Fix event stream filtering so we can filter by ems event or miq event (policy)
  app/models/miq_event.rb
  app/models/mixins/event_mixin.rb
  spec/models/ems_event_spec.rb
  spec/models/miq_event_spec.rb
  spec/models/mixins/event_mixin_spec.rb
  spec/support/evm_spec_helper.rb
Labels: bug, core/events, petrosian/yes?

#22376 Move ems event specifics for event_groups and friends to EmsEvent
  app/models/ems_event.rb
  app/models/event_stream.rb
  spec/models/ems_event_spec.rb
  spec/models/event_stream_spec.rb
  spec/support/evm_spec_helper.rb
Labels: cleanup, petrosian/yes?
