Repository ManageIQ/manageiq, pull requests merged in 2023-03, with the labels that each got.

#22336 Host validation
  app/models/host.rb
  spec/models/host_spec.rb
  spec/models/mixins/authentication_mixin_spec.rb
Labels: enhancement, core

#22333 Kafka broker health checks from evmserver/orchestrator
  app/models/miq_server.rb
Labels: enhancement, core

#22389 Updated some translation after ICT pass 1 on 03/03
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: petrosian/yes?

#22394 [PETROSIAN] Update lockfile for vmware_web_service 3.2.0
  Gemfile.lock.release
Labels: dependencies

#22395 Update rack minimum for CVE-2023-27530
  Gemfile
Labels: dependencies, petrosian/yes

#22399 Updated some translation after ICT pass 2 on 03/10
  locale/de/manageiq.po
  locale/zh_TW/manageiq.po
Labels: petrosian/yes

#22400 [PETROSIAN] Fix lockfile after backport of rack bump
  Gemfile.lock.release
Labels: bug, dependencies

#22254 Add a `EmsRefreshWorkflow#refresh_target` method
  app/models/manageiq/providers/ems_refresh_workflow.rb
Labels: enhancement, providers

#22403 Remove old brakeman patch/Repatch for engine support
  Gemfile
  lib/extensions/brakeman_excludes_patch.rb
  lib/tasks/test_security.rake
Labels: test, dependencies, core/security

#22398 Add virtual delegates for frequently used event stream API columns
  app/models/event_stream.rb
Labels: enhancement, core/events, petrosian/yes?

#20610 Use standard rails memory session store
  lib/extensions/active_record_session_store_patch.rb
  lib/extensions/rack_session_dalli_patch.rb
  lib/manageiq/session.rb
  lib/manageiq/session/active_record_store_adapter.rb
  lib/manageiq/session/mem_cache_store_adapter.rb
  lib/manageiq/session/memory_store_adapter.rb
  spec/lib/manageiq/session_spec.rb
Labels: refactoring, core/security

#22359 Implement cloud snapshot collector, list page, create & delete methods
  app/models/cloud_volume_snapshot.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/storage_manager.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement

#22410 Fix code scanning issue with IO.open
  lib/pid_file.rb
Labels: bug, core/security, petrosian/yes

#22409 update codeql tool
  .github/workflows/codeql-analysis.yml
Labels: test

#22412 Update rack and rails for multiple CVEs
  Gemfile
Labels: dependencies, core/security

#22413 Drop scvmm/hyperv references since it was dropped in #22279
  app/models/ext_management_system.rb
  lib/manageiq/network_discovery/discovery.rb
  spec/models/ext_management_system_spec.rb
Labels: technical debt, providers

#22420 Better ansible runner detection
  config/brakeman.ignore
  lib/ansible/runner.rb
  spec/lib/ansible/runner_spec.rb
Labels: enhancement, technical debt, petrosian/yes?

#22382 Log external authentication groups on failed login.
  app/models/authenticator/base.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/authenticator/ldap_spec.rb
Labels: enhancement

#22422 fix rake issue
  container-assets/entrypoint
Labels: bug, build/docker, petrosian/yes?

#22316 Add basic models for Workflow/WorkflowInstance
  Gemfile
  app/models/manageiq/providers/automation_manager.rb
  app/models/workflow.rb
  app/models/workflow_instance.rb
  spec/factories/ext_management_system.rb
  spec/factories/workflow.rb
  spec/factories/workflow_instance.rb
Labels: dependencies

#22425 storage service edit
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/storage

#22433 Fix collect_current_logs collecting everything
  tools/collect_logs/collect_archive_logs.sh
  tools/collect_logs/collect_current_logs.sh
Labels: bug, tools, petrosian/yes?

#22419 Don't leave trailing hyphen in deployment name
  app/models/miq_worker/container_common.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: bug, build/podified, petrosian/yes

#22411 [PETROSIAN] Update rack and rails for multiple CVEs
  Gemfile
  Gemfile.lock.release
Labels: dependencies, core/security

#22429 Add product features for ManageIQ Workflows
  db/fixtures/miq_product_features.yml
Labels: enhancement, core
