Repository ManageIQ/manageiq, pull requests merged in 2023-08, with the labels that each got.

#22589 VimPerformanceState do not bring back archived records
  app/models/mixins/archived_mixin.rb
  app/models/vim_performance_state.rb
  spec/models/mixins/archived_mixin_spec.rb
  spec/models/vim_performance_state_spec.rb
Labels: performance, providers/containers, petrosian/yes

#22606 Vim performance state time interval
  app/models/metric/helper.rb
  app/models/metric/statistic.rb
  app/models/vim_performance_state.rb
Labels: refactoring

#22611 VimPerformanceState#vim_performance_state_for_ts optimizations
  app/models/chargeback/consumption_with_rollups.rb
  app/models/metric/ci_mixin/capture.rb
  app/models/metric/ci_mixin/state_finders.rb
  app/models/metric/finders.rb
  app/models/metric/rollup.rb
  app/models/vim_performance_state.rb
  spec/models/metric/ci_mixin/state_finders_spec.rb
Labels: enhancement, performance

#22646 Reload UI menu when Settings.prototype changes
  lib/vmdb/settings/activator.rb
Labels: enhancement, petrosian/yes

#22645 Add Switch#ext_management_system
  app/models/switch.rb
  spec/models/switch_spec.rb
Labels: ui, providers/network

#22649 [PETROSIAN] Update manageiq-ui-classic lock reference
  Gemfile.lock.release
Labels: dependencies

#22581 Use Arel helper methods to generate arel
  app/models/disk.rb
  app/models/hardware.rb
  app/models/miq_group.rb
  app/models/mixins/ownership_mixin.rb
  app/models/service/aggregation.rb
  app/models/tenant.rb
  app/models/vm_or_template.rb
  lib/miq_expression.rb
Labels: refactoring

#22652 Change Perf capture timer to medium priority
  app/models/miq_queue.rb
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_schedule_worker/runner.rb
  spec/models/miq_queue_spec.rb
  spec/models/miq_schedule_worker/jobs_spec.rb
Labels: bug, providers/metrics, core/queue, petrosian/yes?

#22585 Keep archived out of VimPerformanceState
  app/models/vim_performance_state.rb
  spec/models/vim_performance_state_spec.rb
Labels: bug, performance, petrosian/yes?

#22608 Metric::Rollup - simplify column declarations
  app/models/metric/rollup.rb
Labels: refactoring, providers/metrics

#22659 Disallow timecop 0.9.7 due to buggy release
  Gemfile
Labels: bug, test, dependencies, petrosian/yes?, quinteros/yes?

#22654 Translations for 2023-07-24 English po file updated (#22621)
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization, quinteros/yes?

#22475 introduce Chargeback group_by date-first
  app/models/chargeback.rb
  app/models/chargeback/report_options.rb
  spec/models/chargeback/report_options_spec.rb
Labels: enhancement, petrosian/yes?

#22653 Add workflow_dispatch to generator ci.yaml
  lib/generators/manageiq/plugin/templates/.github/workflows/ci.yaml
Labels: bug, core/generator

#22655 Prevent more than 1 event_handler from running
  app/models/miq_event_handler.rb
  lib/vmdb/settings/validator.rb
  spec/lib/vmdb/settings/validator_spec.rb
Labels: bug, core/workers, quinteros/yes?

#22660 Ensure provider destroy requeue has long timeout
  app/models/ext_management_system.rb
  spec/models/ext_management_system_spec.rb
Labels: bug, providers, quinteros/yes?

#22672 Upgrade puma to 6.x
  Gemfile
Labels: dependencies, quinteros/yes?

#22668 Fix MiqRegion#remote_*_url returning invalid URL on podified
  app/models/miq_region.rb
  app/models/miq_server.rb
  spec/models/miq_region_spec.rb
Labels: bug, core/pods

#22670 fix GuestDevice#child_device references
  app/models/guest_device.rb
  spec/models/guest_device_spec.rb
Labels: bug

#22676 [QUINTEROS] Quinteros lock timecop 0.9.8 after #22659
  Gemfile.lock.release
Labels: test

#22488 [WIP] Zeitwerk
  config/application.rb
  config/initializers/yaml_autoloader.rb
  config/initializers/zeitwerk.rb
  spec/initializers/yaml_autoloader_spec.rb
Labels: enhancement, dependencies, wip, rails7, petrosian/no

#22682 Let bundler do the require
  Gemfile
Labels: bug, dependencies, rails7, quinteros/yes?

#22687 Add missing benchmark around rollup to parents
  app/models/metric/ci_mixin/rollup.rb
Labels: performance, providers/metrics, quinteros/yes?

#22688 Delete the container_manager reconnect_block
  app/models/manageiq/providers/inventory/persister/builder/container_manager.rb
Labels: technical debt, providers/inventory, quinteros/yes?

#22664 Fix api_system_auth_token missing MiqServer
  app/models/miq_region.rb
Labels: bug, core
