Repository ManageIQ/manageiq, pull requests merged in 2023-10, with the labels that each got.

#22727 Lock down psych to pre-4.0.0 versions
  Gemfile
Labels: dependencies, morphy/yes?, petrosian/yes?, quinteros/yes?

#22737 Fixed physical storage table missing translation
  locale/en.yml
Labels: bug, internationalization

#22740 Set AUTOMATION_JOB_SERVICE_ACCOUNT env var for the automation worker
  app/models/automation_worker.rb
  spec/models/automation_worker_spec.rb
Labels: enhancement, quinteros/yes

#22040 Use type when defining a deprecated attribute
  app/models/host.rb
  app/models/miq_schedule.rb
  app/models/mixins/deprecation_mixin.rb
  app/models/service.rb
Labels: enhancement

#22735 Link AuthKeyPair with an EMS
  app/models/manageiq/providers/cloud_manager/auth_key_pair.rb
Labels: enhancement

#21919 Multiple users being created for the same AD account
  app/models/authenticator/httpd.rb
Labels: bug, core/authentication

#22501 Drop tools/miqssh
  tools/miqssh/.config
  tools/miqssh/.doc-tools/FOOT.md
  tools/miqssh/.doc-tools/HEAD.md
  tools/miqssh/.doc-tools/gen-readme
  tools/miqssh/INSTALL.txt
  tools/miqssh/README.md
  tools/miqssh/miqcollect
  tools/miqssh/miqgrep
  tools/miqssh/miqgrep-collate
  tools/miqssh/miqgrep-request
  tools/miqssh/miqhosts-gen
  tools/miqssh/miqhosts-sample
  tools/miqssh/miqhosts.rb
  tools/miqssh/miqscp
  tools/miqssh/miqssh
  tools/miqssh/miqssh-copy-id
  tools/miqssh/miqssh_wrapper
  tools/miqssh/miqstatus
  tools/miqssh/miqtail
  tools/miqssh/miqtail-request
  tools/miqssh/miqworkermemcheck
Labels: technical debt

#22755 Change URL for the OpenSSF Best Practices badge to the current one
  README.md
Labels: documentation

#22756 Use forked fog-google for pagination fixes
  Gemfile
Labels: bug

#22758 fix specs for Virtual attributes update
  Gemfile
  spec/models/container_service_spec.rb
  spec/support/examples_group/shared_examples_for_ownership_mixin.rb
Labels: test, quinteros/yes?

#22760 Rebuild Gemfile.lock.release after merge of master into quinteros
  Gemfile.lock.release
Labels: dependencies

#22763 Fix locale update all from GitHub actions
  config/initializers/zeitwerk.rb
  lib/tasks/locale.rake
Labels: bug, rails7

#22757 Add Node Affinity arch selector based on the affinity of the orchestrator
  lib/container_orchestrator.rb
  lib/container_orchestrator/object_definition.rb
  spec/lib/container_orchestrator_spec.rb
  spec/models/miq_worker/container_common_spec.rb
Labels: enhancement, quinteros/yes?

#22761 upgrade gems for ruby 3.0.x security issues
  .github/workflows/ci.yaml
  Gemfile
Labels: dependencies, security fix, petrosian/yes?, quinteros/yes?

#22764 [QUINTEROS] Update lockfile after merge of #22761
  Gemfile.lock.release
Labels: dependencies

#22765 Fix ci.yaml syntax error
  .github/workflows/ci.yaml
Labels: bug, test, quinteros/yes

#22766 Use named arguments for psych 4 support
  app/models/dialog_import_validator.rb
  spec/lib/task_helpers/exports/custom_buttons_spec.rb
  spec/lib/task_helpers/exports/widgets_spec.rb
  spec/models/miq_widget_set_spec.rb
Labels: enhancement, ruby3.1

#22768 Drop Ruby 2.7 support
  .github/workflows/ci.yaml
  Gemfile
  spec/models/custom_attribute_spec.rb
Labels: dependencies
