Repository ManageIQ/manageiq, pull requests merged in 2023-04, with the labels that each got.

#22439 add cloud_volume_refresh
  db/fixtures/miq_product_features.yml
  db/fixtures/miq_user_roles.yml
Labels: enhancement, providers/storage

#22417 [WIP] Embedded Workflow integration
  db/fixtures/miq_shortcuts.yml
  db/fixtures/miq_user_roles.yml
Labels: wip

#22437 Kafka SSL options from env if available
  Gemfile
  app/models/miq_queue.rb
  lib/container_orchestrator/object_definition.rb
  spec/models/miq_queue_spec.rb
Labels: enhancement, dependencies, core

#22444 [PETROSIAN] Bump brakeman version after backport of #22403
  Gemfile.lock.release
Labels: dependencies

#22442 added password encryption before adding task to queue in validate and create
  app/models/physical_storage.rb
Labels: enhancement, providers/storage

#22430 document the tenancy strategy rules
  lib/rbac/filterer.rb
Labels: documentation

#22445 Chargeback project date only
  app/models/chargeback.rb
  spec/models/chargeback_spec.rb
Labels: bug, petrosian/yes

#22453 Drop validate_credentials_task
  app/models/mixins/verify_credentials_mixin.rb
  spec/models/mixins/authentication_mixin_spec.rb
Labels: cleanup, providers

#22446 Refactor `ResourceAction#deliver*` methods
  app/models/dynamic_dialog_field_value_processor.rb
  app/models/resource_action.rb
  app/models/resource_action_workflow.rb
  spec/models/dynamic_dialog_field_value_processor_spec.rb
  spec/models/resource_action_spec.rb
  spec/models/resource_action_workflow_spec.rb
Labels: refactoring, core

#22329 Add a way for worker subclasses to handle settings changes
  app/models/miq_server/configuration_management.rb
  app/models/miq_server/worker_management/monitor/settings.rb
  app/models/miq_worker.rb
Labels: enhancement, core/workers, core

#22195 Extract active role syncing out of worker management
  app/models/miq_server.rb
  app/models/miq_server/role_management.rb
  app/models/miq_server/worker_management/monitor.rb
  config/settings.yml
Labels: refactoring, stale

#22463 Upgrade yarn to 3.5.0 for plugin generator
  lib/generators/manageiq/plugin/plugin_generator.rb
  lib/generators/manageiq/plugin/templates/.yarn/releases/yarn-3.0.2.cjs
  lib/generators/manageiq/plugin/templates/.yarn/releases/yarn-3.5.0.cjs
  lib/generators/manageiq/plugin/templates/.yarnrc.yml
  lib/generators/manageiq/plugin/templates/package.json
  lib/generators/manageiq/plugin/templates/yarn.lock
Labels: enhancement, dependencies, core/generator

#22473 Add PhysicalInfraManager::Vm subclass
  app/models/manageiq/providers/physical_infra_manager.rb
  app/models/manageiq/providers/physical_infra_manager/vm.rb
Labels: bug, providers, providers/physical

#22481 Remove extra newlines from persister/builder/infra
  app/models/manageiq/providers/inventory/persister/builder/infra_manager.rb
Labels: cleanup

#22482 Use gettext_i18n_rails with our frozen string fix
  Gemfile
Labels: dependencies, petrosian/yes?

#22483 [PETROSIAN] Update lockfile after backport of #22480
  Gemfile.lock.release
Labels: dependencies

#22458 Dont queue refresh unsupported ems
  app/models/ems_refresh.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager.rb
  app/models/miq_schedule_worker/runner.rb
  spec/models/ems_refresh_spec.rb
  spec/models/miq_schedule_worker/runner_spec.rb
Labels: bug, providers, core/embedded ansible

#22477 Add MiqTask reference to ConfigurationScript
  app/models/configuration_script_base.rb
Labels: enhancement
