Repository ManageIQ/manageiq, pull requests merged in 2023-12, with the labels that each got.

#22800 Drop fog-google from manageiq.rubygems.org
  Gemfile
Labels: dependencies

#22809 Run apt-get update before install in bin/before_install
  lib/generators/manageiq/plugin/templates/bin/before_install
Labels: test, bug/sporadic test failure, quinteros/yes

#22509 Seed an initial service catalog
  app/models/service_template_catalog.rb
  lib/evm_database.rb
  spec/models/service_template_catalog_spec.rb
Labels: enhancement, lifecycle/services

#22814 Bump manageiq-loggers to v1.1.1
  Gemfile
Labels: dependencies, quinteros/yes

#22812 [MORPHY] Fix morphy charts download
  config/initializers/secure_headers.rb
Labels: bug

#22807 Fix dashboard accessibility issues
  app/models/miq_widget/report_content.rb
Labels: enhancement, accessibility

#22698 Support Ruby 3.1
  Gemfile
  config/application.rb
  lib/extensions/yaml_load_aliases.rb
  lib/yaml_permitted_classes.rb
  spec/lib/extensions/ar_yaml_spec.rb
  spec/models/miq_report_spec.rb
  spec/spec_helper.rb
Labels: dependencies, ruby3.1

#22801 There can be only one autoloader: zeitwerk
  config/initializers/zeitwerk.rb
  lib/extensions/as_dependencies_interlock.rb
  spec/initializers/yaml_autoloader_spec.rb
Labels: enhancement, technical debt, rails7
