Repository ManageIQ/manageiq, pull requests merged in 2023-05, with the labels that each got.

#22486 [PETROSIAN] Bump lockfile after backport of nokogiri update
  Gemfile.lock.release
Labels: dependencies

#22450 storage service edit mode: check which attached resources are compliant to selected capabilities
  app/models/storage_service.rb
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/storage

#22489 Normalize screaming case html yaml for zeitwerk
  app/models/authentication.rb
  app/models/file_depot.rb
  app/models/generic_object_definition.rb
  app/models/miq_policy.rb
  app/models/miq_report.rb
  app/models/miq_schedule.rb
  app/models/miq_search.rb
  app/models/miq_widget.rb
  app/models/mixins/yaml_import_export_mixin.rb
  lib/manageiq/reporting/formatter.rb
  lib/manageiq/reporting/formatter/html.rb
  spec/models/mixins/yaml_import_export_mixin_spec.rb
Labels: enhancement, rails7

#22490 Drop responders as we don't use it
  Gemfile
Labels: technical debt, dependencies

#22493 allow dialogs to be destroyed with read only dialog fields
  app/models/dialog_field.rb
  spec/models/dialog_spec.rb
Labels: bug, lifecycle/dialogs, petrosian/yes?

#22495 Bump to appliance_console 7.2.1 for the ipaclient fix
  Gemfile
Labels: bug, dependencies, petrosian/yes?

#22497 [PETROSIAN] Bump lockfile after backport of #22495
  Gemfile.lock.release
Labels: bug, dependencies

#22491 Fix Chargeback not working when company name settings changes
  app/models/chargeback_vm.rb
  spec/models/chargeback_vm_spec.rb
Labels: bug, core/chargeback, petrosian/yes

#22498 Move repository sync to embedded_automation_manager
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  app/models/manageiq/providers/embedded_automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/embedded_automation_manager/crud_common.rb
Labels: refactoring, core/embedded ansible

#22485 Fetch playbook payload from embedded_ansible repos
  app/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
Labels: enhancement, core/embedded ansible

#22508 fix no superclass method conditions= for MiqReport
  app/models/miq_report.rb
Labels: bug

#22347 Miq expression removes sql only fields for filters
  lib/miq_expression.rb
  lib/rbac/filterer.rb
  spec/lib/miq_expression_spec.rb
  spec/lib/rbac/filterer_spec.rb
Labels: performance, petrosian/no

#22523 Add IBM PowerVM to OS types
  app/models/operating_system.rb
Labels: enhancement

#22525 Remove deprecation warnings for InventoryRefresh lazy_find
  spec/models/manageiq/providers/inventory/persister/finders_spec.rb
  spec/models/manageiq/providers/inventory/persister/local_db_finders_spec.rb
  spec/models/manageiq/providers/inventory/persister/serializing_spec.rb
Labels: technical debt, providers/inventory

#22520 drop Vmdb::GlobalMethod#column_type
  lib/vmdb/global_methods.rb
Labels: technical debt

#22524 Extract FakeAnsibleRepo into GitRepoHelper Helper
  spec/support/fake_ansible_repo.rb
  spec/support/fake_git_repo.rb
Labels: refactoring, test, core/embedded ansible

#22529 Update fix_auth to convert openssl_verify_mode value
  tools/fix_auth/models.rb
Labels: enhancement, core/authentication

#22521 merge MiqReport#db_klass and db_class
  app/models/miq_report.rb
  app/models/miq_report/generator.rb
  app/models/miq_report/generator/trend.rb
Labels: technical debt

#22510 Converge batch_size and concurrent_requests
  app/models/manageiq/providers/base_manager/metrics_capture.rb
  app/models/metric/capture.rb
  config/settings.yml
  spec/models/manageiq/providers/base_manager/metrics_capture_spec.rb
  spec/models/metric/ci_mixin/rollup_spec.rb
  spec/support/metric_helper.rb
Labels: enhancement, providers/metrics

#22531 Fixed a missing feature error
  db/fixtures/miq_shortcuts.yml
  db/fixtures/miq_user_roles.yml
Labels: bug

#22519 MiqExpression::Target.parse returns null object to simplify callers
  app/models/condition.rb
  app/models/miq_report.rb
  app/models/miq_report/formatting.rb
  app/models/miq_report/generator.rb
  app/models/miq_report/generator/sorting.rb
  lib/miq_expression.rb
  lib/miq_expression/count_field.rb
  lib/miq_expression/field.rb
  lib/miq_expression/invalid_target.rb
  lib/miq_expression/tag.rb
  lib/miq_expression/target.rb
  spec/lib/miq_expression/field_spec.rb
  spec/lib/miq_expression/target_spec.rb
  spec/lib/miq_expression_spec.rb
  spec/models/miq_report_spec.rb
Labels: enhancement, core

#22517 Fix cloud provision quota memory and cpu counting
  app/models/mixins/miq_provision_quota_mixin.rb
Labels: bug, core

#22426 Adding relative date formatting option for report generation
  app/models/miq_report/formatting.rb
  db/fixtures/miq_report_formats.yml
  spec/models/miq_report/formatting_spec.rb
Labels: enhancement, core/reporting

#22388 Make container class' event_stream_filters match event_where_clause for ems_events
  app/models/container.rb
  app/models/container_group.rb
  app/models/container_node.rb
  app/models/container_project.rb
  app/models/container_replicator.rb
  spec/models/mixins/event_mixin_spec.rb
Labels: bug, core/events, petrosian/yes?

#22537 [PETROSIAN] Synchronize po/pots from master branch into petrosian
  locale/de/manageiq.po
  locale/en/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/manageiq.pot
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization

#22536 Add arm64-darwin to generate_lockfile
  lib/tasks/release.rake
Labels: enhancement, petrosian/backported
