Repository ManageIQ/manageiq, pull requests merged in 2024-04, with the labels that each got.

#22981 Allow null values in worker_settings for unit_config_file
  app/models/miq_worker/systemd_common.rb
  app/models/mixins/per_ems_worker_mixin.rb
Labels: enhancement, core/workers, core

#22993 Update OpenSSF Scorecard link to an actual UI
  README.md
Labels: developer

#22995 Pluggable credential types
  app/models/authentication.rb
  app/models/manageiq/providers/embedded_ansible/automation_manager/credential.rb
  app/models/manageiq/providers/external_automation_manager/authentication.rb
Labels: enhancement, core/embedded ansible

#22976 Fix supports_helper stub_supports to handle unsupported_reason
  spec/lib/supports_helper_spec.rb
  spec/models/manageiq/providers/container_manager/metrics_capture_spec.rb
  spec/models/mixins/supports_feature_mixin_spec.rb
  spec/support/supports_helper.rb
Labels: test, radjabov/yes?

#22998 use hash.fetch instead of key? ? :
  app/models/miq_compare.rb
  app/models/vim_performance_tag_value.rb
  lib/git_worktree.rb
  lib/rbac/filterer.rb
  lib/unique_within_region_validator.rb
  lib/vmdb/settings/hash_differ.rb
  spec/support/service_template_helper.rb
  tools/cleanup_duplicate_host_guest_devices.rb
  tools/reconnect_hosts.rb
  tools/reconnect_vms.rb
Labels: technical debt

#23004 Add referrer_policy to security headers to fix DAST scan
  config/initializers/secure_headers.rb
Labels: security fix

#23007 Fix Renovate PRs
  bin/before_install
  lib/manageiq/environment.rb
Labels: bug, test
