Repository ManageIQ/manageiq, pull requests merged in 2024-10, with the labels that each got.

#23216 Remove sporadic fix_auth spec pt2
  spec/tools/fix_auth/auth_model_spec.rb
Labels: bug/sporadic test failure

#23215 Remove newlines from error message
  app/models/miq_provision_virt_workflow.rb
  app/models/miq_request_workflow.rb
Labels: internationalization

#23220 Bump puma to 6.4.3 for CVE-2024-45614
  Gemfile
Labels: dependencies, core/security, security fix, radjabov/yes

#23219 Fix Marshal.load ArgumentError on ruby3.3
  config/initializers/marshal_autoloader.rb
Labels: bug, ruby3.3

#23222 Host#verify_credentials_task payload string keys
  app/models/host.rb
Labels: bug, radjabov/yes

#23223 [QUINTEROS] Update Gemfile.lock.release for various security issues
  Gemfile.lock.release
Labels: dependencies

#23226 [RADJABOV] Bump lockfile gems
  Gemfile.lock.release
Labels: dependencies

#23227 remove unused tota11y.js reference
  config/environments/development.rb
  config/environments/i18n.rb
Labels: cleanup

#23229 Fix sporadic ansible-runner macOS bug and remove extra listener thread
  lib/ansible/runner.rb
  spec/lib/ansible/runner_execution_spec.rb
Labels: bug

#23230 Poll more frequently in Ansible::Runner::ResponseAsync#wait
  lib/ansible/runner/response_async.rb
Labels: enhancement

#23231 Fix issue where test leaves a dirty git tree
  spec/models/manageiq/providers/embedded_ansible_spec.rb
Labels: technical debt, test

#23232 DRb has been extracted from stdlib to a gem
  Gemfile
Labels: dependencies, ruby3.3

#22960 Remove deletion of data/git_repos for EmbeddedAnsible tests
  spec/models/git_repository_spec.rb
  spec/models/manageiq/providers/embedded_ansible/automation_manager/configuration_script_source_spec.rb
Labels: technical debt, test, core/embedded ansible

#23211 Remove subclassing hack by not subclassing EMS
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: bug, bug/sporadic test failure

#23236 Update rails to 7.0.8.5 for CVEs
  Gemfile
Labels: dependencies, radjabov/yes

#23234 upgrade Factorybot to ruby3.3 friendly version
  Gemfile
  spec/factories/workflow.rb
  spec/factories/workflow_instance.rb
Labels: dependencies, ruby3.3

#23239 Remove task_id from AE deliver_queue
  app/models/resource_action.rb
  spec/models/resource_action_spec.rb
Labels: bug, radjabov/yes?

#23243 Update lockfile after backport of #23236
  Gemfile.lock.release
Labels: dependencies

#23247 Rails 4? Remove long since deprecated bridge monkey patch
  config/initializers/as_to_time.rb
Labels: technical debt, rails7.1

#23250 Fix positional argument deprecations with ERB.new
  tools/miq_config_sssd_ldap/sssd_conf.rb
Labels: technical debt

#23249 Fix deprecations using activesupport deprecation
  app/models/miq_queue.rb
  app/models/mixins/custom_attribute_mixin.rb
  app/models/notification.rb
  lib/manageiq/reporting/formatter.rb
  lib/vmdb/deprecation.rb
  spec/models/miq_queue_spec.rb
  spec/models/mixins/custom_attribute_mixin_spec.rb
Labels: technical debt, rails7.1
