Repository ManageIQ/manageiq, pull requests merged in 2024-07, with the labels that each got.

#23078 Fix dialog tag specs
  spec/models/dialog_field_tag_control_spec.rb
Labels: test

#23082 [RADJABOV] Update lockfile after backport of ManageIQ/manageiq-providers-vmware#916
  Gemfile.lock.release
Labels: dependencies

#23074 Add has_many for annotations custom attribute each summary page that contains labels
  app/models/container_group.rb
  app/models/container_node.rb
  app/models/container_replicator.rb
  app/models/container_route.rb
  app/models/container_service.rb
  app/models/container_template.rb
Labels: enhancement, providers/containers

#23077 Remove calls to supports and supports back to back
  app/models/host.rb
  app/models/storage.rb
  app/models/vm.rb
  app/models/vm/operations/power.rb
  app/models/vm_or_template/operations.rb
  app/models/vm_scan/dispatcher.rb
Labels: refactoring, providers, pluggability

#23096 Don't attempt to load SettingsChange too early
  config/application.rb
  lib/vmdb/settings/database_source.rb
Labels: rails7

#23093 Use default_value_for 4.0 with rails 7+ support
  Gemfile
Labels: dependencies, rails7

#23098 Add a security test that runs yarn npm audit
  lib/tasks/test_security.rake
  lib/vmdb/plugins.rb
Labels: test, core/security

#23092 console methods for running automate and vmware refresh
  lib/vmdb/console_methods.rb
Labels: enhancement, developer

#23101 Use MiqExpression in condition_spec.rb
  spec/models/condition_spec.rb
Labels: test

#23102 Rails7 friendly require during initializers
  config/application.rb
  config/environments/test.rb
  config/initializers/active_metrics.rb
  config/initializers/fast_gettext.rb
  config/initializers/session_store.rb
  lib/extensions/as_include_concern.rb
  lib/extensions/yaml_load_aliases.rb
  lib/manageiq/session.rb
  lib/manageiq/session/mem_cache_store_adapter.rb
  lib/patches/database_configuration_patch.rb
Labels: rails7

#23097 Wait for collect_initial to complete on Kubernetes WorkerManagement
  app/models/miq_server/worker_management/kubernetes.rb
Labels: enhancement, core/pods

#23103 Fix ensure_kube_monitors_started alive?
  app/models/miq_server/worker_management/kubernetes.rb
Labels: bug

#23099 Virtual attribute specs
  spec/models/vm_or_template_spec.rb
Labels: test

#23105 Bump manageiq-appliance_console to 9.1.0
  Gemfile
Labels: bug, dependencies, core, radjabov/yes?

#23113 escape table names and column names
  app/models/mixins/purging_mixin.rb
  lib/manageiq/deep_delete.rb
Labels: technical debt

#23114 [MORPHY] Bump manageiq-loggers to v1.1.1
  Gemfile
  Gemfile.lock.release
Labels: dependencies

#23106 Method List dialog
  app/models/miq_ae_method.rb
  spec/factories/miq_ae_method.rb
  spec/models/miq_ae_method_spec.rb
Labels: enhancement, ui

#23108 Move to AS::DescendantsTracker.subclasses
  spec/models/mixins/supports_feature_mixin_spec.rb
Labels: rails7

#23091 Add more ansible runner specs
  lib/ansible/runner/response_async.rb
  spec/lib/ansible/runner/data/hello_world_vault_encrypted.yml
  spec/lib/ansible/runner_execution_spec.rb
Labels: test
