Repository ManageIQ/manageiq, pull requests merged in 2024-01, with the labels that each got.

#22819 Use DDF style parameters for Host verify_credentials
  app/models/host.rb
  spec/models/host_spec.rb
Labels: cleanup

#22738 Separate vm store and datastore smartstate scan supports checks
  app/models/vm_scan/dispatcher.rb
  spec/models/vm_or_template_spec.rb
Labels: bug, refactoring, quinteros/yes?

#22822 Bump manageiq-messaging to 1.4.1
  Gemfile
Labels: dependencies, quinteros/yes?

#22823 [QUINTEROS] Bump Gemfile.lock.release after backport of #22814
  Gemfile.lock.release
Labels: dependencies

#22713 comment the endpoint_created/destroyed callbacks
  app/models/manageiq/providers/container_manager.rb
Labels: documentation

#22825 [QUINTEROS] Bump lockfile for quinteros branch
  Gemfile.lock.release
Labels: dependencies

#22799 Re-revert enforce kafka changes
  Gemfile
  config/settings.yml
  systemd/evmserverd.service
Labels: enhancement, dependencies, quinteros/yes?

#22826 [QUINTEROS] Bump lockfile after backport of #22799
  Gemfile.lock.release
Labels: dependencies

#22824 FixAuth for ConfigurationScript#credentials
  spec/tools/fix_auth/models/fix_configuration_script_spec.rb
  spec/tools/fix_auth/models/fix_database_yml_spec.rb
  tools/fix_auth/auth_config_model.rb
  tools/fix_auth/auth_model.rb
  tools/fix_auth/fix_auth.rb
  tools/fix_auth/models.rb
Labels: enhancement, quinteros/yes

#22829 Bump vcr to 6.1 for ruby 3.1 finalizer fix
  Gemfile
Labels: bug, test, dependencies, ruby3.1

#22830 Add back parallel_tests
  Gemfile
  config/database.pg.yml
  lib/tasks/test_vmdb.rake
Labels: test, dependencies, performance

#22831 Move require into RSpec defined guard
  lib/tasks/test_vmdb.rake
Labels: bug, core

#22701 Add New Product Feature to See Request Logs
  db/fixtures/miq_product_features.yml
Labels: enhancement

#22840 Bump puma to address CVE-2024-21647
  Gemfile
Labels: dependencies, core/security, quinteros/yes

#22846 Add zone_id to provider generator validationDependencies
  lib/generators/manageiq/provider/templates/app/models/%plugin_path%/%manager_path%.rb
Labels: bug, quinteros/yes?

#22843 Add tenancy scoping to Switches
  app/models/switch.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: core/tenancy, core/rbac, morphy/yes?, petrosian/yes?, quinteros/yes?

#22271 Bump qpid_proton to 0.37.0
  Gemfile
Labels: dependencies

#22852 Use config option in 6.1.7+ instead of an initializer
  config/application.rb
  config/initializers/postgres_bigints.rb
Labels: enhancement, rails7

#22851 [morphy] Add tenancy scoping to switches
  app/models/switch.rb
  lib/rbac/filterer.rb
  spec/lib/rbac/filterer_spec.rb
Labels: enhancement, core/tenancy, core/rbac

#22853 Setup Settings constant before the database is connected
  config/application.rb
Labels: enhancement, rails7

#22856 Drop PR template after merge of ManageIQ/.github#7
  .github/PULL_REQUEST_TEMPLATE.md
Labels: technical debt

#22858 Add a console helper method for enabling roles
  lib/vmdb/console_methods.rb
Labels: enhancement, developer

#22861 Psych 4 won't allow unpermitted classes by default
  app/models/binary_blob.rb
  app/models/miq_task.rb
  spec/models/binary_blob_spec.rb
  spec/models/miq_task_spec.rb
Labels: bug, quinteros/yes

#22866 BinaryBlob was changed in #22861 do this check, so use it
  app/models/miq_task.rb
Labels: cleanup, quinteros/yes
