Repository ManageIQ/manageiq, pull requests merged in 2024-02, with the labels that each got.

#22872 Fix dashboard missing chart
  product/reports/170_Configuration Management - Containers/050_Number of Nodes per CPU Cores.yaml
Labels: bug

#22875 Fix DRB dequeue_method spec
  spec/models/ems_event_spec.rb
Labels: bug, test

#22876 Clear messaging_client between specs
  spec/support/evm_spec_helper.rb
Labels: test, quinteros/yes

#22880 [QUINTEROS] Bump nokogiri to 1.16.2
  Gemfile.lock.release
Labels: dependencies

#22881 Avoid tabnapping exploits for target="_blank"
  product/dialogs/miq_dialogs/miq_provision_google_dialogs_template.yaml
Labels: enhancement, core/security, quinteros/yes

#22878 Psych 3.1 is required since we assert safe_load accepts kwargs
  Gemfile
  lib/extensions/yaml_load_aliases.rb
Labels: dependencies

#22874 Refactor inventory syndication to persister
  app/models/manageiq/providers/base_manager/refresher.rb
  app/models/manageiq/providers/inventory/persister.rb
  spec/models/manageiq/providers/base_manager/refresher_spec.rb
Labels: bug, refactoring, providers/inventory, quinteros/yes?

#22884 connection_config was removed in rails 7
  lib/vmdb/appliance.rb
  tools/fix_auth/fix_auth.rb
Labels: rails7

#22886 Passing legacy binds was deprecated in 6.1 and removed in 7.
  lib/extensions/ar_migration.rb
Labels: rails7

#22887 Provide backward compatible way to globally set permitted classes
  lib/yaml_permitted_classes.rb
Labels: enhancement, rails7

#22889 Bump appliance_console minimum to 8.1.0
  Gemfile
Labels: dependencies, quinteros/yes

#22890 [QUINTEROS] Bump appliance_console to 8.1 in Gemfile.lock.release
  Gemfile.lock.release
Labels: dependencies

#22892 Set inventory refresh minimum version to support rails 7
  Gemfile
Labels: dependencies, rails7

#22893 Vm.supports returns strings
  app/models/vm_or_template/operations.rb
  spec/models/vm_spec.rb
Labels: refactoring

#22894 Update authentications supports to reflect update and delete
  app/models/manageiq/providers/embedded_automation_manager/authentication.rb
  app/models/manageiq/providers/embedded_automation_manager/configuration_script_source.rb
Labels: enhancement, providers

#22857 Don't reject AdvancedSetting#destroy if read-only
  app/models/advanced_setting.rb
Labels: bug, providers, quinteros/yes?

#22897 [QUINTEROS] Fix codename
  lib/vmdb/appliance.rb
Labels: bug

#22901 Replace "some" default_value_for usage
  app/models/assigned_server_role.rb
  app/models/blacklisted_event.rb
  app/models/classification.rb
  app/models/cloud_database_flavor.rb
  app/models/dialog.rb
  app/models/dialog_field.rb
  app/models/endpoint.rb
  app/models/ext_management_system.rb
  app/models/flavor.rb
  app/models/git_repository.rb
  app/models/manageiq/providers/cloud_manager/template.rb
  app/models/manageiq/providers/cloud_manager/vm.rb
  app/models/manageiq/providers/embedded_automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/infra_manager/template.rb
  app/models/manageiq/providers/infra_manager/vm.rb
  app/models/manageiq/providers/physical_infra_manager/vm.rb
  app/models/miq_ae_method.rb
  app/models/miq_approval.rb
  app/models/miq_group.rb
  app/models/miq_policy.rb
  app/models/miq_provision_request.rb
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/miq_schedule.rb
  app/models/miq_server.rb
  app/models/miq_user_role.rb
  app/models/miq_widget.rb
  app/models/notification.rb
  app/models/notification_recipient.rb
  app/models/orchestration_stack_retire_task.rb
  app/models/orchestration_template.rb
  app/models/pxe_server.rb
  app/models/service.rb
  app/models/service_reconfigure_request.rb
  app/models/service_resource.rb
  app/models/service_retire_task.rb
  app/models/service_template.rb
  app/models/service_template_provision_request.rb
  app/models/share.rb
  app/models/system_console.rb
  app/models/tenant.rb
  app/models/time_profile.rb
  app/models/user.rb
  app/models/vm_migrate_task.rb
  app/models/vm_retire_request.rb
  app/models/vm_retire_task.rb
  app/models/zone.rb
  lib/uuid_mixin.rb
  spec/lib/extensions/ar_yaml_spec.rb
  spec/lib/uniqueness_when_changed_validator_spec.rb
  spec/models/blacklisted_event_spec.rb
Labels: technical debt

#22888 Improve managed_resources reporting
  app/models/miq_schedule_worker/jobs.rb
  app/models/miq_server.rb
  app/models/miq_server/at_startup.rb
  app/models/service.rb
  lib/miq_environment.rb
  spec/models/miq_schedule_worker/jobs_spec.rb
  spec/models/miq_server_spec.rb
Labels: enhancement

#22885 Rails 7 removed clear_association_cache
  app/models/ext_management_system.rb
  app/models/pxe_server.rb
  app/models/tenant.rb
  spec/models/pxe_server_spec.rb
  tools/fix_binary_blobs_and_parts_size_column.rb
Labels: technical debt, rails7

#22903 Update manageiq-smartstate to v0.9.0
  Gemfile
Labels: dependencies

#22904 Only run load_subclasses after app is initialized
  lib/extensions/descendant_loader.rb
Labels: rails7

#22899 Add rdoc for rails console
  Gemfile
Labels: bug, dependencies, ruby3.1

#22906 Add url,url= to EMS default_endpoint delegates
  app/models/ext_management_system.rb
Labels: enhancement, providers

#22907 Add default_authentication delegates
  app/models/ext_management_system.rb
Labels: enhancement, core

#22909 Temporarily ignore non-critical CVE as we upgrade to rails 7
  lib/tasks/test_security.rake
Labels: test, core/security, quinteros/yes, radjabov/yes

#22910 Force rails 6.1.7.7 minimum version
  Gemfile
Labels: dependencies, core/security, quinteros/yes?, radjabov/yes?

#22911 Fix monolith build for EL9
  Dockerfile
Labels: dependencies, radjabov/yes

#22913 Remove CVE-2024-26143 as rails 6.1 is not vulnerable
  lib/tasks/test_security.rake
Labels: test, core/security, quinteros/yes, radjabov/yes

#22908 define supports :action
  app/models/vm/operations/lifecycle.rb
  app/models/vm_or_template.rb
  app/models/vm_or_template/operations.rb
Labels: technical debt, core

#22914 Switch to is_podified? check in auditing payload
  app/models/miq_server.rb
Labels: bug, radjabov/yes?

#22912 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#22915 Set system_uid for systemd workers
  app/models/miq_server/worker_management/systemd.rb
  app/models/miq_worker.rb
  app/models/miq_worker/systemd_common.rb
  spec/models/miq_worker/systemd_common_spec.rb
Labels: enhancement, core/workers, core

#22917 Remove tags from entitlement filters from the deleted tag's region
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: bug, core, quinteros/yes?, radjabov/yes?

#22920 Bump manageiq-style minimum to 1.5.0
  Gemfile
Labels: dependencies

#22922 Revert "Merge pull request #22901 from jrafanie/drop_default_value_for"
  app/models/assigned_server_role.rb
  app/models/blacklisted_event.rb
  app/models/classification.rb
  app/models/cloud_database_flavor.rb
  app/models/dialog.rb
  app/models/dialog_field.rb
  app/models/endpoint.rb
  app/models/ext_management_system.rb
  app/models/flavor.rb
  app/models/git_repository.rb
  app/models/manageiq/providers/cloud_manager/template.rb
  app/models/manageiq/providers/cloud_manager/vm.rb
  app/models/manageiq/providers/embedded_automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/infra_manager/template.rb
  app/models/manageiq/providers/infra_manager/vm.rb
  app/models/manageiq/providers/physical_infra_manager/vm.rb
  app/models/miq_ae_method.rb
  app/models/miq_approval.rb
  app/models/miq_group.rb
  app/models/miq_policy.rb
  app/models/miq_provision_request.rb
  app/models/miq_request.rb
  app/models/miq_request_task.rb
  app/models/miq_schedule.rb
  app/models/miq_server.rb
  app/models/miq_user_role.rb
  app/models/miq_widget.rb
  app/models/notification.rb
  app/models/notification_recipient.rb
  app/models/orchestration_stack_retire_task.rb
  app/models/orchestration_template.rb
  app/models/pxe_server.rb
  app/models/service.rb
  app/models/service_reconfigure_request.rb
  app/models/service_resource.rb
  app/models/service_retire_task.rb
  app/models/service_template.rb
  app/models/service_template_provision_request.rb
  app/models/share.rb
  app/models/system_console.rb
  app/models/tenant.rb
  app/models/time_profile.rb
  app/models/user.rb
  app/models/vm_migrate_task.rb
  app/models/vm_retire_request.rb
  app/models/vm_retire_task.rb
  app/models/zone.rb
  lib/uuid_mixin.rb
  spec/lib/extensions/ar_yaml_spec.rb
  spec/lib/uniqueness_when_changed_validator_spec.rb
  spec/models/blacklisted_event_spec.rb
Labels: bug, radjabov/yes?

#22918 Pluggable Server Roles
  app/models/server_role.rb
  lib/vmdb/plugins.rb
  spec/models/server_role_spec.rb
Labels: enhancement, core, pluggability
