Repository ManageIQ/manageiq, pull requests merged in 2025-07, with the labels that each got.

#23496 Add VcrSecrets spec helper
  spec/spec_helper.rb
  spec/support/prepare_engine_root.rb
  spec/support/vcr_secrets.rb
Labels: test, rails7.2

#23493 Let's use lets
  spec/models/miq_widget_spec.rb
Labels: cleanup, spassky/no

#23495 Create, update, delete container projects
  app/models/container_project.rb
Labels: enhancement, providers/containers

#23499 [SPASSKY] Update lockfile after backport of #23465
  Gemfile.lock.release
Labels: dependencies

#23424 Rails 7.2
  .github/workflows/ci.yaml
  Gemfile
  bin/test_database_connectivity
  config/application.rb
  config/initializers/postgres_required_versions.rb
  lib/extensions/ar_base.rb
  lib/extensions/ar_migration.rb
  lib/tasks/evm_application.rb
  lib/tasks/evm_rake_helper.rb
  lib/tasks/test.rake
  lib/vmdb/initializer.rb
  spec/lib/extensions/ar_migration_spec.rb
  spec/lib/vmdb/initializer_spec.rb
Labels: dependencies, rails7.2

#23498 Features for Container project functionalities
  db/fixtures/miq_product_features.yml
Labels: enhancement, providers/containers

#23503 It now takes no args as it uses the connection_specification_name
  lib/workers/evm_server.rb
Labels: bug, rails7.2

#23504 Allow for per-rails-environment permissions files
  lib/vmdb/permission_stores.rb
Labels: enhancement, core

#23505 Drop deprecated require_nested and include_concern
  lib/extensions/as_include_concern.rb
  lib/extensions/require_nested.rb
Labels: technical debt

#23492 remove unnecessary instance variables in specs
  spec/lib/manageiq/reporting/formatter/timeline_message_spec.rb
  spec/lib/miq_environment_spec.rb
  spec/lib/vmdb/initializer_spec.rb
  spec/models/authenticator/httpd_spec.rb
  spec/models/container_project/purging_spec.rb
  spec/models/manageiq/providers/inventory/persister/finders_spec.rb
  spec/models/manageiq/providers/physical_infra_manager/physical_infra_manager_spec.rb
  spec/models/metering_vm_spec.rb
  spec/models/metric/capture_spec.rb
  spec/models/miq_provision_configured_system_request_spec.rb
  spec/models/miq_request_spec.rb
  spec/models/miq_widget/import_export_spec.rb
  spec/models/tenant_quota_spec.rb
  spec/models/vm_scan/dispatcher_embedded_scan_spec.rb
Labels: test

#23507 Rails 7.1 deprecated pool_size in AS::Cache::Store/removed in 7.2
  lib/token_store.rb
Labels: bug, rails7.2

#23508 Rails 7.2 cleanup
  config/application.rb
Labels: cleanup, rails7.2

#23512 Fix 7.1 deprecated and 7.2 removed name arg to remove_connection
  app/models/miq_queue_worker_base/runner.rb
  app/models/miq_server.rb
  app/models/miq_server/queue_management.rb
  lib/extensions/ar_base.rb
  lib/workers/evm_server.rb
  spec/lib/extensions/ar_base_spec.rb
Labels: cleanup, rails7.2

#23513 [spassky] update lockfile
  Gemfile.lock.release
Labels: bug, dependencies

#23511 pool#connection is deprecated in 7.2, use with_connection here
  app/models/miq_region_remote.rb
Labels: cleanup, rails7.2

#23521 Upgrade virtual attributes to 7.2.0.1
  Gemfile
Labels: bug, dependencies, rails7.2

#23525 7.2's proactive checkout/checkin behavior makes this less helpful
  lib/extensions/ar_adapter/ar_checkin_checkout_callbacks.rb
Labels: bug, rails7.2

#23522 upgrade thor CVE-2025-54314
  Gemfile
Labels: dependencies

#23532 clean_up was last called in 2014 :wink:
  tools/fix_auth/auth_model.rb
Labels: cleanup, rails7.2
