Repository ManageIQ/manageiq, pull requests merged in 2025-08, with the labels that each got.

#23530 Add a rack session dalli debug logger
  lib/manageiq/session.rb
  lib/manageiq/session/abstract_store_adapter.rb
  lib/manageiq/session/mem_cache_store_adapter.rb
  lib/manageiq/session/rack_session_dalli_logger.rb
  spec/lib/manageiq/session/active_record_store_adapter_spec.rb
  spec/lib/manageiq/session/mem_cache_store_adapter_spec.rb
  spec/lib/manageiq/session/memory_store_adapter_spec.rb
Labels: tools, developer

#23218 Improve i18n newlines test output
  spec/shared/i18n/newlines.rb
Labels: enhancement, test, internationalization

#23535 CVE-2024-43380 rufus-scheduler version
  Gemfile
Labels: dependencies, core/security, security fix

#23534 Organize rack attack enabler to add cypress exclusion
  app/models/mixins/miq_web_server_runner_mixin.rb
  config/initializers/rack_attack.rb
  lib/manageiq/rack_attack.rb
  lib/vmdb/initializer.rb
Labels: refactoring, api, ui, cypress

#23539 [morphy] upgrade nio4r
  Gemfile.lock.release
Labels: dependencies, developer

#23541 Move EtOrbi monkey patch from initializer to lib/extensions
  config/initializers/add_active_support_duration_to_eo_time.rb
  lib/extensions/et_orbi_as_duration.rb
  spec/lib/et_orbi_spec.rb
  spec/lib/extensions/et_orbi_as_duration_spec.rb
Labels: refactoring

#23549 Fix spec on Rails 7.2.2.2
  spec/models/miq_widget_set_spec.rb
Labels: bug, spassky/yes

#23546 [SPASSKY] Update lockfile after merge of master into spassky
  Gemfile.lock.release
Labels: dependencies

#23552 Ignore changes in locale:update_all when only dates have changed
  .github/workflows/locale_update_all.yaml
  lib/tasks/locale.rake
Labels: internationalization

#23527 Be lenient with schedule expressions
  app/models/miq_schedule.rb
  lib/miq_expression.rb
  spec/lib/miq_expression/field_spec.rb
  spec/lib/miq_expression_spec.rb
  spec/models/miq_schedule_spec.rb
Labels: bug

#23572 Revert ffi upgrade
  Gemfile
Labels: bug, dependencies

#23574 Add script to help setup and execute ansible_runner execution tests
  bin/test_ansible_runner_execution
  lib/tasks/test_ansible_runner.rake
Labels: test, spassky/yes?

#23575 Updates to the i18n catalogs
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
Labels: internationalization
