Repository ManageIQ/manageiq, pull requests merged in 2025-05, with the labels that each got.

#23436 Fix test issues from rspec-mocks 3.13.3
  app/models/miq_schedule.rb
  spec/models/miq_schedule_spec.rb
  spec/models/service/dialog_properties/retirement_spec.rb
Labels: bug, test

#23434 Allow running simulate_queue_worker from a Rake task
  lib/tasks/evm_simulate_queue_worker.rake
  lib/vmdb/console_methods.rb
  lib/vmdb/console_methods/log_level_toggle.rb
  lib/vmdb/console_methods/simulate_queue_worker.rb
Labels: enhancement

#23439 Bump to 10.0.2 for https://github.com/ManageIQ/manageiq-appliance_console/pull/278
  Gemfile
Labels: enhancement, dependencies

#23438 Revert "Merge pull request #23313 from Fryguy/plugin_gen_default_renovate"
  lib/generators/manageiq/plugin/renovate.json
Labels: technical debt

#23440 Add Terraform Enterprise Provider
  Gemfile
Labels: enhancement, providers, providers/automation

#23445 Fix Ansible Tower references for base classes
  locale/en.yml
Labels: technical debt, providers/automation

#23446 Add Terraform Enterprise classes to locale
  locale/en.yml
Labels: enhancement

#23448 Fix ServiceTemplate#available_managers
  app/models/mixins/service_template_automation_mixin.rb
Labels: bug, providers/automation

#23449 Indent the yarn audit pending list
  lib/tasks/test_security_helper.rb
Labels: enhancement

#23452 Bump manageiq-smartstate for OpenStack fix
  Gemfile
Labels: bug, dependencies

#23451 Notify Slack on locale_update_all failure
  .github/workflows/locale_update_all.yaml
Labels: enhancement

#23453 Bump manageiq-loggers to v1.2.1 for journald fix
  Gemfile
Labels: bug, core, spassky/yes?

#23455 Set bcrypt cost low for faster dev and test environment
  config/initializers/bcrypt_engine.rb
Labels: test, performance, developer

#23461 This is an easy easy to speed up cypress by disabling code reloading
  config/environments/development.rb
Labels: cypress

#23464 Address rack cves
  Gemfile
Labels: enhancement, security fix, spassky/yes?
