Repository ManageIQ/manageiq, pull requests merged in 2025-02, with the labels that each got.

#23322 Add brakeman ignores for Ruby 3.1 and Rails 7.0
  config/brakeman.ignore
Labels: test, core/security

#23323 Include the GHSA number when sorting npm excludes
  lib/tasks/test_security_helper.rb
Labels: enhancement

#23324 introduce all_attribute_names
  lib/extensions/ar_visible_attribute.rb
  spec/lib/extensions/ar_visible_attribute_spec.rb
Labels: enhancement, rails7.1

#23326 Bump manageiq-smartstate for EL8,9 RPM support
  Gemfile
Labels: dependencies

#23327 Drop cgi from the Gemfile as the default in ruby 3.1.3 and 3.3 has the CVE fix
  Gemfile
Labels: dependencies

#23329 [MORPHY] Fix CVE-2024-27280,
  Gemfile
  Gemfile.lock.release
Labels: dependencies, Mend: dependency security vulnerability

#23330 Specify the FQ class name for the provisioning manager
  app/models/operating_system_flavor.rb
Labels: rails7.1

#23331 Avoid calling MiqQueue.messaging_client and stub it as missing
  spec/models/ems_event_spec.rb
Labels: test, rails7.1

#23333 [MORPHY] Fix CVE-2021-33621 CVE-2023-28756 CVE-2023-28755 CVE-2023-36617
  Gemfile
  Gemfile.lock.release
Labels: security fix

#23321 deprecate attribute no longer uses virtual attribute
  app/models/mixins/deprecation_mixin.rb
Labels: enhancement, rails7.1

#23337 Rails 7.1 friendly attribute changes
  app/models/automation_request.rb
  app/models/automation_task.rb
  app/models/ext_management_system.rb
  app/models/flavor.rb
  app/models/manageiq/providers/embedded_automation_manager/authentication.rb
  app/models/miq_provision.rb
  app/models/miq_provision_request.rb
  app/models/miq_request.rb
  app/models/mixins/deprecation_mixin.rb
  app/models/persistent_volume.rb
  app/models/physical_switch.rb
  app/models/resource_group.rb
  app/models/service.rb
  app/models/service_template_provision_request.rb
  app/models/tenant_quota.rb
  app/models/vm_cloud_reconfigure_task.rb
  app/models/vm_migrate_task.rb
  app/models/vm_reconfigure_task.rb
  app/models/vm_retire_task.rb
  spec/models/mixins/deprecation_mixin_spec.rb
Labels: rails7.1

#23225 Rails 7.1
  Gemfile
  app/models/service/aggregation.rb
  config/application.rb
  config/initializers/secure_headers.rb
  lib/extensions/ar_migration.rb
  lib/vmdb/loggers.rb
  spec/lib/extensions/ar_migration_spec.rb
  spec/lib/miq_expression/field_spec.rb
  spec/lib/vmdb/loggers_spec.rb
  spec/models/service_spec.rb
Labels: enhancement, dependencies, rails7.1

#23320 Use settings for filtered events
  app/models/blacklisted_event.rb
  app/models/ext_management_system.rb
  app/models/manageiq/providers/base_manager.rb
  app/models/manageiq/providers/base_manager/event_catcher/runner.rb
  app/models/miq_worker/runner.rb
  lib/evm_database.rb
  spec/models/blacklisted_event_spec.rb
  spec/models/manageiq/providers/base_manager_spec.rb
Labels: technical debt

#23351 Set secret_key_base early enough for rails processes
  app/models/mixins/miq_web_server_runner_mixin.rb
  app/models/mixins/miq_web_server_worker_mixin.rb
  config/application.rb
  lib/vmdb/initializer.rb
  spec/lib/vmdb/initializer_spec.rb
  spec/models/miq_ui_worker_spec.rb
  spec/models/miq_web_service_worker_spec.rb
  spec/models/mixins/miq_web_server_worker_mixin_spec.rb
Labels: bug, rails7.1

#23349 Numerics shouldn't be tested for ".bytes" like suffix
  lib/miq_expression.rb
  spec/lib/miq_expression_spec.rb
Labels: bug

#23353 Bump rugged to 1.9.0
  Gemfile
Labels: bug, dependencies, ruby3.3, ruby3.2, spassky/yes?
