Repository ManageIQ/manageiq, pull requests merged in 2025-06, with the labels that each got.

#23467 converge MiqExpression#lenient evaluate and evaluate
  app/models/custom_button.rb
  app/models/miq_report/generator/trend.rb
  lib/miq_expression.rb
  lib/rbac/filterer.rb
  spec/lib/miq_expression_spec.rb
Labels: refactoring

#23463 Drop Tenant#use_config_for_attributes
  app/models/tenant.rb
  locale/en.yml
  spec/models/chargeback_vm_spec.rb
  spec/models/tenant_spec.rb
  spec/support/evm_spec_helper.rb
Labels: bug

#23471 June 2025 translations
  locale/de/manageiq.po
  locale/es/manageiq.po
  locale/fr/manageiq.po
  locale/it/manageiq.po
  locale/ja/manageiq.po
  locale/ko/manageiq.po
  locale/pt_BR/manageiq.po
  locale/zh_CN/manageiq.po
  locale/zh_TW/manageiq.po
Labels: internationalization, spassky/yes

#23475 Use safe_load with known good classes and aliases
  tools/fix_auth/auth_config_model.rb
Labels: bug, core

#23476 Fix typo Memeory->Memory
  locale/en.yml
Labels: bug, internationalization

#23481 Add Nutanix VM Vendor
  app/models/vm_or_template.rb
Labels: enhancement, dependencies, providers/infrastructure

#23482 Add appliance/container tests for ansible-runner
  config/brakeman.ignore
  lib/ansible/content.rb
  lib/ansible/runner.rb
  lib/tasks/test_security_helper.rb
  spec/lib/ansible/content_spec.rb
  spec/lib/ansible/runner/data/aws.yml
  spec/lib/ansible/runner/data/vmware.yml
  spec/lib/ansible/runner_execution_spec.bats
  spec/lib/ansible/runner_spec.rb
Labels: enhancement

#23487 Fallback to existing project if new project name is empty or whitespace
  app/models/service_container_template.rb
Labels: bug, providers/containers, spassky/yes?

#23486 Use virtual_has_many :through and delegate :types
  app/models/manageiq/providers/network_manager.rb
  app/models/physical_server.rb
Labels: cleanup, rails7.2

#23490 upgrade virtual attributes
  Gemfile
Labels: enhancement, dependencies

#23491 Don't include deleted groups in widget generation
  app/models/miq_widget.rb
  spec/models/miq_widget_spec.rb
Labels: bug, core/reporting

#23494 Another translation fix on top of #23484 and #23471
  locale/zh_TW/manageiq.po
Labels: bug, internationalization, spassky/yes?
